### ISSUE TITLE
Add Nest device plugin / support

### ISSUE THREAD

**Issue by johnwyles** [pimatic/pimatic#101]
If I can find a good node library I can implement this, test, and submit for review

**Comment by htca** [comment]
What is the status of this? The Nest developersite does give an example on node.js (https://developer.nest.com/documentation/cloud/control or mulitple examples on different languages https://developer.nest.com/documentation/cloud/sample-code), but I do not have programming skills to implement it.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
