### ISSUE TITLE
Iphone webapp/homescreen no connection to pimatic

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#1011]
from the forum : 
https://forum.pimatic.org/topic/2466/open-pimatic-from-homescreen-ipad-iphone/
the homescreen function seems to be broken
![](http://www.youscreen.de/aunjwaqbv47.jpg)

**Comment by mwittig** [comment]
Works for me. Justed tested it on iOS 10 with Safari. 
Possibly a caching issue?

**Comment by mwittig** [comment]
I am closing this now as forum response is indicating the problem has been solved.

My recommendation is to clear the cache and website-data via settings / safari
