### ISSUE TITLE
RFLink startup issue

### ISSUE THREAD

**Issue by ErikCoen** [pimatic/pimatic#1013]
The RFLink plug-in is new for me. I have added the Kaku switch devices. Controlling these devices is working for a while. Besides this, I have an active Alecto weather station. Adding this device is not done. A restart of pimatic is failed. Even clearing the mysqlite database does not help. I think it is related to the serial communcation failure when the RFLink tried to get the Welcome sentence. Sometimes this sentence is received too late or the first part is corrupted. I think this Welcome should be structured as a receive packet, so 20;ID=9999;Name;LABEL=data; should be sent by Arduino. Alternatively, if any receive message is not well-formated, it will be dropped.

The error message:

21:58:08.420 [pimatic-rflink] warn: No ready message received within connection timeout, reboot device
21:58:08.427 [pimatic-rflink] debug: send: "10;REBOOT;"
21:58:08.458 [pimatic-rflink] debug: data: "20;08;Alecto V20;00;Nodo RadioFrequencyLink - RFLink Gateway V1.1 - R39;"
21:58:08.464 [pimatic-rflink] warn: Received data before the ready message from RFLink, discard and reboot...
21:58:08.467 [pimatic-rflink] debug: send: "10;REBOOT;"
21:58:08.483 [pimatic] info: rule pulse-on-reset-control-bridge: turned Reset HAV bridge (26) off
21:58:08.525 [pimatic-openweather] debug: Weather data received: {"base":"stations","id":520,"temperature":11.3}
21:58:08.582 [pimatic-rflink] debug: data: "20;00;Nodo RadioFrequencyLink - RFLink Gateway V1.1 - R39;"
21:58:08.587 [pimatic-rflink] debug: Received welcome message from RFLink
21:58:08.591 [pimatic-rflink] info: Connected to rflink device.
21:58:08.606 [pimatic-homeduino] debug: data: "PING"
21:58:08.630 [pimatic-rflink] debug: data: "20;00;Nodo RadioFrequencyLink - RFLink Gateway V1.1 - R39;"
21:58:08.685 [pimatic] error: A uncaught exception occured: TypeError: undefined is not a function
21:58:08.685 [pimatic] error:>    at Board._handleAcknowledge (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:183:5)
21:58:08.685 [pimatic] error:>    at Board._processData (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:128:38)
21:58:08.685 [pimatic] error:>    at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/board.coffee:43:8)
21:58:08.685 [pimatic] error:>    at SerialPortDriver.EventEmitter.emit (events.js:95:17)
21:58:08.685 [pimatic] error:>    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-rflink/lib/serialport.coffee:37:8)
21:58:08.685 [pimatic] error:>    at SerialPort.EventEmitter.emit (events.js:95:17)
21:58:08.685 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/lib/parsers.js:24:17
21:58:08.685 [pimatic] error:>    at Array.forEach (native)
21:58:08.685 [pimatic] error:>    at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/lib/parsers.js:23:13)
21:58:08.685 [pimatic] error:>    at SerialPort.settings.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:168:14)
21:58:08.685 [pimatic] error:>    at SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:377:18)
21:58:08.685 [pimatic] error:>    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:356:16)
21:58:08.685 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-rflink/node_modules/serialport/serialport.js:370:7
21:58:08.685 [pimatic] error:>    at Object.wrapper [as oncomplete] (fs.js:454:17)
21:58:08.685 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
21:58:08.689 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!

**Comment by mwittig** [comment]
Sorry, we can't you support you on rflink in this space! 

Please use our user forum https://forum.pimatic.org/ or create an issue for the plugin project at https://github.com/sirchia/pimatic-rflink/issues
