### ISSUE TITLE
error:>Message: null is not an object (evaluating 'd')

### ISSUE THREAD

**Issue by blacktiger333** [pimatic/pimatic#1019]
If I try to add a new device from the plugin pimatic-hue-zll I got the following error messages:

_16:55:43.572 [pimatic-hue-zll] debug: Changing light 1 state: {"on":false}
16:56:17.213 [pimatic] error: Error on incoming http request to /client-error: too many parameters
16:56:18.471 [pimatic-mobile-frontend] info: rendering theme: graphite/water
16:56:22.740 [pimatic-mobile-frontend] info: rendering theme finished
16:56:26.350 [pimatic-mobile-frontend] error: Client error: TypeError: Unable to process binding "template: function (){return { name:$root.getItemTemplate,foreach:$data.getUngroupedDevices(),afterRender:$data.afterRenderDevice} }"
16:56:26.350 [pimatic-mobile-frontend] error:>Message: null is not an object (evaluating 'd')_

Is this a pimatic-mobile-frontend or a pimatic-hue-zll problem?

**Comment by mwittig** [comment]
Possibly related https://github.com/pimatic/pimatic/issues/973

Please try to clear the bowser cache

**Comment by blacktiger333** [comment]
Thx – yes, it was the browser cache.



Von: Marcus Wittig [mailto:notifications@github.com]
Gesendet: Samstag, 26. November 2016 19:33
An: pimatic/pimatic <pimatic@noreply.github.com>
Cc: blacktiger333 <chris3chris3chris@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [pimatic/pimatic] error:>Message: null is not an object (evaluating 'd') (#1019)



Possibly related #973<https://github.com/pimatic/pimatic/issues/973>

Please try to clear the bowser cache
