### ISSUE TITLE
Help with Variable TimeInputDevice Rule

### ISSUE THREAD

**Issue by Freekwilly** [pimatic/pimatic#1021]
Hi,

i am new to pimatic (I just switched from pilight) and got an issue with a set of rules. I want to switch on and off a switch. And I want to set the timepoint when the switch should happen by a VariableTimeInput Device.

The rules are as follows:

Lights off : "when [its after $day_end or its before $day_start] and switch1 is on then turn switch1 off"
Lights on:  "when [its after $day_start or its before $day_end] and switch1 is off then turn switch1 on"

with $day_end and §day_start being Variables of a Variable TimeInputDevice

```


      "variable": "day_start",
      "id": "test",
      "name": "Licht an",
      "class": "VariableTimeInputDevice",
      "min": "0",
      "max": "24",
      "step": 15
    },
    {
      "variable": "day_end",
      "min": "0",
      "max": "24",
      "step": 15,
      "id": "licht-aus",
      "name": "Licht_aus",
      "class": "VariableTimeInputDevice"
    }

```
Variables:

```
"variables": [
    {
      "name": "day_start",
      "value": "19:30"
    },
    {
      "name": "day_end",
      "value": "22:00"
    }
  ]
```

But when its now for example 22:31 and I manually turn off the switch its turned on again by the rule Lights on.
And in some time combinations it gets completely weird and the switch is turned on and off over and over again.

Can you help?

**Comment by mwittig** [comment]
I have already seen yout post in pimatic forum on the the matter. Pimatic Forum which is a good place to get feedback from other users quickly. I am closing this ticket now.
