### ISSUE TITLE
Documentation: howto use other database than sqlite3

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#1023]
I'd like to use postgresql, I understand it's supported, it would be nice to know how. I suspect the same goes for the MySQL users. :)

**Comment by mwittig** [comment]
You can use mysql, but it may not be as smooth as expected. It would be nice if you could report your findings in our user forum. Thanks!
See:
- https://forum.pimatic.org/search?term=mysql&in=titlesposts
- http://www.pimatic.org/docs/pimatic/config-schema/
