### ISSUE TITLE
Homeduino Analog Dimmer

### ISSUE THREAD

**Issue by Oxx90** [pimatic/pimatic#1026]
Hello, 
sorry for my bad english...

if i set the pwm level of an Arduino pin with pimatic the voltage is 0,7v @100%.
but when i send (AW 10 255) to the arduino via serialpython the voltage is 100% of VCC.

have anyone the same problem?

THX

**Comment by mwittig** [comment]
Hi, 
I think this is a duplicate of https://github.com/pimatic/pimatic-homeduino/issues/73
Fixture is in progress.
