### ISSUE TITLE
DummyPresenceSensor  Cannot read property 'labels' of undefined

### ISSUE THREAD

**Issue by WimUtTwente** [pimatic/pimatic#1028]
Edit Device
Error when completing label

It does not matter what I fill behind xClosedLabel or xOpenedLabel

Oops...
Cannot read property 'labels' of undefined
error [pimatic]: Cannot read property 'labels' of undefined

**Comment by mwittig** [comment]
Thanks for reporting! I think it is a bug in the Device Editor. As you may have noticed xClosedLabel/xOpenedLabel is not right in this context. It should be xPresentLabel/xAbsentLabel

**Comment by mwittig** [comment]
Actually, it is a bug in the pimatic device-config-schema.

**Comment by mwittig** [comment]
Fixed and released with version 0.9.38
