### ISSUE TITLE
Could not connect to the pimatic update server: Error: read ECONNRESET

### ISSUE THREAD

**Issue by qistoph** [pimatic/pimatic#1032]
When my pimatic is running for some days it suddenly starts showing errors like the one below.
The errors are shown when accessing the updates page.
The only way I've found to work around the issue is to restart pimatic.
It doesn't seem to be a problem with my connection as other applications keep working fine (and because it's resolved by just restarting pimatic).

```
13:33:29.800 [pimatic] debug: Error: Could not connect to the pimatic update server: Error: read ECONNRESET
13:33:29.800 [pimatic] debug:>    at PluginManager._tranformRequestErrors (/opt/pimatic-app/node_modules/pimatic/lib/plugins.coffee:195:19)
13:38:29.805 [pimatic] error: Could not connect to the pimatic update server: Error: read ECONNRESET
13:38:29.805 [pimatic] error:>Either the update server is currently not available or your internet connection is down.
13:38:29.806 [pimatic] debug: Error: Could not connect to the pimatic update server: Error: read ECONNRESET
13:38:29.806 [pimatic] debug:>    at PluginManager._tranformRequestErrors (/opt/pimatic-app/node_modules/pimatic/lib/plugins.coffee:195:19)
```

**Comment by mwittig** [comment]
Thanks for your report. Which version of pimatic do you run?

**Comment by qistoph** [comment]
├── pimatic@0.9.37
├── pimatic-cron@0.8.8
├── pimatic-homeduino@0.9.11
├── pimatic-kodi@0.1.6
├── pimatic-mobile-frontend@0.9.11
├── pimatic-openweather@0.9.3
├── pimatic-sunrise@0.8.7
└── sqlite3@3.1.3

**Comment by mwittig** [comment]
@qistoph Did the error occur again?

Possibly this happens after an outage of the server like we had some problems with an update server at the end of the past year

**Comment by qistoph** [comment]
It has been a while, but I can't really tell exactly when without checking
my logs. If you're interested in exact times I could look it up. I use
Nagios to regularly check on updates.

Op 8 jan. 2017 14:58 schreef "Marcus Wittig" <notifications@github.com>:

**Comment by sweetpi** [comment]
This happens ones in a while, when the server is not reachable because of some network conditions. It shouldn't be a big problem if it does no happen permanently.

**Comment by qistoph** [comment]
I agree it's not a big issue **while** the server is unreachable, that's fair.

However, the error keeps returning even long after the server is reachable again. IMHO, the app should be resistant and resume to proper functioning when the server is reachable again.

**Comment by sweetpi** [comment]
You are right I didn't noticed that the cache is not cleared probably after an error. A fix will be released with the next version.

**Comment by qistoph** [comment]
Just tested it and it almost works. The same construction should be added in the `searchForCoreUpdate`.

**Comment by sweetpi** [comment]
Thanks, added as well.
