### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by rikki78** [pimatic/pimatic#1034]
Hello,

Today I received this error

17:26:59.003 [pimatic-mysensors] debug: <- request from   6 
17:26:59.007 [pimatic-mysensors] debug: -> Sending  6;4;1;1;3;0
17:26:59.007 [pimatic-mysensors] debug:>
17:26:59.011 [pimatic-mysensors] debug: -> Sending  6;5;1;1;3;0
17:26:59.011 [pimatic-mysensors] debug:>
17:26:59.016 [pimatic-mysensors] debug: <- request from   6 
17:26:59.019 [pimatic-mysensors] debug: -> Sending  6;4;1;1;3;0
17:26:59.019 [pimatic-mysensors] debug:>
17:26:59.022 [pimatic-mysensors] debug: -> Sending  6;5;1;1;3;0
17:26:59.022 [pimatic-mysensors] debug:>
17:26:59.030 [pimatic-mysensors] debug: <- MySensorDimmer  { sender: 4, sensor: 5, type: 3, value: '706' }
17:26:59.096 [pimatic] error: A uncaught exception occured: AssertionError: level <= 100
17:26:59.096 [pimatic] error:>    at MySensorsDimmer.DimmerActuator._setDimlevel (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:360:7)
17:26:59.096 [pimatic] error:>    at MySensorsDimmer._setDimlevel (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:1:1)
17:26:59.096 [pimatic] error:>    at Board.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:1509:12)
17:26:59.096 [pimatic] error:>    at emitOne (events.js:82:20)
17:26:59.096 [pimatic] error:>    at Board.emit (events.js:169:7)
17:26:59.096 [pimatic] error:>    at Board._rfsendtoboard (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:335:8)
17:26:59.096 [pimatic] error:>    at Board._rfReceived (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:214:12)
17:26:59.096 [pimatic] error:>    at SerialPortDriver.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/MySensors.coffee:182:10)
17:26:59.096 [pimatic] error:>    at emitOne (events.js:77:13)
17:26:59.096 [pimatic] error:>    at SerialPortDriver.emit (events.js:169:7)
17:26:59.096 [pimatic] error:>    at SerialPort.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mysensors/serialport.coffee:44:10)
17:26:59.096 [pimatic] error:>    at emitOne (events.js:77:13)
17:26:59.096 [pimatic] error:>    at SerialPort.emit (events.js:169:7)
17:26:59.096 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:25:17
17:26:59.096 [pimatic] error:>    at Array.forEach (native)
17:26:59.096 [pimatic] error:>    at Object.parser (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/parsers.js:24:13)
17:26:59.096 [pimatic] error:>    at Object.SerialPort.opts.dataCallback (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:181:12)
17:26:59.096 [pimatic] error:>    at SerialPortFactory.SerialPort._emitData (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:396:20)
17:26:59.096 [pimatic] error:>    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:372:20)
17:26:59.096 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/serialport.js:388:9
17:26:59.096 [pimatic] error:>    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
17:26:59.096 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
17:26:59.103 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic as soon as possible!

Could this be fixed easily? 
It appears to me the level received is above 100 and this exception is not handled correctly.

**Comment by rikki78** [comment]
Yesterday I received the same error.

I think there are two issues:
First the level received from mysensors is wrong. In the sketch it is not possible to send values higher than 100 so perhaps a transmission or decoding failure? I will post this in pimatic-mysensors as well as that is the better place I guess.

The second thing is that when this occurs (a value higher then 100) this exception is raised making the mysensors plugin not working anymore. Can this be protected easily by cutting off values above 100?

**Comment by mwittig** [comment]
Duplicate
