### ISSUE TITLE
pimatic forum SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by AnduriI** [pimatic/pimatic#1035]
well not a problem with pimatic itself, but my mozilla rejects opening the forum and says the certificate of the forum expired... is that only a problem with my pc or a general one?

```
forum.pimatic.org verwendet ein ungültiges Sicherheitszertifikat.

Das Zertifikat ist am Freitag, 30. Dezember 2016 21:20 abgelaufen. Die aktuelle Zeit ist Samstag, 31. Dezember 2016 00:24.

Fehlercode: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by mwittig** [comment]
thanks for reporting- should be fixed now
