### ISSUE TITLE
VariableInputDevice not working

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#1042]
For me the Variable input device neither shows a value nor does the value I enter there update the variable.

```
    {
      "variable": "timelapse_interval_minutes",
      "type": "number",
      "id": "timelapse-interval-minutes",
      "name": "Timelapse interval  (minutes)",
      "class": "VariableInputDevice",
      "min": 0,
      "max": 120,
      "step": 5
    },
```

```
    {
      "name": "timelapse_interval_minutes",
      "value": 10
    },
```

**Comment by thexperiments** [comment]
It now magically works... no restart of pimatic or anything... Is there something special to creating the device?

**Comment by edautz** [comment]
Same problem here. I created a variable input devices nad corresponding variabeles, but the device doesn't show the variabels and I cannot change the variabeles. The variabeleinputdevice.input variabele got value NULL.

**Comment by edautz** [comment]
After playing with this device, I got it working. I had to change the variable type to string and ommit the $ in the variabele specification. 
The step function is not available this way, but it works.
I think this device is still buggy.

**Comment by mwittig** [comment]
I am closing this issue now as pimatic@0.9.41 will include varius bug fixes for the VariableInputDevice (to be realses shortly). One of the problems was that the initial value of the device input was set to "null" if the no previous values was read from "lastState" at device constructions. However this make the UI part of failing. Hope, this will catches all the anomalies you have seen. In case you still have issues with the device type please file new bug reports with re-producable cases. Thank you!
