### ISSUE TITLE
Shell switch don't recognize the state

### ISSUE THREAD

**Issue by soulrebell** [pimatic/pimatic#1043]
Hello,
i want to use a shell switch for starting a python program.
The starting of the program is working but after a short time i get a timeout because pimatic do not recognize the current state.
Then pimatic change the state of the switch to off.
For the getStateCommand i use the following small bash script, where i search for the process

```
#!/bin/bash
if [ $(ps -C Luefter_pilight_start -o pid=) ]; then echo on; else echo off; fi
```

And the configuration of the switch

```
{
  "onCommand": "/home/pi/Luefter_pilight_start.py &",
  "offCommand": "/home/pi/Luefter_pilight_stop.sh",
  "id": "lufter",
  "name": "Lüfter",
  "class": "ShellSwitch",
  "getStateCommand": "/home/pi/Luefter_state.sh"
}
```
I got no output (error, warning,de.) at the message section of pimatic.

**Comment by leader21** [comment]
but the get state script works on the bash?
why not to switch over to pimatic with the rf communication instead of using two systems in parallel?

**Comment by soulrebell** [comment]
Yes, the get state script works on the bash.
The python script "Luefter_pilight_start.py" is my working solution for the control of the fans at my house with pilight. The move to pimatic would be easier for me, if I can use the script.

**Comment by leader21** [comment]
sorry that i cannot help any further right now.
i would suggest to open a tjread on our forum.pimatic.org
there you certainly reach more useres than on git.

but one question that remains to me is why you stick to pilight with your fans.
is pimatic not capable to translate the protocol?
if it's an issue with rf range, we'now having the ESPimaticRF solution via wifi.
pretty handy if you ask me :)

**Comment by soulrebell** [comment]
I have to say sorry, because the name of the start script (Luefter_pilight_start.py) is misleading.
In the past i had problems with pilight getting the devices to work, therefore i use wiring pi in the python script. And in pilight the shell execute plugin.

The forum was my start point, unfortunately I have not received an answer yet.

**Comment by mwittig** [comment]
No worries. I am closing this ticket now. Follow-up correspondence can be found at 
https://forum.pimatic.org/topic/2699/shell-switch-timeout
