### ISSUE TITLE
DummyPresenceSensor is not correctly handled in rules if never updated

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#1053]
I have a DummyPresenceSensor which indicates absence/presence of a person and is set via some rules.

If I restart pimatic a rule using this Sensor evaluates as if the sensor is present although it is absent.
Currently it looks like this only happens if the sensor has not yet switched states after the reboot.

Rule like:
```
it is 07:00 and XXX Zuhause is present
```
Trigers although the sensor shows absent.

**Comment by mwittig** [comment]
I cannot reproduce this issue. Please re-open and provide an isolated test case if the problem still exists in your setup (e.g. is the combination with a time condition relavant for the error to occur?). Thanks
