### ISSUE TITLE
Allways crash after installation and first start

### ISSUE THREAD

**Issue by dl1ekm** [pimatic/pimatic#1057]
Hi,
I'm new to pimatic but familiar with raspi, linux, JS etc.
So I've installed pimatic several times exactly as in the documentation described on my old Raspi 1 using nodejs 4.6.2 for arm6.
I  start the server with
`sudo node_modules/pimatic/pimatic.js`
First, in 50% of tests the sqlite3 package has not been found and was compiled locally (which took some time...) - but anyway: At the end the http-server is running on port 80.
Logging in via browser is fine (I had some troubles using variables in devices - but that is another topic).
Then I stopped the server using Ctrl-C.

Then I start the server again - and now (each time!)  it doesn't start any more! I got different errors after each reinstallation:

- some JS-files in sub-folders of node_modules are corrupt (suddenly the source code is overwritten by crazy system messages so node is complaining about invalid code in source)
- some json in sub-folders of node_modules are corrupt (suddenly in the json-file all content is replaced by hieroglyphic letters... so node is complaining about invalid characters)
- modules are missing now...

As an example the log of my last installation attached:
```

08:39:55.096 [pimatic-mobile-frontend] packing static assets
08:39:56.465 [pimatic-mobile-frontend] packing static assets finished
```
```
08:39:56.504 [pimatic-mobile-frontend] rendering html
08:40:34.790 [pimatic-mobile-frontend] rendering html finished
08:40:35.041 [pimatic] Listening for HTTP-request on port 80...
09:15:36.543 [pimatic] Error on incoming http request to /socket.io/: Can't set headers after they are sent.
09:15:38.829 [pimatic-mobile-frontend] rendering theme: graphite/water
coffee-cache: compiling coffee-script file "themes/graphite/water.coffee"...Done
coffee-cache: compiling coffee-script file "themes/graphite/base.coffee"...Done
09:15:45.859 [pimatic-mobile-frontend] rendering theme finished
^C09:17:30.061 [pimatic] Flushing database to disk, please wait...
09:17:30.137 [pimatic] Flushing database to disk, please wait... Done.
09:17:30.155 [pimatic] exiting...
pi@raspi:~/pimatic-app $ sudo node_modules/pimatic/pimatic.js
09:17:44.979 2017-03-06 Monday
09:18:09.520 [pimatic] A uncaught exception occured: Error: Cannot find module 'basic-auth'
09:18:09.520 [pimatic]>    at Function.Module._resolveFilename (module.js:325:15)
09:18:09.520 [pimatic]>    at Function.Module._load (module.js:276:25)
09:18:09.520 [pimatic]>    at Module.require (module.js:353:17)
09:18:09.520 [pimatic]>    at require (internal/module.js:12:17)
09:18:09.520 [pimatic]>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:16:13)
09:18:09.520 [pimatic]>    at Module._compile (module.js:409:26)
09:18:09.520 [pimatic]>    at Object.compile (/home/pi/pimatic-app/node_modules/pimatic/coffee-cache.js:169:17)
09:18:09.520 [pimatic]>    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
09:18:09.520 [pimatic]>    at Function.Module._load (module.js:300:12)
09:18:09.520 [pimatic]>    at Module.require (module.js:353:17)
09:18:09.520 [pimatic]>    at require (internal/module.js:12:17)
09:18:09.520 [pimatic]>    at Object.startup (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:92:20)
09:18:09.520 [pimatic]>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
09:18:09.520 [pimatic]>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:20:3)
09:18:09.520 [pimatic]>    at Module._compile (module.js:409:26)
09:18:09.520 [pimatic]>    at Object.Module._extensions..js (module.js:416:10)
09:18:09.520 [pimatic]>    at Module.load (module.js:343:32)
09:18:09.520 [pimatic]>    at Function.Module._load (module.js:300:12)
09:18:09.520 [pimatic]>    at Function.Module.runMain (module.js:441:10)
09:18:09.520 [pimatic]>    at startup (node.js:139:18)
09:18:09.520 [pimatic]>    at node.js:990:3
09:18:09.520 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
09:18:09.629 [pimatic] exiting...

```

Any idea why the solution gets corrupt after first start? I've tried 0.9.38 and 0.9.35.

**Comment by mwittig** [comment]
This sounds to me like your sd-card is corrupted or you have an issue with power-supply. Do you have another sd-card to test with?

Also make sure you don't touch the sd-card while the system is on as this may already create corruptions! The sd-card mount is not perfect with all Raspi models even though it has been improved with Raspi 3.

Another source of error are power supply issues. Make sure you have a power supply which provides sufficient power (>= 2A, you may need more with Raspi3 if you habe USB devices attached). If you provide me with some more details on which Raspi and power supply you have I may be able to provide some guidance here. Also let me know if you have USB devices attached in case.

**Comment by dl1ekm** [comment]
Ok, could be an idea.
Although all other is working fine....
Power is original from Raspi 3. No USB, only LAN.

I'll give a try with another new Raspi 3 and new card tonight.

Crazy...

**Comment by dl1ekm** [comment]
Thanks a lot! 
With new Raspi/Card all fine. I will investigate in the old Raspi (although the new one is MUCH faster :-))

BR
Marcel
