### ISSUE TITLE
WebUI Notifications ignore locale

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [pimatic/pimatic#1059]
The notifications on the webui after switching a device on or off are not translated and not even listed in the locale files.
They say "switching <device> off" and "done" no matter what you've set your locale to.
I haven't found the js file that creates these notifications, cause that sounds like a simple fix.

Maybe you can add locale support for these notifications or simply tell me the files that create these?

**Comment by mwittig** [comment]
Thanks for reporting. You're right the localization is incomplete and changes are quired in various places. I can partially fix that, but please watch out for other notification which also need translation.

**Comment by dieterhatnkleinen** [comment]
Thanks for the fast response.
The 'done' and switching messages are translated now.
There are still a few notifications that seems hardcoded, I list a few up that I've spotted so far:

 - exiting, flushing to disk etc. on shutdown 

- rendering theme

- reconnected, could not connect 

- Oops, no connection popup

**Comment by mwittig** [comment]
Thanks! It will difficult to localize all of them as some notifications are mapped log messages which are currently not localized. I'll be able to handle the connection-related events at least, such as "no connection", "reconnecting", and a few more buried in the code.

**Comment by dieterhatnkleinen** [comment]
Hi again,
I've applied your changes to my pimatic installation.
After restarting I noticed, that my flipswitch labels are in english now, saying "Off" and "On".

Does it have anything to do with your changes or is it just a random bug?

**Comment by mwittig** [comment]
> After restarting I noticed, that my flipswitch labels are in english now, saying "Off" and "On".

Are you sure the flipswitch had German labels before applying the changes? Note, some plugins like led-light and  milight-reloaded use custom UI templates which are not properly localized.

**Comment by dieterhatnkleinen** [comment]
I am sure it had german labels.
I'm only using the shell-execute plugin.

**Comment by mwittig** [comment]
ok, may be I forgot to commit one of the gernated files. I'll check

**Comment by mwittig** [comment]
I think this is working now, however, localization is far from being complete. Please re-open if you still have issues with localized device labels
