### ISSUE TITLE
	Device attributes of 'boolean' should not be avaraged in graph 

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#1060]
If boolean devices change there value within a period shorter than 5 minutes they are not shown correctly in graph. It seems that this values are avaraged like normal numeric values which leads to missing state change events in the graph. See also discussion on https://forum.pimatic.org/topic/2793/device-attributes-of-boolean-should-not-be-avaraged-in-graph.

**Comment by mwittig** [comment]
See follow-up on forum topic.

**Comment by Heizelmann** [comment]
@mwittig Thaqnks for documentation. May be you can add a short explanation about valid format for time contraint strings in interval and experation properties. As far as I know s for seconds, m for minutes, h for hours and y for years is valid. I think for month is no construct available.

**Comment by mwittig** [comment]
@Heizelmann You're right, month is not support, valid time units are: ms, second, seconds, s, minute, minutes, m, hour, hours, h, day, days, d, year, years, y. I'll add that to the schema description.

**Comment by mwittig** [comment]
Oliver has pointed me to the following post which may also be intersting for you https://forum.pimatic.org/topic/44/database-configuration-howto

**Comment by mwittig** [comment]
Documentation now available at https://pimatic.org/pages/config/
