### ISSUE TITLE
error [pimatic]: A uncaught exception occured: Error: dns service error: unknown

### ISSUE THREAD

**Issue by martially1965** [pimatic/pimatic#1062]
Hi Folks,
I got this after installing node-red plugin and a couple of days ago the same for something I dont remember. As ist says "please report it!", I wanna be good boy :-)

error [pimatic]: A uncaught exception occured: Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-´hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Thanks for reporting! The issue appears to be related to pimatic-hap and thus, I have created another issue at https://github.com/michbeck100/pimatic-hap/issues/69

**Comment by michbeck100** [comment]
Please see https://github.com/michbeck100/pimatic-hap/issues/10
There's nothing I can do, as this is most likely a network problem. This issue can closed.

**Comment by mwittig** [comment]
@martially1965 Did you follow the [installation instructions](https://github.com/michbeck100/pimatic-hap/blob/master/README.md#installation)? Make sure the avahi stuff is installed & running, properly. See also https://github.com/michbeck100/pimatic-hap/issues/63
