### ISSUE TITLE
Cannot start pimatic

### ISSUE THREAD

**Issue by quintz** [pimatic/pimatic#1064]
Hi

after a long while I wanted to update pimatic via frontend and encountered an error.
Then I moved to ssh and wanted to do a 

sudo pimatic.js restart

but nothing happened and it prompted me this error

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'logrotate-stream'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/daemon.coffee:30:10)
>     at Module._compile (module.js:409:26)
>     at Object.compile (/home/pi/pimatic-app/node_modules/pimatic/coffee-cache.js:169:17)
>     at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:5:12)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3

Anyone got an idea what's missing?

**Comment by quintz** [comment]
Okay, I just installed the logrotate-stream module via

`npm install logrotate-stream`

and now it works again...weird.
Is it possible that after a previous update one of my addons needs thie logrotate-stream module?

**Comment by quintz** [comment]
Okay after installing manually modules I reached a point where this isn't working anymore...

`A uncaught exception occured: Error: Cannot find module 'jsonlint'
23:29:04.797 [pimatic]>    at Function.Module._resolveFilename (module.js:325:15)
23:29:04.797 [pimatic]>    at Function.Module._load (module.js:276:25)
23:29:04.797 [pimatic]>    at Module.require (module.js:353:17)
23:29:04.797 [pimatic]>    at require (internal/module.js:12:17)
23:29:04.797 [pimatic]>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:26:12)
23:29:04.797 [pimatic]>    at Module._compile (module.js:409:26)
23:29:04.797 [pimatic]>    at Object.compile (/home/pi/pimatic-app/node_modules/pimatic/coffee-cache.js:169:17)
23:29:04.797 [pimatic]>    at Module.load (/home/pi/pimatic-app/node_modules/pimatic/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
23:29:04.797 [pimatic]>    at Function.Module._load (module.js:300:12)
23:29:04.797 [pimatic]>    at Module.require (module.js:353:17)
23:29:04.797 [pimatic]>    at require (internal/module.js:12:17)
23:29:04.797 [pimatic]>    at Object.startup (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:92:20)
23:29:04.797 [pimatic]>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
23:29:04.797 [pimatic]>    at Object.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:20:3)
23:29:04.797 [pimatic]>    at Module._compile (module.js:409:26)
23:29:04.797 [pimatic]>    at Object.Module._extensions..js (module.js:416:10)
23:29:04.797 [pimatic]>    at Module.load (module.js:343:32)
23:29:04.797 [pimatic]>    at Function.Module._load (module.js:300:12)
23:29:04.797 [pimatic]>    at Function.Module.runMain (module.js:441:10)
23:29:04.797 [pimatic]>    at startup (node.js:139:18)
23:29:04.797 [pimatic]>    at node.js:968:3
23:29:04.797 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!`

**Comment by mwittig** [comment]
Most likely, the update via frontend failed as pimatic 0.9 requires node version 4.x and you have node version 0.10. Please make sure you have the right versions of **node** and **npm** installed! Some users also had installation problems as they had different versions of node installed at the same time. My suggestion is to start with a clean install. Please make sure to follow the installation instructions given on the web site. 

Please keep a copy of your "old" config.json and other assets you may require at a later point. See documentation for details. Some useful hints are also given as part of pimatic user forum. I am closing this ticket know. Please follow up on pimatic forum which will give better and speedy support from a growing user base. 

https://pimatic.org/guide/getting-started/
https://forum.pimatic.org/
