### ISSUE TITLE
[wmi-plugin]

### ISSUE THREAD

**Issue by MarcelMertens** [pimatic/pimatic#1066]
The wmi-plugin throws me the following error:

`error [pimatic]: A uncaught exception occurred: Error: spawn wmic ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 This is most probably a bug in pimatic or in a module, please report it!`

My config
`    {
      "host": "192.168.0.13",
      "username": "wmiquery",
      "password": "xxxxxxxxx",
      "command": "select * from Win32_Processor",
      "attributes": {},
      "id": "wmi-test",
      "name": "wmi_test",
      "class": "WmiSensor"
    }`

**Comment by thost96** [comment]
@MarcelMertens  
Could you please check if the destination hosts firewall is turned off? Or the inbound rule is set correctly?
Do you get any results if you using another query like ' Select * from Win32_LocalTime' ? 

If not, please check that the username and passwort are correct and your user has enough rights on the destination host.

**Comment by mwittig** [comment]
No response from @MarcelMertens 
If you whish to follow up on this please use the referenced issue above
