### ISSUE TITLE
Cannot access DummyLedLight variables via rule configuration.

### ISSUE THREAD

**Issue by scobby** [pimatic/pimatic#1068]
Hello,

i cannot access the values from the "DummyLedLight".
All Variables from the Dummy LED Device are not readable via rule.
The only rule i can build is based on change events ($kueche.power changes). Even the combination of the change event and on/off check doesnt work. And Change events from "DummyLedLight" work very strange. if the frontend in opened the event gets fired all the time. So the light goes on/off/on/off....  When i close the frontend, the switching is stopped. 

This rule doesnt work:

when $kueche.power = "on"
then
press mood-kueche-alltag-szene

**Comment by scobby** [comment]
same for .color .mode  and .brigthness

**Comment by mwittig** [comment]
I must admit the behaviour of the power switch is weird, but it is possible to use it and the other attributes as part of rules. You will find a full blown example here: https://forum.pimatic.org/topic/2999/pimatic-johnny-five-rgb-led-can-t-choose-color/6

**Comment by scobby** [comment]
But the variables do not working in the rule .... i can react only to change events not variables .... i tried and implemented the  "change"-Event. But this is far from reliable ...

**Comment by mwittig** [comment]
Did you try the following?

```
when $kueche.power changes and if power of kueche is on 
then press mood-kueche-alltag-szene
```

This combination works reliably for me in the setting described in the forum thread

**Comment by scobby** [comment]
yeah, this works. thanks for help!

But why doesnt this work?

when kueche is switched off
then press mood-kueche-alltag-szene
