### ISSUE TITLE
pimatic crashes every time on a specified RULE

### ISSUE THREAD

**Issue by hyp3rx** [pimatic/pimatic#1070]
Hello,

just created a rule which should execute an command.
After several tries, pimatic completely crashes every time after i create the rule,
unfortunately the reason for the crash cannot be seen on pimatic-deamon.log

rule:

```
When:
check-einfahr is turned on
then:
execute "/usr/bin/vlc -vvv rtsp://192.168.178.141/unicast --sout=file/ts:/home/pi/recording-$(date +"%Y%m%d%H%M%S").ts -I dummy --stop-time=5 vlc://quit"

**Comment by mwittig** [comment]
Does the command terminate after 5 secs as it should when called from the command line?

**Comment by mwittig** [comment]
No feedback received. I assume the issue has been resolved. 

Please re-open otherwise and provide more information. Thanks
