### ISSUE TITLE
SQLITE_ERROR: no such table

### ISSUE THREAD

**Issue by joshendriks** [pimatic/pimatic#1073]
When using sqlite in memory table, pimatic crashes regularly with the error that a table does not exist although logging shows the table was create on startup.

I think this has to do with the fact that in memory databases are not shared over multiple connections by default. This means that each time Knex reconnects, a new database is made. 

Currently I'm testing this by using 'file::memory:?cache=shared' instead of ':memory:' in my config. This also needs a change in database.coffee. I will commit the change when successful.

See https://stackoverflow.com/questions/15720700/can-two-processes-access-in-memory-memory-sqlite-database-concurrently for more info.

**Comment by joshendriks** [comment]
This issue can be closed when #1076 is merged

**Comment by mwittig** [comment]
Thanks again for your contribution! I'll also publish a new release within the next couple of hours
