### ISSUE TITLE
Error in Pimatic-Ultrasonic

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#1074]
Hello,

I'm getting this error:

error [pimatic]: please call `usonic.init()` first
09:55:46error [pimatic-ultrasonic,Ultrasonic]: Error restoring changed device ultrasonic: please call `usonic.init()` first

**Comment by mwittig** [comment]
As the issue is with Pimatic-Ultrasonic which is separate project I am closing this ticket now. Please use the following tickt for fcorrespondence: 

https://github.com/wutu/pimatic-ultrasonic/issues/6
