### ISSUE TITLE
vhduino - High CPU usage since the last update

### ISSUE THREAD

**Issue by yaba** [pimatic/pimatic#1077]
I've updated yesterday to the latest version.
After reboot, process vhduino is always using CPU at 90% (and more)
Thanks.

**Comment by mwittig** [comment]
What do you mean by last update? Did you update your Raspbian OS?

**Comment by yaba** [comment]
Yes, both Raspbian and Pimatic.

**Comment by mwittig** [comment]
Closing this one. Please use https://github.com/pimatic/virtualhomeduino/issues/3 for further correspondence. Thanks

**Comment by mwittig** [comment]
> Yes, both Raspbian and Pimatic.

Ok, thanks. The issue is caused by the new kernel.
