### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by zmathe91** [pimatic/pimatic#1080]
Hello i just found this bug.

![image](https://user-images.githubusercontent.com/29460286/29913969-b5cac7e4-8e2e-11e7-9e0d-562a5d9412b4.png)

**Comment by mwittig** [comment]
The issue seems to be related to pimatic-bme280. Does it also occur when you run pimatic with configuration excluding the BME280Sensor devices?

If "no", please open a ticket at: https://github.com/atus/pimatic-bme280/issues
Thanks

**Comment by mwittig** [comment]
As there has been no feedback so far I have opened an issue on the aforementioned plugin project. 

Please use the following ticket for further correspondence:  https://github.com/atus/pimatic-bme280/issues/2
