### ISSUE TITLE
[pimatic-mobile-frontend] "Client error: Script error" with MacOS and Safari

### ISSUE THREAD

**Issue by osxdoc** [pimatic/pimatic#1082]
Since some month I get the error message "error [pimatic-mobile-frontend]: Client error: Script error".
All other Browsers without error and no Error with iOS Safari.
![bildschirmfoto 2017-11-20 um 20 57 43](https://user-images.githubusercontent.com/19705969/33038728-e6e3963e-ce35-11e7-9f1a-e43b8e1b2b59.png)

**Comment by mwittig** [comment]
Which version of OS X and Safari are using on the Mac?

**Comment by mwittig** [comment]
I am closing this now as there has been no feedback on the matter. 
Please re-open if you wish to follow-up.

**Comment by osxdoc** [comment]
Version 11.0.2 (13604.4.7.1.3)
But I think the problem is the installed 1Password extension in Safari.

**Comment by mwittig** [comment]
Thanks for the update. Does it work when you deactivate or remove the "1Password" extension?

**Comment by osxdoc** [comment]
OK, some hours later. It is not the the "1Password" extension, I think it is the "Ghostery" extension (but the pimatic page is on the whitelist).

**Comment by mwittig** [comment]
No follow-up. Please re-open if you have further input or comments
