### ISSUE TITLE
Collection of Data for Graphs

### ISSUE THREAD

**Issue by Man-in-Black** [pimatic/pimatic#1086]
Hey all together,

I have a little Problem sind I updates to Pimatic v0.9:
My graphs are working very fine with pimatic v0.8.
Since v0.9 the intervals within my graphs between each point is about 9 hours (although I'm in the 24 hours view).
This is the 24 hours view:
![2017-12-06 12_26_11-graph](https://user-images.githubusercontent.com/9048534/33659492-b1a682c2-da80-11e7-95ce-51b86e345f2b.png)
This is the 1 year view:
![2017-12-06 12_27_08-graph](https://user-images.githubusercontent.com/9048534/33659526-cdf80496-da80-11e7-9a76-231c636d6dd7.png)

What can this problem be?

I'm happy about every answer.

Kind regards

Sascha Jelinek

edit: I have this problem with every graph in my pimatic installation.

**Comment by mwittig** [comment]
For general support cases and questions please use our Forum. Thanks
https://forum.pimatic.org
