### ISSUE TITLE
error [pimatic]: Cannot find module 'bitset.js'

### ISSUE THREAD

**Issue by S7EN** [pimatic/pimatic#1091]
Hi, i just got this error and my heating thermostats are not shown. I made update & upgrade of the raspi but nothing changed. I think this is the problem of pimatic-maxcul plugin I updated minutes before.

**Comment by mwittig** [comment]
pimatic-maxcul is not maintained by the pimatic project and thus I am closing this issue. 

Nonetheless, I have filed a PR on pimatic-maxcul to hopefully fix the issue you came across.

**Comment by mwittig** [comment]
pimatic-maxcul@1.0.2 has been released which fixes the issue
