### ISSUE TITLE
Fatal error Repository not found BME280

### ISSUE THREAD

**Issue by Routout** [pimatic/pimatic#1101]
Hi,

Tried to install BME280 plugin with error repository not found.
Log attached
[npm-debug.log](https://github.com/pimatic/pimatic/files/2146799/npm-debug.log)

**Comment by mwittig** [comment]
This is a known issue which we discussed on forum recently. I tried to fix it, but another user reported it did not work for him either. If you want to give it a try you can install: pimatic-i2c-bme280

**Comment by Routout** [comment]
This one seem installing but when trying to add device it gives Cannot find module 'node-bme280' error.
I checked with i2c tools that address is 0x76 and I can get readings from BME with a python script.

**Comment by Routout** [comment]
Same error. Theres no pimatic bme-280 folder. I installed pimatic-i2c-bme280 via command line, there was no errors.
`sudo npm install pimatic-i2c-bme280 --unsafe-perm
npm WARN deprecated coffee-script@1.9.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
\
> i2c@0.2.3 install /home/pi/pimatic-app/node_modules/pimatic-i2c-bme280/node_modules/i2c-bme280/node_modules/i2c
> node-gyp rebuild

make: Entering directory '/home/pi/pimatic-app/node_modules/pimatic-i2c-bme280/node_modules/i2c-bme280/node_modules/i2c/build'
  CXX(target) Release/obj.target/i2c/src/i2c.o
  SOLINK_MODULE(target) Release/obj.target/i2c.node
  COPY Release/i2c.node
make: Leaving directory '/home/pi/pimatic-app/node_modules/pimatic-i2c-bme280/node_modules/i2c-bme280/node_modules/i2c/build'
pimatic-i2c-bme280@0.9.0 pimatic-i2c-bme280
└── i2c-bme280@1.0.0 (i2c@0.2.3)`

My config includes only this, and no other instances of bme280

`{
      "plugin": "i2c-bme280",
      "active": true
    }`

**Comment by mwittig** [comment]
Can you please send along the log file indicating the error: `Cannot find module 'node-bme280' error`
Thanks in advance

**Comment by Routout** [comment]
Let me know if you want any other log.
[log.txt](https://github.com/pimatic/pimatic/files/2149437/log.txt)

**Comment by mwittig** [comment]
Thank you very much. The log file was to  analyzing the problem. I think it is fixed now. Please try the new version 0.9.1 of pimatic-i2c-bme280

**Comment by Routout** [comment]
How to install version 0.9.1? Plugins page shows 0.9.0.

**Comment by mwittig** [comment]
Oooops, sorry. Apparently, I forgot to publish the package. 

Done, now. Should be visible via Plugins page in a few minutes,

**Comment by Routout** [comment]
Working great now, thanks.

**Comment by mwittig** [comment]
Changes are now also available as pimatic-bme280@0.1.3
Closing this now
