### ISSUE TITLE
error [pimatic]: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by FrankyB1983** [pimatic/pimatic#1102]
After re-installing Pimatic I used a backup of my config.json file, but I get some strange errors.
This config file always worked great by the way.

This is the full error report:

error [pimatic,VariablesDevice]: Error getting attribute value E-today.E-vandaag: Could not parse expression
11:14:38error [pimatic,VariablesDevice]: Error getting attribute value t-total.Total Power: Could not parse expression
11:14:38error [pimatic,VariablesDevice]: Error getting attribute value T2-today.power: Could not parse expression
11:14:38error [pimatic,VariablesDevice]: Error getting attribute value T1-today.power: Could not parse expression
11:14:38error [pimatic]: Could not parse rule "when its 00:59:45 or its 01:59:45 or its 02:59:45 or its 03:59:45 or its 04:59:45 or its 05:59:45 or its 06:59:45 or its 07:59:45 or its 08:59:45 or its 09:59:45 or its 10:59:45 or its 11:59:45 or its 12:59:45 or its 13:59:45 or its 14:59:45 or its 15:59:45 or its 16:59:45 or its 17:59:45 or its 18:59:45 or its 19:59:45 or its 20:59:45 or its 21:59:45 or its 22:59:45 or its 23:59:45 then set $G-temp to $G-from-logfile.gas": Could not find an provider that provides the next action of "set $G-temp to $G-from-logfile.gas".
11:14:38error [pimatic]: Could not parse rule "when its 00:00:45 then set $G-at-night to $G-from-logfile.gas": Could not find an provider that provides the next action of "set $G-at-night to $G-from-logfile.gas".
11:14:37error [pimatic]: Could not parse rule "when its 0:00:00 then set $T1-at-night to $T1-from-logfile.power and set $T2-at-night to $T2-from-logfile.power and set $T1-col-at-night to $T1-col-from-logfile.power and set $T2-col-at-night to $T2-col-from-logfile.power": Could not find an provider that provides the next action of "set $T1-at-night to $T1-from-logfile.power and set $T2-at-night to $T2-from-logfile.power and set $T1-col-at-night to $T1-col-from-logfile.power and set $T2-col-at-night to $T2-col-from-logfile.power".
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value G-today.G-vandaag: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value G-last-hour.G-laatste-uur: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T2-col-today.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T1-col-today.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T2-consumed-today.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T1-consumed-today.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T2-total.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value T1-total.power: Could not parse expression
11:14:28error [pimatic,VariablesDevice]: Error getting attribute value E-actual-power.E-actueel: Could not parse expression
11:14:24error [pimatic]: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Any help is appreciated!

**Comment by mwittig** [comment]
Most likely, you are using the wrong Node.js version. Please follow the installation guidelines given below and please use the pimatic forum for further support. Thanks!

- https://pimatic.teamemo.com/Guide

- https://forum.pimatic.org/
