### ISSUE TITLE
Missing timer/programmer plugin

### ISSUE THREAD

**Issue by mat1990dj** [pimatic/pimatic#1108]
I would like to have a simple timer / programmer like this thing:
![image](https://user-images.githubusercontent.com/5220059/46012538-e3f14700-c0c9-11e8-9055-44b6af711eb8.png)
Currently doing it with rules but it's very cumberstone and I'm having a lot of rules.
I would be great to have a timer on UI to be able to add time, turn on/off etc....

**Comment by mwittig** [comment]
Please post feature requests at https://forum.pimatic.org/category/14/feature-requests

Thanks!
