### ISSUE TITLE
Can´t Login Webinterface

### ISSUE THREAD

**Issue by xleeverx** [pimatic/pimatic#1112]
I have now reinstalled Pimatic several times. Another SD card used. And other versions.
I can not log in via webinterface. After I entered username and password, I am back on the home page to login.

About my iphone but it works.

Does anyone know the problem ?

I currently ntuze the 9.42

**Comment by mwittig** [comment]
Please check the trouble shooting section of our user forum: 
https://forum.pimatic.org

Thanks
