### ISSUE TITLE
[pimatic-mobile-frontend} FF & chrome loading with wrong width on first load

### ISSUE THREAD

**Issue by akicker** [pimatic/pimatic#1119]
This issue can be corrected by inserting at the end of: `/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/app/views/pages/index.jade` 
```
script.
      if (typeof(Event) === 'function') {
         // modern browsers
         window.dispatchEvent(new Event('resize'));
      } else {
        // for IE and other old browsers
        // causes deprecation warning on modern browsers
        var evt = window.document.createEvent('UIEvents');
        evt.initUIEvent('resize', true, false, window, 0);
        window.dispatchEvent(evt);
      };

**Comment by mwittig** [comment]
I don't think this can be placed in the jade file unless it is as script template

**Comment by mwittig** [comment]
@akicker Do you have a reproducible example where the width is wrong on first startup? I have tested with FF, Chrome and Edge and I could not find anomalies.

**Comment by akicker** [comment]
Hi Marcus,

 

This is known Problem with FF, Opera, Chrome and Chromium – ask Google: “chrome loading with wrong width on first load”

Same effect at the right corner after reloading the page – remains until Browser itself is resized or entering Menu and leaving again.

No Problem using Edge or IE ;-( 

And its reproducible – see todays screenshots (using Chrome) Home Development without workaround, Home Control with my workaround

Both running the latest mobile-frontend 0.9.14. Maybe my 8 tabs cause the problem ?

 



 



 

Solution found at:  <https://stackoverflow.com/questions/1818474/how-to-trigger-the-window-resize-event-in-javascript> https://stackoverflow.com/questions/1818474/how-to-trigger-the-window-resize-event-in-javascript

… this can be placed in the jade file – works after restarting the system 😉

Kind Regards 

August Kicker

 

Von: Marcus Wittig <notifications@github.com> 
Gesendet: Dienstag, 26. März 2019 14:37
An: pimatic/pimatic <pimatic@noreply.github.com>
Cc: Guss <a.kicker@aon.at>; Mention <mention@noreply.github.com>
Betreff: Re: [pimatic/pimatic] [pimatic-mobile-frontend} FF & chrome loading with wrong width on first load (#1119)

 

@akicker <https://github.com/akicker>  Do you have a reproducible example where the width is wrong on first startup? I have tested with FF, Chrome and Edge and I could not find anomalies.

**Comment by mwittig** [comment]
I was able to reproduce the issue. Fix landed in master will be published with the next release
