### ISSUE TITLE
[pimatic-mobile-frontend] This page is not secure - Chrome Browser - Let’s Encrypt

### ISSUE THREAD

**Issue by mathiaslehmann** [pimatic/pimatic#1120]
Hey folks,
I noticed today that when calling the Pimatic website in the Chrome browser this website is not marked as safe. The website is accessed via an external DynDNS address + port via https with a certificate from Let's Encrypt.
The crazy is now, delete the stored data (caches) of the website and call the website again, the connection is first marked as safe. If I close the browser and call up the website again, it is suddenly no longer safe. It uses Pimatic 0.9.47 and pimatic-mobile-frontend 0.9.14. With other browsers (IE and Firefox) also tested, there is not this problem. Does anyone have an idea what this may be?

This is how it looks after the first visit to the website......

![image](https://user-images.githubusercontent.com/16978467/55333689-1c6a4700-5498-11e9-85ac-f27e705bc79f.png)

And so all the other calls of the website......

![image](https://user-images.githubusercontent.com/16978467/55333098-e4163900-5496-11e9-9b04-c1a7f8869423.png)

**Comment by mwittig** [comment]
No idea, why this happens. Do you always use the same URL, i.e external
hostname as part of the URL, to access the site?
If not, make sure all names are are registered with certificate, i.e.
certificate must contain all names as subject or subjectAltName.

Am Mo., 1. Apr. 2019 um 16:09 Uhr schrieb mathiaslehmann <
notifications@github.com>:

**Comment by mwittig** [comment]
Did you check the web console for any error or warning messages?

**Comment by mathiaslehmann** [comment]
**I tested it once.**

**If the page is loaded the first time (browser cache is still empty) I get the following return. 
Please note that I have falsified my URL (replaced with "URL:PORT").**

> :9094/:1 Creating Application Cache with manifest https://URL:PORT/application.manifest
:9094/:1 Application Cache Checking event
URL:PORT/:1 Application Cache Downloading event
URL:PORT/:1 Application Cache Progress event (0 of 41) https://URL:PORT/worker-json.js
URL:PORT/:1 Application Cache Progress event (1 of 41) https://URL:PORT/assets/index-b27f56742beba8b1b756650136f28eec.js
URL:PORT/:1 Application Cache Progress event (2 of 41) https://URL:PORT/
URL:PORT/:1 Application Cache Progress event (3 of 41) https://URL:PORT/assets/groups-page-20044cde96d0b0998ab0401ff9873225.js
URL:PORT/:1 Application Cache Progress event (4 of 41) https://URL:PORT/socket.io/socket.io.js
URL:PORT/:1 Application Cache Progress event (5 of 41) https://URL:PORT/assets/config-page-b58104dc08e4989824e111b4e9a2cb72.js
URL:PORT/:1 Application Cache Progress event (6 of 41) https://URL:PORT/assets/editor-f6b289578a25e1bf99032a1d581048f4.js
URL:PORT/:1 Application Cache Progress event (7 of 41) https://URL:PORT/assets/variables-page-8e081548292db5a953b5caad266d7f0f.js
URL:PORT/:1 Application Cache Progress event (8 of 41) https://URL:PORT/api/decl-api-client.js
URL:PORT/:1 Application Cache Progress event (9 of 41) https://URL:PORT/assets/add-item-page-0b0bb3992c435ca7cb6dafa445d08276.js
URL:PORT/:1 Application Cache Progress event (10 of 41) https://URL:PORT/assets/base-96c2e43ac38f883a0d3d42d24f11bced.css
URL:PORT/:1 Application Cache Progress event (11 of 41) https://URL:PORT/assets/textcomplete-1538f8f3baeff05ec9134e065cea2cdf.js
URL:PORT/:1 Application Cache Progress event (12 of 41) https://URL:PORT/assets/log-page-a764c13c75464fd183cd515ccb6bdc9d.js
URL:PORT/:1 Application Cache Progress event (13 of 41) https://URL:PORT/assets/base-6efe1007dc7bb1afba34400947d11a0c.js
URL:PORT/:1 Application Cache Progress event (14 of 41) https://URL:PORT/assets/database-page-893ffa723af66f9ceb16c8bae97333d5.js
URL:PORT/:1 Application Cache Progress event (15 of 41) https://URL:PORT/assets/datepicker-28671e2240c35d686ede27b3dd1c313e.js
URL:PORT/:1 Application Cache Progress event (16 of 41) https://URL:PORT/assets/devicepages-page-a937234c4b8d1f14840095cd8ea81757.js
URL:PORT/:1 Application Cache Progress event (17 of 41) https://URL:PORT/assets/devices-page-eab7b3e7e19466b9c6616493b08cb73c.js
URL:PORT/:1 Application Cache Progress event (18 of 41) https://URL:PORT/assets/plugins-page-6151e41ca99b0f1ba48bd8d10c4f4095.js
URL:PORT/:1 Application Cache Progress event (19 of 41) https://URL:PORT/assets/edit-device-page-d2fb1c6c785e83c62c9e97fe16c93bf4.js
URL:PORT/:1 Application Cache Progress event (20 of 41) https://URL:PORT/assets/dygraph-8c88be3f573da706760ad2a4a8f6c6b1.js
URL:PORT/:1 Application Cache Progress event (21 of 41) https://URL:PORT/assets/edit-devicepage-page-973690ee24c348a21bdec69a61c1a543.js
URL:PORT/:1 Application Cache Progress event (22 of 41) https://URL:PORT/assets/events-page-f6756d8a75408ef16a56b60f5211595c.js
URL:PORT/:1 Application Cache Progress event (23 of 41) https://URL:PORT/assets/edit-group-page-756c090299de3ced5697c7192477656e.js
URL:PORT/:1 Application Cache Progress event (24 of 41) https://URL:PORT/assets/edit-plugin-page-2359f78aedf71421652cdd73341ee092.js
URL:PORT/:1 Application Cache Progress event (25 of 41) https://URL:PORT/assets/edit-rule-page-95f2233bfa2111c6d9f5ed3cb9fd4427.js
(index):1 Application Cache Progress event (26 of 41) https://URL:PORT/assets/editor-5825958ee036f091c4ca8f8eae38bcf8.css
(index):1 Application Cache Progress event (27 of 41) https://URL:PORT/assets/edit-variable-page-71a3587ac28495844ff8e92cbec10a75.js
(index):1 Application Cache Progress event (28 of 41) https://URL:PORT/theme/graphite/water.css?save=1
(index):1 Application Cache Progress event (29 of 41) https://URL:PORT/apple-touch-icon-precomposed.png
index-b27f56742beba8b1b756650136f28eec.js:4 DOMException: Failed to execute 'update' on 'ApplicationCache': there is no application cache to update.
    at n.<anonymous> (https://URL:PORT/assets/index-b27f56742beba8b1b756650136f28eec.js:4:402)
    at n.emit (https://URL:PORT/socket.io/socket.io.js:2:28725)
    at n.onopen (https://URL:PORT/socket.io/socket.io.js:1:28686)
    at n.<anonymous> (https://URL:PORT/socket.io/socket.io.js:1:28045)
    at n.emit (https://URL:PORT/socket.io/socket.io.js:2:28725)
    at n.onOpen (https://URL:PORT/socket.io/socket.io.js:2:5286)
    at n.onHandshake (https://URL:PORT/socket.io/socket.io.js:2:6246)
    at n.onPacket (https://URL:PORT/socket.io/socket.io.js:2:5728)
    at o.<anonymous> (https://URL:PORT/socket.io/socket.io.js:2:3527)
    at o.n.emit (https://URL:PORT/socket.io/socket.io.js:2:28725)
(index):1 Application Cache Progress event (30 of 41) https://URL:PORT/assets/graph-page-42ccb7fa7741e9d751de3fca0a6b78ba.js
(index):1 Application Cache Progress event (31 of 41) https://URL:PORT/apple-touch-icon-76x76-precomposed.png
socket.io.js:3 WebSocket connection to 'wss://URL:PORT/socket.io/?EIO=3&transport=websocket&sid=5-scHnv_F_1E_BKTAAAR' failed: WebSocket is closed before the connection is established.
n.doClose @ socket.io.js:3
n.close @ socket.io.js:2
r @ socket.io.js:2
o @ socket.io.js:2
s @ socket.io.js:2
r @ socket.io.js:2
n.emit @ socket.io.js:2
n.onClose @ socket.io.js:2
t @ socket.io.js:2
n.close @ socket.io.js:2
n.close.n.disconnect @ socket.io.js:1
(anonymous) @ index-b27f56742beba8b1b756650136f28eec.js:4
n.emit @ socket.io.js:2
n.emit @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonymous) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
r @ socket.io.js:2
(anonymous) @ socket.io.js:2
e.decodePayloadAsBinary @ socket.io.js:2
e.decodePayload @ socket.io.js:2
n.onData @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
i.onData @ socket.io.js:2
i.onLoad @ socket.io.js:2
hasXDR.r.onreadystatechange @ socket.io.js:2
XMLHttpRequest.send (async)
i.create @ socket.io.js:2
i @ socket.io.js:2
o.request @ socket.io.js:2
o.doPoll @ socket.io.js:2
n.poll @ socket.io.js:2
n.onData @ socket.io.js:2
(anonymous) @ socket.io.js:2
n.emit @ socket.io.js:2
i.onData @ socket.io.js:2
i.onLoad @ socket.io.js:2
hasXDR.r.onreadystatechange @ socket.io.js:2
XMLHttpRequest.send (async)
i.create @ socket.io.js:2
i @ socket.io.js:2
o.request @ socket.io.js:2
o.doPoll @ socket.io.js:2
n.poll @ socket.io.js:2
n.doOpen @ socket.io.js:2
n.open @ socket.io.js:2
n.open @ socket.io.js:2
n @ socket.io.js:2
n @ socket.io.js:1
n.open.n.connect @ socket.io.js:1
n @ socket.io.js:1
n @ socket.io.js:1
n @ socket.io.js:1
(anonymous) @ index-b27f56742beba8b1b756650136f28eec.js:4
dispatch @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
g.handle @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
trigger @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
trigger @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
_trigger @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
_create @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
e @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
_create @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
_createWidget @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
_createWidget @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
e.(anonymous function).(anonymous function) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
e.fn.(anonymous function) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
transition @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
change @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
each @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
e.fn.(anonymous function) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
$.mobile.changePage @ index-b27f56742beba8b1b756650136f28eec.js:2
initializePage @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
(anonymous) @ base-6efe1007dc7bb1afba34400947d11a0c.js:5
c @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
fireWith @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
ready @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
s @ base-6efe1007dc7bb1afba34400947d11a0c.js:3
Show 59 more frames
:9094/#login-page:1 Application Cache Progress event (32 of 41) https://URL:PORT/assets/jsonschemaeditor-363a9dc436f5d3954acc0f5747246df4.js
:9094/#login-page:1 Application Cache Progress event (33 of 41) https://URL:PORT/assets/lazyload-14eac26798edd046aa2dcb23df8ca0b1.js
:9094/#login-page:1 Application Cache Progress event (34 of 41) https://URL:PORT/assets/mobiscroll-a09402cf8a8942de9b41c3ad7235af78.js
:9094/#login-page:1 Application Cache Progress event (35 of 41) https://URL:PORT/assets/rules-page-004eed2a111f4344058db87b9ac724fb.js
:9094/#login-page:1 Application Cache Progress event (36 of 41) https://URL:PORT/assets/style-1712915776ea214612bf2ababf080d38.css
:9094/#login-page:1 Application Cache Progress event (37 of 41) https://URL:PORT/assets/updates-page-2af4774208b365b6328b5f3428f32146.js
:9094/#login-page:1 Application Cache Progress event (38 of 41) https://URL:PORT/apple-touch-icon-120x120-precomposed.png
:9094/#login-page:1 Application Cache Progress event (39 of 41) https://URL:PORT/apple-touch-icon-152x152-precomposed.png
:9094/#login-page:1 Application Cache Progress event (40 of 41) https://URL:PORT/theme/graphite/water.css
:9094/#login-page:1 Application Cache Progress event (41 of 41) 
:9094/#login-page:1 Application Cache Cached event
:9094/#login-page:1 Application Cache Checking event
:9094/#login-page:1 Application Cache NoUpdate event
:9094/#login-page:1 Application Cache Checking event
:9094/#login-page:1 Application Cache NoUpdate event


**For all further calls I receive the following return...**

> (index):1 Document was loaded from Application Cache with manifest https://URL:PORT/application.manifest
(index):1 Application Cache Checking event
(index):1 Application Cache NoUpdate event
(index):1 Application Cache Checking event
socket.io.js:3 WebSocket connection to 'wss://URL:PORT/socket.io/?EIO=3&transport=websocket&sid=MI2aDVgWlQ5f2-CZAAAS' failed: WebSocket is closed before the connection is established.
n.doClose @ socket.io.js:3
:9094/#login-page:1 Application Cache NoUpdate event


**To exclude possible plugins, I have to test a new Pimatic installed. Here only the plugin mobile-frontend 0.9.14 and cron 0.8.8 is installed.**

**Is it correct that the browser loads the page only the cache?**
> Document was loaded from Application Cache with manifest https://URL:PORT/application.manifest

**If I delete this area in the cache of the browser, the page loads correctly.**

![image](https://user-images.githubusercontent.com/16978467/55410863-dfb85180-5564-11e9-89a4-d6c0e5cab583.png)

**Comment by mathiaslehmann** [comment]
Hello,

the problem seems to have settled by itself. The current build of Chrome no longer has the problem. Thank you for the effort.
