### ISSUE TITLE
pimatic error unexpected token illegal

### ISSUE THREAD

**Issue by defmeggi** [pimatic/pimatic#1121]
After inserting the homeduino plug-in in the json.config (correctly) i got the following pimatic error when starting:
error [pimatic]: Unexpected token ILLEGAL

Well, it doesnt prevent it from starting, but i think it didnt load homeduino correctly, cause i cant access it for messages.

Anybody ideas, what went wrong?

**Comment by mwittig** [comment]
It is an issue which hits some users with the current releases. You can downgrade  the homeduino plug-in to 0.9.12 for now. 

```
# Stoppimatic
cd /home/pi/pimatic-app/node_modules/
sudo rm -rf pimatic-homeduino
sudo npm install pimatic-homeduino@0.9.12 --unsafe-perm
# Start pimatic again
```

See also https://forum.pimatic.org/topic/4608/pimatic-homeduino-0-9-13

**Comment by defmeggi** [comment]
Thank you mwittig! Didnt recognize that the issue already exits. It worked after downgrading :)

**Comment by mwittig** [comment]
Please also not the latest version of pimatic-homeduino resolved the issue
