### ISSUE TITLE
round(variabe, x) makes trouble on fresh db

### ISSUE THREAD

**Issue by 0rTiN** [pimatic/pimatic#1128]
Pimatic seems to have problems with a fresh/new DB with an exisitng config.json which contains variables which are rounded by using ```round(variabel, x)``` resp. ```round(device.variable, x)```.
My Pimatic system was not able to startup. 

The log shows nothing. The command prompt show:
``` 20:59:21.015 [pimatic] Could not update variable stromverbrauch.strom-gesamt: Expected variable vzlogger-strom.gesamt to have a numeric value.```

This is only one of many more entries. 

After I deleted all (66) rounding functions in the devices section of the config.json Pimatic came up again.

**Comment by mwittig** [comment]
I think this [has been fixed](https://github.com/pimatic/pimatic/commit/abd2520e6c02c5dc96f1b6831c64a8f160ef0af9). Please re-open if the problem is still occuring
