### ISSUE TITLE
Limit reached?

### ISSUE THREAD

**Issue by Bashtastic** [pimatic/pimatic#1135]
When adding items to a page in the front end of Pimatic by pressing the '+' next to a item in the selection section nothing seems to happen, the plus sign doesn't change into a '✓'. The pimatic-deamon log also doesn't output anything related. Also after adding a rule the rule doesn't show up at the rules page. Therefore I get the feeling that I may have ran into a limit of sorts.

**Comment by mwittig** [comment]
For general support queries please use the pimatic forum

Regarding your problem I don't this this a limitation problem but a caching problem. Normally, using "Reload" in the browser solves the problem
