### ISSUE TITLE
Cannot login webui

### ISSUE THREAD

**Issue by Flight777** [pimatic/pimatic#1141]
Getting the following error on first try to login, afterwhich I keep getting Websocket resets in the browser debug:

![image](https://user-images.githubusercontent.com/5236143/68998437-b4476480-08b2-11ea-977a-dd8a1613bfdb.png)

**Comment by mwittig** [comment]
Sorry for the delay in reply. For general support queries please use the pimatic forum - https://forum.pimatic.org/
