### ISSUE TITLE
Pimatic 0.9.54 problems

### ISSUE THREAD

**Issue by hansjeu** [pimatic/pimatic#1142]
I just updated pimatic to version 0.9.54
On a simple installation it worked but on a somewhat more compicated install (using mqtt) i got in to problems.
First the update could not be restarted. After 10 minutes i had to use a powercut.
Result pimatic dit not start.

I put an older image on the sd and updated again.
All worked but no mqtt. 

Is there a way to update to 0.9.53????????

**Comment by mwittig** [comment]
That sound strange. Other use updated to 0.9.54 without problems. To investigate further please let me know which Node.js version and which Debian version you're using.

You can downgrade as follows:

```
cd /home/pi/pimatic-app/node_modules/pimatic
sudo npm i pimatic@0.9.53

**Comment by hansjeu** [comment]
Thanks for the response.
I wil test everthing Monday.

Greetings Hans

**Comment by hansjeu** [comment]
Hello I am using node 4.6.12
And i am using Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

**Comment by mwittig** [comment]
See also https://forum.pimatic.org/topic/4536/solved-not-able-to-do-a-simple-pimatic-installation-on-raspi-3b 

The resolution for now is to downgrade to an earlier version of pimatic-mqtt if node v4 is used
