### ISSUE TITLE
Broken Update Server

### ISSUE THREAD

**Issue by fbeek** [pimatic/pimatic#1152]
Hello together,

I think the update Server is down, i only get a 502 from api.pimatic.org an now my pimatic ist broken after a reboot.

Regards

**Comment by 00lex** [comment]
agree but my pimatic works. just when is try to update, I get 13 error messages 

https://pastebin.com/raw/NY5ZPTEX

**Comment by fbeek** [comment]
Hi, thanks for your reply. The problem is that my pimatic is dockerized and i rebooted to test a new plugin version. So i cleared my temp volume for packages und pimatic cant install the missing plugins because the update server is not responding. I fixed this now by manually installing the missing plugins and now everything runs smooth. Except for the update check.

I think it would be nice if pimatic would have an install fallback if the server is not available.

Is the code of the api server open source so that i can setup an own server?

**Comment by tehmilcho** [comment]
Still down? :-(

**Comment by fbeek** [comment]
Yes....

**Comment by 00lex** [comment]
its vacation time in Germany. I don't believe michbeck100 can fix this in the next days. 
be patiently and make backups :)

**Comment by mwittig** [comment]
Please be patient. I need to get Oliver to restart the Server

**Comment by mwittig** [comment]
Update Server is back to normal
