### ISSUE TITLE
Wiki not acessible

### ISSUE THREAD

**Issue by Woodhousemelena** [pimatic/pimatic#1173]
The wiki appears to be down...  anyone inclined to fix it?

**Comment by Woodhousemelena** [comment]
I am just presented with a login request, for which I don´t have the right credentials.....

**Comment by mwittig** [comment]
Unfortunately, TEAMMEMO.COM, the company which served our wiki is out of business. There are currently no plans to re-establish the wiki. As the project is currently not actively maintained.
