### ISSUE TITLE
PiMatic still supported/under development ?

### ISSUE THREAD

**Issue by will-code-for-pizza** [pimatic/pimatic#1174]
Hi folks,
I this project still alive or should I switch to IO-broker for bleeding edge environment ?

Regards
Will

**Comment by fbeek** [comment]
Hi,

i think it is dead, the last release is really old and the supported node version should not be used anyway. 
Also it has some quirks in the update procedure etc.

I you are in search for a new solution i would recommend you Home Assistant.

I switched a few years ago from Pimatic and it was the best decision regarding a smart home solution.

Regards
fbeek

**Comment by Man-in-Black** [comment]
I also switched to HomeAssistant, as it is very easy to setup compared to the process a couple of years ago.

Pimatic was a nice project, but I think HomeAssistant is far more future proof.

**Comment by mjray** [comment]
> the supported node version should not be used anyway.

It appeared to run OK on more recent node. Does it not?

> Pimatic was a nice project, but I think HomeAssistant is far more future proof.

Probably, but that seems far more difficult to set up to anything near the same level of ease of use that pimatic had immediately. As well as ioBroker, the other two obvious possibilities at a glance look to be domoticz (C++) and jeedom (PHP?).

**Comment by 00lex** [comment]
Im sad to see what happens with Pimatic. It was great to think about rules and not how the system works. Pimatic is very easy to understand. I spent so much time in my home automation and have no time for a new setup

**Comment by mwittig** [comment]
You already it guessed it! This project is no longer maintained, unfortunately. Whether or not you should switch to IO-broker. I can't tell. There are also other options like HomeAssistant, openHAB. 

The problem with pimatic is that the code base has become hardly maintainable as almost all underlying technologies have become obsolete. That's the downside of the rapidly emerging web technologies we have seen in the passed years!

- CoffeeScript is obsolete, 
- NodeJS created huge legacy issues and problems with backwards compatibility issues. Some people even say NodeJS is dead and one should use Bun now. Great for new projects, horror for project maintenance
- Almost all packages use for the pimatic UI are completely outdated and obsolete to some extent 
- ... and so on, and so on

So, it is not just a lack of developers ... this project requires re-implementation which is an effort several man years of development effort. 

Personally, I am planning to re-implement the nucleus of pimatic one day, but at the moment I am very busy with other activities and can't commit to this.

**Comment by 00lex** [comment]
Hi and thanks for the clarification, even if you could have guessed. 

A personal question: 
How do you proceed? Continue to use pimatic, or have you already switched? And if, where? 

I've been struggling with Home Assistant for 2 weeks now. But it is going well. Not so easy to get used to a new environment after so many years.
