### ISSUE TITLE
Use of sunrise-plugin

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#123]
Can you explain how to use the sunrise plugin?
I have added the plugin to the config and configured the correct coordinates.
It seems the plugin is working correctly.

How can you create rules for the diverse surnrise/set moments?
A simple rule <code>IF it is sunrise THEN turn light on</code> seems to validate, but anything with with extra time does not work.
For switching lights you really want to set rules like <code>IF it is 30 minutes before sunset THEN turn light on</code>

Am I doning something wrong, or is it currently only supported for the exact moments?

**Comment by t1m02k16** [comment]
still added?? 
it dont work yet :(
it is 262 m before sunset starts

**Comment by mwittig** [comment]
@t1m02k16 see also #320 for your use case

**Comment by mwittig** [comment]
@t1m02k16 The following expression works for me. It will fire the action once, exactly 262 minutes before sunset!
`it is before 262 minutes sunset`

**Comment by t1m02k16** [comment]
no, doesent work

**Comment by t1m02k16** [comment]
it take the rule like this. but the rule do nothing

**Comment by mwittig** [comment]
Well, as I said it works for me. Milight had been switch exactly 180 minutes before sunset. Make sure the timezone and time are proeprly set on your Raspi. To check if you get the correct times you can setup a device to display the sunrise and sunet times.

```
{
      "id": "wsunr",
      "name": "wsunr",
      "rule": "if it is 180 minutes before sunset then switch Milight Zone 1 off",
      "active": true,
      "logging": true
    }
```

```
{
      "attributes": [
        {
          "name": "sunrise",
          "label": "Sunrise"
        },
        {
          "name": "sunset",
          "label": "Sunset"
        }
      ],
      "id": "Sunrise",
      "name": "sunrise-1",
      "class": "SunriseDevice"
    },
```

**Comment by t1m02k16** [comment]
hm.... don´t work :/

      "id": "auto-hue",
      "name": "AUTO HUE",
      "rule": "if it is 130 minutes before sunset then switch hue-var-an on",
      "active": true,
      "logging": true

**Comment by t1m02k16** [comment]
time is korrect
