### ISSUE TITLE
predicate request: temperature is rising/falling

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#151]
Currently I have some rules to detect if a certain (environment) temperature is rising or falling.
The process to do this is a little complex. Could this be build in to detect if a temperature is rising or falling?

My current rules:

    IF $temperature > $PreviousTemp and warmte is turned off 
    THEN $WarmtOp = 1 and $PreviousTemp = $temperature

and

    IF $temperature < $PreviousTemp and warmte is turned off 
    THEN $WarmtOp = 0 and $PreviousTemp = $temperature

The result is, that variable $WarmtOp will be 1 when the temp is rising and 0 if it is falling. Other rules prevent the Central Heating to be turned on when $WarmtOp is 1 (because that means the environment is wamring up by itself), even if it is 'to cold'.

**Comment by sweetpi** [comment]
Implemented.
