### ISSUE TITLE
[pimatic-pilight] Request to pilight timed out

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#158]
I'm using a rule to switch 4 devices when a button on a remote is pressed. However, one of the actions fails with this in the log:

01:07:57error: Error on evaluation of rule condition of rule 0: Request to pilight-daemon timeout

I'm using the latest pilight development build and the latest pimatic stabit.

**Comment by sweetpi** [comment]
pilight is not supported anymore.
