### ISSUE TITLE
Wake on Lan and shutdown your computer with pimatic

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#165]
is there any possibility to boot your pc with pilight ary maybe shut it down.
or maybe in the future it will be a great enhancement.

greetings Stefan

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.

**Comment by thost96** [comment]
@p4co86 I have created a plugin for pimatic called pimatic-wakeonlan. Here you can find more: forum.pimatic.org/topic/990/pimatic-plugin-for-wakeonlan

**Comment by p4co86** [comment]
Thanks for that,but i geht the same error message Mike in the post in thr forum
