### ISSUE TITLE
Request : Display popup with text

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#174]
Just another brainfart :)
Would be nice if you could display some text in the browser with a rule.
To avoid issues if in GUI or not, you could make it only available for switches that are switched from the GUI.
Popup of text could be done with a simple javascript alert popup.

Real life example:
I have created a button in pimatic, and created some rules to do stuff when the button is pressed. However, these rules are only allowed to work if some device(s) is in a specific state. When the button is pressed and the depended device is not in the required state: display a popup with a warning (in my case it is not desirable to switch it to the state is needed to).

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
