### ISSUE TITLE
Request: support for active low relay in GPIO-Plugin

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#180]
We use several relays for several projects, but the relays are slight different then what you would expect.
The relays are "active low", which means that instead of turning on when they get a 3.3V signal from a GPIO port, they turn off... 
If you put a lightbulb on the relay, it will be OFF when the GPIO is switched to ON.

Would it be possible to make an optional setting in the confgi.json to tell if the GPIO is an active low relays or not? When it is set to active low, it should set te GPIO to HIGH when it is in OFF state and vice versa for ON state.

**Comment by Flop2006** [comment]
with this configuration
´´´
    {
      "id": "relais1",
      "class": "GpioSwitch",
      "name": "Relais 1",
      "gpio": 4,
      "inverted": true
    },
´´´
my relay is in OFF state till pimatic is initialized, then its switched. On the Pimatic webinterface, the switch is labled "ON".
With this configuration
´´´
    {
      "id": "relais1",
      "class": "GpioSwitch",
      "name": "Relais 1",
      "gpio": 4,
      "inverted": false
    },
´´´
my relay is in OFF state till pimatic is initialized, then its switched. On the Pimatic webinterface, the switch is labled "OFF" but the relay is "ON".

Is the "default_state" already realised?

**Comment by incmve** [comment]
Your first config is the correct one.
pimtic-gpio uses https://github.com/fivdi/onoff during start onoff sets the GPIO pins to low and pimatic set it to high once started.
I switched to SSR cause everytime my Pi was booted my heating and aquarium switched on for a minute.
When using an active High relais it works good.

**Comment by Flop2006** [comment]
Ok, but why there is no "default_state" option which defines the state on pimatic start. It would fit perfect for my relay. (http://www.ebay.de/itm/DC-5V-4-Channel-Relay-Module-With-Optocoupler-For-Arduino-PIC-ARM-AVR-DSP-/271568818861)

**Comment by sweetpi** [comment]
Done.
