### ISSUE TITLE
Changes in 0.8.0 (WIP)

### ISSUE THREAD

**Issue by sweetpi** [pimatic/pimatic#186]
What changes in pimatic 0.8.0:

## General
- Devices, rules and variables can be assigned to groups.
- (Device-)pages can be created and devices can be assigned to multiple pages.
- A database (defaults to sqlite) is used to save log messages and device attribute changes (#161).
- [socket.io](http://socket.io/) was updated to 1.0.0 and is now included in pimatic itself.
- pimatic has now a explicitly defined API that can be used by third party apps (#181).
- Compilation of CoffeeScript files is cached at first compile. That improves startup time after
  the first start significant.
- Preparations for device creation and editing support. This will be enabled in a next release if
  0.8.0 is considered as stable.

## mobile-frontend
- Most of the settings for the mobile-frontend moved to the general settings section of the framework.
- Logged messages and device attribute changes are displayed in the mobile-frontend.
- The graph page from the datalogger plugin is now included in the mobile-frontend (with some enhancements).
- Rules and Variables moved to own pages.
- There are no "button items" anymore. You can now create a "ButtonsDevice" that can have multiple buttons.
- There are no "variable items" anymore. You can now create  a "VariablesDevice" that displays the value of certain variables / expressions.
- the mobile-frontend has a new flat theme option

## Changes for developers
- The framework replaced [node-convict](https://github.com/mozilla/node-convict) for settings validation with [json-schema](http://json-schema.org/) validation.
  - All settings (framework, plugin, devices) are now in [json-schema](http://json-schema.org/) format and are validated and enhanced with defaults by the framework.
- The way devices are created changed. Documentation will be updated with the release of 0.8.0.
- The framework uses a new tagged logger, log message are tagged with the plugin name and can be tagged with submodule name.
- Replaced [Q](https://github.com/kriskowal/q) promises with [bluebird](https://github.com/petkaantonov/bluebird) because of the [better performance](https://github.com/petkaantonov/bluebird/blob/master/benchmark/stats/latest.md).

## WIP
- Documentation for the new API.
- Generation of documentation from json config schema.
- Other open issues tagged with 0.8.0.

**Comment by michbeck100** [comment]
@sweetpi i guess this one can be closed?
