### ISSUE TITLE
Pimatic as a video surveillance system 

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#187]
I am using pimatic together with motion on a raspberry pi.
pimatic is able to start and turn off motion (thanks to ShellSwitch)
```
{
      "id": "Video",
      "name": "Motion",
      "class": "ShellSwitch",
      "onCommand": "/root/aactivate_alarm2.sh",
      "offCommand": "curl -s 'http://127.0.0.1:8080/0/action/quit' || echo OK",
      "getStateCommand": "pidof motion > /dev/null && echo on || echo off"
}
```
pimatic is able to tell me when my smartphone is away and turn on motion when i leave (thanks to ping plugin and mail plugin)
```
{
      "id": "my-phone",
      "name": "my smartphone",
      "class": "PingPresence",
      "host": "192.168.1.49",
      "interval": 100000,
      "retries": 60,
      "timeout": 30000
    },
```
```
{
      "id": "IphoneabsentID",
      "name": "Iphoneabsent",
      "rule": "if my smartphone is absent and its after 8am and its before 11pm then send mail subject:\"Smartphone away\" text:\"bye\" and switch on Motion",
      "active": true,
      "logging": true
    },
```

The only thing missing is the integration of the video stream coming from motion into a pimatic page. You can find some info about motion web stream server here http://www.lavrsen.dk/foswiki/bin/view/Motion/WebcamServer
To see live videostream all you have to do is to add that
```
<div id="video">
    <img src="http://servername:port" />
</div>
```
Problem how to integrate that in pimatic?

btw : there is a huge improvement on quality and number of frames see here http://www.raspberrypi.org/forums/viewtopic.php?f=43&t=75240

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
