### ISSUE TITLE
Controlling IP Cam with pimatic

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#208]
I'm working on a setup to control a IP Cam with pimatic, and would like to use this thread as some sort of think tank to see if someone is dealing with the same or see some other approaches.
The IP Cam I have, is a cheap Chinese outdoor dome (easyn h3-v10r). I want to use the 'surveillance station' app on my Qnap to record the stream. Unfortunately the cheap cam is nog supported by Qnap, so I can only use it as generic cam.

The cam can contact a 'alarm sever' (on TCP port 8) when there is motion, I couldn't find anything about a alarm server, so I made a simple listener script to see what kind of info it would broadcast. Turned it it was thinking that on port 8 a webserver could be found, askiing for /api/alarm.asp
I created the requested file om the Raspberry Pi, and pointed the IP Cam settings to the ip and port of the PI.
Now everytime there is motion detected by the cam, it will connect to my script. When the script is triggered, it will connect to the pilight API and turn a geneirc_switch (called 'motion') to ON. There is a rule to switch it back to OFF after xx seconds.

So far so good, now pimatic is able to notice wether there is motion or not.

Next step was to find out how to talk to the cam to tell to go to a certain preset position. Lucky fo me, it could be done by accessing a CGI script and give the preset number as argument in the URL.
To bad it would block because the web interface would ask for user/pass when accessing the URL. Took some time, but I created a PHP script to open the page with PHP cURL and use custom headers to do the authentication (somehow it would return 401 when using the cURL auth methods),
Added some extra stuff so the PHP script can be called with a argument for the correct preset number.
Next step was to control the presets with pimatic.

I created a generic_switch with the name cam1travel

I created the following variables:
$Cam1Temp (can be 0 or 1)
$Cam1Position

I created the following rules:
Change Cam1 position : <code>IF pilight-alarm-cam1travel is on and $Cam1Temp = 1 for 10 seconds THEN $Cam1Position = $Cam1Position + 1 and after 10 ms execute "php /home/pi/scripts/CamPreset.php $Cam1Position" and $Cam1Temp = 0 and after 10 ms $Cam1Temp = 1 </code>
camposition to 0 : <code>IF $Cam1Position = 8 THEN $Cam1Position = 0</code>
travel on -> camtemp 1 : <code>IF pilight-alarm-cam1travel is turned on THEN $Cam1Temp = 1</code>
travel of-> camtemp 0 : <code>IF pilight-alarm-cam1travel is turned off THEN $Cam1Temp = 0</code>

This would give the following result:
When the cam1travel switch is set to ON, pimatic will call the PHP script to tell it to switch to the next preset position and turn the $Cam1Temp var to 0 for 10 ms, after that it will be set to 1 again.
The value of $Cam1Travel is the trigger to determine how long the cam is in a specific preset position.
When the earlier script detect motion, it would set a swicth called Cam1Motion to ON. When that switch is on pimatic may not continue to travel (as long as there is motion, you don't want to change preset position of the cam).

Allthough the Qnap suveillance station doesn't support my cam, I can trigger it to record by creating a User Defined Event. That even can be triggered by accessng a URL.
Last step would be to create script that would access that URL, and let pimatic execute the script.
Offcourse I don't every motion to be recorded, so the pimatic rule system can be used for that.
Thinking about creating a variable called $AllowRecording and set it to 0. Only when I would want recoridng, it would be set to 1.
Situations when I would set it to 1 : 
- It is after sunset, doors are closed and main lights are off
- It is daylight, but Vacation Timer is enabled
- It is daylight and both main cellphones are absent

Some stuff I created for this setup can be made easier when pimatic can support some stuff:
- Detect change of variables (allready scheduled for 0.8.0 ?)
- URL plugin (simple plugin to access a URL)
- some sort of plugin that would allow to let pimatic respond on custom URL calls (if request URL is 'bla.php?foo=bar&action=doit' then turn light on)

Anyway, perhaps someone can use som 'tricks' I used for this setup, or tell me it could be done much easiers, or share a it own approach?

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
