### ISSUE TITLE
Actions/scenes

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#211]
Would be great to have actions/scenes to make rules less complex.

Example:
If switch 1 is turned off turn off bedroom-light 1 and turn off bedroom-light 2 and turn off bedroom-radio

If we had scenes ther could be a scene "bedroom off/empty"

Rule would look like this:
If switch 1 is turned of activate bedroom off

And if we need other triggers they are easy to add
If presence-bedroom is not present for 5 minutes activate bedroom off
If remotecontrol-button1 is turned off activate bedroom off

And If I add a new device I don't need to change all the rules I only change the scene/action

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
