### ISSUE TITLE
Groups/Rooms/Floors

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#212]
I have to admit I'm not completely getting the current way grouping is working.

As pimatic is intented for Home-Automation I think grouping with areas/rooms/floors would make sense, maybe even to have a directory like structure.

For the gui I would say current concept of pages and "groups" as they are currently ther could work. But the current groups for me are only a way to organize the GUI

For example:
Front Door Sensor -> would be in location Floor1\Hallway\EntranceArea
And in GUI I would display it on the "Security" page in a Group "Doors"

When I want to edit this sensor i would go to Devices>Floor1>Hallway>Entrence Area

Same for lights...
Floor1\Room1\AmbientLight
Floor1\Room2\AmbientLight
Floor2\Room1\AmbientLight
Floor2\Room2\AmbientLight

But in GUI it might be:
Page "Lights" section/group "Ambient Lights"

You see, I'm extending my pimatic setup extensively :D I don't have a multi story 10 bedroom house but still with my little flat the interface starts looking confusing/crowded

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.

**Comment by mat1990dj** [comment]
This would be very nice to have
