### ISSUE TITLE
Homewizzard

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#221]
http://siio.de/homewizard-zentrale-fuer-mehr-komfort-und-sicherheit-im-smart-home/

looks almost like pimatic, would love to see the hardware from the inside

**Comment by mwittig** [comment]
While this still may be relevant, I am closing this ticket as the idea has not been further discussed here. Creating something similar to Homewizard or other offerings in the market is tempting, but requires a significant investment. Moreover, the home automation market is characterized by tough competion these days. There is a large variety of trending products.
