### ISSUE TITLE
[pimatic] Request: variable text in VariablesDevice

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#238]
Spinoff from https://github.com/pimatic/pimatic/issues/186#issuecomment-53683961
Would be very cool to use rules instead of expressions in the 'variables to display' setup.

Let's say we have a variable called $BlockHeat
The normal situation is that this variable should be 0 , anything higher than 0 means it would prevent the central heating to be turned on.
You could have 2 fields to fill in , the rule-field and the expression-field
rule $BlockHeat = 0
expression "allow heating"
rule $BlockHeat > 0
expression "prevent heating"

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
