### ISSUE TITLE
[pimatic] Feature request: Disable rule with rule

### ISSUE THREAD

**Issue by incmve** [pimatic/pimatic#248]
Is there a way to disable a rule with a rule?

For example:
My aquarium is controlled by pimatic and when I am cleaning it I have to turn of some pumps and the heater.

I want to make a button "Aquarium cleaning" with the rule:

     IF Aquarium cleaning is pressed THEN deactivate *rule1* and *rule2*

and a second button "Resume aquarium" or someting like that"

     IF Resume aquarium is pressed THEN activate *rule1* and *rule2*

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
