### ISSUE TITLE
[pimatic] Read only template for switches (LED like)

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#255]
Brainfart: Can you add some sort of 'LEDdevices' devices?
When you goto /#edit-device you select the 'LEDdevices' option. Click on add row, you have 2 fields. One name-field and one device-field. In the device-field you can enter the name of any switch you have configured in pimatic. The name field is free text.
In the GUI this would show a dot/LED in the color green or red (green=on red=off).

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
