### ISSUE TITLE
Logging and graphing the state of devices

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#262]
Allready explained this earlier : https://github.com/pimatic/pimatic/issues/161#issuecomment-48804827
Would this be possible with 0.8 ?

I tried to create some rules that will update a variable to a (the same) high number every minute during the time a device is powered on. A counter rule would update the variable every minute with value 0 as long as it is off.
Created a VariabledDevice in the GUI and configured it as a number (trggering it to save in database and use in plotting) but it looks like it is not writing the updates in the database when the update is the same value.

Is there any other method to accomplish this? Will there be supported for graphng/plotting states in the feature?

**Comment by Yves911** [comment]
pls look here: http://forum.pimatic.org/topic/18/logging-and-graphing-the-state-of-devices/6#

**Comment by sweetpi** [comment]
Done
