### ISSUE TITLE
pimatic online demo

### ISSUE THREAD

**Issue by sweetpi** [pimatic/pimatic#268]
I'm setting up an online demo of pimatic: http://demo.pimatic.org:8080/ as little showroom and for testing. At the moment it is quite empty, so if someone has ideas for things that can be shown without connected hardware let me know :)

**Comment by pimagical** [comment]
I needed some time to collect all the devices types from different sources, a quick start in the demo would help. And http://demo.pimatic.org gives now a 502 bad gateway.

![image1](https://cloud.githubusercontent.com/assets/11790664/7421941/156ca704-ef89-11e4-877d-788cc4571246.PNG)

**Comment by sweetpi** [comment]
@pimagical thanks for pointing this out, started the server again.
