### ISSUE TITLE
Adding Philips hue

### ISSUE THREAD

**Issue by DoktorRPI** [pimatic/pimatic#28]
It would be nice if pimatic can talk to my Philips Hue Lamps (On+Off + Changing Color...). That i don´t need to start a extra App to control my Hue Lamps.

There are already some code´s to maby it´s easy to add them to your system. I think it would be a nice adding for pimatic.

https://github.com/Q42/hue-libs

**Comment by joeyvanderbie** [comment]
Hi quantenbaum, thanks for posting your solution.
Works like a charm!
Only lazy change I made was change http://philips-hue/api/developer1/lights/1/state
to http://philips-hue/api/developer1/groups/0/action
which controls all the lights as once.

Have you made any progress in making a plug-in for Hue?

**Comment by ch-world** [comment]
I started working on a plugin for controlling hue bulbs. Feel free to take a look at it: https://github.com/ch-world/pimatic-hue

**Comment by sweetpi** [comment]
nice

**Comment by mwittig** [comment]
I am closing this ticket as we have two plugins for hue now plus hue support:
* pimatic-hue
* pimatic-hue-zll

Additional, we have the ongoing development of hue support as part of pimatic-led-light, but this has not been released yet.
