### ISSUE TITLE
What steps are needed to use pimatic without pilight?

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#280]
Since @sweetpi is working on te rfcontrol plugin, I have been thinking about a pilightless installation of pimatic.
I cannot continue without Pilight at this moment, but in the future it could, if some functionality is ported into pimatic.

What I would like to see ported into a pimatic plugin:
- DS18B20 support
- probe protocol integrated into the rfcontrol plugin
- Fully KaKu protocol support into rfcontrol
- Weather underground (like) support

Is this something that is a long-term vision, or do you intend to keep using Pilight in its current form?

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
