### ISSUE TITLE
[Enhancement] Where is my iphone?

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#283]
There is a nodejs https://github.com/drudge/node-sosumi (npm install sosumi) that allow you to get location and push messages of/to your iphone.
How hard it is to integrate this as a pimatic-plugin?
It could bring interesting feature such if my iphone is returning home (ie pass a certain checkpoint) then switch my heater on.

**Comment by sweetpi** [comment]
See http://forum.pimatic.org/topic/23/plugin-pimatic-location-rules-based-on-location/47
