### ISSUE TITLE
Colors for the ButtonsDevice

### ISSUE THREAD

**Issue by Icesory** [pimatic/pimatic#304]
It is possible to get Colors for the ButtonDevice?
I would design a RGB Remote like this
https://lh6.ggpht.com/vg_NUPZMmFLqk2-T9L3QnkNhx-LTPepTdQNKogzjEqpkBnAKV8MfzOLiFfgM9gsvMhM=h900

    {
      "id": "colorButtons",
      "name": "Color",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "color1",
          "text": "R",
          "color":  	#ff0000
        },
        {
          "id": "color2",
          "text": "G",
          "color":  	#00ff00
        },
        {
          "id": "color3",
          "text": "B",
          "color":  	#0000ff
        }
      ]
    },

![pimatic rgb button](https://cloud.githubusercontent.com/assets/9157026/4619019/6eba4cd2-5310-11e4-89dc-6fee1478572d.png)

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
