### ISSUE TITLE
icon/logo design

### ISSUE THREAD

**Issue by sweetpi** [pimatic/pimatic#35]
Some artist here, that would create a logo and icon for pimatic? I would love something simple and friendly :)

**Comment by Oitzu** [comment]
@thexperiments i would like to use this icon, in a altered version, as an icon for the pimatic-location app. (See: https://github.com/Oitzu/pimatic-location)
Something like this: https://www.dropbox.com/s/g1zkjuq76qsftoe/pimatic-location-icon-precomposed.png?dl=0
Is this icons under some sort of special license or free to use?

**Comment by numbatboy** [comment]
I would like to make some adjustments to my Pimatic icon set. Would any one be able to indicate in which directory are the icons of favicons are held?
