### ISSUE TITLE
Extended unit support for numeric variables and device attributes

### ISSUE THREAD

**Issue by sweetpi** [pimatic/pimatic#354]
With the release of pimatic 0.8.25 some changes were made to the handling of numeric device attribute values and variables:

* plugins should know emit the attribute values with highest precision they can (**no rounding** to some decimals). The rounding for displaying should be (/is) done by the frontend.
* plugins should emit and declare the values in **base units** (`B` instead of `MB`, ...) The frontend automatically chooses the best unit for displaying and does the conversion. If you want to force the frontend to use a particularly unit then you can declare a `displayUnit` for the attribute.
* **variables can now have units**, too. The frontend display the value of variables in its base unit / declared unit. If the value is used in rules the base unit is used. If you want to display the value, you can use the new `formatNumber(variable, decimals = 2, unit)` function. 

#### Examples: 
```
log "CPU: {formatNumber($syssensor.cpu)}" => "CPU: X.XX%"
```
or if base unit of `$syssensor.memory` is `B`:
```
log "MEM: {formatNumber($syssensor.memory, 2)}"       => "MEM: X.XXMB" (chooses the best display unit)
```
If a unit is given, then **no** conversion is done:
```
log "MEM: {formatNumber($syssensor.memory/1000, 0, 'KB')}"  => "MEM: XXXXXXXXKB" (prints the raw value)
```

**Comment by koffienl** [comment]
How do I round a value to 2 decimals in the GUI ?
I\m playing with the new timer, and have the following variable expression :  <code>$pumptimer.time/3600</code>
This is resulting in large numbers:
<a href="http://zooi.oostindie.com/view.php?filename=126pimatic_decimals.png" target="_blank"><img src="http://zooi.oostindie.com/images/126pimatic_decimals_tn.jpg"></a>

Can I change this behaviour ?

**Comment by sweetpi** [comment]
You could leave the value in seconds and set the unit to `"s"` then it should show a nice time.

**Comment by koffienl** [comment]
thanks for the tip :)

**Comment by sweetpi** [comment]
Just checked, numbers should get rounded to 2 decimals if you set the type of the variable to "number"

**Comment by koffienl** [comment]
I think I have to rebuild that variable deivce, because it won't work with the unit in S, while a new test variabledevice works without a problem. I will try some more today.
