### ISSUE TITLE
Can it be done? 868 solution

### ISSUE THREAD

**Issue by incmve** [pimatic/pimatic#363]
Hi all, 
I got some device in my home working on 868MHz, I came across a transceiver on Ebay ($4,99) and some libraries etc for Arduino.

Would it be possible to integrate this transceiver?
http://blog.zakkemble.co.uk/nrf905-avrarduino-librarydriver/
http://www.instructables.com/id/Ultrasonic-Distance-Measurement-NRF905-Wireless-Tr/
https://github.com/zkemble/nRF905

and I found a Nodejs
https://github.com/SmbatYeranyan/nrf905

http://r.ebay.com/sRuKiN

This module also works with 433MHz.

**Comment by WilcoE** [comment]
Hi, i think we can use the following sketch: https://github.com/jcw/jeelib/tree/master/examples/RF12/RF12demo 

It's from Jeelabs.org they got a arduino clone named Jeenode with 868mhz on it. 
On the blog can you find alot of samples, rf12demo sketch is usable to send information and get information from your 868mhz band

**Comment by incmve** [comment]
Thanks, I haven't really looked into it yet, got to much "toys" atm. :)
