### ISSUE TITLE
Tool tip don't dissappear 

### ISSUE THREAD

**Issue by Icesory** [pimatic/pimatic#368]
On my mobile browser chrome the tool tips don't dissappear. This is happening by the sysinfo and ping plugin. On an normal browser all is good. 
![b9acbdd4-6570-11e4-9ee0-d18401708b2c](https://cloud.githubusercontent.com/assets/9157026/4931117/cbe4c662-6571-11e4-9228-ecb4d9d359c1.png)

**Comment by sweetpi** [comment]
Should be fixed in v0.8.43.

**Comment by Icesory** [comment]
Sorry,  it is still alive.

**Comment by sweetpi** [comment]
device? Did you reload?

**Comment by Icesory** [comment]
It is fixed.
