### ISSUE TITLE
[pimatic] button activation from a rule

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#372]
I know that it's possible to have rules like this "if button testbutton is pressed", but is it possible to trigger a button from a rule, for example
```
if THAT
then
press testbutton
```
Then what is behind testbutton will be activate

**Comment by Yves911** [comment]
Let me explain a bit more why i am looking for that specific need.
Pimatic is controlling my boiler by sending a RF command to turn it on when necessary for a given time : IF temperature < setpoint THEN turn boiler on for 9 minutes.
That will start the boiler and stop it after 9 minutes.
The switch ITL-1000 that i am using can be configured to autostop after a given predefined time (i choose 15 minutes).
If the switch was on and receive an on command again it will start to count again the 15 minutes from that point.

So what i am looking for is a way to simply send ON command (the off side will be handled by the ITL-1000 directly, i won't anymore use the for time in pimatic). So pimatic need to send ON command only.

Do you see a way to do that?
Using a button in the pimatic UI is doing what i want (every time that i press the button the "ON" command is sent), but i can't do it via a rule (if that THEN press/push/activate testbutton).

**Comment by Icesory** [comment]
Ok I understand your problem. I think we should implement a action handler for the buttons device AND an possibility to start a event of an switch again. Is a switch in on state i need to resend the RF code.

**Comment by Yves911** [comment]
Yes that is exactly what i need, resend a RF code independently of the state of the device

**Comment by leader21** [comment]
what about implementing a "repeat" function to rules. 
could also solve some other problems (e.g. my shutters sometimes do not get an rf signal and won't switch, when activated by a rule. if there would be an repeated rf signal triggered after some given time). if i understand the described problem of yves right, this maybe could help?

**Comment by Yves911** [comment]
I would say that RF protocol we are using (one single way no ACK) is by nature not so much reliable, repeating message several times could help.
Here i don't need a repeat functionality (my devices get most of the time the message that pimatic send out), i need more a way to ignore the state of the device in pimatic and send a RF message anyway.
I can use the HomeduinoRFButtonsDevice for that (because this device has no state), the only missing part here is that i can't fire/press/push/activate it from a rule.

**Comment by Icesory** [comment]
I have start a workaround for this.

**Comment by Icesory** [comment]
Easiest way for a fast solution is to remove this two lines
https://github.com/pimatic/pimatic-homeduino/blob/development/homeduino.coffee#L255-L256
Then you can resend a rf signal from a switch by activating it via rule.

**Comment by Yves911** [comment]
Yeah thanks for the tip Icesory, i am experimenting it now

**Comment by Yves911** [comment]
Works fine, the "ON" command is send every minute (independently that the switch is already on)
```
16:16:00.748 [pimatic-homeduino] debug: data: "RF receive 394 2540 187 1209 10168 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:17:00.699 [pimatic-homeduino] debug: data: "RF receive 367 2588 214 1234 10188 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:18:00.709 [pimatic-homeduino] debug: data: "RF receive 366 2596 214 1235 10184 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:19:00.677 [pimatic-homeduino] debug: data: "RF receive 394 2552 187 1207 10168 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:20:00.689 [pimatic-homeduino] debug: data: "RF receive 392 2548 189 1210 10164 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:21:00.715 [pimatic-homeduino] debug: data: "RF receive 388 2552 192 1214 10176 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:22:00.768 [pimatic-homeduino] debug: data: "RF receive 393 2552 189 1208 10172 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
16:23:00.686 [pimatic-homeduino] debug: data: "RF receive 394 2544 188 1207 10164 0 0 0 010203020302030203020302030203020302030203020302030203020302030203020302030203020303020203030202030302020302030302020302030203020304"
```
previously i said
> If the switch was on and receive an on command again it will start to count again the 15 minutes from that point.

I was wrong, redefine delay start from the moment that you turn the device for the first time.

**Comment by sweetpi** [comment]
I've added a `forceSend` option (defaults to true).

**Comment by Yves911** [comment]
@sweetpi @Icesory : thanks both of you, tip was working fine and now the new commit too !

**Comment by Yves911** [comment]
Solved with https://github.com/pimatic/pimatic/commit/0e3520afcfa2164631de844a5736958d7e5e51ff
Thanks guys !
