### ISSUE TITLE
Desktop interface - Freeboard

### ISSUE THREAD

**Issue by grant9742** [pimatic/pimatic#381]
Hi,

Great work!

I've been playing around with using [freeboard](https://github.com/Freeboard/freeboard) as a desktop frontend for pimatic (and ip cameras etc) but i'm having problems using pimatic as a datasource.

When adding a data source to freeboard  http://xxxx:xxxxx@10.1.1.12:8004/api/devices/ 
Pimatic gives me a User not found error.

Error: User not found
    at UserManager.hasPermission (/home/pi/pimatic-app/users.coffee:59:19)
    at /home/pi/pimatic-app/framework.coffee:821:48
    at callbacks (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:164:37)

I'm hoping you can help or point me in the right direction.

Thanks.

**Comment by georg90** [comment]
@grant9742 anything new to report? :)

**Comment by andig** [comment]
For what it's worth: I've build a Freeboard/Volkszaehler integration at https://gist.github.com/andig/d0131392806b7d5aeb18

I believe pimatic should be very similar but just don't have the time to do this right now. Feel free to fork and adapt for pimatic.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.

**Comment by frakman1** [comment]
Can someone please explain how to use the freeboard.io website's data sources to enter an IP web camera? Its options don't seem to include anything familiar.

![image](https://cloud.githubusercontent.com/assets/5826484/25321224/cf92cfec-287a-11e7-890f-27cc2c0b3329.png)

Thank you.

**Comment by mwittig** [comment]
@frakman1 Please use our forum at <https://forum.pimatic.org/> which is backed by an active user community. Note, most pimatic users don't track github issues.
