### ISSUE TITLE
Support for Silvercrest/rolling code switches

### ISSUE THREAD

**Issue by keematic** [pimatic/pimatic#386]
First of all, thanks for developing pimatic.

I'm busy running the pimatic installation, finally got it working (with an Arduino Uno being recognized as ttyACM0 instead of ttyUSB0).

I have two sets of switches, Eurodomest and Silvercrest. I sniffed both transmitters with some Arduino code and got a hold of the binary codes.
The Eurodomest is recognized as switch5 in pimatic-homeduino, as it should. The Silvercrest however was found to have a rolling set of 4 codes for each button with the piece of Arduino code mentioned before. Unfortunately the protocol was not recognized in homeduino.

The weird thing is the binary button-code received by pimatic is not rolling between 4 different ones, but only one code which end in '23'.

If there's a possibility to somehow support rolling codes, it'd be great (increased security for 'sensitive' devices)! I can post the binary codes for all buttons if needed.

Cheers

**Comment by dominikkarall** [comment]
I managed to descramble the part which identifies the unit and ON/OFF state. Unfortunately I'm still stuck with the payload part.
You can find more information here:
https://forum.pilight.org/Thread-QUIGG-GT9000-Globaltronics-ALDI?pid=16489#pid16489

Just want to mention that here as well to get some more people on the topic. Maybe somebody has an idea on how to decode the payload.

**Comment by Icesory** [comment]
@dominikkarall I have looked into your stuff at pilight. But your payload isnt clear for me
```
ON2	3544	3749	603
OFF1	5171	4506	6521
OFF2	8645	9470	9098
OFF2	16102	15699	15345
OFF1	17963	18657	20271
ON1	23169	21772	20578
ON1	26036	27211	26606
ON2	30893	30322	31925
ON1	35679	33343	36502
OFF2	37641	39191	37288
ON1	43372	41912	42205
OFF2	45818	48084	48432
ON2	52288	53097	51396
OFF1	55198	53280	54595
OFF1	57463	59341	59911
ON2	65298	64646	63004
```
What means the collums?

The problem, i don´t own this set by my self so i cant really work on it.
But i am interested to solve this code.

**Comment by dominikkarall** [comment]
@Icesory I have updated my pull request for pilight (see https://github.com/pilight/pilight/pull/215).
You can find all the information in the quigg_gt9000.c file. There are the last findings included. If you have any suggestions how to decode the payload part (see my pull request) I would be very pleased.

**Comment by Exitras** [comment]
Hi,
recently, I also bought those "Silvercrest" 433 MHz plugs which work great with the original remote but not with my Arduino (and ESP8266).
I want to control my wallplugs with Amazons Echo Dot. Can someone of you please explain to me how the solution of Icesory works? I would be grateful if you could provide the whole code in C++ for controlling the Silvercrest plug.

Best
Exitras
