### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by tigelbri** [pimatic/pimatic#396]
Hi everyone,

iam ab big fan of the pimatic framework and for me it used to work very well.
Since iam using the pimatic-weather plugin and the pimatic-dhtxx plugin the incoming values are
stored in the pimatic-database.sqlite file... so far so good this works approximetly two hours and then the follwoing error message raise:
Error: SQLITE_CANTOPEN: unable to open database file

I thought it could be a permission thing and gave 777 permission to every file and every folder i could find :) but no effect. If someone could help that would be great.

Thanks
Tristan

**Comment by sweetpi** [comment]
I think its the SD Card, too. Take a look at #409.

**Comment by Xento** [comment]
I have the Problem, too. 
But i m Running a Banana pi with a SSD At the sata Port. 

I already tried to Switch to mysql but this didn't worked. Lots of querys are only compatible to sqllite.

**Comment by Yves911** [comment]
Maybe could be useful to do a
```
dmesg
```
when this happen and post the last 20 lines, can be a filesystem corruption...

**Comment by Xento** [comment]
Here are the last lines, but nothing interesting in there.
I will try todo a fsck.

   17.692258] Mali DRM initialize, driver name: mali_drm, version 2.1
[   17.709907] [drm] Initialized mali_drm 2.1.1 20101111 on minor 1
[   19.792414] Adding 524284k swap on /swapfile1.  Priority:-1 extents:2 across:532476k SS
[   21.385798] GMAC gpio_power_hd:gpio_direction_output
[   21.656725] eth0: device MAC address 02:55:06:c2:11:f9
[   21.687585] sunxi_gmac: probed
[   21.702339] eth0: PHY ID 001cc915 at 0 IRQ 0 (sunxi_gmac-0:00) active
[   21.719837] eth0: PHY ID 001cc915 at 1 IRQ 0 (sunxi_gmac-0:01)
[   25.511354] Bluetooth: Core ver 2.16
[   25.535908] NET: Registered protocol family 31
[   25.552977] Bluetooth: HCI device and connection manager initialized
[   25.574432] Bluetooth: HCI socket layer initialized
[   25.589628] Bluetooth: L2CAP socket layer initialized
[   25.607189] Bluetooth: SCO socket layer initialized
[   25.661931] Bluetooth: RFCOMM TTY layer initialized
[   25.680256] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   25.696505] Bluetooth: BNEP filters: protocol multicast
[   25.711355] Bluetooth: RFCOMM socket layer initialized
[   25.714157] Bluetooth: RFCOMM ver 1.11
[   29.732644] PHY: sunxi_gmac-0:00 - Link is Up - 1000/Full
[   30.518903] EXT4-fs (sda1): re-mounted. Opts: data=ordered
[   32.172461] eth0: no IPv6 routers present
[  398.642844] usb 3-1: USB disconnect, device number 2
[  398.656655] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[  398.668239] ch341 3-1:1.0: device disconnected
[  510.612732] ehci_irq: port change detect
[  510.831895] ehci_irq: port change detect
[  510.891871] The port change to OHCI now!
[  511.194650] usb 3-1: new full-speed USB device number 3 using sw-ohci
[  511.383151] usb 3-1: New USB device found, idVendor=1a86, idProduct=7523
[  511.396303] usb 3-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  511.406957] usb 3-1: Product: USB2.0-Serial
[  511.418102] ch341 3-1:1.0: ch341-uart converter detected
[  511.452008] usb 3-1: ch341-uart converter now attached to ttyUSB0
[301435.894695] [sched_delayed] sched: RT throttling activated

**Comment by Yves911** [comment]
@Xento : you are right dmesg do not report any trouble about the filesystem.
Maybe you could follow instructions here : https://github.com/pimatic/pimatic/issues/419#issuecomment-68593119 (ie dump the DB and recreate it)

**Comment by sweetpi** [comment]
@Xento Could you post your database config? What file system does the ssd have? Is it ext4?

**Comment by Xento** [comment]
Yes its ext4. 
I will try it but it can take some Time until it Happens again.
