### ISSUE TITLE
dummy switch dont save state when restart pimatic

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#402]
when build a dummy switch and turn it on, then restart pimatic the switch wouldn`t save his state it is turn off after restarting pimatic.

all other switch from pilight save the state after restarting pimatic

**Comment by sweetpi** [comment]
I think this should be fixed in the new version.

**Comment by sgoetze** [comment]
Even if the last entry is 18 month old - is this issue fixed? I have the newest pimatic version but after a restart the only dummyswitch I use to avoid heating during summer falls back to the off state. I think I had this dummyswitch already last spring but I do not remember of any problem. So possibly the issue returned in a newer version of pimatic.
