### ISSUE TITLE
Newbie question : just installed pimatic but webinterface not showing ?

### ISSUE THREAD

**Issue by DirkB19** [pimatic/pimatic#404]
Hi,
Completely newbie here, so bare with me.
Just followed the installation steps ...
Edited the port to 8080, added admin password, waited for sqlite to finish installing, checked status and it says running with PID xx, however ... I can't seem to access http://RPI-IP:8080/ ?
I get ERR_CONNECTION_TIMED_OUT in Chrome.
(where RPI-IP is my local ip address on my local network)
What am I missing ?
Btw : I have not yet made any other config.
Or, do I need to install mobile frontend ?

**Comment by maxim361** [comment]
Hi,
I installed pimatic and edited the port to 8080, but the web interface was not shown in the browser. I got the error message: 
“Cannot connect to destination 192.168.0.14:8080”.

I followed the steps given above by leader21.

I checked the config.json plugin section, the mobile frontend plugin was there.
Then I went to the node_modules, deleted the pimatic-mobile-frontend folder and restarted pimatic, but the pimatic-mobile-frontend folder was not installed again.

I tried to execute the following command:
cd /usr/local/pimatic-app/node_modules
ls –l
The folder did not exist.

Next I removed pimatic-mobile-frontend
sudo rm –rf pimatic-mobile-frontend
and restarted pimatic
sudo service pimatic restart
But the web interface was not shown in the browser.
What is wrong with my installation of pimatic?

**Comment by sweetpi** [comment]
hi,

did you check the logfile?

**Comment by leader21** [comment]
please post your log and your config.json (you can use http://www.pastebin.com for that, the threat will be more clearly arranged then). maybe there's only a minor issue like forgot a comma or something like that.

**Comment by incmve** [comment]
```
cd /usr/local/
```
I bet its installed at the wrong location

**Comment by maxim361** [comment]
Thank you.
log
16:31:48.673 [pimatic] info: Starting pimatic version 0.8.38
16:31:53.215 [pimatic] error: Cannot find module '/home/pi/pimatic-app/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node'

config.json
{
  "//": "Please only change this file when pimatic is NOT running else pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 80      
    },
    "database": {
    }
  },
  "plugins": [
    { 
      "plugin": "cron" 
    }, 
    { 
      "plugin": "mobile-frontend"
    },
    {
      "plugin": "pilight"
    }
  ],
  "devices": [
 
  ],
  "rules": [

  ],
  "pages": [ 
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": []
    }
  ],
  "groups": [

  ],
  "users": [
    {
      "username": "admin",
      "password": "06a23yg5",
      "role": "admin"  
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ]
}

**Comment by incmve** [comment]
sqlite is not installed
see #394 
after that start pimatic and wait, it takes a long time for sqlite to install.

you can monitor the log file in pimatic-app
```
 tail -f pimatic-daemon.log
```
When it says
```
[pimatic-mobile-frontend] info: rendering html finished
[pimatic] info: listening for http-request on port 80...
```
then it's ready

**Comment by maxim361** [comment]
It is working now. Thank you very much.
