### ISSUE TITLE
pimatic-max-thermostat dummy

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#405]
Is it possible to implement the max-thermostat as a dummy to set temperature, eco and boost etc.?

it looks very nice and i believe it is very comfortable to use.
like that:

![1baa3358-749f-11e4-9235-15252328c9ea](https://cloud.githubusercontent.com/assets/7631636/5319424/7a560366-7ca9-11e4-921c-734834a763ed.jpg)

**Comment by sweebee** [comment]
Is there a way to hide auto/manu/boost?
