### ISSUE TITLE
request: icon additional to custom on/off text

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#411]
Is it possible to implement icons additional to on/off commands, so every user can choice his own icons. For example a colored flame when heating is on and grey flame when heating is off. 

Users can copy some icons on sd card and write the directory into custom on/off command like 

/pi/home/icons/flame_on.jpeg

It gives for flexibilty for users to create itS own beautiful/powerfull pimatic surface.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
