### ISSUE TITLE
pimatic-mail with other providers rather than gmail

### ISSUE THREAD

**Issue by HermannDerUser** [pimatic/pimatic#416]
Hello again,

I tested the mail plugin and it's works well with my gmail account. 
Is it's possibily to use other providers like gmx or strato?
Can I change the value for "service" or enter the server, protocoll and ports manuel?
Can you give me an example?

I look the link "mail-config-schema" (http://pimatic.org/plugins/pimatic-mail/mail-config-schema.html) but there ist error 404

Hermann

**Comment by Flop2006** [comment]
@HermannDerUser 
Your example for the GMX configuration didnt work for me.
I get the following errror:

```
[pimatic] error: rule emailtest error executing an action: 3066331968:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:766:
[pimatic] error:>
[pimatic] error: Error on evaluation of rule condition of rule emailtest: 3066331968:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:766:
```
Any suggestions?
Do you use the free version of the gmx mail or the ProMail?

**Comment by HermannDerUser** [comment]
@Flop2006 
I use GMX ProMail but I have a freemail account too. 
I can try it later and then sign up again.

**Comment by HermannDerUser** [comment]
@Flop2006
I tested with my GMX freemail account and got the same error. At the moment I use a Strato email account. Maybe someone else can solve the problem with GMX, sorry

**Comment by Flop2006** [comment]
Finaly i solve the problem by myself:

```json
    {
      "plugin": "mail",
      "transport": "SMTP",
      "transportOptions": {
        "auth": {
          "user": "SENDER@gmx.de",
          "pass": "PASSWORD"
        },
        "maxConnections": 5,
        "transport": "SMTP",
        "host": "mail.gmx.de",
        "secureConnection": false,
        "port": 587,
        "requiresAuth": true,
        "domains": [
          "gmx.de"
        ],
        "maxMessages": null
      },
      "from": "SENDER@gmx.de"
    }
```
The same configuration works for web.de (with ```smtp.web.de```)
