### ISSUE TITLE
[pimatic-mobile-frontend] Pages don't adjust height on iPhone

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#418]
When you are on the bottom of a large page und you swipe to a shorter one you have to scroll up to see something.
All pages should only be as high as needed and it would be glad if it would save the scrollposition and as default the scrollposition should be at the top.

**Comment by incmve** [comment]
After the last update it seems fixed for me, I can delete devices again and the page has a normal layout now.
Scrolling and swiping also solved.

**Comment by Yves911** [comment]
> I can delete devices again and the page has a normal layout now.

Confirmed also here
