### ISSUE TITLE
pimatic: Mobile Frontend Dark-Theme

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#422]
Hey All!
I Have created a nice dark theme for pimatic, actually it looks like in the screenshots below.

![1](https://cloud.githubusercontent.com/assets/7631636/5493910/56628f42-86ef-11e4-8f80-022f16f59681.JPG)
![2](https://cloud.githubusercontent.com/assets/7631636/5493912/5832b23e-86ef-11e4-8e49-0a2c4e8eaaac.JPG)
![3](https://cloud.githubusercontent.com/assets/7631636/5493913/5a480060-86ef-11e4-8c6f-5c6654ca33f7.JPG)

@ sweetpi,
i have changed some color values in 3 different files, is it possible to say for example we have something like this in the config? and the config will change the variable colors in the 3 files?

```
{
  "plugin": "mobile-frontend",
  "main-bg-color": "#xxxxxx",
  "panel-bg-color": "#xxxxxx",
  "button-bg-color": "#xxxxxx",
  "button-font-color": "#xxxxxx",
  "mode": "production"
},
```

**Comment by p4co86** [comment]
Two thinks i have noticed. On the graph page. 
The second graph color, the black one. In my dark theme i have changed it to yellow.
In the graph itself, when you choice a point to get information. The font color have to be changed.

In my dark theme i have changed them both. Maybe you can take a look at it and can fix it fast.

Just another improvment for more flexibility in the theming stuff.

We can make two dropdown menu. 

First: to deffine the main background color (black/white)
Second: to define the menu color (aloe,mint,candy,water.....)

After that you can combine all colors with each background.

**Comment by wutu** [comment]
I started using dark theme, but the graphs still have a white background. Is this normal or I make some mistakes?

**Comment by p4co86** [comment]
As i have created the theme, the background in the graph was also black. But sweetpi changed it, dont know why. i think it is beacause he switched to another graphstyle. actually it is normal that the graph bg is white.
