### ISSUE TITLE
openweathermap plugin?

### ISSUE THREAD

**Issue by htca** [pimatic/pimatic#424]
Last week I encountered some issues with the weahter plugin, I was wondering why the msn weather datastream was used. For my personal work, I use the openweathermap api, which also includes various other weather variables (including sunset). I would like to contribute, but It is hard to start, any clues how to start? Or is anybody interested in a cooperation of developing it?

**Comment by sweetpi** [comment]
There's some discussion about that here: https://github.com/pimatic/pimatic/issues/364

Currently we miss developers with enough free time :)
