### ISSUE TITLE
Pidfile exists, but process is dead. after Update

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#429]
Merry christmas everyone.

I have just a small problem here. After I updated yesterday pimatic the process always dies after the start.

In the log that happens according to the following entry without error.
[pimatic-mobile-frontend] info: rendering theme: jqm/classic

service pimatic status
Pidfile exists, but process is dead.

Version Info:
[pimatic] info: Starting pimatic version 0.8.29
[pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.28)

Kind Regards,
n3ro

**Comment by noxx2015** [comment]
i had also a problem with "pidfile exits...."

npm install pimatic dont help

pi@raspberrypi ~/pimatic-app $ npm install pimatic
npm http GET https://registry.npmjs.org/pimatic
npm http 304 https://registry.npmjs.org/pimatic
npm ERR! error rolling back Error: EACCES, unlink '/home/pi/pimatic-app/node_mod                             ules/pimatic/node_modules/blanket/node_modules/.bin/esparse'
npm ERR! error rolling back  pimatic@0.8.73 { [Error: EACCES, unlink '/home/pi/p                             imatic-app/node_modules/pimatic/node_modules/blanket/node_modules/.bin/esparse']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/pi/pimatic-app/node_modules/pimatic/n                             ode_modules/blanket/node_modules/.bin/esparse' }
npm ERR! Error: EACCES, unlink '/home/pi/pimatic-app/node_modules/pimatic/node_m                             odules/blanket/node_modules/.bin/esparse'
npm ERR!  { [Error: EACCES, unlink '/home/pi/pimatic-app/node_modules/pimatic/no                             de_modules/blanket/node_modules/.bin/esparse']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/pi/pimatic-app/node_modules/pimatic/node_modules/blanket                             /node_modules/.bin/esparse' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.18.16-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! path /home/pi/pimatic-app/node_modules/pimatic/node_modules/blanket/nod                             e_modules/.bin/esparse
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/home/pi/pimatic-app/node_modules/pimatic/                             node_modules/blanket/node_modules/.bin/esparse'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/pimatic-app/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi ~/pimatic-app $

**Comment by sweetpi** [comment]
`EACCES` means you don't have the permissions, try with `sudo npm install pimatic`.
