### ISSUE TITLE
GUI not updated with specific rule

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#435]
I have this rule:

https://dl.dropboxusercontent.com/u/6237916/Screen%20Shot%202014-12-28%20at%2012.22.07.png

The command to turn it off is executed after 8 hours, but the in the GUI the switch is still on (while it's off in the real world) :)

**Comment by neographikal** [comment]
Hmm, seems to behave the same.. Any ideas?

**Comment by sweetpi** [comment]
Which  browser? What happens when you reload the page?

**Comment by neographikal** [comment]
Doesnt matter, it's not a GUI problem it seems. I manipulate the same thing with a remote, it seems the status after x hours is not updated.

**Comment by neographikal** [comment]
Mea culpa I'm an idiot, rule was a bit dumb...
