### ISSUE TITLE
Support for 'increased' or 'decreased' variable

### ISSUE THREAD

**Issue by martenjacobs** [pimatic/pimatic#436]
I'd really like to be able to detect whether a variable has increased or decreased, instead of just changed. Something like:
`IF $variable increased THEN (...)`

Some background:
I've made a command that detects whether my or my girlfriends iPhone is in the house (as you may know detecting an iPhone pinging is not reliable, as it doesn't respond to pings when in deep sleep). My command uses `snmpwalk` to get the connected wifi-clients from my router (which runs dd-wrt), and eventually returns the number of devices on the wifi network with the predefined mac addresses. For reference, the command is this:
`snmpwalk -mUCD-SNMP-MIB -v1 -cpublic 192.168.11.1 .1.3.6.1.4.1.2021.255 2> /dev/null | grep Hex-STRING | grep -oE '[0-9A-Fa-f]{2}[ -:][0-9A-Fa-f]{2}[ -:][0-9A-Fa-f]{2}[ -:][0-9A-Fa-f]{2}[ -:][0-9A-Fa-f]{2}[ -:][0-9A-Fa-f]{2} *$' | tr '[:upper:]' '[:lower:]' | sed 's/ *$//' | sed 's/[ -]/:/g' | grep -oE '^([MAC ADDRESS]|[ANOTHER MAC ADDRESS])$' | wc -l | tr -d ' '`

This command is read using a ShellSensor, which works great. Now I'd like to have rules respond to when one of us gets home, but there's no way I know how to do that. For now I'm using `$variable has changed and $variable > 0` but this also fires when one of us is home and the other comes home or both of us are home and one leaves.

**Comment by sweetpi** [comment]
I added `$var gets updated/increased/decreased/is increasing/is decreasing`
