### ISSUE TITLE
control oil heating with vcontrold and pimatic

### ISSUE THREAD

**Issue by betz0r** [pimatic/pimatic#438]
Hi,
i built one of these IR-ports to control my oil heating (Vitotronic 200) with my raspberry pi. I can see all temperatures and can set them actually and change heating-timetables and so on... it's a very mighty tool so far but only accessible by cli telnet/shellscript. 
As pimatic is in use as my main homeautomation interface so far i want to incluide this new system into pimatic. 
I think using the shell-execute plugin makes most sense to realize this but i am open for any advice on that. 
The values can be called and set with an executed binary: ./vclient -h 127.0.0.1:1234 -c getTempOutside 
http://openv.wikispaces.com/vclient

The site about the IR/oilheating port: http://openv.wikispaces.com/

Any one running a installation like this or is interesting in building one?

**Comment by Heizelmann** [comment]
I am also interested to have it, but unfortunately not able to build such an extension.

**Comment by betz0r** [comment]
I have started to setup some shell-execute devices:
![auswahl_042](https://cloud.githubusercontent.com/assets/1616482/5656435/700ac4bc-96dc-11e4-866e-316cd41195a4.png)
It is also possible to SET values at the central heating device with some shell commands, like "party mode" or "holiday mode". I will add these in near futures.

If anyone is interested in this, i am free to help settin things up!

**Comment by sweetpi** [comment]
@betz0r Would you share these configs here. I think it could be useful for other, too. You can use variables in shell commands like: `execute "/home/pi/myscript.sh $mode"`. You could set the mode variables then with a ButtonsDevice like in the pimatic demo.

**Comment by betz0r** [comment]
As stated before i used shell-execute plugin to get information of my oil heating unit. One the raspberry pi a daemon is running which is listening on port 3002 for TCP requests (i.e. can be done with telnet or the included vclient). I used vclient as it already interprets the HEX-response in human readable floats, strings.
Just add a device (ShellSensor) in the pimatic device section like this:
>    {
>      "id": "VRaumTempSoll",
>      "name": "Raumtemperatur Soll",
>      "class": "ShellSensor",
>      "attributeName": "temperature",
>      "attributeType": "number",
>      "attributeUnit": "°C",
>      "command": "vclient -h 192.168.1.117:3002 -c getRaumTempSollA1M1 -t /home/bbfwg/1val.tmpl"
>    },
>    {
>      "id": "VBrennerstarts",
>      "name": "Brennerstarts",
>      "class": "ShellSensor",
>      "attributeName": "temperature",
>      "attributeType": "number",
>      "attributeUnit": " ",
>      "command": "vclient -h 192.168.1.117:3002 -c getBrennerstarts -t /home/bbfwg/1val.tmpl"
>    },

The /home/bbfwg/1val.tmpl file contains a simple "$1" and is used as a template file for vclient output.

**Comment by betz0r** [comment]
>You can use variables in shell commands like: execute "/home/pi/myscript.sh $mode". You could set >the mode variables then with a ButtonsDevice like in the pimatic demo.

I have checked the demo about Buttons and Mode. Is there any help/documentation on using ButtonDevices combined with a variable to set a mode?
Like i have 4 modes given 0 1 2 3 4, and want a Button to set the mode and execute the shell command to talk to my oil heating?
I have not found any demo-configuration so it's hard to build the logic on my own.

Thx so far!

**Comment by Heizelmann** [comment]
On startup of pimatic I get an error for every sensor like this

[pimatic] listening for http-request on port 80...
[pimatic-homeduino] data: "PING"
[pimatic] Could not update variable SpeichertemperaturIst.temperature: Command failed:
[pimatic] { name: 'OperationalError',
[pimatic]>  message: 'Command failed: ',
[pimatic]>  cause: { [Error: Command failed: ] killed: false, code: 1, signal: null },
[pimatic]>  stack: 'Error: Command failed: \n    at ChildProcess.exithandler (child_process.js:637:15)\n    at ChildProcess.EventEmitter.emit (events.js:98:17)\n    at maybeClose (child_process.js:735:16)\n    at Socket.<anonymous> (child_process.js:948:11)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Pipe.close (net.js:466:12)' }
[pimatic] Could not get attribute value of Speichertemperatur ist.temperature: Command failed:
[pimatic] Error: Command failed:
[pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
[pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
[pimatic]>    at maybeClose (child_process.js:735:16)
[pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
[pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
[pimatic]>    at Pipe.close (net.js:466:12)
Possibly unhandled Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

after that execution goes on normally.

The device definition e.g. is

{
      "id": "SpeichertemperaturIst",
      "name": "Speichertemperatur ist",
      "class": "ShellSensor",
      "attributeName": "temperature",
      "attributeType": "number",
      "attributeUnit": "",
      "command": "vclient -h 127.0.0.1:3002 -t /home/pi/openv/1val.tmpl -c getTempWWist",
      "interval": 2000
    }

What is the problem?

**Comment by betz0r** [comment]
I can't help you with your error but i can provide my working config.

First make sure your vclient ist executable for everyone on the system (or at least the user you are running pimatic with): chmod +x /usr/bin/vclient (or where you stored vclient binary file).
At mine it looks like after "ls -la /usr/bin/vclient"
-rwxr-xr-x 1 root root 127328 Jan  8 01:07 /usr/bin/vclient*

In the pimatic config in the section "devices" i have all sensors set up like this:
```
    {
      "id": "VTempKesselIst",
      "name": "Kesseltemperatur Ist",
      "class": "ShellSensor",
      "attributeName": "Temperatur",
      "attributeType": "number",
      "attributeUnit": "°C",
      "command": "vclient -h 192.168.1.117:3002 -c getTempKTS -t /home/bbfwg/1val.tmpl",
      "interval": 30000
    },
```

Sending data to the heater is done with buttons. Generate a button device in pimatic like this:

```    
{
      "id": "partymodus-buttons",
      "name": "Partymodus",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "partymodus-off",
          "text": "AUS"
        },
        {
          "id": "partymodus-on",
          "text": "AN"
        }
      ]
    },
```
Then add rules related to the button device:
```

    {
      "id": "partymodus-button-on",
      "name": "partymodus-button-on",
      "rule": "if partymodus-on button is pressed then execute \"vclient -h 192.168.1.117:3002 -c 'setPartymodus EIN'\"",
      "active": true,
      "logging": true
    },
    {
      "id": "partymodus-off",
      "name": "partymodus-off",
      "rule": "if partymodus-off button is pressed then execute \"vclient -h 192.168.1.117:3002 -c 'setPartymodus AUS'\"",
      "active": true,
      "logging": true
    }
```
Enjoy!

**Comment by Heizelmann** [comment]
If you have a Vitronic with both 'Partymode' and 'Sparmode' it is better to explicitly toggle the modes to avoid unexpected behaviour of your heating system,
 e.g. you should do
```
vclient -h 192.168.1.117:3002 -c 'setSparmodus AUS,setPartymodus EIN'
vclient -h 192.168.1.117:3002 -c 'setSparmodus EIN,setPartymodus AUS'
vclient -h 192.168.1.117:3002 -c 'setSparmodus AUS,setPartymodus AUS'
```
I think you can realize it with a ButtonsDevice with Buttons 'Party','Spar' and 'Off' or
with two  toggle buttons of type ShellSwitch, e.g.
```JSON
    {
      "id": "party",
      "name": "Party",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 AUS,setPartyBetriebA1M1 EIN'",
      "offCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 AUS'"
    }
```
but in the later case you must change the switch state by rule (if possible), when modes are changed
from another client

**Comment by Heizelmann** [comment]
Another solution is to toggle the two Buttons by rule:
```JSON
  "devices": [
   {
      "id": "party",
      "name": "Party",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 EIN'", 
      "offCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 AUS'"
    },
    {
      "id": "spar",
      "name": "Spar",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 EIN' > /dev/null",
      "offCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 AUS' > /dev/null"
    }
]

  "rules": [
    {
      "id": "spar-event",
      "name": "spar-event",
      "rule": "if spar is switched on then switch party off",
      "active": true,
      "logging": true
    },
    {
      "id": "party event",
      "name": "party-event",
      "rule": "if party is switched on then switch spar off",
      "active": true,
      "logging": true
    }
]
```

**Comment by Icesory** [comment]
We need a shell-buttons-device

**Comment by Heizelmann** [comment]
I would like to use  a **ShellSwitch** to control a certain boolean or enum feature, e.g. the boolean *party-mode*.
```JSON
{
      "id": " party-mode-switch",
      "name": "Set party mode",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 AUS,setPartyBetriebA1M1 EIN'",
      "offCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 AUS'"
    }
```
Because this mode can be changed by the heating system from outside Pimatic, Pimatic needs a feedback. This can be done by **ShellSensor**:
```JSON
{
      "id": " party-mode",
      "name": "Party mode",
      "class": "ShellSensor",
      "attributeName": "value",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "vclient -h localhost:3002 -c get partyBetriebA1M1 -t /home/user/1str.tmpl",
      "interval": 30000
    }
```

Now the problem is that the *set-party-mode* **ShellSwitch** needs to adapt its state.
I thought this can easily be done by a rule but the only thing I found is to switch the **ShellSwitch**, which in turn unnecessarily executes the command. This is not optimal, but shouldn't make a problem. The other problem is that I couldn't find a switched predicate for a **ShellSensor** in the docs. The only suitable construct I found is in *General Device attributes*. This is also suboptimal and needs two rules. So I came up with the following plan:
```JSON
{
      "id": "set-party-mode-on",
      "name": "set-party-mode-on",
      "rule": "IF value of party-mode is equal to \"EIN\" AND party-mode-switch is off THEN switch party-mode-switch on",
      "active": true,
      "logging": true
    },
{
      "id": "set-party-mode-off",
      "name": "set-party-mode-off",
      "rule": "IF value of party-mode is equal to \"AUS\" AND party-mode-switch is on THEN switch party-mode-switch off",
      "active": true,
      "logging": true
    }
```

I have two questions:
1.	I tested this, but the rules get not fired. What is wrong?
2.	Is there a better solution? In my opinion **ButtonsDevice** like used above is not a good solution as long the Buttons couldn't behave like a radio button arry and don't show a ON state.

**Comment by Heizelmann** [comment]
By using the web-gui for defining rules I learned a bit more and I tried the following rule with *party-mode* **ShellSensor**
```JSON
{
      "id": "party-mode-changed",
      "name": "party-mode-changed",
      "rule": "if $party-mode.value changes and $party-mode.value equals \"AUS\" then switch Party off",
      "active": true,
      "logging": true
    }
```
```$party-mode.value changes``` gets *true* but the second part ```$party-mode.value equals \"AUS\"``` never gets true. I also tried ```$party-mode.value == \"AUS\"```. Didn't work too.

**Comment by Heizelmann** [comment]
My issue with the equals comparator is moved to #474. The reason for not matching is the trailing newline character on stdout. If this is solved the following rule will works
```JSON
{
      "id": "party-mode-changed",
      "name": "party-mode-changed",
      "rule": "if $party-mode.value equals \"AUS\" then switch Party off",
      "active": true,
      "logging": true
    }
```

**Comment by Heizelmann** [comment]
Meanwhile I learned a bit more Unix and Pimatic and I came out with a different solution for  the mode switches. When I use a small shell script to convert the console output of the vcontrol commands from 'AUS' to 'false' and from 'EIN' to true, I can use 'getStateCommand' attribute of ShellSwitch. With this all rules and Sensors can be removed. The shell script can be used also for other purposes.

```JSON
    {
      "id": "party-mode-switch",
      "name": "Party",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 EIN,setSparBetriebA1M1 AUS'",
      "offCommand": "vclient -h localhost:3002 -c 'setPartyBetriebA1M1 AUS'",
      "getStateCommand":"/home/pi/openv/isEin 'vclient -h localhost:3002 -t /home/pi/openv/1str.tmpl -c getPartyBetriebA1M1'",
      "interval": 60000
    },
    {
      "id": "spar-mode-switch",
      "name": "Spar",
      "class": "ShellSwitch",
      "onCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 EIN,setPartyBetriebA1M1 AUS'",
      "offCommand": "vclient -h localhost:3002 -c 'setSparBetriebA1M1 AUS'",
      "getStateCommand":"/home/pi/openv/isEin 'vclient -h localhost:3002 -t /home/pi/openv/1str.tmpl -c getSparBetriebA1M1'",
      "interval": 60000
    }
```
with ShellScript isEin:
```Shell
#!/bin/bash

COMMAND_OUTPUT=`$1`

if [ $COMMAND_OUTPUT = 'EIN' ]
        then
                echo true;
        else
                echo false;
fi;
```

**Comment by Heizelmann** [comment]
Still open the issue from 11 Jan, 2015. Has anyone an idea?

**Comment by sweetpi** [comment]
> [pimatic]>  cause: { [Error: Command failed: ] killed: false, code: 1, signal: null },

That means the process (`vclient`) terminated with an error code (1). Does this only happen on an reboot or any time you restart pimatic?

It could be:
1) Some service is not up, yet (networking?, devicebus?)
2) The command is called in parallel and so fails, because the first one locks some file, or so)

**Comment by Heizelmann** [comment]
It happens any time restaring pimatic and only in the startup phase. Later everything works well
There are about 16 ShellSensors and ShellSwitches calling vclient.The intervall is set to 120000.
About 10 Sensors deliver an error. If Pimatic make this calls to vclient in parallel might be vclient has an max. load limit and then returns with errors.

**Comment by Heizelmann** [comment]
Wouldn't it be a good idea not to trigger all shell switches in parallell at startup but schedule them fom the beginning with the given interval? Maybe this solves my problem.

**Comment by sweetpi** [comment]
Could you try first if its help if you add a delay parameter to each? (a shell script that wraps vclient with a sleep just before)

**Comment by Heizelmann** [comment]
I did it with individual delay parameters for each sensor, so that they start calling vclient serial with about 20 seconds delay between each call. This might be unnecessarily too long, but it is for first save testing. 
With this modification the errors are gone.
For me this is only a workaround cause the delay is not only active on startup but also in general operation. What to do next?

**Comment by sweetpi** [comment]
I will add an option where you can decide if the scripts should be run in parallel or in an sequence.

**Comment by Heizelmann** [comment]
Many thanks in advance!!!

**Comment by Heizelmann** [comment]
Not for me, still crashes.

**Comment by sweetpi** [comment]
Option added, @Heizelmann Could you test?

**Comment by Heizelmann** [comment]
Great! It really helps. The warnings on startup are gone with the sequential option
```JSON
{
      "plugin": "shell-execute",
      "sequential": true
}
```
