### ISSUE TITLE
Status LED

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#439]
Does we have a solution to display a device's status within an led, e.g. 
![Image](http://www.clker.com/cliparts/Y/v/Z/A/9/M/led-green-th.png)

I get the status `off / on` with an REST-API, for example: 
`curl --silent http://pool.keno.lan:1880/controller/filterpumpe`

Now, how can i display this status led? We only need two,max three states. `on - off - idle`

**Comment by kenci** [comment]
Do we have an option to display a status of a device with a red button for off, and green for on.

@Icesory i dont understand what you meant with log reader.

I just want to draw a status button/led of my pump. I got this device state as response from an API which is `off` or `on`

**Comment by Icesory** [comment]
You need a external script (Shell/Python or some other speak).
This script must call your api from the pump and reads the state.
Now you have two ways.

First you write the state in a file with this script. Then you use the log-reader to read the file. In pimatic you define two rules to convert the state from the log-reader to an dummy-switch.

The other way is, your script use the api from pimatic and controll a dummy-switch direct.

I think a dummy-presencen device is actually not available. So you should use a dummy-switch with xConfirm:true to avoid switching the switch from the gui.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
