### ISSUE TITLE
DHT22 - negative temperatures problem

### ISSUE THREAD

**Issue by bkiss** [pimatic/pimatic#442]
First of all, i wish you in advance Happy  New Year, for the whole group!

I have just wired my home with ±40m of cable and 5 sensors DHT22, Aosong.. 
Everything was just perfect until comes the cold, and under 0 Celsius my external DHT doesn't read just 0 C, and humidity 0. I have tried to change the sensor, but now it goes to -5 C and below i have the same nothing ... :(

I put an 100microF at the sensor for filtering, no success, and i put 4.7k and other values of pulling up resistor...
I have about 30 m of UTP twisted pair cable, with soldering at joints...and this is the last sensor the farest...:( but, it works with Adafruit_dht command line reader:

-----------
pi@raspberrypi ~ $ sudo ./Adafruit_DHT 22 25
Using pin #25
Data (40): 0x2 0xa5 0x80 0x6a 0x91
Temp =  -10.6 *C, Hum = 67.7 %

------------

And with pimatic:

![screen shot 2014-12-30 at 19 44 10](https://cloud.githubusercontent.com/assets/5294516/5581050/49de8e44-905c-11e4-83ce-9310eeeb6c87.png)

Any ideas? 

Thank you.

**Comment by sweetpi** [comment]
Assuming you are using the pimatic-dhtxx plugin: The node-dht-sensors module (used by the pimatic plugin) uses nearly the same code to read the sensor like the Adafruit lib:

node-dht-sensors: https://github.com/momenso/node-dht-sensor/blob/master/node-dht-sensor.cpp
Adafruit: https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code/blob/master/Adafruit_DHT_Driver/Adafruit_DHT.c

The functions for timings used by the two seems to be different. You would have to try to adjust the node-dht-sensors code, so that uses the same timing functions like the Adafruit version or ask the module author @momenso to adjust the code accordingly.

**Comment by momenso** [comment]
Hi, I was able to reproduce this issue and updated the timings accordingly. Oddly enough, the issue seems to manifest only when temperature is lower than 5&deg;C. 

You should have no more problems from **node-dht-sensor** version **0.0.6** onwards which includes this fix.

**Comment by sweetpi** [comment]
@momenso Thanks for the fast feedback and update.

@wutu Could you update the dependency and release a new npm version?

**Comment by bkiss** [comment]
Wow. 

Happy new Year 4 everyone. 
Thank you for your feedback, i've seen that you are working hard on it, and i hope to see it working. 
Just for the record, i have tried with 2 different sensors, and it was a different temperature when the strange issue happens. 0 and -5 C ... The sensors was from the same lot...
Maybe it's funny, but my question is if i can use the new version before wutu  releases the new version?

**Comment by bkiss** [comment]
Hm, maybe it will work now, in the /home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules folder i run:
npm install node-dht-sensor@0.0.6

I will put the sensor back on the cable and fingers cross :)

**Comment by bkiss** [comment]
I will switch the sensors again, maybe the cable length is too much...Sometimes the reading is OK, and sometimes it goes >3000% humidity.
But now the reading from command line is the same with the displayed data from pimatic ,

I think you can close this issue, but if anyone has the same problem, please let me know (humidity and temperature from DHT22 above 1000)

![screen shot 2015-01-06 at 11 23 48](https://cloud.githubusercontent.com/assets/5294516/5626669/364d2cc4-9597-11e4-9eaa-a8066dd10760.png)

**Comment by incmve** [comment]
Cable length could be an issue, maybe interference somewhere? 
I got 20 to 30 meters CAT5 UTP from my pi to my aquarium, 5v over the wires, ds18b20 and 2 relay signal wires but I have no problems.

**Comment by bkiss** [comment]
Maybe interference, or something else. I have about 30 m UTP CAT5, and 10m other signal cable, used for alarm, but not twisted. Every cable joints are soldered... 
Tried to put 100microFarad capacitor to + and - near the sensor... but nothing, I have 4.4V at the sensor... 
I will try another sensor...
