### ISSUE TITLE
Change variable value with API

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#444]
How to change a variable's value with the API? I tried posting `value` to `.../api/variables/temp-pool` but it doesnt work.

Output:
`{
    "success": false,
    "message": "expected param: type"
}`

**Comment by koffienl** [comment]
You have to PATCH, instead of POST or GET. Can you give a snippet of the code you are using?

**Comment by kenci** [comment]
Can you give me an example how to change variables over API?

**Comment by incmve** [comment]
```
IF $wind changes
THEN execute "curl --silent -X PATCH --header \"Content-Type:application/json\" --user \"USER:PASS\" --data '\{\"type\": \"value\", \"valueOrExpression\": $weather-station.avgAirspeed\}' http://192.168.0.12/api/variables/windspeedavg > /dev/null"
```

**Comment by kenci** [comment]
Got it! Thank you.

**Comment by mwittig** [comment]
If you want to pass shell variables to the curl command arguments make sure you have quoted the arguments correctly. as part of bash use "set -x" which will output each evaluated command line in bash. This way you can find errors with missing or misplaced quotes easily.

See
* https://superuser.com/questions/835587/how-to-include-environment-variable-in-bash-line-curl 
* https://forum.pimatic.org/topic/3043/bash-command-to-update-a-variable/21
