### ISSUE TITLE
Very sensitiv GUI on iPhone

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#445]
When I scroll the pages up and down on the iPhone sometimes I accedently switch the pages.
The GUI is very sensitiv when using swipe left or right.
Maybe you could reduce it a bit.

**Comment by p4co86** [comment]
+1

**Comment by georg90** [comment]
same here iphone - ipad is usable

**Comment by sweetpi** [comment]
Better in pimatic-mobile-frontend v0.8.33?

**Comment by georg90** [comment]
better than before (for me) iphone 4s

**Comment by p4co86** [comment]
better! ;)

**Comment by sweetpi** [comment]
Perfect or better?

**Comment by sweetpi** [comment]
> whats about the development for android? Whats been done, what needs to be done?
> A friend of mine might pick it up, but asked for a status.

Not so much was done:
* Basic websocket connection is working and json is parsed and device model object are created
* It shows the devices in a list view

What need to be done: Update the model, Different gui elements for different templates and all other things and pages.

I would love if someone want to pick it up and I'm willing to give support, if the code will be on github.

> PS: After upgrading, messages keeps showing:

In a new incognito tab, too?

**Comment by p4co86** [comment]
for me perfect!

**Comment by Xento** [comment]
It's much better now, maybe it could be slightly more.
I think it would be perfect when you have to slide 1/3 of the display when you normaly hold your iPhone.

**Comment by georg90** [comment]
> In a new incognito tab, too?

Yesterday with 0.32 to 0.33, yes.
Now with 0.33 to 0.34, no :-)
Also I use Internet Explorer here, I won't complain again for the sake of the IE...it's outdated.
