### ISSUE TITLE
No receive and no send commands over RF using Homeduino

### ISSUE THREAD

**Issue by a4tje** [pimatic/pimatic#447]
Hardware: Arduino Nano V3, Bananapi, Rxmodule MX-05V, Txmodule MX-FS-03V.
Sofware Pimatic , Plugin Homeduino., devices DHT, Pinswitch

When pimatic is running and when I started my rf sensor (a Nano with DHT sensor and RF transmitter) there is a timeout error :
11:21:58.648 [pimatic-homeduino] error: Error reading DHT Sensor: timeout_error.
And there is no code showing in the debug

**Comment by Yves911** [comment]
@a4tje, did you uploaded the sketch to the arduino first (see here https://github.com/pimatic/homeduino)
Could you indicate here what is the results of  DHT type digital_pin?

pimatic should be off for this test and you should get results from your arduino before going ahead with pimatic.

**Comment by a4tje** [comment]
Hi Yves, yes i did. I flashed the Arduino with the Homeduino.ino sketch with the makefile as subscribed.
When i start Pimatic I get the message "connected to homeduino device"

**Comment by Yves911** [comment]
If you can't connect to the arduino with make monitor and receive the "ready" string so no need to check more in deep. First we need a working arduino with the proper sketch loaded.

Ok let's do the following:
1 stop pimatic
2 disconnect the arduino usb
3 connect the arduino again an post me the 10 last lines of dmesg command
4 post your MAKEFILE
5 make upload (post me the output of that command as well)
6 make monitor

**Comment by a4tje** [comment]
Ok, i just did follow your steps, this is the output:

3: 
[  261.444140] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB1
[  261.447881] ch341 4-1:1.0: device disconnected
[  294.528852] ehci_irq: port change detect
[  294.750104] ehci_irq: port change detect
[  294.810107] The port change to OHCI now!
[  295.112868] usb 4-1: new full-speed USB device number 3 using sw-ohci
[  295.291797] usb 4-1: New USB device found, idVendor=1a86, idProduct=7523
[  295.297989] usb 4-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  295.301184] usb 4-1: Product: USB2.0-Serial
[  295.313142] ch341 4-1:1.0: ch341-uart converter detected
[  295.341641] usb 4-1: ch341-uart converter now attached to ttyUSB1

4: Makefile:

# Uses Arduino.mk https://github.com/sudar/Arduino-Makefile
BOARD_TAG    = nano328
ARDUINO_LIBS = SerialCommand RFControl Keypad DHTlib
USER_LIB_PATH := $(realpath ./libraries)
MONITOR_PORT  = /dev/ttyUSB1

ARDMK_DIR := $(realpath ./arduino-mk)
include $(ARDMK_DIR)/Arduino.mk

5 Make Upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [USER]               ARDMK_DIR = /usr/local/pimatic-app/homeduino/arduino-mk
- [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 101
- [DEFAULT]            ARCHITECTURE =
- [DEFAULT]            VENDOR = arduino
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [AUTODETECTED]       AVR_TOOLS_DIR = /usr (found in $PATH)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [USER]               USER_LIB_PATH = /usr/local/pimatic-app/homeduino/libraries
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [USER]               BOARD_TAG = nano328
- [COMPUTED]           OBJDIR = build-nano328 (from BOARD_TAG)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD =
- [DEFAULT]            CXXFLAGS_STD =
- [COMPUTED]           DEVICE_PATH = /dev/ttyUSB1 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [USER]                 SerialCommand
- [USER]                 RFControl
- [USER]                 Keypad
- [USER]                 DHTlib
- [USER]                 Keypad/utility
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.3.4
- [COMPUTED]           CC_VERSION = 4.7.2 (avr-gcc)
-------------------------
mkdir -p build-nano328
/usr/bin/avr-g++ -x c++ -include Arduino.h -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  homeduino.ino -o build-nano328/homeduino.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/WInterrupts.c -o build-nano328/core/WInterrupts.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_analog.c -o build-nano328/core/wiring_analog.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring.c -o build-nano328/core/wiring.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_digital.c -o build-nano328/core/wiring_digital.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_pulse.c -o build-nano328/core/wiring_pulse.o
/usr/bin/avr-gcc -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os  /usr/share/arduino/hardware/arduino//cores/arduino/wiring_shift.c -o build-nano328/core/wiring_shift.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/CDC.cpp -o build-nano328/core/CDC.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp -o build-nano328/core/HardwareSerial.o
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In function ‘void store_char(unsigned char, ring_buffer*)’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:84:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp: In member function ‘virtual size_t HardwareSerial::write(uint8_t)’:
/usr/share/arduino/hardware/arduino//cores/arduino/HardwareSerial.cpp:392:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/HID.cpp -o build-nano328/core/HID.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/IPAddress.cpp -o build-nano328/core/IPAddress.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/main.cpp -o build-nano328/core/main.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/new.cpp -o build-nano328/core/new.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Print.cpp -o build-nano328/core/Print.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Stream.cpp -o build-nano328/core/Stream.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/Tone.cpp -o build-nano328/core/Tone.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/USBCore.cpp -o build-nano328/core/USBCore.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/WMath.cpp -o build-nano328/core/WMath.o
/usr/bin/avr-g++ -MMD -c -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -D__PROG_TYPES_COMPAT__ -I. -I/usr/share/arduino/hardware/arduino//cores/arduino -I/usr/share/arduino/hardware/arduino//variants/eightanaloginputs  -I/usr/local/pimatic-app/homeduino/libraries/SerialCommand -I/usr/local/pimatic-app/homeduino/libraries/RFControl -I/usr/local/pimatic-app/homeduino/libraries/Keypad -I/usr/local/pimatic-app/homeduino/libraries/DHTlib -I/usr/local/pimatic-app/homeduino/libraries/Keypad/utility -Wall -ffunction-sections -fdata-sections -Os -fno-exceptions  /usr/share/arduino/hardware/arduino//cores/arduino/WString.cpp -o build-nano328/core/WString.o
/usr/bin/avr-ar rcs build-nano328/libcore.a  build-nano328/core/WInterrupts.o  build-nano328/core/wiring_analog.o  build-nano328/core/wiring.o  build-nano328/core/wiring_digital.o  build-nano328/core/wiring_pulse.o  build-nano328/core/wiring_shift.o  build-nano328/core/CDC.o  build-nano328/core/HardwareSerial.o  build-nano328/core/HID.o  build-nano328/core/IPAddress.o  build-nano328/core/main.o  build-nano328/core/new.o  build-nano328/core/Print.o  build-nano328/core/Stream.o  build-nano328/core/Tone.o  build-nano328/core/USBCore.o  build-nano328/core/WMath.o  build-nano328/core/WString.o    build-nano328/userlibs/SerialCommand/SerialCommand.o build-nano328/userlibs/RFControl/RFControl.o build-nano328/userlibs/Keypad/Keypad.o build-nano328/userlibs/DHTlib/DHTlib.o build-nano328/userlibs/Keypad/utility/Key.o
/usr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -o build-nano328/homeduino.elf build-nano328/homeduino.o build-nano328/libcore.a  -lc -lm
/usr/bin/avr-objcopy -O ihex -R .eeprom build-nano328/homeduino.elf build-nano328/homeduino.hex

/usr/bin/avr-size --mcu=atmega328p -C --format=avr build-nano328/homeduino.elf
AVR Memory Usage
----------------
Device: atmega328p

Program:    9816 bytes (30.0% Full)
(.text + .data + .bootloader)

Data:       1197 bytes (58.4% Full)
(.data + .bss + .noinit)


make reset
make[1]: Entering directory `/usr/local/pimatic-app/homeduino'
/usr/local/pimatic-app/homeduino/arduino-mk/bin/ard-reset-arduino  /dev/ttyUSB1
make[1]: Leaving directory `/usr/local/pimatic-app/homeduino'
make do_upload
make[1]: Entering directory `/usr/local/pimatic-app/homeduino'
/usr/bin/avrdude -q -V -D -p atmega328p -c arduino -b 57600 -P /dev/ttyUSB1 \
                        -U flash:w:build-nano328/homeduino.hex:i

avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x1e950f
avrdude: reading input file "build-nano328/homeduino.hex"
avrdude: writing flash (9816 bytes):
avrdude: 9816 bytes of flash written

avrdude: safemode: Fuses OK

avrdude done.  Thank you.

make[1]: Leaving directory `/usr/local/pimatic-app/homeduino'

6 Make monitor
Now I get a ready prompt!  But when I type a command like “PING hello” there is no response. No ACK nor ERR.

**Comment by Yves911** [comment]
Ok very good
I never had any reply with PING Hello
Could you try to get data from your DHT

**Comment by Icesory** [comment]
Do your monitor use the right connection parameters?parity: 8N1 
baud: 115200

**Comment by a4tje** [comment]
@Yves911 
I put in the commando DHT 11 0 but no response
I tried  RF receive 0 also no reponse.

@Icesory 
I think so, because the Ready prompt, else it would give garbage. How to check them (Makefile?)

**Comment by Yves911** [comment]
@a4tje could you post a picture of your installation, where did you connected the data pin of the DHT on the arduino ?
![pins-nano](https://cloud.githubusercontent.com/assets/7493675/5617676/96e6989e-9511-11e4-8fa9-9d3ce0059600.png)

**Comment by a4tje** [comment]
@Yves911 
I've tried both receiverpins 0 (D2) and 1 (D3)
I also checked the powersupply of the receiver (5V)
see photo
![dsc_3872](https://cloud.githubusercontent.com/assets/10389288/5618082/85e9bbda-9515-11e4-8f71-196fc009708e.JPG)

**Comment by Yves911** [comment]
I don't see  the dht component on your picture.
Pls focus on make it working first with make monitor and dht, as soon as its working  you can extend..

**Comment by a4tje** [comment]
Allright

Op maandag 5 januari 2015 heeft Yves911 <notifications@github.com> het
volgende geschreven:

**Comment by a4tje** [comment]
I tracked the problem with the make monitor, somehow the commands don't work when you use ssh.
When i actually give the commands on the pi locally, I get the right results, with DHT command.
Also I got it to work with Pimatic. Only thing is that RF doesn't work with me with homeduino.
