### ISSUE TITLE
Set a variable on rule's execution end

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#448]
How can i set a variable when a rule ends?
I have this rule:
`IF
its after 10:00 and before 19:30 and $temp-solar changes and $pool-solarheizung is 0
THEN
turn Solarpumpe on and set $pool-solarheizung to 1 after 10 minutes turn Solarpumpe off`

Now, if its 19:30 and this rule ends, how can i set `$pool-solarheizung` to 0

**Comment by incmve** [comment]
You have to make another rule for that
```
IF its after 19:31 or before 09:59
THEN set $pool-solarheizung to 0
```
