### ISSUE TITLE
local keyboard input / flirc

### ISSUE THREAD

**Issue by packetinspector** [pimatic/pimatic#449]
I want to take commands via IR via Flirc, it converts IR into keypresses.  Is there already a mechanisms for keycodes as events or would I need to create a plugin for that?

**Comment by Icesory** [comment]
You must create a plugin for this. Or you use the api from pimatic on an external program.

**Comment by georg90** [comment]
I use this with a custom script.
Basicly you have a script which calls the API: myscript.sh tv --> toggle tv on/off
Then you use lircd with irexec to call it and bind it to a button..

I use xbmc & custom Scripting to use the keys, since xbmc is running anyway..

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
