### ISSUE TITLE
Change device state without executing action

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#450]
Is it possible to change the current state of a device, without executing the actual code that it is programmed to?
Let's say I have a switch1 device, and pimatic think it is OFF. Somehow I decide this information is false and it should be set to ON but without sending the underlaying RF commands.
The switch1 device is just an example, I want to be able to do this for every type of device, like for instance a shell-execute switch.

Can this be done? Perhaps with the (current) API ?

**Comment by koffienl** [comment]
Anyone ?

**Comment by Icesory** [comment]
I don't know a way to do this. Eventually you can access the database and change the state there. But you must stop pimatic for this.

**Comment by sweetpi** [comment]
Not possible yet. Moving all Feature request to the forum, so closing this.
