### ISSUE TITLE
New protocol : contact2, can be used for cheap door contact

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#451]
A pull request has been created (https://github.com/pimatic/rfcontroljs/pull/27) to include a new protocol for cheap door contact
![wg-alarm-std-wireless-magnetic-contact](https://cloud.githubusercontent.com/assets/7493675/5616231/c1cb4b2c-9502-11e4-9289-d55047c4ccee.jpg)

Those sensors only emit a message when the magnet move away from the sensor (so no way to know if the door is closed or open, but you will be informed when the door has been opened)

**Comment by leader21** [comment]
:+1: 
could you please tell us where to get these items from? maybe some ebay china guy?

**Comment by Yves911** [comment]
here is where i bought mine http://www.chinamade.com/433mhz-wireless-door-window-magnet-sensor-detector-alarm-home-security-system.html 
but you will find plenty of those items on ebay (~2€ each)

**Comment by sweetpi** [comment]
Nice. But how do we reset it to closed? I would propose that we don't handle it as contact sensor, but as alarm sensor. So it just emits an alarm event on open. I know that these have internal jumper where you can select the pulse length. How did you configure it?

**Comment by Yves911** [comment]
Hi, it's a contact sensor but i am using the PIR class (like this the contact is reset after a delay).
There is no jumper at all into these things, you can't configure pulse length, it's simply work out of the box

**Comment by sweetpi** [comment]
![img_20150108_110025](https://cloud.githubusercontent.com/assets/5249312/5660980/96910750-9726-11e4-8c74-fe8ad4f2c8b8.jpg)

Then mine must be different. The jumpers on the right configure the pulse length.

**Comment by sweetpi** [comment]
I've released pimatic-homeduino v0.8.32 with support for these contact sensor. It seems that mine is working with no jumper set. I've added a "autoReset" option to the contact sensor config, see updated readme.

**Comment by koffienl** [comment]
I have the same somewhore in my sensor parts box laying around :)
Would be nice if we somehow could let the device send both open and close. Iirc you could change when it should send (open or close) with a jumper.

**Comment by koffienl** [comment]
This one claims to send open AND close: http://www.ebay.com/itm/433MHZ-Wireless-Home-Door-Window-Entry-Alarm-System-Magnet-Sensor-Detector-White-/131230292363?pt=LH_DefaultDomain_0&hash=item1e8def598b

**Comment by Yves911** [comment]
I am thinking of another solution let me explain:
- normal situation : you place the magnet to be exactly in front of the sensor => when you open the door, the sensor will send the info that the door is open. With cheap magnet you will never know then that someone closed the door afterward (that's why we need automatic reset)
- now let's play with the magnet : instead of placing the magnet exactly in front of the sensor put it behind the door : like this when you will open the door the magnet will move in front of the sensor and send info to pimatic, then when you will close the door the magnet will again pass in front of the sensor => like this you get a message when the door is open and when the door is closed... magic*?

\* Magic : the sensor will always send the same info (same message) so pimatic needs to know the last state to be able to define if door has been closed or opened

**Comment by leader21** [comment]
> the sensor will always send the same info (same message) so pimatic needs to know the last state to be able to define if door has been closed or opened

but what if pimatic fails to receive the signal that the contact sends? then you will have an incorrect state...

**Comment by Yves911** [comment]
Exact, but it can also happen with more expensive sensor that can send 2 different messages (if you miss a message pimatic won't reflect the real status). I don't plan to use pimatic for my bank door

**Comment by Yves911** [comment]
@sweetpi what do you think of:
> now let's play with the magnet : instead of placing the magnet exactly in front of the sensor put it behind the door : like this when you will open the door the magnet will move in front of the sensor and send info to pimatic, then when you will close the door the magnet will again pass in front of the sensor => like this you get a message when the door is open and when the door is closed... magic*?
* magic : the sensor will always send the same info (same message) so pimatic needs to know the last state to be able to define if door has been closed or opened

How can i update contact2 protocol to allow this kind of feature?

**Comment by sweetpi** [comment]
hm, its a very nice idea. But I don't like the risk of missing rf signals, too and you assume that the sensor is mounted in a way it is always triggered on open and close and the door is not stopped in the position of the sensor. So I'm sorry I don't want to implement this workaround.

If you want you can change the protocol for your personal use: The idea would be to remember the last state in the protocol: https://github.com/Yves911/rfcontroljs/pull/1/files

**Comment by Yves911** [comment]
thanks, i tried this proposal and i think that i will keep the original approach (trigger only when magnet move away from the sensor). Results that i have are too poor (maybe due to the fact that the sensor burt the message during x seconds)

**Comment by georg90** [comment]
I got a couple of those, too.
Now the (small) issue is, that the ```autoReset``` doesn't work if pimatic is restarted, so each time it's restarted you'll to open/close all the sensors so it get's a reset.
