### ISSUE TITLE
Pimatic crash on evaluating rule

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#453]
I have this rule set
`... its $alarmanlage-zeit-abends and $alarmanlage-status is "off" ...` 
where `$alarmanlage-zeit-abends` is set to "23:00"

If i set this rule pimatic crashes. Can someone reproduce this?

**Comment by incmve** [comment]
Yup I can confirm this.
but I think using variables as time isn't supported yet, I didn't know it would crash pimatic tho but it did :-0

**Comment by kenci** [comment]
We should not use variables as time, but instead of crashing it should throw an exception, right?

**Comment by incmve** [comment]
I only use times in the rule or sunrise/set etc

**Comment by sweetpi** [comment]
Thanks for reporting should be fixed in pimatic-cron v0.8.4. Variable dates are supported but must be enclose in quotes. Please reopen if there are still issues.

**Comment by incmve** [comment]
Confirmed thanks :+1:
