### ISSUE TITLE
thermostat height. mobile frontend 8.34

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#454]
After update to mf 8.34 i cant see the whole thermostat device on my android in vertial mode.
The temp. And +,- is cutted.

**Comment by sweetpi** [comment]
Thanks, Fixed in 0.8.35?

**Comment by p4co86** [comment]
Fixed

**Comment by Xento** [comment]
Now I can't see the controls on iPhone anymore.

**Comment by georg90** [comment]
Iphone looks okay:
![pimatic](https://cloud.githubusercontent.com/assets/6489464/5632244/79278ab8-95cd-11e4-9ab8-49912e6eef61.PNG)

Just the box with the temp is a little too long^^

**Comment by Xento** [comment]
Oh yes it`s ok. 
I think mine cached something. 
Yes the box is a little bit to high.

**Comment by sweetpi** [comment]
Thanks for reporting. Should be fixed in pimatic-mobile-frontend v0.8.37.
