### ISSUE TITLE
Design of the GUI sometimes breaks on iPhone

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#455]
When I use the GUI on my iPhone sometimes the Design breaks. 

The pages tabs don`t always Stick to the top and there is a gap between the GUI and the controls of safari. 

![](http://i.imgur.com/swFd4FD.jpg)
![](http://i.imgur.com/QvhBxVN.jpg)

**Comment by georg90** [comment]
same issue with the topbar not sticking to the top (on "not so full" pages) (iphone)

**Comment by sweetpi** [comment]
Realy strange, some iphone user here with some css skills to fix it?

**Comment by Xento** [comment]
I have CSS skills but I don't really know how to simulate an iPhone on my PC so i can use Tools like Firebug. 
And there I can't simulate the touch actions. 

By the way i Gounod a new Bug. 
When I scroll a longer page up ob iPhone the Tab switchs to the next on the right side.

**Comment by Xento** [comment]
There are some more issues with the GUI on iPhone. 
In this Screenshot I used the GUI (Scrolled up and down, Changed tabs)

i'm just scrolling up and down when I than Lift my Finger it Switchs the Tab. ![](http://i.imgur.com/6yg5rbq.jpg)

**Comment by Xento** [comment]
I think the Problem with the tabbar is that the page is a littlebit to high. 
I can scroll it on my iPhone but it isn't nessesary because the controls dont Even get in the near of the bottom. 

I will try to change the CSS tomorrow.

**Comment by sweetpi** [comment]
http://moduscreate.com/enable-remote-web-inspector-in-ios-6/
Am 07.01.2015 21:36 schrieb "Xento" <notifications@github.com>:

**Comment by sweetpi** [comment]
Found a way to run an iphone simulator. Should be fixed in pimatic-mobile-frontend v0.8.37.
