### ISSUE TITLE
Wrong signal sent when multi protocol configured for pimatic-homeduino

### ISSUE THREAD

**Issue by cklam2** [pimatic/pimatic#456]
I'm not sure whether this is a bug or by design. For me it's non expected behavior.

In the config.json I added a multi protocol device (see [here](http://pimatic.org/plugins/pimatic-homeduino/)) for a KaKu switch. First protocol with send/receive = true/true and second protocol with send/receive = false/true. 

config.json
```
    {
      "id": "garden",
      "name": "Garden Light",
      "class": "HomeduinoRFSwitch",
      "protocols": [{
          "name": "switch1",
          "options": {
            "id": 10589452,
            "unit": 9
          },
          "send": true,
          "receive": true
        },
        {
          "name": "switch4",
          "options": {
            "id": 17,
            "unit": 16
          },
          "send": false,
          "receive": true
        }]
    }
```

When switching a device I expect that pimatic sends the signal that is defined in the first protocol. However it seems to send a different signal. The debug output when switching 'garden' through the pimatic web interface.
```
10:40:31.189 [pimatic-homeduino] debug: data: "RF receive 304 991 10124 0 0 0 0 0 01010110011001100101010101100110011001100101011002"
10:40:31.222 [pimatic-homeduino] debug: received: [ 304, 991, 10124 ] 01010110011001100101010101100110011001100101011002
10:40:31.264 [pimatic-homeduino] debug: switch2:  { houseCode: 17, unitCode: 16, state: true }
10:40:31.298 [pimatic-homeduino] debug: switch3:  { houseCode: 17, unitCode: 16, state: false }
10:40:31.328 [pimatic-homeduino] debug: switch4:  { unit: 17, id: 16, state: false }
10:40:31.362 [pimatic-homeduino] debug: switch5:  { id: 962474, unit: 0, all: true, state: false }
10:40:31.393 [pimatic-homeduino] debug: pir1:  { unit: 17, id: 16, presence: true }
```

However, when I rename the second protocol name to "switch1" (instead of switch4) then the output is as follows:
```
10:45:11.895 [pimatic-homeduino] debug: switch1:  { id: 10589452, all: false, state: true, unit: 9 }
10:45:12.922 [pimatic-homeduino] debug: contact1:  { id: 10589452, all: false, state: true, unit: 9 }
```

Reason why 2 different protocols are used is that the light can be controlled by different transmitters, some support the new KaKu protocol and 1 only supports the old Kaku protocol. By setting "send": false I hoped that the protocol would only be used for status updates.

**Comment by sweetpi** [comment]
I tried your config and added some debug output and this is what it does:

```
switch1 with send = true
sending switch1 { id: 10589452, unit: 9, all: false, state: true }
switch4 with send = false
```

So it does the right thing here. Maybe the debug output it from another device / remote? Did you check if you edited the right config and saved it probably? Also keep in mind that you have to edit the config while pimatic is not running OR through the editor in the frontend.

**Comment by cklam2** [comment]
That is strange...
I only have 1 rpi device, when switching on and then off i see only those actions appear in the log. And i indeed stop pimatic before editing the json file.

To rule out any other factor i copied the config_default.json file, only added the aforementioned multi protocol configuration part and then started pimatic. After it was started i used the web page to switch it on and then off.

```
23:16:17.394 2015-01-08 Thursday
23:16:28.364 [pimatic] info: Starting pimatic version 0.8.33
23:16:32.732 [pimatic] info: loading plugin: "pimatic-cron" (0.8.3)
23:16:33.456 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.32)
23:16:38.148 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.31)
23:16:39.865 [pimatic-cron] info: the time is: Thu Jan 08 2015 23:16:39 GMT+0100 (CET)
23:16:41.535 [pimatic] info: new device "Garden"...
23:16:42.396 [pimatic-mobile-frontend] info: packing static assets
23:16:43.931 [pimatic-mobile-frontend] info: packing static assets finished
23:16:44.001 [pimatic-mobile-frontend] info: rendering html
23:17:08.844 [pimatic-mobile-frontend] info: rendering html finished
23:17:09.057 [pimatic] info: listening for http-request on port 80...
23:17:09.140 [pimatic-homeduino] debug: Couldn't connect (operation timed out after 20000 ms), retrying...
23:17:10.249 [pimatic-homeduino] debug: data: "PING"
23:17:10.305 [pimatic-homeduino] debug: data: "ready"
23:17:10.369 [pimatic-homeduino] info: Connected to homeduino device.
23:17:10.460 [pimatic-homeduino] debug: data: "ACK"
23:17:10.522 [pimatic-homeduino] debug: Receiving on pin 0
23:17:50.381 [pimatic-homeduino] debug: data: "PING"
23:17:56.540 [pimatic-homeduino] debug: data: "ACK"
23:17:56.651 [pimatic-homeduino] debug: data: "RF receive 335 1191 11252 0 0 0 0 0 01100101011001100101011001010101011001100110011002"
23:17:56.743 [pimatic-homeduino] debug: received: [ 335, 1191, 11252 ] 01100101011001100101011001010101011001100110011002
23:17:56.822 [pimatic-homeduino] debug: switch2:  { houseCode: 9, unitCode: 12, state: false }
23:17:56.867 [pimatic-homeduino] debug: switch3:  { houseCode: 9, unitCode: 12, state: false }
23:17:56.906 [pimatic-homeduino] debug: switch4:  { unit: 9, id: 12, state: true }
23:17:56.947 [pimatic-homeduino] debug: switch5:  { id: 765690, unit: 0, all: true, state: false }
23:17:56.987 [pimatic-homeduino] debug: switch7:  { unit: 1, id: 5, state: false }
23:17:57.026 [pimatic-homeduino] debug: pir1:  { unit: 9, id: 12, presence: true }
23:17:57.067 [pimatic-homeduino] debug: pir2:  { unit: 23, id: 11, presence: true }
23:18:10.386 [pimatic-homeduino] debug: data: "PING"
23:18:30.389 [pimatic-homeduino] debug: data: "PING"
23:18:32.735 [pimatic-homeduino] debug: data: "ACK"
23:18:32.808 [pimatic-homeduino] debug: data: "RF receive 341 1185 11252 0 0 0 0 0 01100101011001100101011001010101011001100110010102"
23:18:32.854 [pimatic-homeduino] debug: received: [ 341, 1185, 11252 ] 01100101011001100101011001010101011001100110010102
23:18:32.902 [pimatic-homeduino] debug: switch2:  { houseCode: 9, unitCode: 12, state: false }
23:18:32.941 [pimatic-homeduino] debug: switch3:  { houseCode: 9, unitCode: 12, state: true }
23:18:32.980 [pimatic-homeduino] debug: switch4:  { unit: 9, id: 12, state: false }
23:18:33.078 [pimatic-homeduino] debug: switch5:  { id: 765690, unit: 0, all: true, state: true }
23:18:33.117 [pimatic-homeduino] debug: switch7:  { unit: 1, id: 5, state: false }
23:18:33.157 [pimatic-homeduino] debug: pir1:  { unit: 9, id: 12, presence: true }
23:18:33.198 [pimatic-homeduino] debug: pir2:  { unit: 23, id: 11, presence: true }
```

I also noticed that the id and unit stated for switch4 are different than the ones defined in the json (12 and 9 vs 17 and 16 + 10589452 and 9) so i am a bit lost now.

How or where can i add additional debug info?

**Comment by sweetpi** [comment]
I think I finally found it. Could you update to pimatic-homeduino v0.8.33 and test? Please reopen if the sends are still wrong.

**Comment by cklam2** [comment]
I can confirm that it's now working with v0.8.33. Thank you so much for the support!

**Comment by sweetpi** [comment]
Thanks for reporting, I would have never found it if it would not have been reported (by you).

**Comment by Icesory** [comment]
@sweetpi can you pls explain the change.

**Comment by sweetpi** [comment]
Sure: It was a common js pitfall: In js variables are scoped by functions and not blocks. 

### Problem
Consider this js/cs code:

```js

// create the send actions
var toSend = [];
for (i = 0; i < 3; i++) { 
  toSend.push(function(){
    console.log(i);
  });
}
// call the send actions
for (j = 0; j < 3; j++) { 
  var f = toSend[j];
  f();
}
```

For every i we are creating a function that logs i to the console and after that call each one. We are doing the same with the send functions in pimatic-homeduino: For every protocol create a send function that gets called after the connection is established to the arduino.

You would expect that `1 3 4` is logged to the console, but it logs `3 3 3` instead, because the variable `i` is not bound to the send function, so all send functions use the same `i`, which has the value 3 at the end of the first loop... We had the problem with the variable p. So p was always the last protocol in the array after the send loop and before the send function was called. I just checked p inside the loop first and not in the send function and so p had the right value at this location.

### Solution

Introduce a unnamed function inside the loop that takes i as a parameter and so each send function has its own variable. The unnamed function is then called directly.

```js
// create the send actions
var toSend = [];
for (i = 0; i < 3; i++) { 
  (function(ip) {
    toSend.push(function(){
      console.log(ip);
    });
  })(i);
}
```

ip is now a parameter of the unnamed function and so different for each iteration. We could also name the parameter ip the same like i (just looks a little bit more confusing: 

```js
// create the send actions
var toSend = [];
for (i = 0; i < 3; i++) { 
  (function(i) {
    toSend.push(function(){
      console.log(i);
    });
  })(i);
}
```

Last thing to know is that cs has an shorthand for this construct because its a common solution:

> When using a JavaScript loop to generate functions, it's common to insert a closure wrapper in order to ensure that loop variables are closed over, and all the generated functions don't just share the final values. CoffeeScript provides the do keyword, which immediately invokes a passed function, forwarding any arguments.

http://coffeescript.org/ for loop with "do" example.

**Comment by Icesory** [comment]
Oh. Js is more complex than all other speaks I know. I musst read this more than one time to understand xD
