### ISSUE TITLE
pimatic-homeduino NANO input analog digital input port A0 - A5 

### ISSUE THREAD

**Issue by WimUtTwente** [pimatic/pimatic#457]
Through NANO gate level reading digital and analog just as:
{
  "id": "pin-switch",
  "name": "Pin Switch",
  "class": "HomeduinoSwitch",
  "inverted": false,
  "pin": 13
}
Is that at all possible?
It gives a nice number of input options.
Especially when you can read the analog values

**Comment by sweebee** [comment]
You can do this by writing analog data to the usb serial port on a arduino. And with a little python script you can log the data to a file. Install the pimatic log reader plugin and you can read analog data.

**Comment by WimUtTwente** [comment]
what I mean and search is a plugin zoal in the following example
   {
      "id": "contact-2",
      "class": "NANO Contact",
      "name": "contact 15",
      "gpio": 15
    }

Which then returns a value 0 or 1 or between 0 and 99 as analog input.

**Comment by sweetpi** [comment]
I've added a AnalogSensor device: https://github.com/pimatic/pimatic-homeduino#analogsensor-example
You have to update your arduino as well. There was a but in homeduino that didn't allow to read analog values: https://github.com/pimatic/homeduino/commit/ea00fc03063d18fda4b4fb2c7efe8ad00a3490e9
Devices for contact and other will follow, follow https://github.com/pimatic/pimatic-homeduino/issues/23 for updates.
