### ISSUE TITLE
Variable changes

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#459]
Is it possible to do something like this
`IF $variable updates THEN ...`

I want to do something if a variable has been updated but not changed.

**Comment by Yves911** [comment]
did you try 
```
IF $variable changes THEN ...
```
maybe could work (no warranty here)

**Comment by kenci** [comment]
Yes, `changes` worked, but i need something like `updates` because `$test` is updated every 10 minutes and it doesnt change everytime. I need it to perform an action every 10 minutes, if it changes or not.

**Comment by Yves911** [comment]
so if you need to do something every 10 minutes look at https://github.com/pimatic/pimatic/issues/412#issuecomment-66488483
then you will be able to do
```
IF its10 THEN ...
```

**Comment by kenci** [comment]
So, no other solution as #412 ?

Thank you anyway, Yves.

**Comment by Yves911** [comment]
sweetpi labeled periodical rule as an enhancement, so it will come when it's come.
If you need something right now use my trick (that's work very fine by the way), or maybe try to implement this functionality (i don't have the necessary skills).
For now, if https://github.com/pimatic/pimatic/issues/412 (ie periodical rule implemented) is what you are looking for maybe you can close this issue to avoid duplicates
