### ISSUE TITLE
reinstall pimatic

### ISSUE THREAD

**Issue by Strunz02** [pimatic/pimatic#460]
Hello everybody!

after the last update will no longer run pimatic and there are also various error messages.

What should I do?
What do I have to delete directories
How a new installation?

The Config.json been saved

**Comment by sweetpi** [comment]
Hi,

could you please post the error message. So if I can get a impression of the root of the errors :)

Do the following for a complete reinstall:

```
cd pimatic-app
sudo rm -rf node_modules
npm cache clean
npm install pimatic --production
```

and start pimatic like before. It will fetch all plugins in your config automaticly. Be patient with the installation and start up. Fetching and compiling sqlite at first start up takes some time...

**Comment by Strunz02** [comment]
Thanks for the TIP is now running it again .....
But my config.json is very large
At the back of Copy Entries missing unfortunately all in frontend

What am I doing wrong

Example:

{
      "id": "schalter",
      "name": "Schalter",
      "devices": [],
      "rules": [
        "shutter-1-up",
        "shutter-1-down",
        "shutter-2-up",
        "shutter-2-down",
        "shutter-3-up",
        "shutter-3-down",
        "shutter-4-up",
        "shutter-4-down"
      ],
      "variables": []
    },
....................................
{
      "id": "timer-week-shutter-4-down",
      "name": "Timer_WEEK_Shutter 4 DOWN",
      "rule": "if [it is monday or tuesday or wednesday or thursday or friday] and [ its 17:30 or 17:32 ] then execute \"sudo java -jar /home/pi/shutter-control/shutter-control.jar -s 4 -o DOWN\"",
      "active": true,
      "logging": true
    },
......
