### ISSUE TITLE
After installing new entries are missing in the frontend

### ISSUE THREAD

**Issue by Strunz02** [pimatic/pimatic#461]
But my config.json is very large.

the backup copy entries missing unfortunately all in frontend

What am I doing wrong

Example:

Example:

{
"id": "schalter",
"name": "Schalter",
"devices": [],
"rules": [
"shutter-1-up",
"shutter-1-down",
"shutter-2-up",
"shutter-2-down",
"shutter-3-up",
"shutter-3-down",
"shutter-4-up",
"shutter-4-down"
],
"variables": []
},
....................................
{
"id": "timer-week-shutter-4-down",
"name": "Timer_WEEK_Shutter 4 DOWN",
"rule": "if [it is monday or tuesday or wednesday or thursday or friday] and [ its 17:30 or 17:32 ] then execute \"sudo java -jar /home/pi/shutter-control/shutter-control.jar -s 4 -o DOWN\"",
"active": true,
"logging": true
},
......

**Comment by sweetpi** [comment]
This looks like a very old mobile-frontend config. The settings moved to other place. So you have to build up the fronend again. Take a look at: #207.
