### ISSUE TITLE
mail plugin question

### ISSUE THREAD

**Issue by incmve** [pimatic/pimatic#462]
Hey Guys,

Any one know how to send multiple lines instead of a single line with the mail plugin?
I tried \n but the mail is still a single line.

**Comment by demlak** [comment]
i was also playing much with linebreaks.. but in textmode it seems to impossible..
you have to use html mode, if you want to have linebreaks

**Comment by mwittig** [comment]
@demlak The mail plugin now supports HTML text. This way a message body with multi-line text can be created. Most e-mail clients support HTML text these days.

@sweetpi I think this issue ticket can be closed.

**Comment by demlak** [comment]
I would prefer multiline Text Mail
HTML Mails Produce more traffic and are not that good automatic readable by scripts/progs

**Comment by mwittig** [comment]
Unfortunately, this does not sem to be possible with the nodemailer package used as part of pimatic-mail. The author appears to believe it is not a nodemailer issue but  a problem with the MTA. I tend to disagree on that as I have tested with various MTAs. See https://github.com/andris9/Nodemailer/issues/41

**Comment by sweetpi** [comment]
I don't see the problem. If the string contains new lines, then these should be in the email, or? Some mail clients need two new lines to render it as one new line.

**Comment by mwittig** [comment]
Unfortunately not. I have tried the following:
text:"Just\\n\\na test"  --> Just\n\na test
text:"Just\\r\\na test"  --> Just\r\na test
text:"Just\r\na test"  --> Justrna test

**Comment by sweetpi** [comment]
With  pimatic v0.8.83 "\n" should now be parsed as new line :)

**Comment by mwittig** [comment]
Wow, that great! Works fine for me! Thanks for sorting this!

text:"Hi\neverybody"  --> 
Hi
everybody

**Comment by incmve** [comment]
:+1:

**Comment by mwittig** [comment]
Actually, this has changed with pimatic v0.8.87 and rules parsing may bail out with an syntax. The backslash need to be escaped now in the configuration file!
