### ISSUE TITLE
pimatic does not send off signal when turned off by pimatic but was turned on by remote

### ISSUE THREAD

**Issue by nimpie** [pimatic/pimatic#463]
When a switch is turned on by a remote (my rpi setup does not have a receiver), pimatic still shows "off" of course. However, if a rule applies to turn off all switches at midnight, pimatic does not send an "off" signal. Is there a way to force pimatic to send a signal anyway?

**Comment by Icesory** [comment]
At the moment not. But I think too it must give a method to resend the command from a switch. 
Some times my power plugs don't recognize the transmission and then I must turn toggle the switch in pimatic. It should be possible to click on the actual state of a switch to send his state again. This should be able from rules too.

**Comment by sweetpi** [comment]
Is implemented.
