### ISSUE TITLE
Make pimatic a smart thermostat (PID like?)

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#464]
Currently I'm creating a bunch of rules and variables to calculate how long the central heating is ON, how long did it take to get to the setpoint and how many degrees is that per minute.

When heating starts, it writes in the log a line telling current temperature, setpoint temperature and a calculation of the time needed (based on previous calculated values). When heating is finished, the variables used for the calculations are updated.

When this is working without any issues, I would like to go further and calculate the overshooting temperature (difference between setpoint and highest temperature until roomtemp stops increasing). After that, going further and calculate the time needed to heat room to a certain temp, and start heating so the setpoint is achieved at desired time.

Any ideas and approaches are welcome :+1:

**Comment by bkiss** [comment]
Yesss!
This is what i want also from my raspi. 
If we can make this we will have increased comfort and lower bills. 
The algorythm i like is from Siemens Landis Staefa rev11, is PID-like, i have one and it's much more nice then a normal thermostat.
The king is the Nest, maybe we will get there with pimatic.
For the moment, i have a system with 4 DHT22 sensors, in each room, and the relay for heating online, but only for manual use...for the moment.
I can see the status of the alarm, so i can detect if someone has arrived home, or leave the house, and set the heating regarding this status, maybe he can learn from our behaviour.
I was thinking on heating prcedures with python scripts if we cannot manage with pimatic rules...

Good idea anyway.

**Comment by incmve** [comment]
Currently I am detecting if someones home with the ping plugin, my router has DHCP reservations so all phones have the same IP every time they connect.
if all pings are false then the heating temp is going to a lower temp.

**Comment by koffienl** [comment]
What I have so far:

$OldTemp
$HeatTime
$HeatMinute
$HeatDiff

Detect, and count heating device on
```
IF warmte is on and every 1 minute
THEN $HeatTimer = $HeatTimer + 1
```

Set variables when heating is turned on, calculate time need to reach setpoint
```
IF warmte is on for 15 seconds
THEN $OldTemp = $probe-woonkamer.temperature and $HeatDiff = $thermostaat.temperatureSetpoint - $probe-woonkamer.temperature and after 1 second $HeatTimeNeeded = $HeatDiff / $HeatMinute and after 2 seconds log "Heating from $probe-woonkamer.temperature to $thermostaat.temperatureSetpoint should take $HeatTimeNeeded minutes"
```

Calculate times when heating is off
```
IF warmte is off for 15 seconds
THEN $HeatTime = $probe-woonkamer.temperature - $OldTemp and after 1 second $HeatMinute = $HeatTime / $HeatTimer and after 2 second log "Room changed from $OldTemp to $probe-woonkamer.temperature in $HeatTimer minutes That is $HeatMinute degree per minute" and after 3 seconds $HeatTimer = 0
```

$OvershootTime
$OvershootTemp
$OvershootHelper
$OvershootStartTemp

Add this to the "heat off" rule: <code> and $OvershootHelper = 1 and $OvershootTime = 0 and $OvershootStartTemp = $probe-woonkamer.temperature</code> and add this to the rule where you detect rising/falling of room temp <code>and $OvershootHelper = 0</code>

Detect overshooting right after heating
```
IF $OvershootHelper = 1 and every 1 minute
THEN $OvershootTime = $OvershootTime + 1
```

Detect end of overshoot and calculate overshoot temp and time
```
IF $OvershootHelper = 1 and $BenedenWarmtOp = 0
THEN $OvershootHelper = 0 and after 1 second $OvershootTemp = $probe-woonkamer.temperature - $OvershootStartTemp and after 2 seconds log "Overshoot from $OvershootStartTemp to $probe-woonkamer.temperature in $OvershootTime minutes"
```

**Comment by bkiss** [comment]
Maybe it is not so bad idea to do the heating in cycles, like the Siemens does. I can make the selection from dipswitch setting if i want 7min, 14min or AUTO. That means that i have 7 minutes the heat ON, and after that 7 minutes OFF and in the meantime you can make the measurements with the temperature to decide if is needed another 7 minutes cycle, or less. 
If you have bigger house, with huge walls you will need the longer cycle, but in a small apartment is ok with less.

Anyway, another idea is to make the system stable, failsafe. I want to insert a NC relay with the old thermostat, to have a backup thermostat if the PI is failing or something bad happens.

Until now, my system is not so stable as i wish :( 
A few times per week the node process stops, without loosing the pid file, now i started using the watchdog service to reset the pi if the sql file does not change for 10 minutes, but i'm still not happy...

**Comment by incmve** [comment]
I still have my old thermostat hooked up parallel to my relay.
I am going to remove it, my pimatic/pi is stable enough, as a fallback I am going to make a simple switch on the heater so if I really screw up I can still turn it on ;)

**Comment by koffienl** [comment]
I have a large, detached house. So cycling in 7 minutes is way to short for me. It will take at least 15 minutes for me to detect a increase in roomtemperature.
Right now I'm testing with the overshoot temp. It can build up 0.5 degree in 30 tot 60 minutes coming from waste heat in the radiators.
When turning on the central heating, I heat up to setpoint + upper limit, where upper limit is 0.3
The 0.3 is also used as under limit. 
Example : when the setpoint it 20 , heating will kick in at 19.7 and stay on until 20.3
When you take the overshooting in account, you could stop heating earlier.

**Comment by incmve** [comment]
I currently use this setup
When my heating turns on it sets $cvstarttemp with current temp and there is a rule counting the minutes it's turned on to $cvlasttime
Calculate heat per minute
```
IF Centrale verwarming is turned off
THEN $cvheatdiff = $woonkamer-temp.temperature - $cvstarttemp and after 1 second $cvheatpermin = $cvheatdiff / $cvlasttime
```
In my GUI I have a variable device.
![capture](https://cloud.githubusercontent.com/assets/3177116/5745049/36efee10-9c26-11e4-9864-992ede249c8b.JPG)

Update time needed to heat to desired temp
```
IF every 1 minute
THEN $cvheattimeestimate = ($thermostaat.temperatureSetpoint - $woonkamer-temp.temperature) / $cvheatpermin
```

**Comment by WimUtTwente** [comment]
Are doing the same but even more complex. now can through old DOS computer 7 rooms heat independently and 5 rooms have private termastaat. The aim is to arrange that through pimatic. And optimally so to measure the outside temperature and of going in and out of water. Would like to see your config.json i as possible. Who knows, we can bring together here in on good ideas.

**Comment by bkiss** [comment]
koffienl :  "Example : when the setpoint it 20 , heating will kick in at 19.7 and stay on until 20.3
When you take the overshooting in account, you could stop heating earlier."

I don't know if we can make an online calibration, but i will be pleased if we can, even manually, set a few rules, taking in calculation the external temperature, to know how long (time) is the cycle, to get the smallest overshoot. I hope you can understand my english :)
Like this: 
1. If (outside_temp < -5 C) and (inside_temp < set_temp - 0.2) and (inside_temp is not rising) turn heat on for 15 min
2. If (outside_temp > -5 C) and (inside_temp < set_temp - 0.2) and (inside_temp is not rising) turn heat on for 10 min
3. If (outside_temp > 5 C) and (inside_temp < set_temp - 0.2) and (inside_temp is not rising) turn heat on for 5 min

I am sure that these rules is not enough, is just for illustration...

**Comment by bkiss** [comment]
I think we don't need PID, just ID, like TPI thermostats. 

------------
How does TPI Control work?
A thermostat operates using a fixed number of firing periods per hour (normally selected to suit the appliance and system). This can often mean a thermostat can fire the boiler even when the set temperature is reached.
 
A TPI room thermostat will have 100% demand when the system first calls for heat. When the room temperature approaches the set point, it then calculates how many minutes are required within each firing period to satisfy the set temperature. The TPI thermostat will then reduce the firing time in that cycle period in proportion with the demand.  This means that as the room temperature approaches set point, the boiler is fired progressively less.
----------------
source: http://www .  homexpertbyhoneywell . com


Or:
TPI - Traditionally, room thermostats have used an on/off algorithm. Put simply, this means that when a room’s temperature is below the thermostat’s setting, the heating is on, and when it is above the necessary temperature, the heating is off. This effectively means that the actual room temperature is constantly fluctuating around the target temperature and consequently, wasting energy.

However, more advanced room thermostats use Time Proportional Integral (TPI) control to ensure more accurate temperature control and the resulting energy savings.

TPI offers a more complex algorithm, which uses past information to estimate the correct steady state ratio of each room within six, ten-minute cycles per hour. During each one of these ten-minute periods, the algorithm has set a period of time with the heating on that is calculated to maintain thermal equilibrium. The ‘I’ (integral) part of the TPI control makes small, long-term adjustments to the process, varying the length of the heating times to keep the room temperature even more precisely on set-point.
-------------
source: http://www.  draytoncontrols.  co.  uk/

 Maybe this helps.

**Comment by bkiss** [comment]
Ok,

My actual working rules are the following:
Futes = Heating
khnappali - set point temperature. 

      "rule": "if $nappali.temperature > $PreviousTemp and Futes is turned off then $WarmsUp = 1 and $PreviousTemp = $nappali.temperature",

      "rule": "if $nappali.temperature < $PreviousTemp and Futes is turned off then $WarmsUp = 0 and $PreviousTemp = $nappali.temperature",
  
      "rule": "if $nappali.temperature < $khnappali-0.2 and Futes is turned off and disable_siemens is turned on and $WarmsUp = 0 for 3 minutes then turn Futes on for $WarmTime minutes and after $WarmTime minutes $OvershootTime = 0 and $StateHelper = 1",

      "rule": "if $WarmsUp = 1 and Futes is turned on and disable_siemens is turned on and $nappali.temperature > $khnappali and every 1 minutes then $OvershootHelper = 1 and $OvershootTime = $OvershootTime + 1 and $OvershootTemp = $nappali.temperature",

      "rule": "if $OvershootTemp - $khnappali > 0.2 and $WarmsUp = 0 and $StateHelper = 1 then $WarmTime = $WarmTime - 1 and $StateHelper = 0",

      "rule": "if $WarmsUp = 0 and $StateHelper = 1 and $nappali.temperature < $khnappali then $WarmTime = $WarmTime + 1 and $StateHelper = 0",
    

The concept is if i have overshooting then lower the minutes for the next heating cycle, if i cannot rise the temperature to the set point then try to heat even more.

**Comment by bkiss** [comment]
Not good enough :(

In the graph you can see the difference during at night was the Siemens... 

![screen shot 2015-02-13 at 16 04 27](https://cloud.githubusercontent.com/assets/5294516/6188483/37951d3c-b39a-11e4-8096-2164ea8fcc61.png)

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
