### ISSUE TITLE
homeduino in combination with self programmed sketch.

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#466]
hi all, 
i have installed a receiver on my raspberry to receive temp. and humidity. but without the attiny the cpu load is too high.

now i want to switch with the receiver to my arduino.
on my arduino runs a sketch that send values from energy consumption into a file.

my question now is, is it possible to use the homeduino sketch with my sketch together?
and does it lower my high cpu load?

can someone please give me a short instruction to realize that?
when is install the homeduino plugin, does it overwrite my sketch?

thank you all.

**Comment by Icesory** [comment]
When you upload the Homeduino sketch then overrides yours. How is the arduino connected at the moment with your sketch? When it used the serial connection to communicate with the raspberry it is not easy possible to solve this.

**Comment by p4co86** [comment]
```
#!/usr/bin/python
import os
import time
import serial
ser = serial.Serial('/dev/ttyACM0', 9600)
......
```

**Comment by Icesory** [comment]
The problem is that only one program can access the serial connection at the same time. You have three ways to solve this. First you write some code in the pimatic-homeduino plugin to read your part of the script. Or the other way is to use a Softwareserial on the arduino and a second Serial2Usb converter. So you have two serial connections. The last way is to use two arduinos.

**Comment by p4co86** [comment]
You mean one programm on the raspberry can access the serial port. I use the alecto wsd 17 temp./hum. Sensor, is it possible to use it with homeduino?

**Comment by Oitzu** [comment]
Alecto should be the weather5 protocol. See https://github.com/pimatic/rfcontroljs/blob/master/protocols.md

**Comment by Yves911** [comment]
can't you connect 2 arduino and get /dev/ttyACM0 and /dev/ttyACM1?

**Comment by p4co86** [comment]
in pimatic i used the protocol alecto_ws1700 with id 1483

but when i use weatherstation 5 i get 0° and 0%

make monitor shows this
```
RF receive 519 1923 3875 9180 0 0 0 0 01020102020201010201020202010102010101010202010202020202010102010201020103
RF receive 517 1923 3879 9172 0 0 0 0 01020102020201010201020202010102010101010202010202020202010102010201020103
RF receive 515 1927 3879 9172 0 0 0 0 01020102020201010201020202010102010101010202020101010101010102010201020103
RF receive 513 1928 3881 9176 0 0 0 0 01020102020201010201020202010102010101010202020101010101010102010201020103
RF receive 518 1925 3875 9180 0 0 0 0 01020102020201010201020202010102010101010202010202020202010102010201020103
RF receive 518 1924 3877 9168 0 0 0 0 01020102020201010201020202010102010101010202010202020202010102010201020103
```

**Comment by htca** [comment]
could you put some debug log lines and your device config?
