### ISSUE TITLE
SSDP Problem with Pilight

### ISSUE THREAD

**Issue by suchalaugh** [pimatic/pimatic#467]
Hi, I'm kind of new to this stuff but very willing to learn. I set up a functioning pilight system but want to enhance it with pimatic. Pilight-Plugin is installed (I guess) but it comes out this, everytime I start it

13.01.2015 18:18:43info [pimatic-pilight]: connected to pilight-daemon
18:18:43info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:43info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:43warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:43info [pimatic-pilight]: connected to pilight-daemon
18:18:43info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:43info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:43warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:42info [pimatic-pilight]: connected to pilight-daemon
18:18:42info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:42info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:42warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:42info [pimatic-pilight]: connected to pilight-daemon
18:18:42info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:42info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:42warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:42info [pimatic-pilight]: connected to pilight-daemon
18:18:42info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:42info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:42warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:42info [pimatic-pilight]: connected to pilight-daemon
18:18:42info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:42info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:41warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:41info [pimatic-pilight]: connected to pilight-daemon
18:18:41info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:41info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:41warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:41info [pimatic-pilight]: connected to pilight-daemon
18:18:41info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:41info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:41warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:41info [pimatic-pilight]: connected to pilight-daemon
18:18:41info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:41info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:41warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:41info [pimatic-pilight]: connected to pilight-daemon
18:18:41info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:41info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:40warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:40info [pimatic-pilight]: connected to pilight-daemon
18:18:40info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:40info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:40warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:40info [pimatic-pilight]: connected to pilight-daemon
18:18:40info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:40info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:40warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:40info [pimatic-pilight]: connected to pilight-daemon
18:18:40info [pimatic-pilight]: pilight: found pilight server , trying to connect
18:18:40info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:40warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:40info [pimatic-pilight]: connected to pilight-daemon
18:18:40info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:40info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:39warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:39info [pimatic-pilight]: connected to pilight-daemon
18:18:39info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:39info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:39warn [pimatic-pilight]: Lost connection to pilight-daemon
18:18:39info [pimatic-pilight]: connected to pilight-daemon
18:18:39info [pimatic-pilight]: pilight: found pilight server 192.168.1.127:34174, trying to connect
18:18:39info [pimatic-pilight]: pilight: trying to find pilight via SSDP
18:18:39warn [pimatic-pilight]: Lost connection to pilight-daemon

Maybe you can tell me what I did wrong? Greetings from Vienna

**Comment by incmve** [comment]
See #149 are you using the pilight development/nightly version?

**Comment by sweetpi** [comment]
Looks like the development version, see #149
