### ISSUE TITLE
cannot drill down to graph at lowest device on screen

### ISSUE THREAD

**Issue by skipper79** [pimatic/pimatic#470]
when my screen is filled with devices and the lowest devices contains a graph, I cannot drill down to the graph. It is shown under the device and not possible to click/tab.
Tested on a device with iOS 8.1.2
![fullsizerender](https://cloud.githubusercontent.com/assets/3088540/5739472/24c7c8c4-9bfa-11e4-8283-710b1c5f6759.jpg)

**Comment by Oitzu** [comment]
Copy of #465
