### ISSUE TITLE
CUL @ 433 MHz with pimatic

### ISSUE THREAD

**Issue by archipita** [pimatic/pimatic#471]
Hello,
I am trying to bind a CUL USB module @ 433 MHz using the COC plugin, but it is not working.
I could use this module with FHEM driving switches from Intertechno without issues, but I'd like to have it under pimatic.
Has anyone already tried successfully?

I get the info:
...
[pimatic-coc] init with serial device name /dev/ttyAMA0@9600, hardwareType CUL
[pimatic-coc] info: open serialPort /dev/ttyAMA0
...
[pimatic] error: Error loading device socket2: Cannot convert null to object
...

Thank you.

**Comment by sweetpi** [comment]
Please ask the plugin author at: https://github.com/dfischbach/pimatic-coc
