### ISSUE TITLE
Graphical rule editor

### ISSUE THREAD

**Issue by sweetpi** [pimatic/pimatic#473]
Just some preview of what I'm currently working on: https://drive.google.com/file/d/0BwcdO4MVniTzQ1hieXB4ZWc5a2c/view?usp=sharing

**Comment by incmve** [comment]
I just saw in in the dev version and was googeling it :)
:+1: really nice

**Comment by leader21** [comment]
wheeew :+1:  looks very promising

**Comment by Fritz4all** [comment]
Nice :+1:

**Comment by Yves911** [comment]
Will be a great help for beginners not for us : advanced users :-)
look promising

**Comment by Icesory** [comment]
Realy nice. But it looks verry hard to code.

**Comment by sweebee** [comment]
How about a in GUI device editing and adding?

**Comment by stat2** [comment]
Is it possible to switch the graphical gui off? I am facing issues where the trigger: is always removed from the rule (using git development branch of about 1 week old)

**Comment by sweetpi** [comment]
> Will be a great help for beginners not for us : advanced users :-)
> look promising

I think in particular on mobile devices its useful for everybody :)

> Realy nice. But it looks verry hard to code.

Yes, but it's fun.

> How about a in GUI device editing and adding?

Hopefully soon.

> Is it possible to switch the graphical gui off? I am facing issues where the trigger: is always removed from the rule (using git development branch of about 1 week old)

I will add support for the trigger keyword. It will remember the last used editor per device in the future. There is currently no easy way to deactivate the editor.

**Comment by sweetpi** [comment]
Released with pimatic-mobile-frontend 0.8.40. Some plugins have still to be expanded.
