### ISSUE TITLE
Equals comparator for device attributes does not work

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#474]
I am not able to get a rule firing on an equals compare for a device attribute. With variables it works fine, but not with a **ShellSensor**.
 ```
   {
      "id": "mode",
      "name": "ModeSensor",
      "class": "ShellSensor",
      "attributeName": "value",
      "attributeType": "string",
      "attributeUnit": " ",
      "command": "getOnOrOff",
      "interval": 10000
    }
```
and the rule
```
    {
      "id": "rule1",
      "name": "rule1",
      "rule": "if $mode.value = \"ON\" then log \"mode sensor changed to on \"",
      "active": true,
      "logging": true
    },
```
I also tried 
```"if value of mode equals = \"ON\"" ```

but nothing works. Other comparators like < or > works fine.

**Comment by sweetpi** [comment]
Thanks for the report.

Could you try to set `attributeUnit` to an empty string (not one space)? How does your `getOnOrOff`-Script output the mode (Best would be the corresponding script line)?

**Comment by Heizelmann** [comment]
Setting ```attributeUnit``` to an empty string doesn't help.

The ```getOnOrOff``` is only a placeholder I used only to describe the problem in a more general way. In fact I use those vclient from discussion  #438 which delivers the strings AUS or EIN to the shell.

```
~/pimatic-app > $ vclient -h localhost:3002 -t /home/pi/openv/1str.tmpl -c getPartyBetriebA1M1
AUS
~/pimatic-app >$
```

**Comment by Heizelmann** [comment]
I think I found the reason. I am not so familiar with UNIX Shell programming, but with a little node.js javascript I analyzed that a NEWLINE character is added automatically to an  output string when send to stdout. When removing this (I did it in the javascript) the match is OK. Maybe this should be fixed in Pimatic.
Meanwhile can some UNIX-Expert give me a simple pipe construct to remove the linefeed from the output of the vclient command? 
Here my provisional javascript which should become obsolete:
```
var sys = require('sys');
var exec = require('child_process').exec;
function puts(error, stdout, stderr) {
  var result = stdout.toString();
  result = result.substr(0,result.length-1);
  process.stdout.write(result);
}
exec("vclient -h localhost:3002 -t /home/pi/openv/1str.tmpl -c getPartyBetriebA1M1", puts);
```

**Comment by sweetpi** [comment]
Thanks for the info: I've updated the plugin so that it trims the string before further processing. This should remove all leading and tailing whitespaces and new lines. Could you try your luck with pimatic-shell-execute v0.8.3?

**Comment by Heizelmann** [comment]
Thanks, it works. Another small issue might be on the output side of execute a shell command. If the command returns a value it seems that the logging also print out the Linefeed:

```
20:54:19.757 [pimatic] info: rule betriebsart-heizen-und-ww: executed "vclient -h localhost:3002  -c 'setBetriebsartA1M1 Heizen und WW'": setBetriebsartA1M1 Heizen und WW:
20:54:19.757 [pimatic] info:>OK
20:54:19.757 [pimatic] info:>
```

**Comment by sweetpi** [comment]
Fixed.
