### ISSUE TITLE
Special Characters on the UI like °C

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#475]
How can I enter special characters like the degree sign (°) in the config.json so that they apear correctly on UI? When I enter directly from the keyboard the characters get overriden by the pimatic system. For example ° is changed to ï¿½

**Comment by Yves911** [comment]
are you using utf-8 in your text editor?

**Comment by Heizelmann** [comment]
No it was ANSI-LATIN1. I switched to UTF and now it works. Thanks!
