### ISSUE TITLE
[Mobile-frontend] Switch linked to variable?

### ISSUE THREAD

**Issue by Nears** [pimatic/pimatic#478]
Hi,

I was just wondering if it is possible to add a switch to the frontend wich is linked to a variable, so i can change the state of the variable via the switch.
After that I could define a rule which e.g. shuts down my pi via the shell-execute plugin.

Is this possible?
Thanks for any help or tipps.

**Comment by Icesory** [comment]
You can use a dummy switch and two rules to set a every variables. 
If button xyz is switched to on then set variable to 1
If button xyz is switched to off then set variable to 0

**Comment by Nears** [comment]
Cool i did not know that there is a possibility for dummy switches.
How do I add them? Via the GUI?

**Comment by Icesory** [comment]
You must define all devices in the Config. 
Look there 
https://github.com/pimatic/pimatic/issues/250

**Comment by Nears** [comment]
Thanks. This helps me out!
