### ISSUE TITLE
Any way to show Sunrise / Sunset time on screen?

### ISSUE THREAD

**Issue by DDNRN** [pimatic/pimatic#479]
For the pimatic sunrise Plugin I am looking for a way to show the actual sunset or sunrise times in GUI.
Is there anything like that usable in the moment?

I would prefer if there was a kind of device on the screen, like a temperatur-sensor for example, what gives the actual sunset and sunrise time to see when my next action is triggerd.

Diffferent times for sunrise, sunset and more maybe choseable through different device-config.

**Comment by Icesory** [comment]
i dont know a native method.
But i think you can create a variables device with string as type and every day at sunrise or sunset you wrote with rules the current time into this. I am not shure how to get the current time in a rule but i think this is possible.

A TimeDevice for the Sunset plugin would be nice.

**Comment by leader21** [comment]
> Is there anything like that usable in the moment

not at the moment. i extracted this information out of an protocol from my photovoltaic inverter and used the logreader plugin to show the actual time of sunrise and sunset.
Somebody with coding skills needs to implement this to pimatic.

**Comment by cklam2** [comment]
You could use pimatic plugin [shell-execute](http://pimatic.org/plugins/pimatic-shell-execute/) to execute a shell command like this and capture the output + show on the pimatic web page.
```l
=12765843;curl -s http://weather.yahooapis.com/forecastrss?w=$l|grep astronomy| awk -F\" '{print $2 "\n" $4;}'
```
See [here] (http://www.commandlinefu.com/commands/view/6882/get-sunrise-and-sunset-times) for more info, also describes how to get the correct l-value.

**Comment by sebster6** [comment]
I finally got this working, thanks to your input from this thread. So I have these two ShellSensors (w should be your Yahoo location code), and they are working just fine to display sunrise and sunset in the UI:

```json
    {
      "id": "sonnenaufgang",
      "name": "Sonnenaufgang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss?w=XXX|grep astronomy| awk -F\\\" '{print $2}'",
      "interval": 43200
    },
    {
      "id": "sonnenuntergang",
      "name": "Sonnenuntergang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss?w=XXX|grep astronomy| awk -F\\\" '{print $4}'",
      "interval": 43200
    },
```

The only thing I can't work out is how to do the conversion to 24 hour format. I tried getting the resulting value as an input to date (date +"%H:%M" -d "some 12 hr value"), but how can I get this working in the command above? Any hint on how this might work is very much appreciated.

Best regards
Sebastian

**Comment by cklam2** [comment]
Took me a while to figure out but if you add following to the end of your command it will output the time in 24h format
```
|{ date -f - +%R; }
```

**Comment by sebster6** [comment]
Thank you so much, works like a charm! :)
![bildschirmfoto 2015-02-08 um 11](https://cloud.githubusercontent.com/assets/9269030/6096176/e9f021cc-af83-11e4-9dfd-8930e5fd150d.png)

**Comment by cklam2** [comment]
Glad that it works :)

Btw, in your configuration the interval is set to 43200, guess you want to poll every 12h? According to the interface description the interval is in ms (milliseconds) which means, in your case it is polling every 43 seconds.

**Comment by sebster6** [comment]
Whoops. Thanks for the hint, changed it to 43200000 - sunrise/sunset times probably won't change every minute. ;)

**Comment by kenulu** [comment]
Hi,
something is wrong in my code, its not working. here is my code, what is wrong?

"command": "curl -s http://weather.yahooapis.com/forecastrss?w=695336|grep astronomy| awk -F\\\" '|{print $4}'|{ date -f - +%R; }",

**Comment by sebster6** [comment]
You need to escape the backslash in the awk command (so there have to be three after the -F).

**Comment by kenulu** [comment]
Hallo Sebster6,

thank for you answer, but it is not working in the 24h format. Here my code:
<code>"command": "curl -s http://weather.yahooapis.com/forecastrss?w=XXX|grep astronomy| awk -F\\\\\\" '{print $4}'|{ date -f - +%R; }",</code>
Soory in my first post kills the forum software one backslash

**Comment by cklam2** [comment]
What is not working? Is the time displayed in 12h format?
Try to execute the command in the shell and post what you see:
```
curl -s http://weather.yahooapis.com/forecastrss?w=695336|grep astronomy| awk -F\" '{print $4}'|{ date -f - +%R; }
```
I also noted that in your previous post there is a pipe in front of {print $4}, did you remove that one?

**Comment by kenulu** [comment]
Hallo cklamm2,
thanks its work now in 24h Format!
I had not see the three backslash!

**Comment by ituri** [comment]
I tried to set up the same shell-sensor, but it doesn't work for me. Here's my configuration:
```
    {
      "id": "sonnenaufgang",
      "name": "Sonnenaufgang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss\?w\=xxx | grep astronomy | awk -F\\\" '{print $2}'",
      "interval": 43200000
    },
    {
      "id": "sonnenuntergang",
      "name": "Sonnenuntergang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss\?w\=xxx | grep astronomy | awk -F\\\" '{print $4}'|{ date -f - +%R; }",
      "interval": 43200000
    },
```
And here's the error that I get when I try to start pimatic:
```
15:46:48.908 [pimatic] info: Starting pimatic version 0.8.43
15:46:49.108 [pimatic] error: Unexpected character: "
15:46:52.035 [pimatic] debug: SyntaxError: Unexpected character: "
15:46:52.035 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:68:21
15:46:52.035 [pimatic] debug:>    at Object.transform (/home/pi/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:224:18)
15:46:52.035 [pimatic] debug:>    at Framework._loadConfig (/framework.coffee:96:36)
15:46:52.035 [pimatic] debug:>    at new Framework (/framework.coffee:54:8)
15:46:52.035 [pimatic] debug:>    at /startup.coffee:36:21
15:46:52.035 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
15:46:52.035 [pimatic] debug:>    at Function.Promise$_Try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:233:11)
15:46:52.035 [pimatic] debug:>    at Object.module.exports.startup (/startup.coffee:35:10)
15:46:52.035 [pimatic] debug:>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
15:46:52.035 [pimatic] debug:>    at /daemon.coffee:98:9
15:46:52.035 [pimatic] debug:>    at Object.oncomplete (fs.js:107:15)
```
Any ideas?

**Comment by cklam2** [comment]
You need to remove the backslashes between forecastrss, ?w and =xxx
Also I assume that you entered a number instead of xxx :)
So
```
"command": "curl -s http://weather.yahooapis.com/forecastrss?w=xxx | grep astronomy | awk -F\\\" '{print $2}'",
```

**Comment by ituri** [comment]
ah! now it's working. Thanks! :)

**Comment by DDNRN** [comment]
Great!  I got it working on my first attempt. 
Thank you all!

pimatic is my friend ;-)

**Comment by cklam2** [comment]
Congratulations :)
Now you can close this issue.

**Comment by DDNRN** [comment]
@cklam2 
not at all: I would prefer a native value from the sunrise-plugin.
Now we using two different services to get the value on screen an switch with rules from plugin.

But of course yes, this is not a important issue

**Comment by Icesory** [comment]
I have open a feature request 
http://forum.pimatic.org/topic/70/device-to-show-times-from-pimatic-sunrise

**Comment by mcblacky** [comment]
If you do not want to use an external website you could install sunwait (https://www.risacher.org/sunwait/) and use this configuration with ShellSensor:

 {
      "id": "Zonsopkomst",
      "name": "Zonsopkomst",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "/home/pi/sunwait -p 52N 5E | grep 'Sun rises' | awk '{print $3, $4}' | rev | cut -c 2- | rev",
      "interval": 43200000
    },
    {
      "id": "Zonsondergang",
      "name": "Zonsondergang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "/home/pi/sunwait -p 52N 5E | grep 'Sun rises' | awk '{print $6, $7}'",
      "interval": 43200000
    }

**Comment by p24matze** [comment]
@sebster6 how do you make the switch alle schalten?

**Comment by Icesory** [comment]
@p24matze It is a type of the ButtonsDevice
I think it is a "DummyButton" and linked with rules to all the other switches.

**Comment by p24matze** [comment]
How can I link rules, can you give me an example pls?

**Comment by Icesory** [comment]
I forgot that at the moment no ActionProvider for ButtonDevice exist.
So this is a HomeduinoRFButtonsDevice with multiple rules.
https://github.com/pimatic/pimatic-homeduino

**Comment by sebster6** [comment]
This is how my config looks like:

```
    {
      "id": "all-on-off-eg",
      "name": "Alle schalten",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "eg-on",
          "text": "An"
        },
        {
          "id": "eg-off",
          "text": "Aus"
        }
      ]
    }
```

The rest is done by rules like:
_if eg-on is pressed then switch Esszimmer on and after 1 second switch Wohnzimmer on and after 2 seconds switch Küche on and display "Zuletzt: EG an" on lcd line 3"_

**Comment by p24matze** [comment]
Nice, thank you! Works pretty well.

**Comment by noxx2015** [comment]
will not run on my system

16:59:53.995 [pimatic] info: Starting pimatic version 0.8.73
16:59:54.496 [pimatic] error: Startup error: SyntaxError: Unexpected character: "
16:59:54.496 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:68:21
16:59:54.496 [pimatic] error:>    at Object.transform (/home/pi/pimatic-app/node_modules/pimatic/node_modules/relaxed-json/relaxed-json.js:224:18)
16:59:54.496 [pimatic] error:>    at Framework._loadConfig (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:98:36)
16:59:54.496 [pimatic] error:>    at new Framework (/home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:56:8)
16:59:54.496 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/startup.coffee:48:21
16:59:54.496 [pimatic] error:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
16:59:54.496 [pimatic] error:>    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/method.js:31:24)
16:59:54.496 [pimatic] error:>    at Object.module.exports.startup (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:47:10)
16:59:54.496 [pimatic] error:>    at run (/home/pi/pimatic-app/node_modules/pimatic/pimatic.js:15:24)
16:59:54.496 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/daemon.coffee:87:9
16:59:54.496 [pimatic] error:>    at Object.oncomplete (fs.js:107:15)
16:59:54.500 [pimatic] info: exiting...




      "plugin": "shell-execute"
    {
      "id": "sonnenaufgang",
      "name": "Sonnenaufgang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss?w=xyz | grep astronomy | awk -F\\\" '{print $2}'",
      "interval": 43200000
    },
    {
      "id": "sonnenuntergang",
      "name": "Sonnenuntergang",
      "class": "ShellSensor",
      "attributeName": "time",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "curl -s http://weather.yahooapis.com/forecastrss?w=xyz | grep astronomy | awk -F\\\" '{print $4}'|{ date -f - +%R; }",
      "interval": 43200000
    }
    },

**Comment by leader21** [comment]
where do you put the plugin at your config? at the plugin section?

have a look here for another option
http://forum.pimatic.org/topic/108/sunrise-and-sunset-device-via-shellsensor-plugin
