### ISSUE TITLE
SSL connection gets closed immediately

### ISSUE THREAD

**Issue by ituri** [pimatic/pimatic#480]
Hi,

I've tried setting up SSL. Here's my config:
```
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 8001
    },
    "httpsServer": {
      "enabled": true,
      "port": 8002,
      "hostname": "",
      "keyFile": "ca/pimatic-ssl/private/privkey.pem",
      "certFile": "ca/pimatic-ssl/public/cert.pem",
      "rootCertFile": "ca/certs/cacert.crt"
    },
```
HTTP works fine, but when I try connecting, Chrome tells me that the connection gets interrupted immediately after hitting enter. Same for Firefox: ```The connection to 192.168.0.5:8002 was interrupted while the page was loading.```
Any ideas as to what is happening there?

Best
Philipp

**Comment by sweetpi** [comment]
Hi,

how did you generate the certificates/keys?

**Comment by ituri** [comment]
I used the script from https://raw.githubusercontent.com/pimatic/pimatic/master/install/ssl-setup

**Comment by sweetpi** [comment]
hm strange. I've no idea whats wrong. Maybe try another port. Any errors in pimatic's logifle?

**Comment by ituri** [comment]
Wow. Wouldn't have thought that, but picking a different port has worked just fine. Thanks for the help!
