### ISSUE TITLE
pimatic-log-reader: Show temperature/humidity on main screen

### ISSUE THREAD

**Issue by ituri** [pimatic/pimatic#481]
Hi,

I've set up pimatic-log-reader so that it reads the current temperature from a text file. In this text file, the current temperature is always on top, followed by the temperature from five minutes ago in the second line and so on. Here's what it looks like:
```
7.6
7.6
7.6
7.7
7.8
```
Here's the corresponding part of my pimatic configuration:
```
  "devices": [
    {
      "id": "temperature-strasse-from-logfile",
      "name": "Temperature-Strasse",
      "class": "LogWatcher",
      "file": "/home/pi/wetter/strasse.temp",
      "attributes": [
        {
          "name": "temperature",
          "type": "number",
          "unit": "°C"
        }
      ],
      "lines": [
        {
          "match": "(.+)",
          "temperature": "$1"
        }
      ]
    },
```
When I click on the graph, pimatic shows me the current temperature without any problems. However, the temperature on the main screen doesn't seem to get updated. It always shows the same old temperature back from the first time that I ran this plugin. Is this a known problem?
Here's a screen shot in order to show you what I mean by "main screen":
![screen shot 2015-01-17 at 19 44 08](https://cloud.githubusercontent.com/assets/871297/5789941/7c49b768-9e81-11e4-9c1b-c905708cb671.png)

Cheers
Philipp

P.S.: I opened this issue here since pimatic-log-reader doesn't seem to have a issue-section on github. I hope that's okay.

**Comment by leader21** [comment]
the values are rounded. I already mentioned that in issue #387 
i don't know if maybe another match would do the job ... but i guess it's a generic issue since i am also having it at the volkszaehler plugin while reading out photovoltaic data.

**Comment by sweetpi** [comment]
> P.S.: I opened this issue here since pimatic-log-reader doesn't seem to have a issue-section on github. I hope that's okay.

That's perfectly fine.

> the values are rounded. I already mentioned that in issue #387 
> i don't know if maybe another match would do the job ... but i guess it's a generic issue since i am also having it at the volkszaehler plugin while reading out photovoltaic data.

It's right, that the values are rounded, but the values are rounded to two decimals. So this shouldn't be the problem here. I've done a quick test with the config, but I get the correct values. @ituri How do you write the values to the log file?

**Comment by ituri** [comment]
I'm getting the data from my rrdtool-db. The script (which might be ugly - I'm not got at shell scripting) looks as follows:
```tmp="$(rrdtool lastupdate weather.rrd | tail -1 | sed 's/^.\{,12\}//' | sed 's/\ U//g' | awk '{print $1}')"
echo $tmp | cat - /home/pi/wetter/strasse.temp > /tmp/strasse.temp && mv /tmp/strasse.temp /home/pi/wetter/strasse.temp```

I might have an idea about what could be wrong here:
1. Does pimatic need a) the complete logfile with all the past temperature values or does b) it only need the current temperature and then store it in its own database?
2. Where does pimatic look for the latest temperature value? In the first or in the last line of the file?

**Comment by sweetpi** [comment]
1. It only needs the current temperature.
2. In the last line.

I think a ShellSensor should work much better in you use case: https://github.com/pimatic/pimatic-shell-execute

**Comment by ituri** [comment]
I've modified my script to just write the latest temperature value into the corresponding file. After that I've switched to pimatic-shell-execute and it works much better - I now have the latest and correct value in my dashboard. Thanks!
