### ISSUE TITLE
pimatic and Infrared Signals receive and send?

### ISSUE THREAD

**Issue by Tueftler1983** [pimatic/pimatic#483]
Hallo is it possible to receive and send infrared signals? I like to switch on my Soundbar but the only way to do this is sending a infrared signal or electric welding wires on the ON/OFF switch.

I now it is not possible to to it with lirc.

Please don't be angry about my English I have used it not for long time.
Es darf auch gerne auf Deutsch geantwortet werden

**Comment by incmve** [comment]
@koffienl has used an Arduino nano with RF receiver and IR.
The nano pics up a RF signal and transmits an IR signal to his devices.
https://github.com/koffienl/pimatic-probe

**Comment by georg90** [comment]
Also here: https://github.com/Icesory/Rf-Ir-Remote

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
