### ISSUE TITLE
I2C protocoll

### ISSUE THREAD

**Issue by BenI2C** [pimatic/pimatic#486]
I have at home a I2C bus for monitors several windows, doors,  temp sensors and a counter for the watermeter.
For now i use a raspberry, and upload it to Xively. https://xively.com/feeds/103524/
How can i read and manipulate these I2C-bus data also in pimatic ?

**Comment by sweetpi** [comment]
If you have programming skills you can write a plugin for pimatic. If not, you can use a ShellSensor (http://pimatic.org/plugins/pimatic-shell-execute/) or the pimatic-log-reader (http://pimatic.org/plugins/pimatic-log-reader/).

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
