### ISSUE TITLE
ShellSwitch on Windows problem with echo on/off

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#489]
As also reported  in discussion #293 **ShellSwitch** causes a problem on WINDOWS 
```"getStateCommand": "echo false"```.  WINDOWS echo command does not return on or off as string. It uses it for switching off/on the echo mode.

For compatibility in my opinion it would be good to enhance the plugin shell-execute in that way that it not only accepts on/off but additionally true/false as stdout value. This would easily solve the problem.

**Comment by Xento** [comment]
I modified the plugin that true and false is although accepted

**Comment by sweetpi** [comment]
Thanks, merged in v0.8.5
