### ISSUE TITLE
RF signals do not always switch devices when triggered via rule

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#491]
I was wondering why sometimes my devices do not switch when triggered via rule. 
I had installed another wall switch to switch my fan at the ceiling.
The fan is attached to an Intertechno ITL3500 triple device and I wanted to switch it via RF wall switch and a rule like <code>"IF wallswitch is turned on THEN switch ceilingfan on"</code> and vice versa. The switch for the fan has a different id then the wallswitch (otherwise it would switch the fan directly). Now my issue is, that the fan doesn't always switch when triggered via rule. When I set the id for the itl-3500 fan switch device and the wall switch to the same the fan switches without any problems. 

Also my shutter switches for the blinds do not always react when they should open or close by sunrise or sunset (triggered via rule). It's not always the same shutter that does not close or open. It's totally different. Even the shutters at the living room that are only three meters away from the pimatic pi has some RF lags. 
I already tried different antennas but this doesn't seem to make any difference. At the moment i use a simple 17.5cm straight copper wire. (receiving data at the pi is not the problem! i am receiving all switch data or weather data from several weather devices).

The interesting thing is, that when i switch devices via GUI, they switch reliable! 
I would say there's a tolerance of 5% not switching via GUI and approx. 30% when switching via rule.
Almost every morning or evening i must open/shut blinds manually or switch on/off my fan manually.

To give some background info for the fan - i am measuring the temperature at the living room. We're having a pellet oven and when it's on, it's getting warm very quickly but most of the warm air is located at the ceiling, sure ^^. When the temperature is above 21.5°C the fan should switch on and if the temperature is lower than 21.5 it should switch off. Therefore I created a simple rule <code>"IF $weathersensor2.temperature is > 21.5 THEN switch ceilingfan on"</code> and vice versa. If the temperature in the living room is below 21.5°C and the fan sometimes is still on 'cause it was not receiving the RF signal, it's getting cold ^^ usually the fan should whirl the warm air at the ceiling down, but if there's no warm air anymore ... *brrr* getting cold.

I discovered, that i had better results in receiving RF data with homeduino after switching over to the RFControl from Icesory. Maybe there could be some little patch to get things straight here for transmitting RF signals too? Don't know if this is only at my setup here.

Has anybody else similar issues with devices not switching via rules or has any tips for me?! 
(sorry for this long story ;)

**Comment by incmve** [comment]
if I'm correct the RFcontrol from @Icesory handles the receive verification different.
I have 2 Pi's one with the original and the other with Ronny's but I havent really compared the difference in receiving.

**Comment by sweetpi** [comment]
I think most of the time RF collisions are the problem (two devices that send at the same time) In particular the rule "IF wallswitch is turned on THEN switch ceilingfan on" is fragile for this, because if the wallswitch still sends repeated messages for "turn on" the ceilingfan message gets lost. Maybe a delay could help here "... after 5 seconds".

@Icesory and I are working currently on some ideas to improve this. One idea is to listen before talk, so wait till no message is in the air before sending. 
The master branch contains a simple listen before talk implementation: https://github.com/pimatic/RFControl/commits/master

The development branch contains @Icesory's new verification algorithm: https://github.com/pimatic/RFControl/commits/development

If you want to test one of these, you have to replace the RFControl directory of homeduino, because homeduino points still to the well tested old version.

Another problem is the verification algorithm. Both of them need a at lease 1 footer + 2 full message, so at least 3 repeats of the message. I would love to reduce that to just 1 footer + 1 full message, skipping the verification message completely, but currently not much success with this.

**Comment by leader21** [comment]
thanks for your explanation!

> I think most of the time RF collisions are the problem

I'm having 7 weatherstation sensors around here at the house to get the temperatures in the rooms. They are indeed producing very much traffic for pimatic receiving their data. Maybe this could be the problem? Think I will switch to max! wall thermostats then to get rid of the weather sensors.

so, if pimatic is receiving, it's not able to send? 
maybe a "batch" will work or stop listening / shut off receiving when sending?! 

> The development branch contains @Icesory's new verification algorithm

Already have done this, I pulled the RFControl directly from Ronnys development branch. 
Receiving is much better now! But now I think those 7 weather sensors could be the problem with RF collision then. Shoot!!

**Comment by bkiss** [comment]
leader21 :  I want to change the configuration of my setup, i have 4 DHT22 wired directly to the PI, and i want to switch to RF.
My question is regarding the hardware i need for this. Another question is if it's not too much 4 sensors, and 3 switches, all communicating on RF. --(i see your setup)

I have never used the homeduino or rf plugins, but in my mind is the hardware:

BASE:
PI + 433 receiver/transmitter

Sensors:
DHT22+ ARDUINO NANO + RF transmitter

SWITCH

RELAY + ARDUINO NANO + RF transmitter/receiver

Please tell me if i'm wrong.

Thank you.

**Comment by sweebee** [comment]
Don't know if its related to this, but i have a wall switch.

If wallswitch is turned on then turn couch on and turn closet on etc.

But if i press the wallswitch once (short trigger) nothing happens. I have to press it for about 0,5/1 second before the rule starts.

**Comment by leader21** [comment]
@bkiss - i am working with wireless weatherstation devices at the moment.
have a look here : http://www.ebay.de/itm/Logilink-WS0002-Outdoor-Sensor-einheit-fur-Wireless-Wetterstation-WS0001-/131098170352. was the easiest and cheapest method to realise imo.
this is how my temperature page is looking like (at the bottom of this page there's the max! control for radiator control : http://www.youscreen.de/rjfbc94-pimatic.jpg

if you want to use pimatic with homeduino you will have to get an arduino nano with USB and a receiver/transmitter set. that's all for pimatic. if you want to have your own wireless sensor box you could have a look here #74. there are some people already developing this. 

@sweebee - maybe you could try to use icesory's RFControl from the development branch. as i said above, it improved the RF receiving for me! 

> The development branch contains @Icesory's new verification algorithm: https://github.com/pimatic/RFControl/commits/development

(usage - go to the homeduino directory, replace the RFControl directory at homeduino/libraries/ with the one from the development branch, go back to the homeduino directory and use <code>make upload</code> to update the arduino with the changed software.

**Comment by incmve** [comment]
I have the alecto weather station, it sends data almost every 30 seconds :-1: that sometimes causes misses for door/window contacts.
I made a RF sensor for humidity and temperature to replace the weather station, only thing I need to replace is the wind sensor.


@bkiss if your looking for a sensor code example
https://github.com/incmve/generic-rfbox/blob/development/rfbox-multiprobe.ino

**Comment by bkiss** [comment]
@leader21 You saved my life (my budget and time :) ) ! Specially with the Max! radiator thermostat, i like it, especially the price. My question is if i need the command center for this, or i can use the raspberry to communicate with the radiator thermostat...
-and please forgive me for hijacking this issue.

@incmve thank you, this was what i needed to start...

**Comment by sweebee** [comment]
Thanks @leader21 I will try that one.

**Comment by sweetpi** [comment]
> @leader21 You saved my life (my budget and time :) ) ! Specially with the Max! radiator thermostat, i like it, especially the price. My question is if i need the command center for this, or i can use the raspberry to communicate with the radiator thermostat...
> -and please forgive me for hijacking this issue.

You need the max cube connected to the router.

**Comment by leader21** [comment]
yes, the cube is needed since it's the gateway for the thermostats (they are running on 868 mhz).
using the cube also has the advantage that all processing and transmitting is done by itself.
you can have a look at http://www.elv.de/max-arr-bausatz-starterset-hausloesung-mit-cube-lan-gateway-2-heizkoerper-thermostaten-2-funk-fensterkontakten-wandthermostat-wt-und-eco-taster.html (if you're from Germany) there you can buy DIY sets that are much cheaper than ready made ones (for this  you will save 60 Euros!). usually there's just some connection wires to solder and assembling the parts together. the pcb's are already assembled and soldered. no big skills necessary. 

Back to topic
ok i will replace some of the weather sensors to get rid of the RF traffic.
i just was watching the homeduino log and figured out that there's a signal every 5 seconds, sometimes only 2 secs. apart. think that's definitely too much. 

![homeduino traffic](https://cloud.githubusercontent.com/assets/8620305/5860782/28912c6e-a264-11e4-9063-1e6613a46642.jpg)

**Comment by Icesory** [comment]
That is a lot of traffic. When i would build a sensor it transmit only 1 message per minute or per five minutes. every 10-30 seconds is rely much.

Its nice to hear that my modified version of RFControl works a little bit better. The low-pass filter i have implemented is borrowed from the New-Remote-Switch library.
https://github.com/hjgode/homewatch/blob/master/arduino/libraries/NewRemoteSwitch/NewRemoteReceiver.cpp#L89-L99

**Comment by stat2** [comment]
I have also testes the modified version of RFControl and it seems to work better indeed. It handles multiple requests (followed by rules) very well!
I did have to update the rfjontroljs in pimatic to get it to work, additionally to leader21's 'manual' above.

**Comment by sweebee** [comment]
RFControl is software for the arduino? I'm using a Attiny45 so don't know what i can do? The Attiny is flashed with the pilight firmware.

**Comment by leader21** [comment]
> RFControl is software for the arduino?

yes indeed! it's the software for the arduino nano to get pimatic-homeduino running.
homeduino is needed to have the RF sender and receiver connected to an arduino nano to have several advantages like lower cpu load, more connectivity since you're able to use the gpio from the nano too and more. it's not hard to set up and easy to install. even i as linux and pimatic noob was able to get it running ^^ i deinstalled pilight since i did not need it anymore.
check here to learn more : https://github.com/pimatic/pimatic-homeduino

**Comment by sweebee** [comment]
I'm not using plight, just the bandpass-filter firmware in the attiny45 (replacing a large arduino). So everything fits in to a raspberry case.

**Comment by leader21** [comment]
ah ok sorry, got that wrong!

**Comment by sweebee** [comment]
This is what it looks like (but i replaced the antenna's with simple 17,3cm wires, which work better).
![img_0661](https://cloud.githubusercontent.com/assets/10496485/5865973/c221f416-a28d-11e4-9ddd-a2137ca16991.JPG)
![img_0662](https://cloud.githubusercontent.com/assets/10496485/5865974/c369a71a-a28d-11e4-8c7d-b25a84afcd19.JPG)

**Comment by Icesory** [comment]
When you use Homeduino without a Arduino you have a virtual arduino running. I am not sure if it possible to flash the RFControl to it. But with your Attiny you have a very good setup.

**Comment by leader21** [comment]
issue has been solved. there was just too much traffic on 433.92 Mhz.
i reduced the weather sensors, now all works fine.
