### ISSUE TITLE
MPD Plugin does not start playing

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#492]
When nothing was played with mpd before I can't start playing.
Its because the player is not in the state "paused".
The command that the plugin sends tells mpd to unpause but it can't unpause when there was nothing paused.
I fixed it here https://github.com/pimatic/pimatic-mpd/pull/5

**Comment by sweetpi** [comment]
Thanks again, fix released with pimatic-mpd v0.8.6.
