### ISSUE TITLE
View stored values instead of graph

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#493]
Good moring guys!
What about an enhancement that shows the stored values of variables or devices not as graph but as table? Could be interesting when checking differences or peaks. 

I thought of something like that at the GUI: 
![graph-value](https://cloud.githubusercontent.com/assets/8620305/5851863/98da9cfa-a20d-11e4-9c91-3f901c522274.jpg)

When clicking on Value instead of Graph, you will get a table with the date and time and the stored value of the variable or device at that time. If possible, there should be an export option to a file somehow to use these values as log or in other programs like excel or whatever.

Maybe some variables/devices will have too much database entries or it doesn't make sense to show all data, then there could be a comprehension to a given period of time, lets say show all data / every 10 minutes / daily / monthly and show  highest / lowest (to get a monthly file maybe filter the highest / lowest value for every day at the month/year. this could be good when reading energy meters. so you are having the highest value for each day and have a monthly log etc. (should be optional to choose from different time periods).
And maybe a filter and sort option could be implemented too. Let's say filter the highest/lowest value or sort ascending/descending and so on.
(ok, I'm dreaming too much I guess. but maybe creating a table with value and date/time and export function would do for the beginning ;)

I just wonder if that would be possible, since the sqlite database is already present and could be used for this, doesn't it? 

What do you think of that?! Sounds like lots of work to me but was an interesting idea imho.

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.
