### ISSUE TITLE
How do I delete values from the database?

### ISSUE THREAD

**Issue by ituri** [pimatic/pimatic#494]
Hi,

I'm recording the air pressure with the following `ShellSensor`:
```
    {
      "id": "luftdruck",
      "name": "Luftdruck",
      "class": "ShellSensor",
      "attributeName": "air-pressure",
      "attributeType": "number",
      "attributeUnit": "hPa",
      "command": "cat /tmp/hpa.baro",
      "interval": 180000
    },
```
However, I had some errors in the script which is used to read the values from the sensor, so I now have some bogus numbers in my database. For instance, the sensor showed an air pressure of 1123.90 hPa at one time.
Now I want to delete this value from the database. I've tried searching the table `attributeValueNumber` for that string, but I didn't get any results. The other tables didn't have any results either. So my question is: How is this value stored? What do I need to look for in order to find and delete that value?

Thanks
ituri

**Comment by bkiss** [comment]
I have seen at my setup similar problems with DHT22, recording values of 3000% of humidity and doesn't looks good... 
I think the simplest way is to stop pimatic, transfer the database to PC, and edit the sqlite with some GUI sqlite client, and the transfer it back.
Another solution is to install sqlite3 on Pi (sudo apt-get install sqlite3), and do it with sql-commands, but in this case you will need to know exactly where is stored the bogus data....

**Comment by ituri** [comment]
@bkiss Well, I've already copied the database onto my Mac and looked at it with a GUI client, but I still can't find the value in the database. This is why I opened this issue and asked, whether pimatic stores its values in another format.

Regarding the bogus data, I've optimized my setup a bit: I now store and read the values from rrdtool. I then installed a cronjob which runs `http://oss.oetiker.ch/rrdtool/pub/contrib/removespikes.tar.gz` every five minutes and removes any bogus data. Maybe this might be a solution for your problem, too.

**Comment by leader21** [comment]
just a thought on this - i had an idea for a pimatic enhancement here #493 
if this idea could be realised to see values in a table instead of graph, maybe there could be a "delete value" option too.

**Comment by sweetpi** [comment]
There is no gui for this yet. But you can run the following SQL-Query:

```json
SELECT av.id, av.value, datetime(av.time)
FROM attributeValueNumber av 
JOIN deviceAttribute d 
WHERE av.deviceAttributeId == d.id 
AND deviceId  = "luftdruck"
AND attributeName ="air-pressure"
AND av.value > 1000
```

Check if the wrong values are shown and then delete with:

```json
DELETE FROM attributeValueNumber 
WHERE id IN
(
  SELECT av.id
  FROM attributeValueNumber av 
  JOIN deviceAttribute d 
  WHERE av.deviceAttributeId == d.id 
  AND d.deviceId  = "luftdruck"
  AND d.attributeName ="air-pressure"
  AND av.value > 1000
)
```

**Comment by ituri** [comment]
This has worked just fine, thanks!
