### ISSUE TITLE
recycle NinjaCrust with HomeDuino

### ISSUE THREAD

**Issue by sebastienvg** [pimatic/pimatic#496]
Few months ago I ordered couple NinjaCrust (I am sure some of you heard of these board that transform a RaspberryPI in a NinjaBlock), in fact in nothing more than an arduino with RF sender and receiver. The arduino connects via /dev/ttyAMA0 and I managed to flash the homeduino sketch, so far so good. Now I'd like to play around with RF and the problem I am running in is fact that whenever I set the pins in

``
{``
   ``   "plugin": "homeduino",``
``      "driver": "serialport",``
``      "driverOptions": {``
``        "serialDevice": "/dev/ttyAMA0",``
``        "baudrate": 115200``
``      },``
``      "receiverPin": 3,``
``      "transmitterPin": 5``
 ``   },``

I get an error that receiver should be either 0 or 1, but the modules on the board are connected to 3 and 5, anyway to work around this without loosing the ability to update pimatic-homeduino without breaking the config?

**Comment by punchlinegroup** [comment]
Can anyone explain why this limitation is in place, why aren't you able to just pick whatever pin you'd like to use for transceiver and receiver?

**Comment by Icesory** [comment]
Homeduino is written for arduino devices. The RFControl library uses an external interupt to measure the time between signals. On arduino only pin 0 and 1 have this functionality. To provide failures all other pins are blocked. I am not sure what happens when you attach a interrupt to non existing pin. I think it can create a massive bug while writing to the registers on the Atmega chip. 
You can search in the pimatic-Homeduino and overwrite this function.

**Comment by sweetpi** [comment]
Yes that's the reason. Ony INT0 and INT1 pins have real hardware interrupts. But there is other you could use with modifications of the homeduino/rdcontrol sketch. The best way would be to modify the homeduino sketch to use a fixed pin you like and ignore the pin used in pimatic-homeduino. So you could update pimatic-homeduino without worries.

**Comment by punchlinegroup** [comment]
Maybe I had too much Bavaria while reading the [schema](https://github.com/ninjablocks/hardware/tree/master/RPi%20Crust)  can anyone confirm 

``
"receiverPin": 3,
"transmitterPin": 5
``

**Comment by sweetpi** [comment]
Almost right. Its `D2` and `D5` in arduino notation, so 

``
"receiverPin": 0,
"transmitterPin": 4
``

in the homeduino config, which are the defaults :)

**Comment by sweetpi** [comment]
Did it work?

**Comment by sebastienvg** [comment]
with ```"receiverPin": 0, "transmitterPin": 4 ``` it didn't work for me, I'll have to read that schema and the xls file with headers description one more time I guess. Where I am confused is the pins # I am not sure if the pin# in the config file is the actual pin number on the board?

**Comment by sweetpi** [comment]
hm strange, If the schema is correct then there should be the following relation:

| ATMEGA238P Pin | ninja  schema    | arduino nano | homeduino pin         |
|--------------------------|------------------------|-------------------|----------------------------|
| PD2 (INT0)            | RFA                    | D2                 | receiverPin = 0         |
| PD4                       | RFB                    | D4                 | transmitterPin = 4     |


http://jkblog.azurewebsites.net/wp-content/uploads/2013/04/nano.png
