### ISSUE TITLE
[pimatic] SQL malformed probably SD card died due to much write

### ISSUE THREAD

**Issue by Icesory** [pimatic/pimatic#497]
Some days ago I got the sql malformed failure. I removed the database and restart pimatic. But a short time after this my pi crashed. It wasn't able to start again. I have repaired the SD card with fsck on an other computer. It shows a lot of failures. 
Today I got the same SQL failure. I stopped pimatic instantly and printed the performed writes with
```
awk '{print $7}' /sys/block/mmcblk0/stat
```
It's over 100.000.000 writes in 7days! That is to much for an SD card. 

Sorry for my bad english it is really late. 
![screenshot_2015-01-23-04-17-23](https://cloud.githubusercontent.com/assets/9157026/5869354/2309196a-a2b8-11e4-8d14-70bbb6371f29.png)

**Comment by leader21** [comment]
Well ... I'm shocked ^^ 
![writecycles](https://cloud.githubusercontent.com/assets/8620305/5870337/af6e812a-a2cb-11e4-82ec-767e9dc7df63.jpg)

almost 250.000.000 writes within 5 days uptime . I've hat this issue before, have a look here : #409 
It's possible to install raspbian on an usb harddisk. this should be a better solution. 
I did not try this for myself by now, but actually I'm seriously thinking of it ... 

btw : 

> Sorry for my bad english it is really late.

no need for apologizes! your english is very good, even that late (or early in the morning ;)
now go and grab some coffee ^^

**Comment by Yves911** [comment]
i have excellent result with a raspbian installation on a USB disk (it's more reliable and faster than the SD).
The time you will invest to move things to USB will be less than the one you will loose every time you have to reinstall after a SD corruption...

**Comment by Icesory** [comment]
The problem is, that all disks (USB-Stick, SSD, SD-Card) based on NAND Flash Chips. These Chips have a write cycle amount of 100.000 per cell. After this the cell can probably die. The controller of the medium has around 7% extra storage cells to replace the defect ones. Is this reserve completely over the storage produced failures. I think we should reduce massive the write access to prevent your systems from failures and hardware defects.
Sure a USB-Stick can probably better quality as an SD card but after some time it would die too.

**Comment by Yves911** [comment]
> I think we should reduce massive the write access to prevent your systems from failures and hardware defects.

User can do that already, look at the syssensor plugin, if you log 3 or 4 values (+timestamp) every 5s and do that for some extra devices it result in a big load.

**Comment by incmve** [comment]
I assume it's the database that is written a lot, how about an external DB like MySQL would that reduce the writes?

**Comment by sweetpi** [comment]
> I think we should reduce massive the write access to prevent your systems from failures and hardware defects.

I agree. Could someone investigate if there are some sqlite settings that could be tweaked?

**Comment by Yves911** [comment]
i think the first thing to do is to reduce the quantity of data to write into the DB. Currently in pimatic it is possible to retain data into the DB for 0d, doing that you will still write and erase data frequently and fragmentation will increase (and DB size as well). Some plugins syssensor actually but also logs (homeduino) create a lot of insert into the DB.

**Comment by Icesory** [comment]
A method is to set the database in a ram disk. On an raspberry we have about 256_512MB of ram. My biggest database was 10MB. Once per day this database is written to the file system. 

I am not a Linux pro but is the directory tempfs a ram disk? 
A other improvement is to set the swap size to zero. The swap is a ram extension on the filesystem. Programs they are loaded but sleep would be transferred in to the swap. The swap can also create a lot of writes.

**Comment by sweebee** [comment]
Wow, this has to be fixed quickly. Writing new data every several hours would be better.

My Pi: 12264048 writes in 1 day.

**Comment by sweetpi** [comment]
> i think the first thing to do is to reduce the quantity of data to write into the DB. Currently in pimatic it is possible to retain data into the DB for 0d, doing that you will still write and erase data frequently and fragmentation will increase (and DB size as well). Some plugins syssensor actually but also logs (homeduino) create a lot of insert into the DB.

Thanks for reminding me. I did forget this completely.

> I am not a Linux pro but is the directory tempfs a ram disk?

The filesystem tempfs is a ram filesystem, so indeed no disk writes.

> A other improvement is to set the swap size to zero.

I wouldn't change the swap to 0 that could be lead to serious problems if npm eats up you ram or so. Set `vm.swappiness = 0` so that the swap is only used if really needed. I think the default is already 1, what should be fine, too.

Maybe a option would be to use the in-memory mode of sqlite and sync it to disk periodically.

**Comment by sweetpi** [comment]
Just for the stats```
1 root@bananapi ~/pimatic-git # uptime                                                                              
 18:46:02 up 31 days,  5:42,  1 user,  load average: 0,23, 0,48, 0,40
root@bananapi ~/pimatic-git # awk '{print $7}' /sys/block/mmcblk0/stat
941872440
```

**Comment by Yves911** [comment]
Just for a smile 
uptime
 18:48:24 up  2:42,  2 users,  load average: 0,11, 0,22, 0,39
awk '{print $7}' /sys/block/mmcblk0/stat
9 
=> i am using a hard drive attach to the pi and not the sdcard :-)

**Comment by Yves911** [comment]
Today my DB was 70 MB huge, after dump all the data to sql and recreate the DB from that file (https://github.com/pimatic/pimatic/issues/419#issuecomment-68593119) : 40 MB only ==> that prove fragmentation

**Comment by sweetpi** [comment]
Does someone want to create a topic with some database tips in the forum?

**Comment by Yves911** [comment]
I can start with, could we create a category for all DB stuff?

**Comment by sweetpi** [comment]
That would be great. I would collect it in one topic "Database tips" or so in the general discussions section. I will split it if it should get to much.

**Comment by Icesory** [comment]
@Yves911 can you pls post your writes per one week.

**Comment by incmve** [comment]
My SD broke today, not because of the writing but because it cracked :(
I installed a new one and moved everything to USB stick.
```
pi@raspberrypi:~/pimatic-app$ awk '{print $7}' /sys/block/mmcblk0/stat
1
pi@raspberrypi:~/pimatic-app$ uptime
 18:15:58 up  2:41,  1 user,  load average: 0.25, 0.27, 0.32
```
and the USB
```
pi@raspberrypi:~/pimatic-app$ awk '{print $7}' /sys/block/sda/stat
2279744
```

**Comment by Yves911** [comment]
@Icesory 
> can you pls post your writes per one week. 

make not so much sense : i am doing a lot of things outside of pimatic on my rasp...

**Comment by Yves911** [comment]
@incmve i have notice big improvement (not only for pimatic) when i switched from SD to USB, what about you?

**Comment by incmve** [comment]
it looks a little faster but I'm not really sure, haven't tested much really.

**Comment by incmve** [comment]
You could also write to RAM instead of SD
http://www.zdnet.com/article/raspberry-pi-extending-the-life-of-the-sd-card/
On my other Pi I am using the RAM as temp space, after reboot it's gone.

**Comment by sweebee** [comment]
@sweetpi Only log values if expire time is not set to 0, option for logging in…

What does this do? Does this fix the write problem? do i have to change anything in my config looking at the config-schema.coffee

**Comment by sweetpi** [comment]
DON'T PANIC in large, friendly letters... I think that I've found a way to massively decrease database writes. But it needs some testing. You can checkout the development branch and what for changes to the database file:

```
inotifywait -m pimatic-app 
```

or where ever your database file is. I've also introduced options to log values only in certain intervals independent of their update interval for gui or rules. I will write some infos if its tested and finished.

**Comment by Icesory** [comment]
@sweetpi a other way is to implement a interval to crate automatically a backup of the database. 
So we can set the normal database in a tempfs directory and pimatic safes the database by it self. 

```json
"connection":
{
  "filepath": "/path/to/ramdisk/database"
}, 
"backup":
{
 "filapath": "/path/to/normal/space/databse",
 "interval": "24h" 
} 
```
Pimatic should copy the backup to the normal file isn't exist. Safe the normal file to the backup after the interval. 


At the moment I don't have a SD card ( my old is definitely dead) to test your new improvements.

**Comment by sweetpi** [comment]
> @sweetpi a other way is to implement a interval to crate automatically a backup of the database. 
> So we can set the normal database in a tempfs directory and pimatic safes the database by it self.

The current approach is almost like that, but better. You can set sqlites journal mode to memory, then all inserts inside a transaction are not written to the disk until the transaction is commited. So I use now one transaction for all logging action that gets only commited when pimatic is stoped / restarted or after a certain time interval (checkpoint). This has the advantage that you don't have to hold the whole database in memory, only the changes and only the changes are written to disk on a checkpoint.

The disadvantage is, that your database can easily get corrupted if the commiting action is interrupted. So we still need a additional backup mechanism.

**Comment by sweetpi** [comment]
After some testing, it seems that my approach does not work. The database saving to disk does take to long and the risk is to high, that it get corrupted. Next try would be to use temporary tables for caching.

**Comment by DDNRN** [comment]
My sdcard died last night while testing. 
Took me 4 h to setup all again, my update/ upgrade needs always about 1 h and then again about 2h for pimatic npm ...

**Comment by Yves911** [comment]
Guys move to a USB disk instead of a SD

**Comment by DDNRN** [comment]
Can someone give short instructions how to manage with usb? I'm not that linux guy.

**Comment by sebastienvg** [comment]
I still believe the easiest way to get raspbian on a stick is to use [BerryBoot]( https://github.com/maxnet/berryboot) . It allows you to select different medium for install, there's usb-stick but also iscsi (if you happen to have a NAS that's a great option).

**Comment by Icesory** [comment]
>Guys move to a USB disk instead of a SD

A USB Stick use the same technology as a SD-Card! That don´t change the problem.
I see 2 options for this.
Ramdisk or improvements in Pimatic.
And i have seen Sweetpi make a lot of work to reduce the writes

**Comment by Yves911** [comment]
USB disk = hardrive
pls see here http://www.raspipress.com/2013/05/install-and-run-raspbian-from-a-usb-flash-drive/

**Comment by Icesory** [comment]
Yves you are wrong.
USB = NAND Flash
SD = NAND Flash
Same technology. A Usb stick will die too. Eventual is the bad sector management better in a USB stick and it will run longer but it will die.

**Comment by Yves911** [comment]
Ok how can i explain: take an old traditional hardrive from an old laptop put it in a case that you can connect to the rasp using USB : you will get a USB disk/hardrive

**Comment by Icesory** [comment]
Sorry dont read the "disk".
A normal harddisk can handle many more writes. But it should fixed in the core of the problem

**Comment by Yves911** [comment]
No problem, i am just sharing my xp, i moved to USB disk since 1,5 year and it's working super fine and much faster than with a SD. No corruption at all, the "core problem" can be also a apt-get with large data that can corrupt your SD as well. So hardrive fix the core of the problem (ie rasp can corrupt the SD on heavy load)

**Comment by sebastienvg** [comment]
I personally choose the iscsi target since I have FREENAS running with RAID Z 2 setup. I do regular snapshot of the pi(s) filesystem. I have to admit iscsi is a bit slow (8mb/s in write) on a pi however it is totally acceptable for a pimatic production instance in my opinion.

**Comment by sweebee** [comment]
An USB stick is not the solution. Only a temporary solution till sweetpi finds a way to reduce the writes.

**Comment by DDNRN** [comment]
I don't know how you did it, but is it a bigger problem to catch all the data (events, logging etc.) in memory for let me say 5 min. and save it then in one task? Wouldn't be more then some hundred operations a day. 

Is there a workaround i can use already to reduce data amount to be logged in pimatic?

**Comment by sweebee** [comment]
I reduced it by removing the systemstats and increasing the weather timeout

**Comment by sweetpi** [comment]
> I don't know how you did it, but is it a bigger problem to catch all the data (events, logging etc.) in pimatic memory for let me say 5 min. and save it then in one task? Wouldn't be more then some hundred operations a day.

That's what I'm currently doing in the development version. It turns out that the you can configure the sqlite database to keep all changes inside a transaction in memory and you can flush them to disk by committing in WAL journal mode. I don't know if it really does save much writes, but theoretically it should.

> Is there a workaround i can use already to reduce data amount to be logged in pimatic?

Best is to move the database to a external drive (flash memory or harddisk) or if you can live without logging, you can use the in memory database mode of sqlite (Set filename to `":memory:").

Btw.: I've debug logging and much more enabled and had never problems with my sdcard. I can recommend to always choose a class 10 card or better, if you rebuy one. Maybe I had just luck. Anyway I do my best to reduce writes and will write together some database tips and warnings.

**Comment by sweebee** [comment]
Where can i set the database location? And is it possible to choose the data that is logged? Like i want to log my temperature, but i'm not interested in the dimmer values or humidity.

**Comment by sweebee** [comment]
Tested the latest development version from sweetpi and it looks like he got something.

re-added the weather and I've got 95.000 writes in 10 hours. So much better. pimatic writes the data every 4 hours to the disk. Don't know if everything else is working but its going in the right direction :+1:

**Comment by Icesory** [comment]
Nice to hear.

**Comment by DDNRN** [comment]
Would be good to release the changes asap.

**Comment by sweetpi** [comment]
@DDNRN You can always checkout the development version. I will release it as soon as I know it does no other bad things ;)

**Comment by DDNRN** [comment]
OK let me try ..
But!
How can i install on my pi? 
I'm not a Java programmer and don't know about npm and it's way of installing.

You could do me a big vavour with writing some small sentence on the pimatic.org website to so.
Others maybe also looking for it ;-)

**Comment by sweetpi** [comment]
Java != JavaScript...

You should only try it if you know what you doing and there is a "Help"-Link on the website which points to a list with FAQ in which this is: https://github.com/pimatic/pimatic/issues/112

Please first use the search before asking, thank you :)

Another thing: Don't report bugs in the dev version. They much likely known :)

**Comment by DDNRN** [comment]
Upss. Sorry :-(

**Comment by sweetpi** [comment]
The new version is released. See http://forum.pimatic.org/topic/44/database-configuration-howto for configurations.
