### ISSUE TITLE
How to automatically restart service

### ISSUE THREAD

**Issue by cklam2** [pimatic/pimatic#499]
Right now i start the pimatic service with init.d script. 

Every now and then the process seems to crash but the service doesn't start again automatically.
Yes, the pimatic shouldn't crash but I'm still investigating why (different issue). 

In the meantime I'd like to know if there is a way to automatically start the service again when it crashed.

**Comment by incmve** [comment]
you could use a script like this
http://www.anyexample.com/linux_bsd/bash/check_if_program_is_running_with_bash_shell_script.xml
and put it in the cron to run every x minutes

**Comment by bkiss** [comment]
I use this:

pi@raspberrypi ~ $ cat test.sh 
#!/bin/bash
exec 6<>/dev/tcp/127.0.0.1/8080 || sudo reboot
exec 6>&- # close output connection
exec 6<&- # close input connection

You can change the reboot, to something else. This checks port 8080 if it's open, if not reboots the PI.
And cron every 5 minutes...

**Comment by incmve** [comment]
When pimatic crashes en my heating is on it stays on so I am running this script every 5 minutes to check if pimatic is running and if not put the GPIO High so the heating relay turns off and pimatic is restarted.

```
#!/bin/sh
SERVICE='pimatic'
 
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
    echo "$SERVICE service running, everything is fine"
else
    echo "$SERVICE is not running"	| gpio mode 5 out && gpio write 5 1
    echo "$SERVICE is not running!" | echo "Failed"
	echo "$SERVICE is not running!" | sudo service pimatic restart
fi
```

**Comment by cklam2** [comment]
Thanks guys, now using incmve's sample. 

I had trouble using it, it always said, 'everything is fine', even after stopping the service. Then I discovered that the script's name shouldn't start with pimatic...

Waiting for the pimatic to crash, then will know if cron job applied correctly.

**Comment by incmve** [comment]
lol I named my script failsafe.sh ^^

you can test it bij just stopping the pimatic service.
<code>sudo service pimatic stop</code>
The script should start it if not set permissions on the sh file <code>chmod +x failsafe.sh<code>

**Comment by cklam2** [comment]
Yup, seems to work. Very happy :)

I called my script "pimatic-wd.sh" and put it in the "pimatic-app" directory, so wrong... So for people who also want to use the script, make sure that the entire file path does NOT contain the word pimatic.

**Comment by cklam2** [comment]
The script already restored the service twice, so nice...

In the web page i wanted to see the pimatic uptime so I can see how long it has been running. Discovered the pimatic shell-execute plugin, added the following to the config file.
```
  {
      "id": "pimatic-uptime",
      "name": "Pimatic uptime",  
      "class": "ShellSensor",
      "attributeName": "Uptime",
      "attributeType": "number", 
      "attributeUnit": "hrs",
            "command": "ps -eo etimes,cmd|grep -v grep|grep -i pimatic|awk '{print $1/3600}' OFMT='%3.1f'",
      "interval": 3600000
    }
```

This script executes the shell command every hour and the value is displayed on the page. You can decrease the poll interval but i am happy with a rough figure (and will avoid too many writes into the database). It also shows a graph which, hopefully, is a linear line instead of a sawtooth :)

Would even be nicer if @sweetpi could integrate the uptime in pimatic sysinfo plugin.
