### ISSUE TITLE
howto pimatic-log-reader 

### ISSUE THREAD

**Issue by BenI2C** [pimatic/pimatic#501]
Hi , 
I try the example "Gather temperature values from a log file:"
i made a file in   /var/log named "temperature"
In that file i've added a txt line "temperature: 21.1" 
My configfile with the pimati-log setup:

    {
      "id": "temperature-from-logfile",
      "name": "Temperature1",
      "class": "LogWatcher",
      "file": "/var/log/temperature",
      "attributes": [
        {
          "name": "temperature1",
          "type": "number",
          "unit": "  °C"
        }
      ],
      "lines": [
        {
          "match": "temperature: (.+)",
          "temperature": "$1"
        }
      ]
    },

When i start pimatic i see : 
"Temperature1                  0 C."
Always display 0 C 
I thought  i will see 21.1,  the value from the line in the file.
Can  somebody help me ?

**Comment by leader21** [comment]
wait until the log has been updated.
then it usually should begin to work properly.
or try another match like 
"\\s*temperature\\s*:\\s*([0-9]+\\:[0-9]+)

**Comment by ituri** [comment]
As noted in https://github.com/pimatic/pimatic/issues/481 I'd advise you to use [pimatic-shell-execute](https://github.com/pimatic/pimatic-shell-execute) instead. I have the same setup as you and here's how I display the temperature using the aforementioned plugin (add this to the device section):
```
    {
      "id": "temp-innen-wohnzimmer",
      "name": "Temperatur Wohnzimmer",
      "class": "ShellSensor",
      "attributeName": "temperature",
      "attributeType": "number",
      "attributeUnit": "°C",
      "command": "cat /var/tmp/wohnzimmer.temp",
      "interval": 180000
    },
```

**Comment by leader21** [comment]
but this will work only if you're having numbers and no text in your logfile, doesn't it?
it does not parse the file for any match. so Beni2C needs to change his logfile output then.

**Comment by ituri** [comment]
@leader21: Oh, right. Sorry, I got that wrong. 
But since there are still other issues with pimatic-logreader (such as the problem described in the linked issue), I would advise to rather change the logfile format than to solve this problem with pimatic-logreader.

**Comment by BenI2C** [comment]
So, the pimatic-log example will not work as shown? Hmm.
The logfile who i wil use has 3 lines with numbers and will updated every 10 minutes.
Is that possible with pimatic-shell-execute ?

**Comment by ituri** [comment]
Should be possible, yes.You could to use sed in order to get your data into a format that can be understood by pimatic-shell-excute. Perhaps try the following command (not tested) in order to get most recent value (that is: as long as your most recent value is stored in the first line of your file):
`cat /var/log/temperature | head -n 1 | sed 's/temperature:\ //'`

**Comment by BenI2C** [comment]
I will try. 
Thanks

**Comment by BenI2C** [comment]
Ok, now i got the first value  with the script earlyer from ituri.
 But when i change the log file for a new value, i am lost the connection. 
So i have to "pimatic.js start" again.

**Comment by sweetpi** [comment]
Any errors in the pimatic-daemon.log file?

**Comment by BenI2C** [comment]
11:07:06.360 [pimatic-homeduino] debug: data: "PING"
11:07:26.364 [pimatic-homeduino] debug: data: "PING"
11:07:46.375 [pimatic-homeduino] debug: data: "PING"
11:08:06.369 [pimatic-homeduino] debug: data: "PING"
11:08:26.376 [pimatic-homeduino] debug: data: "PING"
11:08:46.376 [pimatic-homeduino] debug: data: "PING"
11:09:06.381 [pimatic-homeduino] debug: data: "PING"
11:09:26.384 [pimatic-homeduino] debug: data: "PING"
Error: ENOENT, no such file or directory '/var/log/temperature.log'

**Comment by BenI2C** [comment]
Maybe i have found this issue. 
I did edit with "KATE" editor. 
Now i edit with "NANO" then no problem !

**Comment by BenI2C** [comment]
It's Ok now.
I have made several shell scrips started by the pimatic shell-execute script.

{
      "id": "cv-aanvoertemp",
      "name": "CV-aanvoer",
      "class": "ShellSensor",
      "attributeName": "temperature",
      "attributeType": "number",
      "attributeUnit": "°C",
      "command": "/home/pi/cvaanvoertemperatuurLM75.sh",
      "interval": 5000
    },
     {
      "id": "cv-retourtemp",
      "name": "CV-retour",
      "class": "ShellSensor",
      "attributeName": "temperature",
      "attributeType": "number",
      "attributeUnit": "°C",
      "command": "/home/pi/cvretourtemperatuurLM75.sh",
      "interval": 5000
    },
    {
      "id": "warmwater",
      "name": "Warmwater",
      "class": "ShellSensor",
      "attributeName": "temperature",
      "attributeType": "number",
      "attributeUnit": "°C",
      "command": "/home/pi/warmwatertemperatuurLM75.sh",
      "interval": 5000
    },
