### ISSUE TITLE
pimatic-rules: Add timer

### ISSUE THREAD

**Issue by ituri** [pimatic/pimatic#502]
I was wondering if there is a way to add a timer in the rules-model. Here's the use case: I have my coffee machine attached to a wireless socket. However, I would like to create a rule, which turns the socket off after a certain period of time has passed. It should look like that:
```
if 
   CoffeeMachine was on >10min
then
   turn CoffeeMachine off
```

**Comment by incmve** [comment]
You could use:
```
IF Coffeemachine is turned on
THEN turn Coffeemachine off after 10 minutes
```

**Comment by ituri** [comment]
I knew there would be some way to do this with the existing set of rules. ;-) 
Thanks, works fine!

**Comment by ituri** [comment]
Turns out I was too quick ...

The problem is that my Coffeemachine is connected to an Intertechno socket. For Intertechno sockets, there is no such state as `is turned on`. So how do I test the state of those sockets? 
`if Coffeemachine is up [...]` doesn't seem to work.

**Comment by kenci** [comment]
`IF ...
THEN turn Coffemachine on for 10 minutes`

**Comment by ituri** [comment]
@kenci: But this doesn't test whether Coffeemachine is up, does it?

**Comment by kenci** [comment]
No, you have to switch it on. Do you want to switch it with a remote or Pimatic?

**Comment by ituri** [comment]
I want to switch the Coffeemachine on with Pimatic. And afterwards I want Pimatic to turn it off automatically. 
The action-part of this rule (move CoffeMachine down after 10 minutes) seems to work, but there doesn't appear to be a condition which tests whether moved up or down.

Again, the problem is that I'm using Intertechno sockets. They don't support `is ON/OFF` but only `UP/DOWN`.

**Comment by Icesory** [comment]
can you show your config for this device.
I think you used a shutter device instead of a switch device.

**Comment by kenci** [comment]
What are the device attributes in the "variables" section?

**Comment by leader21** [comment]
try to use this pimatic device (but set your own unit and id ;) : 
```
    {
      "id": "coffeemachine",
      "name": "Coffeemachine",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch4",
          "options": {
            "unit": 30,
            "id": 24
          }
        }
      ]
    },
```

**Comment by ituri** [comment]
Ah, now I've got it! 

I accidentally configured the device as a screen, not as a switch. Now I've changed its device type and everything is working as expected. Sorry for the trouble!
