### ISSUE TITLE
Integrated watchdog

### ISSUE THREAD

**Issue by Gargoyle112** [pimatic/pimatic#503]
At first some background infos:

I want to control my Terrarium with my Pi and Pimatic.
The Raspberry Pi is connected to two [DHT22](http://www.amazon.co.uk/SODIAL-Digital-Temperature-Humidity-3-5V-6V/dp/B00KBPS6R8/ref=sr_1_1?s=diy&ie=UTF8&qid=1422220753&sr=1-1&keywords=dht22), a LED with a blink script, a reset switch and a [USB Power Strip](http://www.amazon.co.uk/Gembird-EG-PMS2/dp/B00BAQZJ4K/ref=sr_1_1?ie=UTF8&qid=1422220545&sr=8-1&keywords=eg-pms2). With the Power Strip I am operating two [Halogen Spots](http://www.amazon.co.uk/Philips-Halogen-Light-Bulb-GU10/dp/B001BZ029M/ref=sr_1_2?ie=UTF8&qid=1422220972&sr=8-2&keywords=halogen+spot), an [electronic ballast](http://www.amazon.de/gp/product/B00CDJDD5U?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00) with daylight lamp and a [fogger](http://www.amazon.co.uk/Trixie-Fogger-Ultrasonic-Generator-Maker/dp/B004V2P3DW/ref=sr_1_1?ie=UTF8&qid=1422221365&sr=8-1&keywords=Trixie+76123). The Power Strip is connected to the Pi over an active [USB Hub](http://www.amazon.co.uk/D-Link-DUB-H7-Port-USB-External/dp/B0002AFZVM/ref=sr_1_1?ie=UTF8&qid=1422221536&sr=8-1&keywords=DUB-H7) which also powers the Pi.

So much for the background, now for my problem:

The Pi keeps freezing every couple of hours and I have to reset it. I cannot connect to the Pi over SSH / PuTTY but the blinking script for the LED keeps running. 

Is there a way to point the internal [watchdog](http://linux.die.net/man/8/watchdog) of the [Raspberry Pi](http://pi.gadgetoid.com/article/who-watches-the-watcher) towards the Pimatic process or the active database so it resets the Pi after a freeze? Or - much better - stop the Pi from freezing?

**Comment by sweetpi** [comment]
Wouldn't it be better to find the reason? If you say, that just your network / ssh connection dies, did you check the syslog?

**Comment by Gargoyle112** [comment]
It's not only the SSH connection that dies. The system also does not turn on the lights or the fogger when its supposed to (not only time, but also temperature rules.
Which logfile should I check / post?

**Comment by sweetpi** [comment]
The last entries in `/var/log/syslog` at the time of the last crash.

**Comment by Gargoyle112** [comment]
Cleared the syslog and will post it after the next crash

**Comment by Gargoyle112** [comment]
Here are the last lines:

```
Jan 25 23:57:53 raspberrypi kernel: [    4.290883] usb 1-1.5.1.2: Product: Gembird Silver Shield PM
Jan 25 23:57:53 raspberrypi kernel: [    4.299306] usb 1-1.5.1.2: Manufacturer: Gembird Electronics
Jan 25 23:57:53 raspberrypi kernel: [    4.313465] usbhid 1-1.5.1.2:1.0: couldn't find an input interrupt endpoint
Jan 25 23:57:53 raspberrypi kernel: [   10.740494] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
Jan 25 23:57:53 raspberrypi kernel: [   11.270746] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
Jan 25 23:57:53 raspberrypi kernel: [   12.065471] bcm2708 watchdog, heartbeat=10 sec (nowayout=0)
Jan 25 23:57:53 raspberrypi kernel: [   22.664710] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
Jan 25 23:57:54 raspberrypi kernel: [   24.268730] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1947]: (CRON) INFO (pidfile fd = 3)
Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1948]: (CRON) STARTUP (fork ok)
Jan 25 23:57:54 raspberrypi cron[1948]: Error: bad username; while reading /etc/crontab
Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1948]: (*system*) ERROR (Syntax error, this crontab file will be ignored)
Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1948]: (CRON) INFO (Running @reboot jobs)
Jan 25 23:57:55 raspberrypi ifplugd(eth0)[1793]: Link beat detected.
Jan 25 23:57:55 raspberrypi ifplugd(eth0)[1793]: Executing '/etc/ifplugd/ifplugd.action eth0 up'.
Jan 25 23:57:55 raspberrypi ifplugd(eth0)[1793]: Program executed successfully.
Jan 25 23:57:56 raspberrypi kernel: [   25.779929] Adding 102396k swap on /var/swap.  Priority:-1 extents:2 across:2134012k SSFS
Jan 25 23:57:56 raspberrypi ntpd[2061]: ntpd 4.2.6p5@1.2349-o Sat Dec 20 21:33:54 UTC 2014 (1)
Jan 25 23:57:56 raspberrypi ntpd[2063]: proto: precision = 1.000 usec
Jan 25 23:57:56 raspberrypi ntpd[2063]: Listen and drop on 0 v4wildcard 0.0.0.0 UDP 123
Jan 25 23:57:56 raspberrypi ntpd[2063]: Listen normally on 1 eth0 192.168.2.112 UDP 123
Jan 25 23:57:56 raspberrypi ntpd[2063]: peers refreshed
Jan 25 23:57:56 raspberrypi ntpd[2063]: Listening on routing socket on fd #18 for interface updates
Jan 25 23:57:56 raspberrypi ntpd[2063]: restrict: error in address '::' on line 38. Ignoring...
Jan 25 23:57:56 raspberrypi ntpd[2063]: restrict: error in address '::1' on line 42. Ignoring...
Jan 26 07:14:21 raspberrypi kernel: [   71.102390] [sched_delayed] sched: RT throttling activated
```

This time, the Pi didn't freeze, only the pimatic service died. I Cannot tell you when or why. Do you need any more infos?

**Comment by bkiss** [comment]
I was playing with similar problems and i used the internal watchdog but with no success. 
I have tried the ping test, interface test, file changing test, and almost every time i was in reboot loop.

The file test was to watch the database file, and if doesn't change for 10 minutes then reset. Ok, but at the first reboot the watchdog service started earlier then the pimatic service and the database file mtime was not changes, so again endless loop. 

Anyway i am interested in some solution regarding the hardware watchdog...

My problem was solved by changing the usb-wifi interface, it was a TPLINK with external antenna(some atheros chip), and now is Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter.
The symptoms was very similar to yours...

**Comment by sweetpi** [comment]
> Jan 25 23:57:53 raspberrypi kernel: [   10.740494] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)

Check you filesystem. If you have a different sd card, test it.

> Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1947]: (CRON) INFO (pidfile fd = 3)
> Jan 25 23:57:54 raspberrypi /usr/sbin/cron[1948]: (CRON) STARTUP (fork ok)
> Jan 25 23:57:54 raspberrypi cron[1948]: Error: bad username; while reading /etc/crontab

I don't think this has something to do with the problem. But you should fix your crontab.

**Comment by bkiss** [comment]
Another annoying thing with hardware watchdog is, when i wanted to restart the pimatic service i get reset. So for now i don't use the watchdog at all. 
My system is up all the time, but with the code submitted before, with the port watching, i get reboot once per day.

**Comment by Gargoyle112** [comment]
@bkiss The hardware watchdog is only capable of resetting the Pi. you have to use a software watchdog for your problem.

**Comment by Gargoyle112** [comment]
@sweetpi crontab is fixed and I think it WAS a defective SD card. At the moment, everything works like a charm.

Thanks for all the help for an intermediate linux beginner!!!
