### ISSUE TITLE
[pimatic-weather] error: ETIMEDOUT

### ISSUE THREAD

**Issue by berry02** [pimatic/pimatic#504]
Hi, I am using pimatic for a while now and after the last pimatic weather update I receive the following error messages in my pimatic-daemon.log:

21:09:04.853 [pimatic-weather] error: ETIMEDOUT
21:09:05.008 [pimatic-weather] error: err is not defined
21:09:05.084 [pimatic] error: Could not get attribute value of Apeldoorn.status: ETIMEDOUT
21:09:05.155 [pimatic] error: Could not get attribute value of Apeldoorn.windspeed: ETIMEDOUT
21:09:05.222 [pimatic] error: Could not get attribute value of Apeldoorn.temperature: ETIMEDOUT
21:09:05.292 [pimatic] error: Could not get attribute value of Apeldoorn.humidity: ETIMEDOUT
21:09:05.367 [pimatic] warn: Could not update variable weather.status: ETIMEDOUT
21:09:05.440 [pimatic] warn: Could not update variable weather.windspeed: ETIMEDOUT
21:09:05.582 [pimatic] warn: Could not update variable weather.temperature: ETIMEDOUT
21:09:05.684 [pimatic] warn: Could not update variable weather.humidity: ETIMEDOUT

My config looks like this:

  "devices": [
    {
      "id": "weather",
      "class": "WeatherDevice",
      "name": "Apeldoorn",
      "location": "Apeldoorn, Netherlands",
      "degreeType": "C",
      "timeout": 300000
    },
    {
      "id": "forecast",
      "class": "WeatherForecastDevice",
      "name": "Apeldoorn 1 dag",
      "location": "Apeldoorn, Netherlands",
      "degreeType": "C",
      "timeout": 300000,
      "day": 1
    },

Although the devices are working fine. They are displaying the weather and the forecast. Does anyone got an idea what these entries mean?

**Comment by sweetpi** [comment]
This error means that the weather request to msn timedout. If this happens just ones a while it does not matter much. Just ignore it. Was it just one time?

**Comment by sweebee** [comment]
This is normal i guess, it only happens when pimatic is started.

**Comment by berry02** [comment]
Oke, thanks for the answer. Now my database is corrupt, for the second time in one hour... I am going to format my sdcard and start over.

**Comment by sweebee** [comment]
What kind of sd card do you have?

**Comment by berry02** [comment]
It is a Transcend SDHC 16GB class 10.

It comes from: https://www.sossolutions.nl/opslag/9324449-raspberry-pi-behuizing-doorzichtig.html

**Comment by sweebee** [comment]
I have the same, no problems so far. Maybe your just unlucky,reinstall and check for several days.

**Comment by berry02** [comment]
Yes, I guess so... Never had problems with this card. Let's see what a new start brings...
