### ISSUE TITLE
2 pi's in the same network with pimatic and pilight

### ISSUE THREAD

**Issue by bommey** [pimatic/pimatic#506]
Hey there, 

i hope someone could help me.
i have 2 pi's in the same network with pimatic and pilight 
when i start both pi's one of them connects to the pilight server of the other pi,

when i disable ssdp, enable local host, and fixed port,@ one of the pi it connects to its own pilight server, but only for 10 seconds. 
aber 10 seconds the connections broke up.

i tried watchlist @ pilight config, but there was no effect, when only local host was allowed to connect.

10:31:32.201 [pimatic] new device "GPIO1"...
10:31:32.310 [pimatic] new device "GPIO2"...
10:31:32.431 [pimatic] new device "S1"...
10:31:32.553 [pimatic] new device "S2"...
10:31:32.742 [pimatic] new device "Start1"...
10:31:32.850 [pimatic] new device "Start2"...
10:31:33.046 [pimatic-pilight] connected to pilight-daemon
10:31:33.725 [pimatic-mobile-frontend] packing static assets
10:31:36.097 [pimatic-mobile-frontend] packing static assets finished
10:31:36.154 [pimatic-mobile-frontend] rendering html
10:31:56.669 [pimatic-mobile-frontend] rendering html finished
10:31:56.834 [pimatic] listening for http-request on port 80...
10:32:02.893 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:32:13.942 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:32:24.984 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:32:36.023 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:32:47.066 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:32:58.116 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.
10:33:09.157 [pimatic-pilight] heartbeat to pilight-daemon timedout after 6000ms.

**Comment by incmve** [comment]
See #505
