### ISSUE TITLE
Banana Pi / Raspbian / pimatic-homeduino

### ISSUE THREAD

**Issue by MikeOne86** [pimatic/pimatic#507]
hey, i can not switch my device and not read my dht22 sensor with pimatic-homeduino:

error [pimatic-homeduino]: Error reading DHT Sensor: unknown_command.
error [pimatic]: Could not get attribute value of DHT-22-1.humidity: unknown_command
error [pimatic]: Could not get attribute value of DHT-22-1.temperature: unknown_command
config.json

All pin number is in wiringpi number

"plugins": [
{
      "plugin": "homeduino",
      "driver": "gpio",
      "driverOptions": {},
      "receiverPin": 1,
      "transmitterPin": 0
    }
],
  "devices": [
{
      "id": "temperature1",
      "name": "DHT-22-1",
      "class": "HomeduinoDHTSensor",
      "type": 22,
      "pin": 7
    },
    {
      "id": "rfswitch",
      "name": "TV Steckerleiste",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch2",
          "options": {
            "houseCode": 5,
            "unitCode": 1
          }
        }
      ]
    }
  ],

**Comment by incmve** [comment]
Check the transmitter receiver pin to be sure they are connected with the correct pin, I have made that mistake myself.

How did you connect the DHT11, directly to the pi or to a arduino?
if your DHT is connected directly to the pi use this plugin and not homeduino
http://pimatic.org/plugins/pimatic-dhtxx/
```
{
  "id": "my-sensor",
  "name": "dhtxx example",
  "class": "DHTxxSensor",
  "type": 22,
  "gpio": 7,
  "interval": 60000
}
```

**Comment by MikeOne86** [comment]
DHT is connected directly to the pi

error [pimatic]: Error running "npm install pimatic-dhtxx"

the transmitter and receiver pin is connected with the correct pin
because pilight works :/

**Comment by incmve** [comment]
I have no problem installing it
``` 
pi@raspdev ~/pimatic-app $ sudo npm install pimatic-dhtxx
npm http GET https://registry.npmjs.org/pimatic-dhtxx
npm http 200 https://registry.npmjs.org/pimatic-dhtxx
npm http GET https://registry.npmjs.org/pimatic-dhtxx/-/pimatic-dhtxx-0.8.4.tgz
npm http 200 https://registry.npmjs.org/pimatic-dhtxx/-/pimatic-dhtxx-0.8.4.tgz
``` 
maybe npm had problems

**Comment by incmve** [comment]
wait I to am having problems installing the plugin,
```c
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! node-dht-sensor@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-dht-sensor@0.0.5 install script.
npm ERR! This is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-dhtxx"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
```

**Comment by MikeOne86** [comment]
yes I have the same problem

**Comment by Icesory** [comment]
I'm not sure if this is your problem. 
https://github.com/pimatic/pimatic/issues/477

**Comment by MikeOne86** [comment]
Yes install the lib first: http://www.airspayce.com/mikem/bcm2835/
and then installing the plugin pimatic-dhtxx!

**Comment by MikeOne86** [comment]
Okay i can switch my Device :+1: 

in pilight:
"systemcode": 5,
"unitcode": 1

and in pimatic
"houseCode": 10100,
"unitCode": 10000

Thanks incmve and Icesory
