### ISSUE TITLE
Feature request: Iframe page

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#508]
You can create pages in Pimatic to organize stuff, I'd like a specific type of page that open an url in an iframe. This would come in handy for some custom home built stuff (graphs app, maybe even open gmail in it with a tablet on the wall, etc).

**Comment by leader21** [comment]
hello neographikal!
at the new pimatic forum there's a voting for new features.
have a look here : http://forum.pimatic.org/topic/12/device-that-shows-a-iframe-with-an-external-webpage
can you please sign up and vote for this? 
you can sign up by using your already existing git user (during the registration at the forum)

**Comment by sweebee** [comment]
This is already possible with the piratic-links plugin.

**Comment by incmve** [comment]
Nope the pimatic-links plugin only gives you a link in the left menu not an iFrame

**Comment by sweebee** [comment]
Add this: target	:	iframe

**Comment by incmve** [comment]
You are correct but that only shows an iframe when clicked on, I personaly prefer a device like iframe like this #364

**Comment by sweetpi** [comment]
Moving all Feature request to the forum, so closing this.

**Comment by DheerajKhajuria** [comment]
@sweetpi great work!!

any idea how to intermix  http iframe links within https secure login  session.

**Comment by sweetpi** [comment]
No easy way at the moment. You could use a local proxy that provides the page via https and custom cert.

**Comment by Yves911** [comment]
@DheerajKhajuria have a look to stunnel
