### ISSUE TITLE
Serial Port not open + SQL malfunction

### ISSUE THREAD

**Issue by Rantir** [pimatic/pimatic#510]
Hi guys guys ive Gattung the Error
Serial port not open Ehen ever i want to turn in vor off a switch.
Also i getting SQLITE_CORRUPT database disk image malformed.

Ive using a rapi b+ with homeduino.
And it workedfor somedays,now its gone.

**Comment by DDNRN** [comment]
you are the next one ...

The RASPI SD Card should be burned by pimatic 
See issue: https://github.com/pimatic/pimatic/issues/497

**Comment by Rantir** [comment]
But my xbmc in the rapi still runs:/
Am 30.01.2015 18:14 schrieb "DDNRN" <notifications@github.com>:

**Comment by sweetpi** [comment]
SQLITE_CORRUPT does not mean that your SD card died or so...it just says the database was corrupted somehow (For example because of a power failure "hot reboot"). Delete the database file and it should work again. A good idea is to run a filesystem check, too and backup your data, just in case.

**Comment by 1000io** [comment]
I have my RBPi with the boot files in the sd card and rest of raspbian in a external hard disk. Im using pimatic for 6 month without problems.

**Comment by Rantir** [comment]
Wellwhere to delete the db file ;) ?

Jeah my power supply Burnet down dunno why, it just zaped out my fuse.
Am 30.01.2015 21:33 schrieb "sweet pi - sweet home" <
notifications@github.com>:

**Comment by sweetpi** [comment]
> Wellwhere to delete the db file ;) ?

```
cd pimatic-app
sudo rm pimatic-database.sqlite
```

**Comment by sweetpi** [comment]
Considered cloes. Please reopen if thee is still an issue.
