### ISSUE TITLE
Initial install fails: ENOENT

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#512]
I'm having the same problem as https://github.com/pimatic/pimatic/issues/393

During startup, many of the dependencies fail. Started with sqlite3, continues with cron:

	13:03:53.065 [pimatic] Installing: "cron"
	Error: spawn ENOENT
	    at errnoException (child_process.js:1011:11)
	    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

Can be fixed by `npm install`ing them but wondering why those fail in the first place?

**Comment by sweetpi** [comment]
This means that npm is not in your path or out path while spawning is wrong. How do you start pimatic? What does `echo $PATH` right before starting say? `whereis npm`?

**Comment by andig** [comment]
Mhm. Both node and npm are in the path:

	pi@prodpi ~/pimatic $ which node
	/usr/local/bin/node
	pi@prodpi ~/pimatic $ which npm
	/usr/local/bin/npm

I have a service for starting pimatic which works fine not after reinstalling.

However, as soon as I install updates from the gui it dies again:

	11:49:49.319 [pimatic] listening for http-request on port 88...
	Error: spawn ENOENT
	    at errnoException (child_process.js:1011:11)
	    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by sweetpi** [comment]
> I have a service for starting pimatic which works fine not after reinstalling.

What's in the service script file, does it change/set the path variable?

**Comment by andig** [comment]
Not really- it's a copy of the raspbian `init.d/skeleton`:

	#! /bin/sh
	### BEGIN INIT INFO
	# Provides:          pimatic
	# Required-Start:    $remote_fs $syslog
	# Required-Stop:     $remote_fs $syslog
	# Default-Start:     2 3 4 5
	# Default-Stop:      0 1 6
	# Short-Description: Example initscript
	# Description:       This file should be used to construct scripts to be
	#                    placed in /etc/init.d.
	### END INIT INFO

	# Author: Foo Bar <foobar@baz.org>
	#
	# Please remove the "Author" lines above and replace them
	# with your own name if you copy and modify this script.

	# Do NOT "set -e"

	# PATH should only include /usr/* if it runs after the mountnfs.sh script
	PATH=/sbin:/usr/sbin:/bin:/usr/bin
	DESC="Pimatic"
	NAME=pimatic.js
	DAEMON=/home/pi/pimatic/$NAME
	DAEMON_ARGS=""
	PIDFILE=/var/run/$NAME.pid
	SCRIPTNAME=/etc/init.d/$NAME

	# Exit if the package is not installed
	[ -x "$DAEMON" ] || exit 0

	# Read configuration variable file if it is present
	[ -r /etc/default/$NAME ] && . /etc/default/$NAME

	# Load the VERBOSE setting and other rcS variables
	. /lib/init/vars.sh

	# Define LSB log_* functions.
	# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
	# and status_of_proc is working.
	. /lib/lsb/init-functions

	#
	# Function that starts the daemon/service
	#
	do_start()
	{
		# Return
		#   0 if daemon has been started
		#   1 if daemon was already running
		#   2 if daemon could not be started
		start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
			|| return 1
		start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
			$DAEMON_ARGS \
			|| return 2
		# Add code here, if necessary, that waits for the process to be ready
		# to handle requests from services started subsequently which depend
		# on this one.  As a last resort, sleep for some time.
	}

	#
	# Function that stops the daemon/service
	#
	do_stop()
	{
		# Return
		#   0 if daemon has been stopped
		#   1 if daemon was already stopped
		#   2 if daemon could not be stopped
		#   other if a failure occurred
		start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
		RETVAL="$?"
		[ "$RETVAL" = 2 ] && return 2
		# Wait for children to finish too if this is a daemon that forks
		# and if the daemon is only ever run from this initscript.
		# If the above conditions are not satisfied then add some other code
		# that waits for the process to drop all resources that could be
		# needed by services started subsequently.  A last resort is to
		# sleep for some time.
		start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
		[ "$?" = 2 ] && return 2
		# Many daemons don't delete their pidfiles when they exit.
		rm -f $PIDFILE
		return "$RETVAL"
	}

	#
	# Function that sends a SIGHUP to the daemon/service
	#
	do_reload() {
		#
		# If the daemon can reload its configuration without
		# restarting (for example, when it is sent a SIGHUP),
		# then implement that here.
		#
		start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
		return 0
	}

	case "$1" in
	  start)
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		do_start
		case "$?" in
			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;
	  stop)
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop
		case "$?" in
			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;
	  status)
		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
		;;
	  #reload|force-reload)
		#
		# If do_reload() is not implemented then leave this commented out
		# and leave 'force-reload' as an alias for 'restart'.
		#
		#log_daemon_msg "Reloading $DESC" "$NAME"
		#do_reload
		#log_end_msg $?
		#;;
	  restart|force-reload)
		#
		# If the "reload" option is implemented then remove the
		# 'force-reload' alias
		#
		log_daemon_msg "Restarting $DESC" "$NAME"
		do_stop
		case "$?" in
		  0|1)
			do_start
			case "$?" in
				0) log_end_msg 0 ;;
				1) log_end_msg 1 ;; # Old process is still running
				*) log_end_msg 1 ;; # Failed to start
			esac
			;;
		  *)
			# Failed to stop
			log_end_msg 1
			;;
		esac
		;;
	  *)
		#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
		echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
		exit 3
		;;
	esac

	:

**Comment by sweetpi** [comment]
> PATH=/sbin:/usr/sbin:/bin:/usr/bin

Looks for me like overwriting the path. And as npm is installed to `/usr/local/bin/npm` it's no big surprise that it can't be found. Hm I think a better error message would be nice, here. Do you want to make a pull request?

> pi@prodpi ~/pimatic $ which node
> /usr/local/bin/node
> pi@prodpi ~/pimatic $ which npm
> /usr/local/bin/npm

I don't think it's a good idea to use this at all. I would recommend to use the official one (https://github.com/pimatic/pimatic/blob/master/install/pimatic-init-d) ?

**Comment by andig** [comment]
> Do you want to make a pull request?

Don't have any time right now, please take my apologies. Default script is wfm, sorry for the confusion.

**Comment by sweetpi** [comment]
Almost all plugins are know installed from precompiled tar balls, so this should be no issue anymore.
