### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#517]
Just discovered this here : 
![flashing database](https://cloud.githubusercontent.com/assets/8620305/6015209/f384abb0-ab71-11e4-8776-7414ca807ee7.jpg)

guess this should be "Flashing database" instead ? 
maybe "Writing database to disk" could be another expression for this.

**Comment by fritz-hh** [comment]
See #516
Am 03.02.2015 07:01 schrieb "Chris" <notifications@github.com>:

**Comment by leader21** [comment]
oh sorry! closing this!
