### ISSUE TITLE
Add stop-button to mpd-plugin

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#520]
When you use the mpd-plugin for listening to internet radiostations pause is not what you want.
When you pause the stream and continue it after some minutes only the last saved buffer is played and then mpd stops playing.

I made pull-requests for it: 
https://github.com/pimatic/pimatic-mobile-frontend/pull/3
https://github.com/pimatic/pimatic-mpd/pull/6

For me everything works now as expected.

**Comment by sweetpi** [comment]
Thank you very much.

Released with pimatic-mpd v0.8.8
and pimatic-mobile-frontend v0.8.42

(Just updated the versions again, because my release script did it..)
