### ISSUE TITLE
fritz pligin at pimatic

### ISSUE THREAD

**Issue by bommey** [pimatic/pimatic#522]
Hey,

i am Using Fritbox 7362sl, with a connected Smarthome device (dect 200 socket). (working)
Now i want to use Fritz plug in to control everything with pimatic.

When i want to connect to pimatic:

Cannot access 192.168.178.1/webservices/homeautoswitch.lua?0=0&switchcmd=getswitchlist: undefined

my config is:

   {
      "plugin": "fritz",
      "url": "192.168.178.1",
      "user": "gpio",  \\ i created this user
      "password": "xxxx",  \\ i have changed the user pw to the pw of the fritzbox... so they are using   the same pw, because i do not know which pw is the one i need
      "interval": 60
    },

and the device config:
    {
      "id": "home-switch",
      "name": "Fritz outlet",
      "class": "FritzOutlet",
      "ain": "xxxxx yyyyyyy",
      "interval": 60
    }

after  a while :
Cannot access 192.168.178.1/webservices/homeautoswitch.lua?0=0&switchcmd=getswitchstate&ain=xxxxx yyyyyyy: undefined

I am Using:
Firtbox 7362 SL with
Aktor Versionsnumber 03.36
Fritzversion 06.20

I hope you can help me

**Comment by leader21** [comment]
have you tried to use <code>"url": "http://fritz.box",</code> instead of the ip?

**Comment by bommey** [comment]
yes i have tried this, as well
same effect.

**Comment by bommey** [comment]
http://192.168.178.1  is working
thank you
