### ISSUE TITLE
only absend and off in the events log

### ISSUE THREAD

**Issue by HermannDerUser** [pimatic/pimatic#523]
Hello,

since use pimatic v0.8.40 there is in the logs for all devices with the attribute state the value always OFF and with the attribute presence always ABSEND.

In the Web-GUI and on the page "Variables" ist the value correct.

Hermann
![Uploading Zwischenablage01.jpg . . .]()

**Comment by sweetpi** [comment]
Thanks for reporting, this should already be fixed in 0.8.42. Could you test?

**Comment by HermannDerUser** [comment]
I have updated pimatic via "npm install pimatic" without errors on the console but the GUI shows "Found update for pimatic: current version is 0.8.40, latest version is: 0.8.42"

How can I check the pimatic version on the console?

**Comment by HermannDerUser** [comment]
Ups, now I have found my mistake. :-( I forgot to change into the pimatic-app directory BEFORE installation.
Now I can check that the above-mentioned error is resolved .

**Comment by HermannDerUser** [comment]
@sweetpi
The error into the event log is fixed in version 0.8.42 . Thank you
