### ISSUE TITLE
How to set up the pimatic-play plugin

### ISSUE THREAD

**Issue by Sebi30** [pimatic/pimatic#525]
Hello I need help with the pimatic-payer plugin.
I have instaled plugin. I have the script omxplayer entered in the play-config-schema.coffee.
Here is my setting:

module.exports = {
title: "play config options"
type "object"
required: ["omxplayer"]
properties:
player:
description: "player used to play audio"
type "string"
required: no
}

But on the GUI is the message:

Could not find on provider did Provides the next action of
  "play" /home/audio/hallo.wav "".

What am I doing wrong?
Please post an example

**Comment by sweebee** [comment]
Please post questions like this in the forum next time :)

To answer your question, you have to add only this to your config (devices):
```json
{
  "plugin": "play",
}
```
and then add it to a rule:

```
play "alarm.wav"
```
