### ISSUE TITLE
pimatic-homeduino installation problems

### ISSUE THREAD

**Issue by kenulu** [pimatic/pimatic#528]
Hello everybody,
I would like to use the Arduino Nono with the plugin pimatic - homeduino . However, this does not work for me.

The plugin is installed and changed the config accordingly. 
I see on the GUI the Shutter Switch on and off , but when I run it comes after a while the error <blockquote>"operation timed out after 300000 ms"</blockquote> and in the messages I see <blockquote>" error [ pimatic - homeduino ] : Timeout Error : operation timed out after 300000 ms at Promise $ _afterTimeout (/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:45:15) at null._onTimeout (/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:30:9) at Timer.listOnTimeout [as OnTimeOut ] ( timers.js : 110: 15)
11 : 33: 39error [ pimatic - homeduino ] : Could not connect to homeduino device : operation timed out after 300000 ms " .</blockquote>

what am I doing wrong ? Here are the steps how I proceeded :
<quote>
1. Plugin " athome " installed
2. install plugin " Homeduione "
3. stopped Pimatic
4. config.json following changes :
{
"plugin" : " homeduino ",
" driver" , " serial port",
"driver options" : {
"serial device" : " / dev / ttyUSB0 ",
"baudrate " : 115200
  } ,
" receiverPin ": 0,
" transmitterPin " : 5
}
5. added in the config shutters Device
6. Encouraging connected breadboard Arduino Nano
7. Started  Pimatic
</quote>
Result: did not work!

I ask because my perfect Englich to excuse, but google can not bear better :)

A German forum I miss at this point ...

**Comment by leader21** [comment]
try to use transmitter pin 4 and connect the wire at the nano to D4.
for some support in German you may contact me over the chat at the pimatic forum.

generally pimatic is an international project, therefore the chosen language is English.
so everybody can contribute and participate from others. 
hope that does not keep you off ;)

**Comment by kenulu** [comment]
Hallo leader21,
There are so google, available , ideal of this non mutatis mutandis Translated it is no problem for me with my school English to understand everything . I hope I understood :)

I 've been chanced the Config and the set transmitter to D4 on Anduiono Nano. Unfortunately, no success. It is still propagated the error:
<blockquote>
" error [ pimatic - homeduino ] : Timeout Error : operation timed out after 300000 ms at Promise $ _afterTimeout (/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:45:15) at null._onTimeout (/usr/local/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/bluebird/js/main/timers.js:30:9) at Timer.listOnTimeout as OnTimeOut
15 : 35: 14error [ pimatic - homeduino ] : Could not connect to homeduino device : operation timed out after 300000 ms " .</blockquote>

**Comment by leader21** [comment]
another question - did you flash the homeduino sketch to your nano as described here https://github.com/pimatic/homeduino ? the nano needs to be flashed with this first, before it's ready to use. 
without the homeduino "software" running on the nano there's no connection to pimatic!

**Comment by kenulu** [comment]
that makes sense :) No, I did not - and I could not , because via USB the Arduino (program) gives at compile some error .
Is there a howto for dummies ?

**Comment by ituri** [comment]
> Is there a howto for dummies ?
Have a look at https://github.com/pimatic/homeduino. I just installed my homeduino today and the steps described there were really helpful. Basically, all you need to do is run the Makefile.

**Comment by leader21** [comment]
no howto for dummies but support for users ;)

just follow these steps 
1. install the needed libraries
`sudo apt-get install arduino-core avr-libc avrdude binutils-avr gcc-avr libconfig-yaml-perl libftdi1 libyaml-perl screen python-serial`

2. go to your pimatic directory (or wherever you want to put the homeduino directory to)
`cd /usr/local/pimatic-app`

3. clone the git repository of the homeduino to your directory
`git clone --recursive https://github.com/pimatic/homeduino.git`

4. go to the homeduino directory
`cd homeduino`

5. if you are using an arduino nano at usb port you usually do not need to change anything at the makefile, unless you are using another arduino or another controller and another serial port.
so go ahead with the following command 
`make upload`

you're done!

**Comment by Icesory** [comment]
@sweetpi is it possible to put the flash process into pimatic-homeduino? It was easier for users and updates for the Arduino can uploaded automatical

**Comment by kenulu** [comment]
Thanks for the help !
Have the written and implemented Pimatic - homeduino no errors in the console.
Unfortunately that does not work yet with sending . That means that I can not turn the shutter button and I could switch with pilight .

**Comment by Icesory** [comment]
Can you post some pictures of your hardware and your device in the config?


You can write in German. It isnt a law to be an english people. When it is to hard to write in english than write in german. People are interessted in this specific thread can translate it by it self. 
But in your own interest it should be to write in english. It is the speak of the world (i dont like it too)

**Comment by kenulu** [comment]
![2015-02-09 17 43 25](https://cloud.githubusercontent.com/assets/10913504/6111277/f0c57290-b087-11e4-976b-b01ab368ae63.jpg)
![2015-02-09 17 43 30](https://cloud.githubusercontent.com/assets/10913504/6111276/f0c3b216-b087-11e4-92d5-590d4c6dbedf.jpg)
![2015-02-09 17 43 39](https://cloud.githubusercontent.com/assets/10913504/6111278/f0c98f1a-b087-11e4-88e1-ed32e37b3606.jpg)
The hardware does not report any errors. The config.json must now be adjusted with the right codes for shutter, buttons ect.

**Comment by leader21** [comment]
ok, lasst uns mal auf deutsch weitermachen leute, dann bekommen wir das ruckzuck in den griff.
welchen rolladenschalter willst du ansteuern? intertechno oder elro bzw. was für eine hardware willst du ansteuern via pimatic. das wollte icesory eigentlich wissen. 
wenn wir das wissen dann können wir dir auch schnell die passenden devices für die config basteln. 

wenn du im pimatic menu auf messages klickst kannst du oben auswählen was du als nachrichten sehen möchtest. da klickst du auf homeduino und wählst in dem anderen dropdown feld debug aus. 
wenn du nun deinen schalter für den rolladen betätigst (shutter switch ...) dann wird dir dort eine ganze reihe von codes angezeigt. einer davon wird dann auf deinen schalter passen.

**Comment by DDNRN** [comment]
>>Icesory commented 3 hours ago
@sweetpi is it possible to put the flash process into pimatic-homeduino? It was easier for users and updates for the Arduino can uploaded automatical

But needs to be customized in any way to give ability to change from standard homeduino code for special configs.

**Comment by DDNRN** [comment]
@kenulu 
Passt die Antennenlänge?  ca. 17cm, möglichst aus starrem Draht!
Evtl. doch besser diesen einen Draht anlöten und nicht ins Breadbord stecken.

**Comment by kenulu** [comment]
Ja vielen Dank dafür. 
Ich schalte momentan mit Pimatic-pilight Elro AB440 WD Funksteckdosen und Coco Asun650 Rolladenfunkschalter.
Hier die pilight config.json:
<code>

{
        "living": {
                "name": "Wohnzimmer",
                "led1": {
                        "name": "LED Wand I",
                        "protocol": [ "elro_he" ],
                        "id": [{
                                "systemcode": 31,
                                "unitcode": 2
                        }],
                        "state": "on"
                },
                "led2": {
                        "name": "LED Wand II",
                        "protocol": [ "elro_he" ],
                        "id": [{
                                "systemcode": 31,
                                "unitcode": 1
                        }],
                        "state": "off"
                },
                "tvamb": {
                        "name": "TV Ambiente",
                        "protocol": [ "elro_he" ],
                        "id": [{
                                "systemcode": 31,
                                "unitcode": 4
                        }],
                        "state": "on"
                }
        },
        "kitchen": {
                "name": "Küche",
                "sockel": {

**Comment by DDNRN** [comment]
Hast du von den ELRO mal eben die DIP-Schalterstellung?

**Comment by DDNRN** [comment]
Mit der normalen (4-Tasten) Fernbedienung schaltbar entsprächen die Codes dem: 
SystemCode = 
DIP-No. = Value (=on)
1 = 16
2 = 8
3 = 4
4 = 2
5 = 1
UnitCode (für den gedrückten Knopf auf der FB)
no = U-code
A/ 1 = 16
B/ 2 = 8
C/ 3 = 4
D/ 4 = 2
na = 1

als Device in pimatic dann etwa so: (Entspricht dem FB Knopf B / 2)
````
    {
      "id": "living-switch",
      "name": "Stkd-Lampe1",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch2",
          "options": {
            "unitCode": 8,
            "houseCode": "31"
          }
        }
      ]
    },
````

**Comment by leader21** [comment]
hm ... wenn ich mir die protokoll liste anschaue ist CoCo mit switch1 gelistet. 
allerdings wird hier in pilight alles mit elro_he geschaltet. 

daher geh ich mal von aus dass es sich auch um ein elro protokoll handelt welches du für pimatic nehmen kannst. 

probier mal dieses hier : 

```
{
  "id": "rollo",
  "name": "Rollo",
  "class": "HomeduinoRFShutter",
  "protocols": [{
    "name": "switch2",
    "options": {
      "houseCode": 28,
      "unitCode": 11
    }
  }]
},
```

**Comment by DDNRN** [comment]
Bin mir nicht sicher, hatte aber beim unitCode irgend was ändern müssen als ich von pimatic auf homduino umgestellt habe. Kann es sein, dass man die Richtung der DIP-Bits umdrehen musste?
Wenn der Empfänger funktioniert probier mal was pimatic dir unter messages/debug anzeigt.
Da sollte dann schon der richtige Code drin stehen.

**Comment by leader21** [comment]
beim umstieg von pilight auf pimatic mit intertechno / kaku / düwi, also alles was diese beiden drehräder hat ist das so. da gibt es auf jedenfall änderungen. die neuen codes dafür hab ich mal in einer tabelle verfasst. ob das bei elro auch so ist weiss ich leider auch nicht, da ich keine elros habe. aber wäre generell mal interessant zu wissen ob sich haus und unitcode ändern. dann würde ich mir mal ein/zwei elro produkte zulegen zum testen.

**Comment by kenulu** [comment]
```
info [pimatic-homeduino]: Connected to homeduino device.
```
wie es aussieht steht der Kommunikation zwischen dem Pi und Nano nichts im Wege.

Rolladenschalter habe ich jetzt auch in Pimatic und wenn ich hoch oder runter steuere passiert nichts. Da auch keine Fehlermeldung erscheint muss wohl etwas am Code falsch sein.

**Comment by leader21** [comment]
> Rolladenschalter habe ich jetzt auch in Pimatic und wenn ich hoch oder runter steuere passiert nichts. Da auch keine Fehlermeldung erscheint muss wohl etwas am Code falsch sein.

wie schon mal gesagt - geh in das menu "messages" dann oben homeduino und debug auswählen. den schalter für rauf und runter betätigen und den code im debug menu ablesen. dann das device in der config dementsprechend anpassen.

**Comment by kenulu** [comment]
Soo, habe mal 1 x hoch und dann 1 x runter gedrückt und folgende Info in Messages erhalten:

```
debug [pimatic-homeduino]: contact1: { id: 4006642, all: false, contact: true, unit: 0 }
21:29:07debug [pimatic-homeduino]: switch1: { id: 4006642, all: false, state: false, unit: 0 }
21:29:07debug [pimatic-homeduino]: received: [ 213, 292, 1252, 2596, 10236 ] 131012101210121012121112111211121110121211101211121211111211121112121111121211121112111211111211121211111211121112101211121112111214
21:29:07debug [pimatic-homeduino]: data: "RF receive 292 2596 213 1252 10236 0 0 0 010203020302030203030003000300030002030300020300030300000300030003030000030300030003000300000300030300000300030003020300030003000304"
21:29:03debug [pimatic-homeduino]: contact1: { id: 4006642, all: false, contact: false, unit: 0 }
21:29:03debug [pimatic-homeduino]: switch1: { id: 4006642, all: false, state: true, unit: 0 }
21:29:03debug [pimatic-homeduino]: received: [ 184, 287, 1254, 2628, 10240 ] 131112111210121112121112111211121111121211111211121211111211121112121111121211121112111211111211121211111211121211111211121112111214
21:29:03debug [pimatic-homeduino]: data: "RF receive 287 2628 1254 184 10240 0 0 0 010002000203020002020002000200020000020200000200020200000200020002020000020200020002000200000200020200000200020200000200020002000204"
21:15:45info [pimatic-homeduino]: Connected to homeduino device.
```

**Comment by leader21** [comment]
wunderbar, da haben wir doch input ;)
so sollte das funktionieren 
```
{
  "id": "rollo",
  "name": "Rollo",
  "class": "HomeduinoRFShutter",
  "protocols": [{
    "name": "switch1",
    "options": {
      "id": 4006642,
      "unit": 0
    }
  }]
},
```

**Comment by kenulu** [comment]
Eureka :) Es funktioniert! Habe aus den Messages den Code genommen und wie unten angewendet:

```
   {
     "id": "rollo-home",
     "name": "Rollo Home",
     "class": "HomeduinoRFShutter",
     "protocols": [
       {
         "name": "switch1",
         "options": {
           "houseCode": 4006642,
           "unitCode": 0
         }
       }
     ]
   },

```
Kann ich mit der gleichen Methode alle meine Schalter finden?

**Comment by DDNRN** [comment]
So sollte es sein! und wenn nicht, gibts hier immer freundliche Helfer die dir unter die Arme greifen.
Die brauche ich auch immer :-)   (in englisch gibt's natürlich eher eine Antwort )

**Comment by leader21** [comment]
alle rolladenschalter von CoCo auf jedenfall. 
die elro funksteckdosen musst du mal ausprobieren. normalerweise sind das switch2 oder switch3 protokolle.
bei steckdosen oder an/aus schaltern heisst es dann aber "class": "HomeduinoRFSwitch", anstelle shutter

**Comment by kenulu** [comment]
I owe you all warmly and find pimatic as well as the Community simply cool :) Even if I have written for the first time, experementiere and follows you for a long time ;) 

```
http://de.pons.com/text-%C3%BCbersetzung

**Comment by Icesory** [comment]
Das switch1 Protokoll benutzt id und unit nicht housecode usw. Das muss in der Config auch beachtet werden.

**Comment by leader21** [comment]
hm... seltsamerweise scheint es bei kenulu wohl aber so zu funktionieren.

**Comment by kenulu** [comment]
Doch hatte ich, aber in der Euphorie hatte ich nicht bemerkt, dass sich beide meiner Rolloschalter gleichzeitig öffneten oder schlossen. Das ist interresant und könnte alls ein "All down - All up" schalter genutzt werden :)
Ich habe es aber korrigiert und schalte meine beiden Rollos einzeln.

**Comment by sweetpi** [comment]
Solved?

**Comment by leader21** [comment]
guess so.

**Comment by n3roGit** [comment]
Hello everybody,
I have already helped the instructions here. I can switch on and off without a timeout error.

Unfortunately, I still seem to send the wrong signal. Because no device is responding.

In Pilight I had:
"Stehlampe": {
                        "name": "Stehlampe",
                        "protocol": [ "elro_he" ],
                        "id": [{
                                "systemcode": 26,
                                "unitcode": 1
                        }],
                        "state": "on"
                }

in Pimatic it is:

{
      "id": "rfswitch",
      "name": "RFSwitch",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch2",
          "options": {
            "houseCode": 26,
            "unitCode": 1
          }
        }
      ]
    }

What am I doing wrong?


Best Regards,
n3ro

**Comment by DDNRN** [comment]
"The pin numbers are arduino pin numbers. The receiverPin must be either 0 (INT0) or 1 (INT1). The transmitterPin can must bq a digitial pin between 2 (D2) and 13 (D13) ."

Be aware: Receiving on pin 0 does not mean Arduino PIN#0  >> it should be the PIN corresponding with INT0 depending on your arduino-hardware. On UNO for example it is PIN2 = INT0
Also in Plugin example it is:
````
{
  "plugin": "homeduino",
  "driver": "serialport",
  "driverOptions": {
    "serialDevice": "/dev/ttyUSB0",
    "baudrate": 115200
  },
  "receiverPin": 0,
  "transmitterPin": 4
}
````
Check and try again or post your config here and send a foto from hardware wiring.

**Comment by beniroquai** [comment]
Hello. I'm also facing a problem using pimatic with the arduino.. 

Following Log from the web-interface:
info [pimatic]: listening for http-request on port 5001...
23:47:19info [pimatic-mobile-frontend]: rendering html finished
23:47:00info [pimatic-mobile-frontend]: rendering html
23:47:00info [pimatic-mobile-frontend]: packing static assets finished
23:46:58info [pimatic-mobile-frontend]: packing static assets
23:46:58warn [pimatic]: no plugin found for device "rfswitch" of class "HomeduinoRFSwitch"!
23:46:58warn [pimatic]: no plugin found for device "Lampe" of class "HomeduinoRFSwitch"!
23:46:58info [pimatic]: new device "Xperia"...
23:46:57error [pimatic]: Cannot find module 'bluebird'
23:46:54info [pimatic]: loading plugin: "pimatic-homeduino" (0.8.45)
23:46:54info [pimatic]: loading plugin: "pimatic-ping" (0.8.3)
23:46:50info [pimatic]: loading plugin: "pimatic-mobile-frontend" (0.8.50)
23:46:30info [pimatic]: restarting...

(sorry for inverse order)

I followed this tutorial: http://www.sweetpi.de/blog/1157/funksteckdosen-mit-dem-raspberry-pi-und-pimatic-schalten from a clean installation. My config file should be fine. Anybody an idea what 
23:46:58warn [pimatic]: no plugin found for device "rfswitch" of class "HomeduinoRFSwitch"! 
means? Homeduino is set in the pluginsection.

**Comment by leader21** [comment]
how do you use homeduino? via arduino nano or gpio at raspberry pi?

i am just up to create howto's. maybe this here will help you :
http://forum.pimatic.org/topic/202/4-homeduino-433-mhz-sending-receiving-and-even-more

**Comment by beniroquai** [comment]
Thanks. I tried what you've said. But no success. Flashing the code on the arduino had no errors. Homeduino is installed in node_modules as far as I can see.

**Comment by sash85** [comment]
Hello,
i only want to use the sender (because my receiver is broken and I don't need him). 
Is there way to find out the right codes?
I have calculated my codes for Pilight (e.g. from AB C DE to 00100 -> inverted and convert to decimal -> 4). 
I have four elro switches.

Pilight config:
"cdose": {
                        "protocol": [ "pollin" ],
                        "id": [{
                                "systemcode": 19,
                                "unitcode": 4
                        }],
                        "state": "off"

Thank you in advance!

**Comment by sash85** [comment]
I found a solution :-).

You can calculate it (ABCDE On=1, Off=0 -> convert from binar to decimal. (http://forum.pimatic.org/topic/167/solved-elro-ab440s-and-pimatic/3)

Ich need to use switch2 protocol.
