### ISSUE TITLE
Causality problems with  rule systems. 

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#529]
I have several problems with rules. Here is one of them:
Let's look  at the following rule:
```
if $timerRemain gets updated and $timerRemain > 0 
    then set $timerRemain to ($timerRemain - 1) after 1s
```
1. `$timerRemain` is initially 0 or below
2. Now change it to a positve value. Nothing will happen
3. Change it again to different positiv value. Now the rule will fire and counts down the variable
4. `$timerRemain` reaches 0. The process doesn't stop as expected by the rule
5. `$timerRemain` reaches -1. The process stops one step to late.

Alternativ:
3. b) Change it back to a value <= 0. The rule fires once.

I conclude that the change of the variable `$timerRemain` triggers the rule before its value of `$timerRemain` is updated.

**Comment by sweetpi** [comment]
I will look into that problem. Seems indeed that the "gets updated" event fires to early.

**Comment by Heizelmann** [comment]
Might be solved, see http://forum.pimatic.org/topic/170/strange-behaviour-of-if-var-changes
