### ISSUE TITLE
Changing order of rules in the UI has no effect until restart

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#530]
Rules are processed from top to bottom. If I change the order in the web UI this has no effect for processing order until I restart the server.

**Comment by sweetpi** [comment]
Hm I don't think its a good idea to depend on the ordering of the rules in the frontend. Do you have an example where the ordering matters?

**Comment by Heizelmann** [comment]
First experiments let me thought that rules are processed sequentially and changes in order get only active after restarting the server. So I created this issue.
Later I detected a random behaviour. So I assumed processing is concurrent.

I tested it with two rules:
```
If $myvar changes then switch MySwitch on
If $myvar changes then switch MySwitch off
```
as workaround for the issue #531
```
If $myvar changes then switch MySwitch on and switch MySwitch off
```
Anyway the behaviour should be clear documented. Is the processing concurrent (means order is random) or is it sequential?

**Comment by sweetpi** [comment]
> Anyway the behaviour should be clear documented. Is the processing concurrent (means order is random) or is it sequential?

It's not guaranteed that processing is in any order. I just wanted to know if there is a use case, where you would like to have a particular order?

**Comment by Heizelmann** [comment]
As stated above I tried this as a workaround for a missing causal AND-Action.
Concrete uses case:
```If it is 00:00 then $cntday = $newCnt - $oldCnt and $oldCnt = $newCnt```

**Comment by mggg** [comment]
Hi. I think rule's order always matters...
When pimatic starts all rules are executed, so the order is key.
In a complex system like this, when you use variables to change devices' state, the order of a rule execution always matters... And also helps to understand the system's behaviour.
On other hand, this order thing is key to me, I've been searching which is the order rules are executed and I found nothing.
Also tried to figure it out with the code, but I'm a little rusty :)
Anyone could confirm what is the processing order of the rules?

**Comment by sweetpi** [comment]
The rules are created top to down at startup and event listener are setup in this order, but if your sort the rules, the rules are not recreated and so the event listener are still bound in the original order.

For the `then` part I think, yes, these actions should be run in the order left to right. But I don't think its a good idea to guarantee a order between rules. You could always use a varibales to force a specific order if you want to. 

@mggg If you have a use case where the order matters, please post it and we can discuss it how it could be solved better or why the rule order should or should not matter in the future.
