### ISSUE TITLE
redirect error

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#532]
Hey guys,

i get this error by redirecting an URL:

TypeError: Cannot call method 'indexOf' of undefined at ServerResponse.res.location (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/response.js:643:13) at ServerResponse.res.redirect (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/response.js:698:8) at /redirect.coffee:13:15 at callbacks (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:164:37) at param (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:138:11) at pass (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:145:5) at Router._dispatch (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:173:5) at Object.router (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:33:10) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.handle (/framework.coffee:254:18) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.cookieSession [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/cookieSession.js:120:5) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.json [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.urlencoded [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:41:37) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.cookieParser [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:65:5) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.expressInit [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/lib/middleware.js:30:5) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Object.query [as handle] (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5) at next (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:193:15) at Function.app.handle (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/proto.js:201:3) at Server.app (/opt/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect/lib/connect.js:65:37) at Server.EventEmitter.emit (events.js:98:17) at HTTPParser.parser.onIncoming (http.js:2108:12) at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23) at CleartextStream.socket.ondata (http.js:1966:22) at CleartextStream.read [as _read] (tls.js:511:12) at CleartextStream.Readable.read (_stream_readable.js:320:10) at EncryptedStream.write [as _write] (tls.js:366:25) at doWrite (_stream_writable.js:221:10) at writeOrBuffer (_stream_writable.js:211:5) at EncryptedStream.Writable.write (_stream_writable.js:180:11) at write (_stream_readable.js:583:24) at flow (_stream_readable.js:592:7) at Socket.pipeOnReadable (_stream_readable.js:624:5) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10) at TCP.onread (net.js:526:21)

Any Ideas?

Regards,
n3ro

**Comment by n3roGit** [comment]
No ideas ? :-/

**Comment by sebastienvg** [comment]
can you tell what URL you are trying to redirect?

**Comment by n3roGit** [comment]
A http Page.

i have tested:
Printer-Configuration page - http port 80
twonkyserver - http port 9000
fritzbox config page - http port 80

every time i get the same error.

**Comment by sweetpi** [comment]
@n3roGit Could you show your config?

**Comment by n3roGit** [comment]
"plugin": "redirect",
      "routes": [
        {
          "path": "/fritzbox",
          "route": "http://192.168.1.1:80"
        },
        {
          "path": "/twonky",
          "route": "http://192.168.1.2:9000"
        },
        {
          "path": "/brother",
          "route": "http://192.168.1.26:80"
        }
      ]
    }

**Comment by leader21** [comment]
i can reproduce that, plugin pimatic-redirect 0.8.0.
just tried with the following and had the same issue : 
```
	{
	  "plugin": "redirect",
           "routes": [
        { 
         "path": "/fritzbox",
         "route": "http://192.168.178.1"
        }
      ]
    }
```

here's the output from the browser http://pastebin.com/duJ7JkYk

**Comment by n3roGit** [comment]
has the addon ever work for anyone?
maybe someone still has a tip :)

**Comment by n3roGit** [comment]
I have found this error in the log file:

warn [pimatic]: package.json of "pimatic-redirect" has no "configSchema" property. Could not validate config

**Comment by n3roGit** [comment]
Error in Log:
[pimatic] error: Couldn't find plugin info for pimatic-redirect

**Comment by sweetpi** [comment]
Sorry pimatic-redirect is currently not support and therefore removed from the plugin list.

**Comment by n3roGit** [comment]
aaaahhh okay :)
