### ISSUE TITLE
mobile front-end bubbles aren't visible at the bottom of the page.

### ISSUE THREAD

**Issue by sebastienvg** [pimatic/pimatic#533]
I am unable to see the content of the bubbles or click their content (the graph link for example) when the devices are located at the bottom of the page. Is there a way to have these bubbles appear inline instead of under the mouse when you hover it?

**Comment by sweetpi** [comment]
Thanks for reporting. That's a known bug in the mobile-frontend, it will hopefully be fixed soon.

**Comment by sweetpi** [comment]
Oh duplicate of #465.
