### ISSUE TITLE
Interaction on WAN

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic#536]
I cannot update variables, rules... over the Internet  anymore. Port is forwarded, but if I want to update a rule an error "timeout"  occurs.

**Comment by sweetpi** [comment]
and its working when you are in the same network?

**Comment by kenci** [comment]
Its working on LAN

**Comment by georg90** [comment]
Over the Internet you can connect to the mobile frontend but when you switch something it gives you a timeout? Have you used a dyndns Service? Try to use your IP - sometimes DNS is quite slow..I experienced something similar with my dyndns service.

**Comment by kenci** [comment]
Can someone try to update variables over WAN?

**Comment by sweetpi** [comment]
There's probably something wrong with your router or port forwarding setup. Could you post a screenshot of your port forwarding setup?

**Comment by kenci** [comment]
Sorry, but it worked last months, so this could not be the problem. I can connect to the gui, scroll through the menus, look at messages, events, rules. So, no problem with forwarding at all. But I can't update anything. 

Does pimatic have a access_log like Apache? 

Please, can someone connect to his phone provider and try to update variables from outside of LAN?

**Comment by sweetpi** [comment]
Which browser do you use?

**Comment by kenci** [comment]
Chrome 40
Android 4.4.4

Should I try another browser?

**Comment by sweetpi** [comment]
> Does pimatic have a access_log like Apache?

No


> Please, can someone connect to his phone provider and try to update variables from outside of LAN?

It's working fine here and I think many do it.



> Chrome 40
> Android 4.4.4
> 
> Should I try another browser?

No, that's well tested and works. 

Did you try to logout and login again? Do you use SSL? If yes did you import the cert?

**Comment by georg90** [comment]
Permissions of the user are "write"?

**Comment by sweetpi** [comment]
> Permissions of the user are "write"?

Don't think it can be the issue, because then he would get an error message. It looks like all thinks where a POST-Request is used are not working. But I've no idea why. Maybe a firewall or router setting.

**Comment by kenci** [comment]
After the latest update it's working again. But I didn't change anything on my smartphone :)
