### ISSUE TITLE
Mail Plugin

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#537]
Hey guys,

how do I configure the mail plugin to mail over the localhost relayer?

{
      "plugin": "mail",
      "transport": "SMTP",
      "transportOptions": {
        "service": "localhost",
        "maxConnections": 5,
        "maxMessages": null
      },
      "to": "root"
    }

**Comment by Talorin** [comment]
{
      "plugin": "mail"
}

That's all

**Comment by n3roGit** [comment]
Perfect! THX!!!
