### ISSUE TITLE
Pimatic crashes about every day

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#541]
Pimatic runs without problems but irregulary it is not reachable anymore. It happen after many hours of operation but nearly every day. Nothing seriously is seen in the log.
ps aux | grep pimatic shows only
... pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/bin/vhduino
running.
Delete pimatic.pid and kill the process vhduino.
Restart the logs:
Startup error: Error: SQLITE_BUSY: database is locked 
Only reboot helps.
I am using the following plugins:
"pimatic-mobile-frontend" (0.8.44)
"pimatic-sysinfo" (0.8.10)
 "pimatic-mail" (0.8.2)
"pimatic-homeduino" (0.8.41)
 "homeduino.coffee"...Done
 "pimatic-shell-execute" (0.8.6)
"pimatic-sunrise" (0.8.0)

**Comment by sweetpi** [comment]
Thanks for reporting. Do you monitor your ram usage with the sysinfo plugin?

I just released a new version, the old version is eating your ram because of an leak in an important dependency.

![mem](https://cloud.githubusercontent.com/assets/5249312/6236410/d2f6fd88-b6ea-11e4-8833-90f232ba379e.png)

Maybe this fixes the issue already. If not we will investigate further.

**Comment by Heizelmann** [comment]
Thanks for your reply.

The plugin is not listed in the updates-page on web UI. Only see:

  Found update for pimatic: current version is 0.8.45, latest version is: 0.8.46
  All plugins are up to date.

I also can not found the new release you mentioned. Which commit is it?

I will do a manually update with
  npm install pimatic-sysinfo
and then will see what happens.

**Comment by sweetpi** [comment]
I wasn't clear. The problem was in pimatic core, not the plugin.

**Comment by Yves911** [comment]
I noticed also the increase of memory usage over the time with previous version of pimatic.
will check with the new pimatic version and report here tomorrow...

**Comment by Yves911** [comment]
memory usage do not increase anymore over the time, for me this issue can be closed

**Comment by Heizelmann** [comment]
For me not. It still crashes.

**Comment by sweetpi** [comment]
Ok, You get no error in the log, right? 

Please start pimatic with the following command:

```
sudo  nohup ./node_modules/pimatic/pimatic.js > crash.log  2>&1&
```

And let's hope we get an error message in crash.log.

**Comment by Heizelmann** [comment]
I did it and it crashes  toonight again but no errors are seen in crash.log.
The last access I had via webinterface with the warning I get everytime produced the log
'socket.io: Cookie is invalid' but this can not be the reason because this happens often and the system do not crash. I have no idea what to do. pwd after the crash gives:

... grep --color=auto pimatic
... sudo nohup ./node_modules/pimatic/pimatic.js
... /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/bin/vhduino

which shows that only the nohup and homeduino is runnning but not pimatic itself.

**Comment by sweetpi** [comment]
@Heizelmann I think pimatic is still running. The process list confirms this and as you stated in the first post the database is still locked (this means pimatic running). 

* What does happen if you access the webinterface after the "crash"?
* Would you post your config, maybe I can see something (blackout secrets!)?
* Does the "crash" happens after a certain time or random?
* Did you test if the webinterface is accessable from an ingognito tab? Maybe its a client side (caching) problem.

**Comment by Heizelmann** [comment]
I observe 2 memory values. First with a ShellSensor the total memory usage
   ```JSON
 {
      "id": "mem-usage",
      "name": "Memory Usage",
      "class": "ShellSensor",
      "attributeName": "mem-usage",
      "attributeType": "number",
      "attributeUnit": "MB",
      "command": "free -m | awk '$5 ~ /[0-9.]+/ { print $3 }'",
      "interval": 300000
    }
```
and second with the SystemSensor the memory usage of pimatic
```JSON
   {
      "class": "SystemSensor",
      "id": "syssensor",
      "name": "System",
      "attributes": [
        {
          "name": "cpu"
        },
        {
          "name": "memory"
        },
        {
          "name": "dbsize",
          "interval": 300000
        }
      ]
    }
```
When I restart pimatic total mem is about 280 MB and pimatic mem is about 170 MB. During the next 8-15 hours total mem grows continously up to about 320 MB while pimatic mem keeps nearly constant. then suddenly without any log message both values jump up: total mem to about 410MB and pimatic mem the same amout to about 260 MB. From then both values keep constant. Pimatic is still working.

**Comment by bkiss** [comment]
Hi there, 

a have the "same" or something similar problem, my pimatic does not work 2 days or longer. I have a little script in cron which is testing if port open on localhost:8080, if not, then reboot. 
In my observation the free memory is shrinking in time, but i have swap also, so i am not sure if this is related to periodic death of pimatic. In the logs, nothing.
I will now try to catch the problem, like you want, in crash.log, and will come back with info.

**Comment by bkiss** [comment]
2 days max.

My last entry in crash log:

21:00:00.741 [pimatic] rule akvarium-off: turned Akvarium off
bcm2835_init: gpio mmap failed: Cannot allocate memory

?

**Comment by sweetpi** [comment]
@bkiss What plugins do you use? Do you monitor memory usage? If yes please post a screenshot of the graph.

It looks that you are running out of memory.

**Comment by sweetpi** [comment]
> When I restart pimatic total mem is about 280 MB and pimatic mem is about 170 MB. During the next 8-15 hours total mem grows continously up to about 320 MB while pimatic mem keeps nearly constant. then suddenly without any log message both values jump up: total mem to about 410MB and pimatic mem the same amout to about 260 MB. From then both values keep constant. Pimatic is still working.

The SystemSensor monitory system memory not ram used by pimatic. Realy hard to interpret your memory history without seeing a graph and knowing what's else running.

I really want this crashed be fixed, but without the reason I can't do anything. My setup doesn't crash so can't debug it myself.

Also make sure you are testing with the last version.

**Comment by bkiss** [comment]
Ok, i will put a sensor for memory usage, 

Pimatic:
current version is 0.8.46


my plugins:

 "plugins": [
    {
      "plugin": "shell-execute"
    },
    {
      "plugin": "ping"
    },
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    },
    {
      "plugin": "gpio"
    },
    {
      "plugin": "sysinfo"
    },
    {
      "plugin": "dhtxx"
    },
    {
      "plugin": "weather"
    },
    {
      "plugin": "homeduino",
      "driver": "serialport",
      "driverOptions": {
        "serialDevice": "/dev/ttyACM0",
        "baudrate": 115200
      },
      "receiverPin": 0,
      "transmitterPin": 4
    }
  ],

**Comment by sweetpi** [comment]
@bkiss I think it is the dhtxx plugin in your case. I think we have this issue: https://github.com/momenso/node-dht-sensor/issues/6

This line in the code is the issue: https://github.com/wutu/pimatic-dhtxx/blob/development/dhtxx.coffee#L54

The problem is that @wutu seems to be be active anymore.

**Comment by Heizelmann** [comment]
I must know how to input pictures here, then I will post a graph. 5 days ago I gave a wrong listing. After the crash pimatic process is realy not seen with pwd, only homeduino.

**Comment by Heizelmann** [comment]
This is what I recorded with the two Sensors described 2 days ago:
![bild2](https://cloud.githubusercontent.com/assets/10366345/6379734/b1059fea-bd34-11e4-9420-d1a64063e046.png)

**Comment by bkiss** [comment]
Here is my graph for 24h and 7days.

Still rebooting. maybe i will put the dht-s to the arduino board, with homeduino...

![screen shot 2015-03-09 at 16 45 48](https://cloud.githubusercontent.com/assets/5294516/6557192/e8e12e0c-c67b-11e4-9d58-4d6f791ae403.png)

![screen shot 2015-03-09 at 16 44 52](https://cloud.githubusercontent.com/assets/5294516/6557196/f22936bc-c67b-11e4-95d4-f46e4285fdb7.png)

**Comment by djnilse** [comment]
I have the same problem, but my installation crashes every hour. I have the RPI B with 256MB.
![capture](https://cloud.githubusercontent.com/assets/1096841/6954420/d99f97a4-d8d1-11e4-8917-7cd40a117ea0.PNG)

@sweetpi Should it be possible to adapt the code of the pimatic-dhtxx plugin like in the issue you mentoined ? Anyway I will try this

**Comment by djnilse** [comment]
Changed it, it works, I have to see if it is taking less RAM now.

But nevermind, just saw you forked the dhtxx plugin and it is now using wiringpi. Will try that too, but still test the orginal dhtxx

**Comment by elektronaut69** [comment]
I had the same problem. Testing the new dht-sensors plugin now.

**Comment by sweetpi** [comment]
@elektronaut69 Did the dht-sensors plugin work for you (note that pin numbers changed because of wiringpi)? Didn't have time to fully test it, yet.

**Comment by sweetpi** [comment]
@bjornhij The original dhtxx is definitively broken and leads to crashes. Unfortunately the plugin author does not respond, so I needed to create a new one.

**Comment by elektronaut69** [comment]
@sweetpi It did work, but on the next day I was not able to connect to pimatic via the web-frontend. pimatic was running though. Stopping the service was not possible. Rebooting the pi failed until i manually killed pimatic via sudo kill -9 <pid>. There are no errors in the pimatic-daemon.log.
As I use pimatic to control lighting, CO2 and heating of my fishtank I had to remove the plugin as I am no at home for the next days.

**Comment by elektronaut69** [comment]
@sweetpi I tried once more. Same result. After some hours I cannot open the web-gui any more. CPU usage of node is at 100%
```
2806 root      -2   0  174m 124m  10m R  99,9 13,4 102:25.22 node 
```
It is not possible to kill this process. I had to hard-reset the rpi and there is nothing in the pimatic-daemon.log:

```
pi@aquapi ~ $ sudo service pimatic status
Process running with pid 2806.
pi@aquapi ~ $ tail -f pimatic-app/pimatic-daemon.log 
16:31:09.380 [pimatic] info: New device "Flur"...
16:31:14.898 [pimatic-mobile-frontend] info: packing static assets
16:31:15.889 [pimatic-mobile-frontend] info: packing static assets finished
16:31:15.918 [pimatic-mobile-frontend] info: rendering html
16:31:24.382 [pimatic-mobile-frontend] info: rendering html finished
16:31:24.440 [pimatic] info: Listening for HTTPS-request on port 8082...
16:31:25.020 [pimatic-homeduino] info: Connected to homeduino device.
16:36:16.053 [pimatic] info: rule fernsehlicht-aus: Fernsehlicht ausgeschaltet
19:52:13.615 [pimatic] info: rule pflanzenlampe-aus: Pflanzenlampe ausgeschaltet
20:00:00.431 [pimatic] info: rule co2-ende: Kohlendioxid ausgeschaltet
^C
pi@aquapi ~ $ sudo service pimatic stop
Sending SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGQUIT to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
^Cpi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:38:27 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17954 17912  0 22:20 pts/0    00:00:00 grep --color=auto pimatic
pi@aquapi ~ $ sudo kill 2806
pi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:38:40 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17958 17912  0 22:20 pts/0    00:00:00 grep --color=auto pimatic
pi@aquapi ~ $ sudo kill -9 2806
pi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:38:57 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17962 17912  0 22:20 pts/0    00:00:00 grep --color=auto pimatic
pi@aquapi ~ $ sudo killall pimatic
pimatic: Kein Prozess gefunden
pi@aquapi ~ $ sudo killall -9 pimatic
pimatic: Kein Prozess gefunden
pi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:39:16 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17968 17912  0 22:20 pts/0    00:00:00 grep --color=auto pimatic
pi@aquapi ~ $ sudo kill -9 2806
pi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:39:45 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17972 17912  0 22:21 pts/0    00:00:00 grep --color=auto pimatic
pi@aquapi ~ $ ps -ef | grep pimatic
root      2806     1 28 16:30 ?        01:39:47 /usr/local/bin/node /usr/local/bin/pimatic.js start
pi       17974 17912  0 22:21 pts/0    00:00:00 grep --color=auto pimatic
```

Removing the plugin again. I think I will connect the DHT22 to the arduino.

**Comment by Icesory** [comment]
Sweetpi has published a new dth plugin. Try this new one. 
https://github.com/pimatic/pimatic-dht-sensors

**Comment by elektronaut69** [comment]
@Icesory ;-) That's what I did. See my posts before.

**Comment by Icesory** [comment]
Ah sorry. Haven't seen this.

**Comment by elektronaut69** [comment]
Never mind.

Ronny <notifications@github.com> schrieb am Do., 9. Apr. 2015 23:16:

**Comment by sweetpi** [comment]
@elektronaut69 Could you open a new issue for the sht-sensors plugin, so we can trace this down.

**Comment by fennsen64** [comment]
Hi Together, neverthelless this is somehow an old track:
I tried to use dht-sensor plugin while migrating from pilight to homeduino (move from B+ to V2). 

Unfort. this plugin doesn't read my DHT22 sensors with long cables (throws continius 11,5 Celsius and > 3300% Hum.)
Therefore i tried the dht-sensor plugin with the same result.

After a while of research i found, that the included underlying node-dht-sensor module is quite old ("0.0.5")

https://github.com/momenso/node-dht-sensor

After removing the node (../pimatic-app/node_modules/pimatic-dht-sensors/node_modules/node-dht-sensor) with 'npm remove node-dht-sensor' and install the latest version ("0.0.18") with 'sudo npm install node-dht-sensor@0.0.18' everything works fine!

Attention: the Library bcm2835 has to be installed first

**Comment by fennsen64** [comment]
aaahhh.. and the case is, that the plugin uses BCM pin numbers, not WiringPi numbers as documented! Unsure if this is related to the node-dht-sensor update or is an error in the doc...

**Comment by mwittig** [comment]
@fennsen64 Which version of pimatic are you using?

I am just asking as you said the underlying node-dht-sensor module is quite old ("0.0.5"). Actually, we're using a [fork](https://github.com/sweetpi/node-dht-sensor/tree/v0.9.x) of 'node-dht-sensor' as there were some issues with node-dht-sensor and to use 'wiringPi' instead of 'bcm2835'. This why you had to change the pin numbering when you replaced the module. 

For pimatic 0.9 I had resynced the fork. So, the version is 0.0.12 as we're using v0.9.x branch. May be you just looked at the version number highlighted on the master branch which we kept intact for pimatic 0.8. Looking at the version history of momenso/node-dht-sensor, a couple of issues had been fixed. So, I'll resync our fork. 

I'll keep you posted and it'll be great if you can do some testing once the changes have been done.

**Comment by mwittig** [comment]
@fennsen64 Please have a look at <https://forum.pimatic.org/topic/2217/pimatic-dht-sensors-node-dht-sensor-update-for-testing>. It'll be great if you can give this a try. Note, however, this is using  wiringPi pin numbering instead of bcm pin numbering.
