### ISSUE TITLE
On Andoid device the 'graph' overlay can not be clicked.

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#542]
I mean this grey overlay with this small button labeled 'graph' which apears when I click on the minature graph of a sensor. When I click this graph button it looks like it was transparent for this click and the event is catched from what is just behind this button or grey box.

**Comment by Heizelmann** [comment]
Extension: Only when I am very fast and touch the graph button directly afte the overlay appears it reacts and opens the graph view.

**Comment by sweetpi** [comment]
@Heizelmann This should be fixed, can you confirm it?

**Comment by Heizelmann** [comment]
Yes, confirmed. Thanks!
