### ISSUE TITLE
Feature free-text

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#544]
It would be cool if there was a free-text field in pimatic with optional keyboard input like this.

{
 "class": "DummyField",
 "id": "dummy-field",
 "name": "Freetext"
 }

or

 {
 "class": "DummyField",
"id": "dummy-field",
"name": "Freetext",
"keyboard": "0;1;2;3;4;5;6;7;8;9"
}

so you could set the alarm for the alarm clock or other variables.

Regards,
n3ro

**Comment by Yves911** [comment]
You can post this on the forum : http://forum.pimatic.org/topic/10/feature-voting/3
then community will vote (and maybe someone will develop it)

**Comment by n3roGit** [comment]
Perfect THX

**Comment by sweetpi** [comment]
Closing this in favor of the forum post.
