### ISSUE TITLE
ShellSensor System Uptime

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#546]
Can anyone tell me why this query does not work? On the shell it works.

{
      "id": "system-uptime",
      "name": "System uptime",
      "class": "ShellSensor",
      "attributeName": "Uptime",
      "attributeType": "string",
      "attributeUnit": "",
      "command": "/usr/bin/uptime | /bin/sed 's/.\*up \\([^,]\*\\), .\*/\1/'",
      "interval": 3600000
    }

SyntaxError: Unexpected Token (

**Comment by leader21** [comment]
you need to escape the backslashes, then it works
![](http://www.youscreen.de/nyzfwtie01.jpg)

```
    {
	  "id": "system-uptime",
	  "name": "System uptime",
	  "class": "ShellSensor",
	  "attributeName": "Uptime",
	  "attributeType": "string",
	  "attributeUnit": "",
	  "command": "/usr/bin/uptime | /bin/sed 's/.*up \\([^,]*\\), .*/\\1/'",
	  "interval": 3600000
	},
```

have fun with it ;)
cheers

**Comment by n3roGit** [comment]
Perfect THX :) It Works! :)

**Comment by leader21** [comment]
please have a look at the forum for the latest development on this. i changed the processing of the command. now we use a separate script to get the uptime from /proc/uptime

http://forum.pimatic.org/topic/98/system-uptime-shellsensor-device
