### ISSUE TITLE
Pimatic crashed during startup due to variable value

### ISSUE THREAD

**Issue by incmve** [pimatic/pimatic#555]
Sometimes when I restart pimatic it crashes during start because one of my variables has a value of "null".
I have to edit the config.json, change the variable to a number and everything is fine.
Can this be fixed?

```
09:38:21.445 [pimatic] error: Startup error: TypeError: Cannot read property '1' of null
09:38:21.445 [pimatic] error:>    at getAssertionExpression (/home/pi/pimatic-app/node_modules/pimatic/node_modules/cassert/index.js:54:43)
09:38:21.445 [pimatic] error:>    at assert (/home/pi/pimatic-app/node_modules/pimatic/node_modules/cassert/index.js:27:18)
09:38:21.445 [pimatic] error:>    at /variables.coffee:259:13
09:38:21.445 [pimatic] error:>    at VariableManager.init (/variables.coffee:229:9)
09:38:21.445 [pimatic] error:>    at /framework.coffee:645:26
09:38:21.445 [pimatic] error:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:24:31)
09:38:21.445 [pimatic] error:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:466:31)
09:38:21.445 [pimatic] error:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:545:18)
09:38:21.445 [pimatic] error:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:84:12)
09:38:21.445 [pimatic] error:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10)
09:38:21.445 [pimatic] error:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14)
09:38:21.445 [pimatic] error:>    at process._tickCallback (node.js:415:13)
09:38:21.456 [pimatic] info: exiting...
```

**Comment by koffienl** [comment]
Confirmed, I have the same issue.
Would be nice to not to crash on value NULL

**Comment by Yves911** [comment]
Yes i got also the error, what i did to solve that was to make sure that the value won't get null value (so the rule that calculate the value of the variable will check that value is not null)

**Comment by Icesory** [comment]
Do you mean zero or NULL?

**Comment by incmve** [comment]
Null

**Comment by WimUtTwente** [comment]
after update 02-24-2014 at two different raspberry's this error

15:13:50.146 [pimatic] error: A uncaught exception occured: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'
15:13:50.146 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
15:13:50.153 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'

15:13:50.172 [pimatic] error: A uncaught exception occured: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-mint.css'
15:13:50.172 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
15:13:50.179 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-mint.css'

15:12:00.713 [pimatic] error: A uncaught exception occured: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'
15:12:00.713 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
15:12:00.721 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'
15:12:00.739 [pimatic] error: A uncaught exception occured: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'
15:12:00.739 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
15:12:00.747 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: ENOENT, open '/home/pimatic-app/node_modules/pimatic-mobile-frontend/public/theme/graphite-water.css'

After restart everything ok

**Comment by sweetpi** [comment]
> after update 02-24-2014 at two different raspberry's this error

@WimUtTwente Did this only happen ones or does the error occure periodically?

**Comment by WimUtTwente** [comment]
| after update 02-24-2014 at two different raspberry's this error
| @WimUtTwente Did this only happen ones or does the error occur periodically?
It was right after the update at 3 different raspberrie' s. After restarting pimatic no more problems.

**Comment by incmve** [comment]
Thanks @sweetpi https://github.com/pimatic/pimatic/commit/9a7671c2fcc1cb1e7fd32709cf99e25c101a5d71 fixed it :+1:
