### ISSUE TITLE
devices in pimatic config are not loaded into pilight

### ISSUE THREAD

**Issue by rikki78** [pimatic/pimatic#556]
Hi

I have pilight and pimatic running. I have two devices in the pilight config and I can control both of them from pimatic. When I add devices in the pimatic config, I can't control them from pimatic and they aren't shown in the pilight gui. Below one of the devices I'm trying to control.

    {
      "id": "eettafel",
      "name": "Eettafel lamp",
      "class": "PilightDimmer",
      "inPilightConfig": false,
      "location": "woonkamer",
      "device": "eettafel2",
      "minDimlevel": 5,
      "maxDimlevel": 100
    },

Maybe it has something to do with it, when pimatic is starting I get this error:
 [pimatic-pilight] Error on connection to pilight-daemon: Error: write EPIPE

Can anybody tell me what I'm doing wrong?
thanks

**Comment by sebastienvg** [comment]
@rikki78 do you have 

```
{ 
   "plugin": "pilight"
}
```

in the plugins section?

**Comment by leader21** [comment]
pilight has changed its API. It's not supported anymore unless anybody changes the pilight plugin.
we recommend to use pimatic with homeduino.

if you need more information on homeduino you can learn more here : 
https://github.com/pimatic/pimatic-homeduino

you need to install the homeduino plugin, as hardware you will need an arduino nano flashed with the homeduino sketch from here https://github.com/pimatic/homeduino

**Comment by sebastienvg** [comment]
right I remember reading this, meanwhile I never used pilight

**Comment by rikki78** [comment]
Thank you all.

@sebastienvg yes, I have. The pilight plugin is working I'm able to control the devices that are put in the pilight configuration, just not the devices I've added from pimatic.

@leader21 I'm still using pilight v5.0, I believe that is the version that still uses the original API, right?

I'm looking into using homeduino and it looks very nice. Maybe I'll switch to using this.

**Comment by sweetpi** [comment]
@rikki78 pilight has no api to add devices, so pimatic can't add devices to the pilight config. Device are only synced from pilight to pimatic not vice versa. Please note that pilight v6.0 is not supported and there is no more support for the pimatic-pilight plugin by me, because I switched to homeduino.

**Comment by rikki78** [comment]
@sweetpi thanks that explains it!
