### ISSUE TITLE
[pimatic-pilight] Lost connection to pilight-daemon

### ISSUE THREAD

**Issue by sysdev41** [pimatic/pimatic#561]
Hi,
i installed current version of pilight (6.0). I can see the correct values of my 433mhz temperature/humidity sensor. In pilight, everything is working fine so far.

I disabled the pilight webgui and configured pilight daemon to use port 5000.

Finally i installed pimatic with pilight-plugin. But sadly it doesn't work. Is it a config problem or does the current pimatic-pilight plugin not work with pilight 6.0?

I attached the logs:

node_modules/pimatic/pimatic.js
10:02:38.536 2015-02-27 Friday
10:02:59.627 [pimatic] Starting pimatic version 0.8.52
10:03:08.371 [pimatic] loading plugin: "pimatic-cron" (0.8.5)
10:03:13.536 [pimatic] loading plugin: "pimatic-mobile-frontend" (0.8.47)
10:03:20.652 [pimatic] loading plugin: "pimatic-pilight" (0.8.6)
10:03:21.477 [pimatic-cron] the time is: Fri Feb 27 2015 10:03:21 GMT+0000 (UTC)
10:03:21.988 [pimatic-pilight] connected to pilight-daemon
10:03:22.329 [pimatic-pilight] Lost connection to pilight-daemon
10:03:23.578 [pimatic-mobile-frontend] packing static assets
10:03:26.128 [pimatic-mobile-frontend] packing static assets finished
10:03:26.184 [pimatic-mobile-frontend] rendering html
10:04:27.381 [pimatic-mobile-frontend] rendering html finished
10:04:27.813 [pimatic-pilight] connected to pilight-daemon
10:04:27.855 [pimatic] listening for http-request on port 80...
10:04:28.037 [pimatic-pilight] Lost connection to pilight-daemon
10:04:38.081 [pimatic-pilight] connected to pilight-daemon
10:04:38.113 [pimatic-pilight] Lost connection to pilight-daemon
10:04:48.140 [pimatic-pilight] connected to pilight-daemon
10:04:48.169 [pimatic-pilight] Lost connection to pilight-daemon
10:04:58.196 [pimatic-pilight] connected to pilight-daemon
10:04:58.225 [pimatic-pilight] Lost connection to pilight-daemon
10:05:08.243 [pimatic-pilight] connected to pilight-daemon

**Comment by Yves911** [comment]
@sysdev41, we are looking for someone to update and maintain the pilight plugin for Pimatic at the moment.
I strongly encourage you to switch to homeduino https://github.com/pimatic/pimatic-homeduino rather pilight : it works extremely fine..

**Comment by sweetpi** [comment]
Please read #389.

**Comment by sysdev41** [comment]
Thanks for the answers. I am very sad about the facts, because i wanted to use pimatic in combination with pilight due to the graphing functionality (e.g. record some temperature sensors and display values over the time elapsed in a nice graph).

**Comment by Icesory** [comment]
Why you dont want use the pimatic-homeduino plugin?

**Comment by leader21** [comment]
Temp. Sensors like dht11/22 or ds18b20 are already supported by pimatic. Try to switch over to pimatic. Once your setup is done you will forget about pilight ;) for switching rf devices you can use the pimatic homeduino plugin. You can learn more at the how to section on forum.pimatic.org
if you need any help feel free to post your questions there. The pimatic community is continously growing and the support is good and quickly.
