### ISSUE TITLE
pimatic shell execute requires discrete setting

### ISSUE THREAD

**Issue by cklam2** [pimatic/pimatic#563]
Yesterday i updated the pimatic plugins. After restart all the shell execute items in my config don't work anymore. Seems that the option "discrete" is added which is not made optional.

Can it be made optional or do i need to change my config? And what does it do?

**Comment by sweetpi** [comment]
Could you post the error message you get?

**Comment by cklam2** [comment]
```23:57:52.211 [pimatic] debug: Error: Missing config entry discrete. ```
But see that you already made a change in the code. Will try it, thanks.

**Comment by cklam2** [comment]
The fix works, thanks!

**Comment by sweetpi** [comment]
you are welcome, thanks for reporting.
