### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#564]
When I use **date +%A** on command line I get the day of week in my language. When I use the same command in a ShellSensor it returns it in English. What must I do to get in my language too?

**Comment by sweetpi** [comment]
You have to set the envirements variables according to your language:

Determine your locals with `echo $LANG`

then wrap the `date` call into an script which sets the locals according to your language. For example:

```
#!/bin/bash
export LANG=de_DE.UTF-8
export LC_ALL=de_DE.UTF-8
date +%A
```

**Comment by Heizelmann** [comment]
I made these export commands in a command shell and then it works. No need to wrap it in the script. Thanks!
