### ISSUE TITLE
missing integrity value filter in pimatic-shell

### ISSUE THREAD

**Issue by betz0r** [pimatic/pimatic#566]
Is use some shell scripts to sensor values from my oilheater to pimatic but these values are not filtered by their integrity as I.e. in dhtxx protocol where way higher values then last values are ignored. I have not found anything in the docs or protocols. Is there a way to set this up?

**Comment by sweetpi** [comment]
It's currently not easily to filter the values directly. You would have to do it in your shell script. I will look if there is a easy solution for that.

**Comment by betz0r** [comment]
Ok thx for the response, but how is it done with the dhtxx sensor values retrieved from pilight-daemon?

**Comment by sweetpi** [comment]
There's some extra code in the pilight plugin. Please open a feature request in the forum if there's still interest.
