### ISSUE TITLE
Dont get any Signals from remote [NEW INSTALLATION]

### ISSUE THREAD

**Issue by Rantir** [pimatic/pimatic#573]
hey guys,

ive needed to reinstall my pi.

So i followed the steps and i can access the frontend.

Well but the homeduino dont get any signals by now.

I cant see them in the log message part 
it just displays:
Connected to Homeduino device.

when i use 
screen /dev/ttyUSB0 115200
i just get 
```
"ready"
```
and sometime later
```
PING
```
thats all.

That is my config.json file

```
cat config.json
{
  "//": "Please only change this file when pimatic is NOT running else pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 80
    },
    "debug": true,
    "logLevel": "debug",
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "UDONTKNOWJACK"
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "homeduino",
      "driver": "serialport",
      "driverOptions": {
        "serialDevice": "/dev/ttyUSB0",
        "baudrate": 115200
      },
      "receiverPin": 0,
      "transmitterPin": 4,
    },
    {
      "plugin": "mobile-frontend"
    }
  ],
  "devices": [
    {
      "id": "rfswitch",
      "name": "RFSwitch",
      "class": "HomeduinoRFSwitch",
      "protocols": [
        {
          "name": "switch1",
          "options": {
            "id": 42,
            "unit": 0
          }
        }
      ]
    }
  ],
  "rules": [],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": []
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "admin",
      "password": "ente",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}

```

**Comment by Icesory** [comment]
To test the arduino you must send this command
```
RF receive PIN
```
PIN must be replaced with number of the pin where the receiver is connected. 

Are you sure that the receiver works properly? 


And in your config is the authentication secret shown. This you should remove

**Comment by Rantir** [comment]
EDIT:

cant type without misstakes ;)

Well he sends ACK.

nothing else happens here nor in the WebGui log

**Comment by Yves911** [comment]
I think this is because https://github.com/pimatic/pimatic/issues/562#issuecomment-77739301 
Can you try and see if it solves your problem

**Comment by Rantir** [comment]
Well, just add this inside the honeduino part before the receiver part ?

**Comment by Yves911** [comment]
@Rantir you can insert start at the beginning of your config right after the "locale" thing for example

**Comment by Rantir** [comment]
@Yves911 Iam dump, soory.

Could you tell me please at which line i should enter:

"logLevel": "debug",


i dont find any locale part.

**Comment by Icesory** [comment]
In your config is this line already. 

Can you please post a picture of your hardware. Eventually is there a failure.

**Comment by Yves911** [comment]
@Rantir, here is the few first lines of my config
```
 {
  "settings": {
    "locale": "en",
    "debug": true,
    "logLevel": "debug",
    "httpServer": {
      "enabled": false,
      "port": 8091,
      "hostname": ""
    },
```
If you don't have any logLevel entry in your config, just add one in the settings session...

**Comment by Yves911** [comment]
@Rantir did you manage to get something in the log now?

**Comment by Rantir** [comment]
there is already logLevel : debug in line 9

about my soldering, ive connected gnd and power from the modules to the pi. as i did with the rapi b+ as well. could i connect power and gnd from the modules to the aduino as well?

**Comment by leader21** [comment]
> could i connect power and gnd from the modules to the aduino as well?

sure! no problems with that!
have a look here : http://forum.pimatic.org/topic/202/4-homeduino-433-mhz-sending-receiving-and-even-more/1

**Comment by Icesory** [comment]
No! 
When you use a Arduino, then you should power the receiver and transmitter by the arduino too! 
You work there with HF technics and there are good power supplies necessary. Don't make some strange ground loops etc. 
The other thing is, the arduino is 5V compatible the pi only 3,3 v

**Comment by Rantir** [comment]
Well how to wire the 5v and gnd to the aduino ? Ive got a Auino Nano here

btw the way i wired them worked with the rapi b+ without any problems, thats why i didnt changed it already.

**Comment by leader21** [comment]
check my above howto! there's all explained.
the nano has 5v and 3.3v output and gnd pins too.

> could i connect power and gnd from the modules to the aduino as well?

do you want to connect them in row? pi -> receiver/sender -> arduino?! NO that's no good! 
use the voltages provided by the nano. i got you wrong.

**Comment by Rantir** [comment]
Well i dont use any breadboard but just thoose jump wires.
are there more than one 5v pin on the nano ?

**Comment by Rantir** [comment]
Well i tryed to follow leader21's how to and build it again, but i got 2 errors:

´´´´

osmc@osmc:~/pimatic-app/homeduino$ sudo make upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [USER]               ARDMK_DIR = /home/osmc/pimatic-app/homeduino/arduino-mk
- [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 105
- [DEFAULT]            ARCHITECTURE =
- [DEFAULT]            VENDOR = arduino
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [USER]               USER_LIB_PATH = /home/osmc/pimatic-app/homeduino/libraries
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [USER]               BOARD_TAG = nano328
- [COMPUTED]           OBJDIR = build-nano328 (from BOARD_TAG)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD =
- [DEFAULT]            CXXFLAGS_STD =
- [COMPUTED]           DEVICE_PATH = /dev/ttyUSB0 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [USER]                 SerialCommand
- [USER]                 RFControl
- [USER]                 Keypad
- [USER]                 DHTlib
- [USER]                 Keypad/utility
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.3.4
- [COMPUTED]           CC_VERSION = 4.8.1 (avr-gcc)
-------------------------
mkdir -p build-nano328
make reset
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/bin/ard-reset-arduino  /dev/ttyUSB0
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
make do_upload
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -D -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -c arduino -b 57600 -P /dev/ttyUSB0 \
                -U flash:w:build-nano328/homeduino.hex:i
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00

avrdude done.  Thank you.

/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1292: recipe for target 'do_upload' failed
make[1]: *** [do_upload] Error 1
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1284: recipe for target 'upload' failed
make: *** [upload] Error 2
osmc@osmc:~/pimatic-app/homeduino$ avrdude: stk500_recv(): programmer is not responding
-bash: syntax error near unexpected token `('
osmc@osmc:~/pimatic-app/homeduino$ avrdude: stk500_recv(): programmer is not responding
-bash: syntax error near unexpected token `('
osmc@osmc:~/pimatic-app/homeduino$
´´´´

**Comment by Icesory** [comment]
Can you post the output from this command

```
dmesg | grep tty
```

The upload fails. Eventually is the comport wrong.

**Comment by Rantir** [comment]
osmc@osmc:~/pimatic-app/homeduino$ dmesg | grep tty
[    0.000549] console [tty0] enabled
[    0.746035] dev:f1: ttyAMA0 at MMIO 0x3f201000 (irq = 83, base_baud = 0) is a PL011 rev3
[   13.956440] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
[41421.908764] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[41421.908887] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[41422.077760] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[41424.115204] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
[43177.468442] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[43177.468561] ftdi_sio ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[43177.706349] ftdi_sio ttyUSB0: error from flowcontrol urb
[43177.708709] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[43179.735805] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
[43181.538738] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[43190.239352] usb 1-1.3: FTDI USB Serial Device converter now attached to ttyUSB0
osmc@osmc:~/pimatic-app/homeduino$

**Comment by Icesory** [comment]
You can try to press the reset button when the uploader tried to upload the hex.

**Comment by Rantir** [comment]
and how can I see if it worked?
Am 15.03.2015 00:32 schrieb "Ronny" <notifications@github.com>:

**Comment by Icesory** [comment]
When this lines are showed
```
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
```
In this time you must press the reset button. But it is possible that the FTDI Chip is a chines copy and don't work. Or on the Arduino isn't a Bootloader installed

**Comment by Rantir** [comment]
well i guess i got a chiniese one (was high rated nano on amazon, anyway)

´´´

osmc@osmc:~/pimatic-app/homeduino$ sudo make upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [USER]               ARDMK_DIR = /home/osmc/pimatic-app/homeduino/arduino-mk
- [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 105
- [DEFAULT]            ARCHITECTURE =
- [DEFAULT]            VENDOR = arduino
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [USER]               USER_LIB_PATH = /home/osmc/pimatic-app/homeduino/libraries
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [USER]               BOARD_TAG = nano328
- [COMPUTED]           OBJDIR = build-nano328 (from BOARD_TAG)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD =
- [DEFAULT]            CXXFLAGS_STD =
- [COMPUTED]           DEVICE_PATH = /dev/ttyUSB0 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [USER]                 SerialCommand
- [USER]                 RFControl
- [USER]                 Keypad
- [USER]                 DHTlib
- [USER]                 Keypad/utility
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.3.4
- [COMPUTED]           CC_VERSION = 4.8.1 (avr-gcc)
-------------------------
mkdir -p build-nano328
make reset
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/bin/ard-reset-arduino  /dev/ttyUSB0
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
make do_upload
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -D -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -c arduino -b 57600 -P /dev/ttyUSB0 \
                -U flash:w:build-nano328/homeduino.hex:i
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xe4
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xe4
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xe4
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xe4
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xe6

avrdude done.  Thank you.

/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1292: recipe for target 'do_upload' failed
make[1]: *** [do_upload] Error 1
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1284: recipe for target 'upload' failed
make: *** [upload] Error 2

´´´

**Comment by Rantir** [comment]
any idears ?

i still need a wire plan without a breadboard

**Comment by Icesory** [comment]
What is the problem with a plan on an breadboard?
Are you own a other arduino? Have you pressed the reset button while the upload procedure

**Comment by Rantir** [comment]
ive pressed the reset button and i also posted what the console says while
i pressed it.

i dont a bread board ;)
thats why i asked if there are More 5v Pins or if i need to solder somekind
of Y jumpwire
Am 18.03.2015 16:27 schrieb "Ronny" <notifications@github.com>:

**Comment by Icesory** [comment]
It depens of the arduino how much 5V pins are existing. But i think it should not be a problem to create a Y line for the power supply.

You must press and release the reset button while upload

**Comment by Rantir** [comment]
i will re try it
Am 18.03.2015 16:42 schrieb "Ronny" <notifications@github.com>:

**Comment by Rantir** [comment]
```
osmc@osmc:~/pimatic-app/homeduino$ sudo make upload
-------------------------
Arduino.mk Configuration:
- [AUTODETECTED]       CURRENT_OS = LINUX
- [USER]               ARDMK_DIR = /home/osmc/pimatic-app/homeduino/arduino-mk
- [AUTODETECTED]       ARDUINO_DIR = /usr/share/arduino
- [AUTODETECTED]       ARDUINO_VERSION = 105
- [DEFAULT]            ARCHITECTURE =
- [DEFAULT]            VENDOR = arduino
- [DEFAULT]            ARDUINO_SKETCHBOOK = /root/sketchbook
- [BUNDLED]            AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr (in Arduino distribution)
- [COMPUTED]           ARDUINO_LIB_PATH = /usr/share/arduino/libraries (from ARDUINO_DIR)
- [DEFAULT]            ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino//cores/arduino
- [COMPUTED]           ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino//variants (from ARDUINO_DIR)
- [COMPUTED]           BOARDS_TXT = /usr/share/arduino/hardware/arduino//boards.txt (from ARDUINO_DIR)
- [USER]               USER_LIB_PATH = /home/osmc/pimatic-app/homeduino/libraries
- [DEFAULT]            PRE_BUILD_HOOK = pre-build-hook.sh
- [USER]               BOARD_TAG = nano328
- [COMPUTED]           OBJDIR = build-nano328 (from BOARD_TAG)
- [DETECTED]           MONITOR_BAUDRATE = 115200  (in sketch)
- [DEFAULT]            OPTIMIZATION_LEVEL = s
- [DEFAULT]            MCU_FLAG_NAME = mmcu
- [DEFAULT]            CFLAGS_STD =
- [DEFAULT]            CXXFLAGS_STD =
- [COMPUTED]           DEVICE_PATH = /dev/ttyUSB0 (from MONITOR_PORT)
- [AUTODETECTED]       Size utility: AVR-aware for enhanced output
-
-                      ARDUINO_LIBS =
- [USER]                 SerialCommand
- [USER]                 RFControl
- [USER]                 Keypad
- [USER]                 DHTlib
- [USER]                 Keypad/utility
- [COMPUTED]           BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino//bootloaders (from ARDUINO_DIR)
- [COMPUTED]           ARDMK_VERSION = 1.3.4
- [COMPUTED]           CC_VERSION = 4.8.1 (avr-gcc)
-------------------------
mkdir -p build-nano328
make reset
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/bin/ard-reset-arduino  /dev/ttyUSB0
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
make do_upload
make[1]: Entering directory '/home/osmc/pimatic-app/homeduino'
/usr/share/arduino/hardware/tools/avr/../avrdude -q -V -D -p atmega328p -C /usr/share/arduino/hardware/tools/avr/../avrdude.conf -c arduino -b 57600 -P /dev/ttyUSB0 \
                -U flash:w:build-nano328/homeduino.hex:i
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
```

I pressed 1 sek and released it.
2 different LED on the aduino glowed

```
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xe6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xe6

avrdude done.  Thank you.

/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1292: recipe for target 'do_upload' failed
make[1]: *** [do_upload] Error 1
make[1]: Leaving directory '/home/osmc/pimatic-app/homeduino'
/home/osmc/pimatic-app/homeduino/arduino-mk/Arduino.mk:1284: recipe for target 'upload' failed
make: *** [upload] Error 2
osmc@osmc:~/pimatic-app/homeduino$
```

**Comment by Icesory** [comment]
How you flashed the Homeduino at the first time? It looks that your bootloader is dead.

**Comment by Rantir** [comment]
well i used a homeduino guide, dont know exactly what I did.

anyway to reanimate him?
Am 18.03.2015 18:11 schrieb "Ronny" <notifications@github.com>:

**Comment by leader21** [comment]
how's your pi powered? 
maybe there's an issue with low voltage and the arduino isn't able to work properly.

**Comment by Rantir** [comment]
with this power supply.

well is there a way to install the bootloader via commandline/ via the pi ?

**Comment by Icesory** [comment]
To flash the Bootloader isnt easy.
Look there
http://www.instructables.com/id/How-To-Burn-a-Bootloader-to-Clone-Arduino-Nano-30/?lang=de

**Comment by Rantir** [comment]
Well btw this is the one i got.

http://www.amazon.de/gp/product/B00PL70XWW?psc=1&redirect=true&ref_=oh_aui_detailpage_o03_s00

**Comment by leader21** [comment]
hm... very strange thing. there's a question on the amazon page a little bit below that points out to install a driver. the ftdi on this nano is a fake one and causes trouble (as you are experiencing now). FTDI has provided a driver for these fake chips that made the fake nanos unusable. don't know what happened to your nano but if you bought it with amazon prime - send it back as defective or whatever! maybe this chip has already been sold before and was used/killed by another person that received it before you did and sent it back (who knows ...)

what did you change? you say that you used the b+. do you have the pi2 now? could be that the new kernel doesn't support this chip anymore (maybe...). just some thoughts on that. 
i suggest to buy a nano with ch340 chipset. 

if you're from germany or you can read german you might be interested in this : http://www.heise.de/make/meldung/Treiber-gegen-gefaelschte-Chips-FTDI-ruft-Fake-Killer-zurueck-2435079.html

**Comment by Rantir** [comment]
Well i used a pi b+ with this aduino for mounths without any problems, thats why  wonder.

Also the nano is not dead as u can see by the ack.

Well what i did:
I got the pi2 installed osmc and connected the nano the sameway i did before.
and followed the pimatic guide.

About the PI2: as far as i remebered there ae already ppl around which uses th pi 2

**Comment by incmve** [comment]
Have you tried flashing it with the B+ again or with Windows?

**Comment by Rantir** [comment]
i tryed to flash it with the pi2.

**Comment by Rantir** [comment]
Well the good old turn it on and off again helped.

it fresh flashed lets see if it can clear my problems by now

**Comment by sweetpi** [comment]
@Rantir Please ask you open questions in the forum.
