### ISSUE TITLE
SystemSensor multiple diskusage

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#574]
hi guys,
if I is use one system sensor to monitor multiple hard drives. i can see only one variable in gui. 

I suspect this is an bug.    

## settings in config:
{
      "class": "SystemSensor",
      "id": "disk-usage",
      "name": "root opt data DB",
      "attributes": [
        {
          "name": "diskusage",
          "path": "/"
        },
        {
          "name": "diskusage",
          "path": "/opt"
        },
        {
          "name": "diskusage",
          "path": "/mnt/data"
        },
        {
          "name": "dbsize",
          "interval": 1800000
        }
      ]
    }

# output in gui
root opt data DB         DISK XX.XX% DB XX.XXMB

**Comment by leader21** [comment]
you are naming the variable all the same.
i suggest using diskusage1 diskusage2 diskusage3 or root opt data instead

```
{
"class": "SystemSensor",
"id": "disk-usage",
"name": "root opt data DB",
"attributes": [
{
"name": "root",
"path": "/"
},
{
"name": "opt",
"path": "/opt"
},
{
"name": "data",
"path": "/mnt/data"
},
{
"name": "dbsize",
"interval": 1800000
}
]
}

**Comment by n3roGit** [comment]
aaaahhhh okay!!!


but now i get the following error:
error [pimatic]: Error loading device disk-usage: Cannot read property '1' of null

**Comment by leader21** [comment]
oha! my bad, i guess your setup from the first post was correct and i told you some crap ... sorry!!
seems like the diskusage cannot be in an array and so you'll have to create several devices for each directory to be monitored.
maybe @sweetpi can check this?

**Comment by sweetpi** [comment]
Currently only one diskusage property per `SystemSensor` is possible. So you need to create one device per directory you want to monitor. This may change in the future.

**Comment by sweetpi** [comment]
Closing this, please make a Feature Request for this Feature in the forum, if there is still interest for it.
