### ISSUE TITLE
A uncaught exception occured: Error: socket hang up

### ISSUE THREAD

**Issue by WimUtTwente** [pimatic/pimatic#577]
14:33:51.648 [pimatic] error: A uncaught exception occured: Error: socket hang up
14:33:51.648 [pimatic] error:>    at createHangUpError (http.js:1472:15)
14:33:51.648 [pimatic] error:>    at Socket.socketCloseListener (http.js:1522:23)
14:33:51.648 [pimatic] error:>    at Socket.EventEmitter.emit (events.js:117:20)
14:33:51.648 [pimatic] error:>    at TCP.close (net.js:466:12)
14:33:51.648 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
14:33:51.657 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!

I use this plugin
14:39:35.596 [pimatic] info: loading plugin: "pimatic-log-reader" (0.8.2)
14:39:35.953 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
14:39:36.186 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.45)
14:39:38.017 [pimatic] info: loading plugin: "pimatic-gpio" (0.8.3)
14:39:38.555 [pimatic] info: loading plugin: "pimatic-openweather" (0.8.3)
14:39:39.238 [pimatic] info: loading plugin: "pimatic-mail" (0.8.2)
14:39:41.298 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.12)
14:39:41.796 [pimatic] info: loading plugin: "pimatic-dhtxx" (0.8.4)
14:39:41.959 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
14:39:42.439 [pimatic] info: loading plugin: "pimatic-ds18b20" (0.8.3)
14:39:42.622 [pimatic] info: loading plugin: "pimatic-athome" (0.8.2)
14:39:43.485 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.10)

**Comment by WimUtTwente** [comment]
After restart:
14:40:35.553 [pimatic] info: listening for http-request on port 7104...
14:40:35.669 [pimatic-homeduino] info: Connected to homeduino device.
14:44:27.476 [pimatic] error: A uncaught exception occured: Error: read ECONNRESET
14:44:27.476 [pimatic] error:>    at errnoException (net.js:901:11)
14:44:27.476 [pimatic] error:>    at TCP.onread (net.js:556:19)
14:44:27.476 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
14:44:27.488 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
14:44:27.527 [pimatic] error: A uncaught exception occured: Error: socket hang up
14:44:27.527 [pimatic] error:>    at createHangUpError (http.js:1472:15)
14:44:27.527 [pimatic] error:>    at Socket.socketCloseListener (http.js:1522:23)
14:44:27.527 [pimatic] error:>    at Socket.EventEmitter.emit (events.js:117:20)
14:44:27.527 [pimatic] error:>    at TCP.close (net.js:466:12)
14:44:27.527 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
14:44:27.536 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!

**Comment by WimUtTwente** [comment]
After removing  plugin: "pimatic-openweather" (0.8.3) and install  "pimatic-weather" (0.8.11) 
no error more.

**Comment by sweetpi** [comment]
Thanks for reporting. Please report the problem in https://github.com/josecastroleon/pimatic-openweather/ so that it can be fixed in the module.
