### ISSUE TITLE
weather status comparison

### ISSUE THREAD

**Issue by rikki78** [pimatic/pimatic#580]
Hi,

I'm trying to set a value based on the current weather. i.e. if it is cloudy set a value to 30, if it is clear set it to 10.
Using this rule
status of Het weer in Amsterdam is not "Clear" and status of Het weer in Amsterdam is not "Fair" and status of Het weer in Amsterdam is not "Partly Cloudy"
is always true, even if it is Clear, Fair or Partly Cloudy.
Am I doing something wrong?

thanks

**Comment by sweetpi** [comment]
The rule looks good. I did a quick test here and it worked. Could you post the full rule(s)?

**Comment by rikki78** [comment]
Hi sweetpi thanks for the quick reply. There are more rules but they are not related to this. Do you want me to post them as well? I've changed to rule a bit but still no success. Even with only one comparison it doesn't work. When using "equals" it does work ok but than I don't have the result I want (or is an else statement possible somehow?)

This is the rule:

{
      "id": "wee4",
      "name": "weer bewolkt 2",
      "rule": "if status of Het weer in Amsterdam is not \"Partly Cloudy\" and status of Het weer in Amsterdam is not \"Clear\" then set $time-before-sunset to 30",
      "active": true,
      "logging": true
    }

**Comment by rikki78** [comment]
@sweetpi Did you have the possibility to have a look at these rules? Is there a test I can do to further investigate what is happening?

**Comment by mggg** [comment]
Hi, I'm in the same situation.
Some versions ago the rules based on weather status worked fine.
I'm using the weather plugin: 
```
    {
      "id": "curweather",
      "class": "WeatherDevice",
      "name": "curLondon",
      "location": "London",
      "degreeType": "C",
      "timeout": 300000
    }
    {
      "id": "noon-weekend",
      "name": "Noon-Weekend",
      "rule": "if its solar noon and $curweather.status is not \"Cloudy\" then lower cShutter1 down",
      "active": true,
      "logging": true
    }
```
Also I logged the status with another rule, And I get nothing:
```
log \"$curweather.status $curweather.temperature\"
23:02:27.963 [pimatic] info: rule weather-cloudy: Unknown 0
```
If I check the events page, all seems ok...

**Comment by sweebee** [comment]
Same here: If $weather.status = "Bewolkt" isnt working.

**Comment by Sjeff** [comment]
I had the same and removed all the " in all my rules. that seems to help

**Comment by sweebee** [comment]
I can't remove the ". I get a error if i save the rule

**Comment by mggg** [comment]
seems something related to how the system gets the info from the attributes
When I log the variable it gets 0 for numbers (temperature), or "Unknown" for strings, but the device shows the info ok... the odd thing is that this was working sometime ago

**Comment by sweetpi** [comment]
Oh ok, seems I did not test with the npm version, but with my local copy. I submitted a patch for this in the past: https://github.com/josecastroleon/pimatic-weather/commit/096eeefcdad9279682994ce9f104e040d0754e87

It seems that @josecastroleon did not merge it into his master branch and released a new version without the fix. @josecastroleon could you please merge it into master and release a new version with the fix?

**Comment by sweetpi** [comment]
The plugin does not work anymore because the weather service was shutdown.
