### ISSUE TITLE
Error while updating from 0.8.57 to 0.8.60

### ISSUE THREAD

**Issue by Sjeff** [pimatic/pimatic#581]
Hi just try to update pimatic from 0.8.57 to 0.8.60 and i get the following error : http://pastebin.com/J2qAgF0K

**Comment by WimUtTwente** [comment]
update pimatic from 0.8.58, to 0.8.60 gives the same error
15:02:28.947 [pimatic] error: Cannot read property '1' of null
tested with two raspberries

**Comment by elektronaut69** [comment]
Same here.

**Comment by incmve** [comment]
Yup

**Comment by sweetpi** [comment]
You've to update manually. I did break the updater in 0.8.57. You can use the new install script:

```
sudo apt-get install wget curl
cd /home/pi
sudo curl -s https://raw.githubusercontent.com/pimatic/pimatic/master/install/install-production | bash /dev/stdin pimatic-app
```

**Comment by elektronaut69** [comment]
Hm. Doing that broke my installation. pimatic is not starting any more. Resoring my backup now ;-)

**Comment by WimUtTwente** [comment]
Everything works 100%
as a focal point "cd /home/pi" only for install in the workmap   "home/pi/pimatic-app"
i use "home/pimatic-app"
At one of the two raspberry the config.json was maimed or back to defoult
luckily I had backed

**Comment by sweetpi** [comment]
I removed the copy of the default_config from the install script. Thought it wouldn't replace if the file already exists. Big thanks for the feedback.

**Comment by Sjeff** [comment]
Everything works again ! thanks !

**Comment by incmve** [comment]
> You've to update manually. I did break the updater in 0.8.57. You can use the new install script:

didn't work for me I used <code>sudo npm install</code> inside the pimatic dir.
