### ISSUE TITLE
Button in pimatic

### ISSUE THREAD

**Issue by p24matze** [pimatic/pimatic#582]
Can someone explain how can I get a Button (not a switch) in pimatic?
Can someone give me the device code for the config.json?
Thank u!

**Comment by Icesory** [comment]
What do you want to make with this button?

**Comment by p24matze** [comment]
Ich will set a rule on it, all devices off with on touch

**Comment by Icesory** [comment]
That isn't possible at the moment. 
When you want to switch RF devices than you can use a HomeduinoRFButtonsDevice with multiple protocols.

**Comment by leader21** [comment]
hmmm. i wonder if this wouldn't be possible with a buttons device and a rule that switches the devices off?

**Comment by Icesory** [comment]
I am not sure but exist a "if button is pressed"?

**Comment by leader21** [comment]
yes it does exist! therefore a rule like "IF offbutton is pressed THEN switch off TV and switch off Radio and switch off Light" should work. 
using this for switching my wifi led device
![](https://cloud.githubusercontent.com/assets/8620305/5584641/c6ee900a-9093-11e4-9524-79611aa6ba71.jpg)

**Comment by leader21** [comment]
use a buttons device like that : 
```    {
      "id": "",
      "name": "All On Off",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "all-off",
          "text": "On"
        },
        {
          "id": "all-on",
          "text": "Off"
        }
      ]
    },
```
then create your rules accordingly

**Comment by p24matze** [comment]
Yes it works pretty well, thank u!
