### ISSUE TITLE
 [pimatic-openweather] Error: socket hang up at createHangUpError 

### ISSUE THREAD

**Issue by dj-dano** [pimatic/pimatic#584]
error [pimatic]: A uncaught exception occured: Error: socket hang up at createHangUpError (http.js:1472:15) at Socket.socketCloseListener (http.js:1522:23) at Socket.EventEmitter.emit (events.js:117:20) at TCP.close (net.js:466:12) This is most probably a bug in pimatic or in a module, please report it!19:46:36

error [pimatic]: A uncaught exception occured: Error: connect ETIMEDOUT at errnoException (net.js:901:11) at Object.afterConnect [as oncomplete] (net.js:892:19) This is most probably a bug in pimatic or in a module, please report it!

**Comment by sweetpi** [comment]
Thanks for reporting, do you use an weather plugin?

**Comment by dj-dano** [comment]
yes i use pimatic-open-weahter plugin

**Comment by sweetpi** [comment]
Ok, thats a problem with a library used in the plugin, that does not handle errors probably. I've submitted a pull request so we can fix the issue if the lib gets updates: https://github.com/baslr/node-openweathermap/pull/5

**Comment by sweetpi** [comment]
Should be fixes in the newest release of pimatic-openweather.
