### ISSUE TITLE
Getting started with development for pimatic / Arduino

### ISSUE THREAD

**Issue by AvdH** [pimatic/pimatic#590]
Hi, all.
I'm new at pimatic and arduino, but i have much experience in programming in C and Java. 
The only coffee I know is the one in a cup and i have plenty of experience with that. But i'm willing to learn the other one is necessary. If needed I'm also willing to participate in further development of pimatic.
I'm planning on building my own arduino sensors and using RF (for now, later possible Ethernet) to connect to homeduino / pimatic. Can you give me some hints so I can kickstart my development (besides studying the homeduino code)

**Comment by sweetpi** [comment]
Hi,

that sound great :) What RF technology do you want to use? 

If you want to use 433 Mhz and want to get started with 433mhz hardware development its best to  take a look at

* The [gerneric-rfbox from incmve](https://github.com/incmve/generic-rfbox)
* The used [processing pipeline](https://github.com/pimatic/rfcontroljs#the-processing-pipeline) of rfcontroljs (used by homeduino)
* and finaly the [implementation of the generic protocol](https://github.com/pimatic/rfcontroljs/blob/master/src/protocols/generic.coffee)

If you need any help, feel free to ask. Coffeescript is hard to read, when you are used to C/Java Syntax but belief me you get addicted to it like you get addicted to coffee, if you used it for a while. Just be sure to read the [manual page](http://coffeescript.org/) if there's any syntax you don't know.
