### ISSUE TITLE
pimatic play pause

### ISSUE THREAD

**Issue by bommey** [pimatic/pimatic#591]
Hi there,

i want to pause some music files by pressing dummybuttons, which are played bei pimatic using play "....mp3"

How can i do that?

**Comment by sweetpi** [comment]
hi,

pimatic-play can't do that, it is build to play short sounds like a dorbell. Buf you can use mpd with the [pimatic-mpd](http://pimatic.org/plugins/pimatic-mpd/) plugin.

**Comment by bommey** [comment]
when in want to install mpd-plugin i use
"mpd-player"

this is the message log i get

09:50:50.269 [pimatic] Installing: "mpd-player"
09:50:59.371 [pimatic, npm] http GET https://registry.npmjs.org/pimatic-mpd-player
09:51:00.431 [pimatic, npm] http 404 https://registry.npmjs.org/pimatic-mpd-player
09:51:00.600 [pimatic, npm] ERR! 404 'pimatic-mpd-player' is not in the npm registry.
09:51:00.704 [pimatic, npm] ERR! 404 You should bug the author to publish it
09:51:00.786 [pimatic, npm] ERR! 404
09:51:00.866 [pimatic, npm] ERR! 404 Note that you can also install from a
09:51:00.943 [pimatic, npm] ERR! 404 tarball, folder, or http url, or git url.
09:51:00.985 [pimatic, npm] ERR! System Linux 3.12.28+
09:51:01.026 [pimatic, npm] ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-mpd-player"
09:51:01.066 [pimatic, npm] ERR! cwd /usr/local/pimatic-app/pimatic-app
09:51:01.108 [pimatic, npm] ERR! node -v v0.10.24
09:51:01.150 [pimatic, npm] ERR! npm -v 1.3.21
09:51:01.191 [pimatic, npm] ERR! code E404
09:51:01.239 [pimatic, npm] ERR!
09:51:01.297 [pimatic, npm] ERR! Additional logging details can be found in:
09:51:01.337 [pimatic, npm] ERR!     /usr/local/pimatic-app/pimatic-app/npm-debug.log
09:51:01.377 [pimatic, npm] ERR! not ok code 0
09:51:01.496 [pimatic] Error running "npm install pimatic-mpd-player"

can you help me?

**Comment by leader21** [comment]
sure! the plugin is named ```pimatic-mpd```
so go ahead with this and have fun :)

**Comment by bommey** [comment]
Now i have tried,   
  {
      "plugin": "mpd"
    }
with success @ installing, 

but now the problem is, that i get bad request while using.

hier is the log for starting pimatic


18:05:37.043 [pimatic] loading plugin: "pimatic-play" (0.8.0)
18:05:37.543 [pimatic] loading plugin: "pimatic-mpd" (0.8.1)
...
18:05:45.916 [pimatic-mpd] undefined
18:05:46.822 [pimatic-mobile-frontend] packing static assets
18:05:49.864 [pimatic-mobile-frontend] packing static assets finished
18:05:49.946 [pimatic-mobile-frontend] rendering html

**Comment by sweetpi** [comment]
Please post your issue in in the troubleshooting section of the forum: http://forum.pimatic.org/category/17/troubleshooting

Thanks.
