### ISSUE TITLE
Dist package not found error

### ISSUE THREAD

**Issue by spicchio72** [pimatic/pimatic#595]
I installed Pimatic under a Debian chroot in a XPenology NAS setup (thanks to obi tutorial: http://forum.pimatic.org/topic/65/bye-bye-pi-hello-synology). Installation went fine for both npm package and pimatic compiled the needed files and created the sql database, but everytime I start the server I have some errors:

root@SYNOLOGY:/home/pi/pimatic-app/node_modules/pimatic# pimatic.js
20:16:27.702 2015-03-15 Sunday
20:16:29.549 [pimatic] Starting pimatic version 0.8.60
20:16:36.555 [pimatic] dist package not found
20:16:36.566 [pimatic] dist package not found
20:16:36.570 [pimatic] dist package not found
20:16:36.586 [pimatic] Listening for HTTP-request on port 1081...

If I connect through the browser to the 1081 port I get this error:

Cannot GET /

It looks like Pimatic can't get plugin packages from the dist server, but the NAS has full internet access. I tried uninstalling and reinstalling pimatic-app both with "rm -rf" and "npm uninstall" but without success, any help?

**Comment by spicchio72** [comment]
Solved. I had to manually install the missing default plugins (mobile-frontend and cron) right after installing pimatic and before actually running it for the first time. Pimatic is running fine now without errors and with full web access.

I'll explore it and try to configure some devices to find if it can be used succesfully in this xpenology nas setup.

**Comment by sweetpi** [comment]
That is fixed in the newest version, it now falls back to npm install if the packages isn't available precompiled. 

Btw. Which arch does your NAS have?

```
node -e "console.log(process.arch)"
```

**Comment by spicchio72** [comment]
Thanks. Reply to the command is "ia32".

2015-03-19 21:59 GMT+01:00 sweet pi - sweet home <notifications@github.com>:
