### ISSUE TITLE
dns.js error

### ISSUE THREAD

**Issue by spicchio72** [pimatic/pimatic#596]
After 3-4 hours running pimatic I have this error and pimatic.js is shut down:

17:14:19.913 [pimatic] A uncaught exception occured: Error: getaddrinfo ENOTFOUND
17:14:19.913 [pimatic]>    at errnoException (dns.js:37:11)
17:14:19.913 [pimatic]>    at Object.onanswer [as oncomplete] (dns.js:124:16)
17:14:19.913 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!

Reported since pimatic itself asks to do it!

**Comment by sweetpi** [comment]
Thanks for reporting. Do you use the openweather plugin?

I think its the same problem like in https://github.com/pimatic/pimatic/issues/584 A fix is on the way :)

**Comment by spicchio72** [comment]
Yes, I have the openweather plugin installed and pimatic on ia32 arch. Looks like the issue will be fixed in next build... Thanks!

**Comment by sweetpi** [comment]
Should be fixes in the newest release of pimatic-openweather.
