### ISSUE TITLE
[pimatic-mobile-frontend] Page switchs to the right when scrolling up on iPhone

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#597]
When I'm on a large page where I can scroll sometimes the left page jumps into the screen. Than I can still scroll the right side, but when I lift my finger the screen completely switchs to the left page. See the screenshot. 
Sometimes the page switches to the left without half switching before. 
![](http://i.imgur.com/mqVSk3k.jpg)

**Comment by sweetpi** [comment]
Hm, strange. I remember we had added a higher offset till the page swipe is triggered and I can't reproduce this in the emulator. What iOS-Device do you use?

**Comment by Xento** [comment]
Yeah I know.

I tested some more. 
It only happens when I scroll the page down and then it only switches to the left page never the right. 

I'm using safari on an iPhone 5.

**Comment by Xento** [comment]
Correction it doesn't matter if I scroll down or up.

**Comment by Xento** [comment]
Maybe it woud be a workaround when you can disable swipe gestures in the config.

**Comment by Xento** [comment]
I think there is something wrong with the calculation of base.newRelativeX.
I put an alert in function dragEnd to monitor this value.
Sometimes when i onl scrol down or up, this value is 100 or more.

**Comment by sweetpi** [comment]
I would prefer solving the problem. Would be cool if you find out, what the problem is.

**Comment by Xento** [comment]
Seems that a wrong touch or something is detected.
I tried to fix that. I tried to detect when a user wants to scroll and than disable the swipe functionality.
Seems to work on my iPhone.
https://github.com/Xento/pimatic-mobile-frontend/commit/914cedb0ddef4b947f06a62d89c49f12ad327c70

**Comment by Xento** [comment]
Is there a way to stop minimizing the javascripts?
I set up a mac os in a vmware, so I can debug the scripts.

**Comment by sweetpi** [comment]
set "mode" setting of the mobile frontend to "development" and clear all caches / use an incognito tab,

**Comment by Xento** [comment]
That worked.
Maybe I fixed the issue.
When you want to scroll up or down and you hit the screen very shortly, the dragMove don't fires. Only start and end.
In dragEnd you don't check if the user swiped over the minimum value.
I will checkin my changes tomorrow after some more testing, than you can see.

Do you have an iPhone?
Maybe you could setup a vmware with Mac OS like my for future testing.

**Comment by sweetpi** [comment]
Thanks for the fix. I've released a version with your fix. Please reopen if the problem appears again.
