### ISSUE TITLE
Pimatic-max rename opened / closed

### ISSUE THREAD

**Issue by p24matze** [pimatic/pimatic#598]
Where can I rename the status "opened" to "offen" and the status "closed" to "geschlossen"?

**Comment by leader21** [comment]
hey p24matze,
please post upcomming questions at the pimatic forum : http://forum.pimatic.org
but to answer your question - you'll have to add ``` "locale": "de",``` to the settings section of your config.json. 
looks like this :
{
  "settings": {
    "locale": "de",
    "authentication": {
      "secret": "blablabla"
    },
    "httpServer": {
      "enabled": true,
      "port": 80
    },
and so on ...
```

**Comment by sweetpi** [comment]
That looks not like a good idea ...

**Comment by leader21** [comment]
ok forget what i said! just listen to sweetpi, he's the code guru :)

**Comment by sweetpi** [comment]
We need an translation guru as well. Looks like its time to finally cleanup the translation files.

**Comment by p24matze** [comment]
I changed pimatic to german here:
/home/pimatic-app/node_modules/pimatic/config-schema.coffee
but pimatic-max is not included.

**Comment by p24matze** [comment]
Somebody has a solution? :)

**Comment by sweetpi** [comment]
I published a update, that should include a fix.

**Comment by p24matze** [comment]
nice, thank you very much!
