### ISSUE TITLE
 Updating plugin pimatic-mobile-frontend

### ISSUE THREAD

**Issue by thomasvt1** [pimatic/pimatic#599]
Pimatic update screen;

```pimatic is up to date.
Found update for pimatic-mobile-frontend: current version is 0.8.50, latest version is: 0.8.53```


But when the update button is pressed it says:
```error: Error Updating plugin pimatic-mobile-frontend: dist package not found```

and the button changes to "Updates were successful. Please restart pimatic"

**Comment by leader21** [comment]
you can try to delete the pimatic-mobile-frontend folder in the node_modules directory and restart pimatic. the mobile frontend will be automatically installed again.

**Comment by sweetpi** [comment]
Just wait some time, the new update system packs the new release, this needs some time. I need to handle this better...

**Comment by thomasvt1** [comment]
It's fixed, thanks a lot!
