### ISSUE TITLE
Rule description missing spaces

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#603]
Not really a bug but a little flaw:

after IF and before/after THEN a space is missing.

![](https://s3.amazonaws.com/f.cl.ly/items/1z3n2v14093k2T3Q3j2H/Schermafbeelding%202015-03-20%20om%2016.17.27.png)

**Comment by sweetpi** [comment]
thanks for reporting, should be fixed in newest version.

**Comment by Yves911** [comment]
Solved confirm (i did a refresh of the page after installing latest version of pimatic-mobile-frontend)
