### ISSUE TITLE
[bug] No pop-up info when adding rule

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#604]
When i add a rule i normally get a pop-up when rule options. But its completely gone now.

I also tried this, but its not working?

IF $light1.state = "false" THEN turn light1 on

Browser: Safari Mac OS

**Comment by koffienl** [comment]
Noticed the same. just after updating pimatic today.

**Comment by KlausFeld** [comment]
At my system the same.

**Comment by KlausFeld** [comment]
Testet with Chrome, Firefox and IE. Hard to handle the rules without the auto complete function.

**Comment by Yves911** [comment]
Solved confirm
