### ISSUE TITLE
Installing pimatic-ping

### ISSUE THREAD

**Issue by thomasvt1** [pimatic/pimatic#605]
After running ```npm install pimatic-ping```

It wont install, and I get this error;

http://pastebin.com/WNvNvCfn

npm-debug.log;

http://paste.ubuntu.com/10637470/

**Comment by mggg** [comment]
same problem here... seems raw-socket installation
And also with when installing pimatic-sysinfo pluing. On this case, the error comes with nsutil installation

**Comment by Icesory** [comment]
Normally you don't need to install a plugin. You must just put it into the config. Pimatic install it by it self.

**Comment by thomasvt1** [comment]
@Icesory That didn't work, so I tried using npm

**Comment by sweetpi** [comment]
You need to install/use node v0.10. Version 0.12 is not supported yet by the dependencies used...

**Comment by mggg** [comment]
Thanks for your answer!!!
I don't thought it would be incompatibility issues using a newer version...
Could be the [tutorial](http://pimatic.org/guide/getting-started/installation/) modified to note the recommended or tested version?

**Comment by mggg** [comment]
Hi @sweetpi 
Checked!
Trying to downgrade node version with n and nvm not easy for me, so I reinstall raspbian with node v0.10.24 and everything went fine... both plugins, ping and sysinfo working like a charm!

Than you again!

**Comment by sweetpi** [comment]
Great. I've added a notice to the guide.
