### ISSUE TITLE
cant install dhtxx

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#606]
Hey Guys,

i get this Error by installing the dhtxx addon:

npm install pimatic-dhtxx
npm http GET https://registry.npmjs.org/pimatic-dhtxx
npm http 304 https://registry.npmjs.org/pimatic-dhtxx
npm http GET https://registry.npmjs.org/node-dht-sensor
npm http 304 https://registry.npmjs.org/node-dht-sensor

> node-dht-sensor@0.0.5 install /opt/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor
> node-gyp rebuild

make: Entering directory '/opt/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor/build'
  CXX(target) Release/obj.target/node-dht-sensor/node-dht-sensor.o
../node-dht-sensor.cpp:21:21: fatal error: bcm2835.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
node-dht-sensor.target.mk:80: recipe for target 'Release/obj.target/node-dht-sensor/node-dht-sensor.o' failed
make: *** [Release/obj.target/node-dht-sensor/node-dht-sensor.o] Error 1
make: Leaving directory '/opt/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/pimatic-app/node_modules/pimatic-dhtxx/node_modules/node-dht-sensor
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! node-dht-sensor@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-dht-sensor@0.0.5 install script.
npm ERR! This is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-dhtxx"
npm ERR! cwd /opt/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/pimatic-app/npm-debug.log
npm ERR! not ok code 0

Any ideas?

**Comment by n3roGit** [comment]
hmm :-(

**Comment by leader21** [comment]
don't know if this helps but did you install the bcm2835 library ?
check here http://forum.pimatic.org/topic/138/solved-unable-to-get-dht22-to-work/7

**Comment by n3roGit** [comment]
Perfect =) BIG THX! It works fine :)
