### ISSUE TITLE
DS18B20 "unknown" since latest update

### ISSUE THREAD

**Issue by olihaeg** [pimatic/pimatic#609]
Hello,
since the pimatic + plugin update at 21-03-2015 my temperature sensors report "unknown".
I have not found any changes in the how to sections so I left the implementation as it was before the update.
What do I have to change to get back values from my temp sensors?
Greetings
Oliver

**Comment by KlausFeld** [comment]
Hi, same problem here.
Even the downgrade to DS18B20 plugin ver 0.8.3 gives no success. It's seems a problem with the mobile frontend? The plugin gives the error "Not an number".

**Comment by skipper79** [comment]
I have the same problem

**Comment by demlak** [comment]
same here.. 
> npm install pimatic-ds18b20@0.8.3

fixed it

**Comment by incmve** [comment]
#593

**Comment by sweetpi** [comment]
I've released pimatic-ds18b20 that should finally fix any trouble. Sorry for the inconvenience. I totaly fail here with testing and update management.
