### ISSUE TITLE
[pimatic-mobile-frontend] PIR devices wrong height (Safari Mac OS)

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#610]
The PIR devices are higher than all other devices, so arrangement is wrong.
![](http://cl.ly/image/0B31043s1G1s/Schermafbeelding%202015-03-22%20om%2011.47.10.png)

**Comment by Yves911** [comment]
@sweebee i don't have this trouble on my side maybe you can try to refresh your cache

**Comment by sweebee** [comment]
Looks like its safari specific. Working fine in Chrome.

**Comment by sweebee** [comment]
Don't know what the css class is and where the css file is.
!()[http://cl.ly/image/1d0J2w2w0e2U/Schermafbeelding%202015-03-22%20om%2014.05.13.png]
