### ISSUE TITLE
Max-Plugin

### ISSUE THREAD

**Issue by p24matze** [pimatic/pimatic#611]
I have 2 questions :)
When will you publishing the translation for the window feature opened/closed sweetpi? :)
And can I limiting the manuel heating correctness to 30? I can go up to 100 and this is to high.
Thanks 4 all

**Comment by sweebee** [comment]
Do you mean the open/closed label? You can rename it yourself in the config:

```
"xOpenLabel": "YOUR OPEN NAME",
"xClosedLabel": "YOUR CLOSED NAME",
```

**Comment by p24matze** [comment]
I put it in the de translation file. It doesnt work. I mean the window contact closed and opened

**Comment by Icesory** [comment]
Put it direct to the device
```
{ 
  "id": "window-bathroom",
  "class": "MaxContactSensor", 
  "name": "Bathroom Window",
  "rfAddress": "12345df",
  "xOpenLabel": "YOUR OPEN NAME",
  "xClosedLabel": "YOUR CLOSED NAME"
}
```

**Comment by p24matze** [comment]
Nothing is happend :/
![sh](https://cloud.githubusercontent.com/assets/11429831/6790701/cfc70584-d1a9-11e4-8e37-27d11d49b2c8.JPG)

**Comment by sweebee** [comment]
Try to clean your cache or refresh the page

**Comment by p24matze** [comment]
didnt work

**Comment by sweebee** [comment]
Can you post your config devices?

**Comment by p24matze** [comment]
{
      "id": "f_wohnzimmer",
      "class": "MaxContactSensor",
      "name": "Fenster",
      "rfAddress": "109698",
      "xOpenLabel": "offen",
      "xClosedLabel": "geschlossen"
    },
    {
      "id": "f_schlafzimmer",
      "class": "MaxContactSensor",
      "name": "Fenster",
      "rfAddress": "1097fc",
      "xOpenLabel": "offen",
      "xClosedLabel": "geschlossen"
    },
    {

**Comment by sweebee** [comment]
I made a little mistake, its xOpened instead of xOpen (sorry). Try this:

```
{
  "id": "f_wohnzimmer",
  "class": "MaxContactSensor",
  "name": "Fenster",
  "rfAddress": "109698",
  "xOpenedLabel": "offen",
  "xClosedLabel": "geschlossen"
},
{
  "id": "f_schlafzimmer",
  "class": "MaxContactSensor",
  "name": "Fenster",
  "rfAddress": "1097fc",
  "xOpenedLabel": "offen",
  "xClosedLabel": "geschlossen"
},
```

**Comment by p24matze** [comment]
its not working, i have no idea

**Comment by sweebee** [comment]
Wait a sec, it looks like the piratic-max plugin doesn't support it. (homeduino does). @sweetpi has to add it.

**Comment by p24matze** [comment]
that makes sense. thank u!

**Comment by sweebee** [comment]
I created a pull request to add the function. You could wait till sweetpi accept it or add it yourself:

Edit the device-config-schema.coffee in: pimatic-app > node_modules > pimatic-max > device-config-schema.coffee

search for (line 36/37)
```
MaxContactSensor: {
    title: "MaxContactSensor config options"
```
And add ```extensions: ["xClosedLabel", "xOpenedLabel"]``` 

Should look like this:
```
 MaxContactSensor: {
    title: "MaxContactSensor config options"
    extensions: ["xClosedLabel", "xOpenedLabel"]
    type: "object"
    properties:
      rfAddress:
        description: "The Device RF address"
        type: "string"
        default: ""
  }
```

**Comment by sweetpi** [comment]
@p24matze I released the patch for translation already, but another bug prevented it from working. With the new version is should be working without additional config. 

Please make a seperate issue for the second question.
