### ISSUE TITLE
pimatic-enigma2

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#612]
I created a small plugin to interact with a linux tv receiver.
At the moment it can only send messages to your tv screen.
You can althought send a question to your tv and do something with the answer, but this is not implemented yet.
It would be possible to switch your tv on, mute it, change the volume or channel and much more.

https://github.com/Xento/pimatic-enigma2

**Comment by Xento** [comment]
I have one problem.
I get this error message in pimatic log: rule tv-test3 error executing an action: Cannot read property '1' of null
I don't know what could cause this error because everything seems to work.

**Comment by sweetpi** [comment]
Could you update to the newest version or post the full stack trace. There was a bug so that assertion errors were reported this strange way.

**Comment by Xento** [comment]
Now I get this error: rule tv-test3 error executing an action: Array.isArray result
Don't know where it comes from.

**Comment by Xento** [comment]
You can although send questions to your tv with a specified timeout.
You have to ask the receiver if the user answered and than it gives you the answer or tells you that the user didn't answered in time.
So how should I implement it?

Rule: if Doorbell is turned on and tv-question message:"open door?" is true
This construct requires that the first expression is evaluated at first and then the others.
Aditionally it has to wait for the answer until the execution continues.

An other way would be to send the question at the execution of a rule:
send tv-question message:"Open door?" 
And than create an other rule:
If tv-question question equals "Open door?" and tv-question answer is true

**Comment by sweetpi** [comment]
@Xento Could you post the open questions on the forum. I want to clean up the issue section here. Thanks.
