### ISSUE TITLE
Pidfile exists, but process is dead.

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#613]
Hey :)

since this day pimatic dont start. after a moment the process is simply dead.

The logging is already set to debug and pimatic and the mobile-frontend is reinstalled.

does anyone have an idea?

00:23:38.192 [pimatic] info: Starting pimatic version 0.8.63
coffee-cache: compiling coffee-script file "config-schema.coffee"...Done
00:23:40.709 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.5)
00:23:40.928 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.58)
coffee-cache: compiling coffee-script file "mobile-frontend.coffee"...Done
coffee-cache: compiling coffee-script file "mobile-frontend-config-schema.coffee"...Done
00:23:43.229 [pimatic] info: Loading plugin: "pimatic-homeduino" (0.8.47)
00:23:44.503 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.3)
00:23:44.590 [pimatic] info: Loading plugin: "pimatic-links" (0.8.5)

**Comment by sweetpi** [comment]
The pimatic-dhtxx plugin is broken. Remove it, restart and it should be fine again.

**Comment by n3roGit** [comment]
This plugin isnt  installed on this pi. 

Only the following :

pimatic                  pimatic-ping
pimatic-athome           pimatic-play
pimatic-cron             pimatic-pushover
pimatic-fritz            pimatic-shell-execute
pimatic-gpio             pimatic-sunrise
pimatic-homeduino        pimatic-sysinfo
pimatic-kodi             pimatic-voice-recognition
pimatic-links            pimatic-weather
pimatic-mail             pimatic-z-way
pimatic-mobile-frontend  sqlite3

**Comment by sweetpi** [comment]
Anything in the log if you don't start it in service mode (`sudo ./node_modules/pimatic/pimatic.js`)?

**Comment by n3roGit** [comment]
aaaaaahhhhhh!
now i have an error output:

09:46:49.910 [pimatic] rule schlafzimmer-tv-aus: turned TV off
09:46:50.019 [pimatic-fritz] Re-establishing session at http://fritz.box
09:46:50.104 [pimatic] Error on evaluation of rule condition of rule abend-an-test: Command failed:
09:46:50.110 [pimatic] Error: Command failed:
09:46:50.110 [pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
09:46:50.110 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
09:46:50.110 [pimatic]>    at maybeClose (child_process.js:735:16)
09:46:50.110 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
09:46:50.110 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:46:50.110 [pimatic]>    at Pipe.close (net.js:466:12)
09:46:50.126 [pimatic] Could not update variable motion2.motion2: Command failed:
09:46:50.129 [pimatic] Error: Command failed:
09:46:50.129 [pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
09:46:50.129 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
09:46:50.129 [pimatic]>    at maybeClose (child_process.js:735:16)
09:46:50.129 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
09:46:50.129 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:46:50.129 [pimatic]>    at Pipe.close (net.js:466:12)
09:46:50.146 [pimatic] Could not get attribute value of motion2.motion2: Command failed:
09:46:50.150 [pimatic] Error: Command failed:
09:46:50.150 [pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
09:46:50.150 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
09:46:50.150 [pimatic]>    at maybeClose (child_process.js:735:16)
09:46:50.150 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
09:46:50.150 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:46:50.150 [pimatic]>    at Pipe.close (net.js:466:12)
Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
09:46:50.182 [pimatic] Could not update variable motion.motion: Command failed:
09:46:50.185 [pimatic] Error: Command failed:
09:46:50.185 [pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
09:46:50.185 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
09:46:50.185 [pimatic]>    at maybeClose (child_process.js:735:16)
09:46:50.185 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
09:46:50.185 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:46:50.185 [pimatic]>    at Pipe.close (net.js:466:12)
09:46:50.201 [pimatic] Could not get attribute value of motion.motion: Command failed:
09:46:50.203 [pimatic] Error: Command failed:
09:46:50.203 [pimatic]>    at ChildProcess.exithandler (child_process.js:637:15)
09:46:50.203 [pimatic]>    at ChildProcess.EventEmitter.emit (events.js:98:17)
09:46:50.203 [pimatic]>    at maybeClose (child_process.js:735:16)
09:46:50.203 [pimatic]>    at Socket.<anonymous> (child_process.js:948:11)
09:46:50.203 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
09:46:50.203 [pimatic]>    at Pipe.close (net.js:466:12)
Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
09:46:50.561 [pimatic-mobile-frontend] packing static assets
09:46:51.793 [pimatic-mobile-frontend] packing static assets finished
09:46:51.805 [pimatic-mobile-frontend] rendering html
09:46:58.525 [pimatic-mobile-frontend] rendering html finished
09:46:58.575 [pimatic] Could not listen on port 443. Error: listen EADDRINUSE. Is a server already running?
09:46:58.587 [pimatic] Error: listen EADDRINUSE
09:46:58.587 [pimatic]>    at errnoException (net.js:901:11)
09:46:58.587 [pimatic]>    at Server._listen2 (net.js:1039:14)
09:46:58.587 [pimatic]>    at listen (net.js:1061:10)
09:46:58.587 [pimatic]>    at net.js:1135:9
09:46:58.587 [pimatic]>    at dns.js:72:18
09:46:58.587 [pimatic]>    at process._tickCallback (node.js:415:13)

/opt/pimatic-app/node_modules/pimatic/lib/framework.coffee:627
            throw err;
                  ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)

**Comment by sweetpi** [comment]
You have another webserver running on port 443 or another pimatic instance is already running?

```
ps alx|grep node
```

**Comment by n3roGit** [comment]
ahh. a mongoose webserver is running on my server. 

this could be from the ZWave server.

THX!!! :)
