### ISSUE TITLE
Displaying graphs broken on latest Chrome dev

### ISSUE THREAD

**Issue by demichiel** [pimatic/pimatic#617]
I've attached 3 screenshots from my local testing setup. Making graphs seems to be broken on the latest version of Chrome on ChromeOS (First two screenshots) but still works on Android (Last screenshot)

Some quick googling turned up this: [Webogram github issue](https://github.com/zhukov/webogram/issues/731)

Which points out that something changed in Chrome's console.memory property. 

If I can provide you with any logs or data, feel free to ask. I don't have any real javascript/node experience so I'm afraid I can't be of any more help.

ChromeOS Chrome version: Version 43.0.2334.0 dev
Android Chrome version: Version 41.0.2272.96

**Edit**: So I think I've narrowed it down to [this commit](https://github.com/paulmillr/console-polyfill/commit/b50590c90da0d37246eed06f3fcf991d394ea980) in the console-polyfill package which is used by the dygraph package which in turn produces the graphs on the mobile frontend plugin. I'll try to patch it in manually later on this evening.

**Edit 2** Created [Pull request](https://github.com/pimatic/pimatic-mobile-frontend/pull/5) in the pimatic-mobile-frontend repo.

![screenshot 2015-03-25 at 13 08 42](https://cloud.githubusercontent.com/assets/573269/6824190/20116236-d2f0-11e4-9296-8fde925cc7c4.png)
![screenshot 2015-03-25 at 13 08 30](https://cloud.githubusercontent.com/assets/573269/6824189/200e7dbe-d2f0-11e4-96bc-3226044c6a8d.png)

![screenshot3](https://cloud.githubusercontent.com/assets/573269/6824022/3b63300c-d2ee-11e4-8da4-6d0ca615b7a8.png)

**Comment by sweetpi** [comment]
Thanks for the patch.

**Comment by demichiel** [comment]
Happy to help! (and made my first github commit!)
