### ISSUE TITLE
DS18b20 one fail value of 85°C after reboot

### ISSUE THREAD

**Issue by demlak** [pimatic/pimatic#619]
hi,
after a reboot, i get exactly _ONE_ fail-value for each ds18b20 sensor of exactly 85°C in my database..
im not sure if this is a pimatic based problem. maybe this depends on my weird 1-wire network.. i´ve got a star-network with different wire length.. 
1. - 1 Meter
2. - 4 Meter
3. - 10 Meter
All are cat5 cables.. 

but.. maybe it´s a problem of the 1-wire kernel modules?

im lost i´n debugging this.. but the final result is allways this fail-value of 85°C after booting the RPi.

as a workaround i stop pimatic to edit the database.. but that´s very uncormfortable.

any idea on this?

**Comment by incmve** [comment]
I got my ds18b20 on cat5 aswell but I have no problems.
What kernel are you running on the Pi?

**Comment by demlak** [comment]
> \# cat /proc/version
Linux version 3.18.7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015

**Comment by incmve** [comment]
I think the "problem" is the kernel
see http://forum.pimatic.org/topic/55/solved-ds1820-no-dir-in-w1-devices

**Comment by demlak** [comment]
ahh.. ok.. i did forget to say, that there is only one failure value.. but the messurment works perfect after this.. i don´t have a problem with 1-wire sensors after this one 85°C value.. 
they are "online".. no problems with the filesystem etc..

**Comment by demlak** [comment]
how many sensors do you use? currently im thinking about a problem on current.. maybe the RPi can´t drive that much sensors.. AND 433mhz receiver/sender at the same time.. (all are on 5v)

**Comment by incmve** [comment]
I got 1 sensors on a 30 meter cat5 cable, on the same cable I power a double relay.
On another cable around 20 meters I got another sensor, all from the same Pi.
On the Pi there is a second relay also powered by the Pi.

I did distribute them acros both 5v pins.

When I upgraded my Pi to the 3.18 kernel I got errors on GPIO pins when I restarted the Pi.
After the restart I restarted pimatic and everything is working normal.

I downgraded the kernel and my problems are gone.

**Comment by koffienl** [comment]
Did you connect 3 different wires to one GPIO, or is it one long cable with several sensors on the same line ?

**Comment by incmve** [comment]
First post ;)
> i´ve got a star-network with different wire length.. 
1. - 1 Meter
2. - 4 Meter
3. - 10 Meter

**Comment by sweetpi** [comment]
@demlak Any updates?

**Comment by demlak** [comment]
i can´t reproduce this at the moment.. maybe the high cpu usage of the 433mhz receiver was the problem.. 
i removed the receiver last week.. and i was never rebooting since then.. so i just rebooted now 2 times to test..

**Comment by sweetpi** [comment]
I think the patch should have solved the problem. Please reopen if there are still issues.
