### ISSUE TITLE
[pimatic-max] Not working on a NAS

### ISSUE THREAD

**Issue by bboab** [pimatic/pimatic#622]
Hi, 
I'm running pimatic on a NAS DS 214play in a debian enviroment. The pimatic software worked fine until I tried to use the max plugin:

22:31:26.646 2015-03-26 Thursday
22:31:30.466 [pimatic] Starting pimatic version 0.8.64
22:31:31.355 [pimatic] Loading plugin: "pimatic-cron" (0.8.5)
22:31:31.784 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.8.60)
22:31:32.784 [pimatic] Loading plugin: "pimatic-max" (0.8.12)
22:31:32.852 [pimatic-cron] the time is: Thu Mar 26 2015 22:31:32 GMT+0100 (CET)
22:31:33.061 [pimatic-mobile-frontend] packing static assets
22:31:33.444 [pimatic-mobile-frontend] packing static assets finished
22:31:33.452 [pimatic-mobile-frontend] rendering html
22:31:37.385 [pimatic-mobile-frontend] rendering html finished
22:31:37.415 [pimatic] Listening for HTTP-request on port 1337...
22:31:37.438 [pimatic] A uncaught exception occured: TypeError: First argument needs to be a number, array or string.
22:31:37.438 [pimatic]>    at new Buffer (buffer.js:188:15)
22:31:37.438 [pimatic]>    at MaxCube.parseCommandMetadata (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:172:24)
22:31:37.438 [pimatic]>    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:109:19)
22:31:37.438 [pimatic]>    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:66:26)
22:31:37.438 [pimatic]>    at Array.forEach (native)
22:31:37.438 [pimatic]>    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:61:8)
22:31:37.438 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
22:31:37.438 [pimatic]>    at Socket.<anonymous> (_stream_readable.js:746:14)
22:31:37.438 [pimatic]>    at Socket.EventEmitter.emit (events.js:92:17)
22:31:37.438 [pimatic]>    at emitReadable_ (_stream_readable.js:408:10)
22:31:37.438 [pimatic]>    at emitReadable (_stream_readable.js:404:5)
22:31:37.438 [pimatic]>    at readableAddChunk (_stream_readable.js:165:9)
22:31:37.438 [pimatic]>    at Socket.Readable.push (_stream_readable.js:127:10)
22:31:37.438 [pimatic]>    at TCP.onread (net.js:526:21)
22:31:37.438 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
22:31:37.443 [pimatic] shutting pimatic down...
22:31:37.448 [pimatic] Flushing database to disk, please wait...
22:31:37.604 [pimatic] Flushing database to disk, please wait... Done.
22:31:37.607 [pimatic] exiting...

**Comment by sweetpi** [comment]
What is the version of the max software you used to setup the cube?

**Comment by mwittig** [comment]
@sweetpi I think this one can be closed as @bboab has not replied for 5 months. Most likely this configuration error.
