### ISSUE TITLE
[pimatic-ping] No hostname resolution

### ISSUE THREAD

**Issue by dandresm** [pimatic/pimatic#623]
I have realized that pimatic-ping doesn't resolve host names. It only works with IPs. I don't know if it is a bug or if it is really not implemented. It would be interesting to resolve host names due to my network configuration, because I have DHCP enabled.
Thanks in advance!

**Comment by leader21** [comment]
it's not implemented.
there's a feature request at the forum where you can vote for.
http://forum.pimatic.org/topic/261/pimatic-ping-with-dns

**Comment by dandresm** [comment]
Thanks for the info! I have just voted for it. I hope it gets implemented...
