### ISSUE TITLE
uncaught exception occured: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by NietGiftig** [pimatic/pimatic#625]
I'm not sure what the problem is, got it today after an update.
pimatic works sometime for a while, sometimes the error comes instantly

````
[90m18:18:02.487[39m[32m [pimatic][39m[90m [39m[31mA uncaught exception occured: Error: connect ETIMEDOUT[39m
[90m18:18:02.487[39m[32m [pimatic][39m[90m>[39m[31m    at errnoException (net.js:901:11)[39m
[90m18:18:02.487[39m[32m [pimatic][39m[90m>[39m[31m    at Object.afterConnect [as oncomplete] (net.js:892:19)[39m
[90m18:18:02.487[39m[32m [pimatic][39m[90m>[39m[31m This is most probably a bug in pimatic or in a module, please report it![39m
[90m18:18:02.497[39m[32m [pimatic][39m[90m [39m[33mshutting pimatic down...[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m [39m[31mA uncaught exception occured: Error: socket hang up[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m>[39m[31m    at createHangUpError (http.js:1472:15)[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m>[39m[31m    at Socket.socketCloseListener (http.js:1522:23)[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m>[39m[31m    at Socket.EventEmitter.emit (events.js:117:20)[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m>[39m[31m    at TCP.close (net.js:466:12)[39m
[90m18:18:02.516[39m[32m [pimatic][39m[90m>[39m[31m This is most probably a bug in pimatic or in a module, please report it![39m
[90m18:18:02.524[39m[32m [pimatic][39m[90m [39m[33mshutting pimatic down...[39m
[90m18:18:02.541[39m[32m [pimatic][39m[90m [39mFlushing database to disk, please wait...
[90m18:18:03.064[39m[32m [pimatic][39m[90m [39mFlushing database to disk, please wait... Done.
[90m18:18:03.069[39m[32m [pimatic][39m[90m [39mexiting...
````

**Comment by dandresm** [comment]
I have the same problem. Pimatic works, but the error occurs randomly.

**Comment by leader21** [comment]
having a similar issue after updating. Don't exactly know which plugins have been updated but i remember that i uploaded the new homeduino lib  at the nano yesterday evening and updated all for update available plugins.

running pimatic 0.8.65 and homeduino 0.8.50 now and the latest homeduino lib on the nano.
pimatic is still working and i've not detected any malfunction by now except the openweather plugin from josecastroleon. it shows only values of 0

![](http://www.youscreen.de/ygdmilwl78.jpg)

and here's the error log from pimatic
![](http://www.youscreen.de/rxpixkhm44.jpg)

**Comment by NietGiftig** [comment]
Leader21 wrote : but i remember that i uploaded the new homeduino lib at the nano

I forgot to tell that I did the same

**Comment by sweetpi** [comment]
@NietGiftig Do you use the openweather-plugin?

**Comment by NietGiftig** [comment]
@sweetpi 
Yes I have the openweather plugin installed.
I'm just beginning to explore the working of pimatic.
Because pimatic did not run anymore, i did a reinstall of pimatic yesterday afternoon.
Have pimatic raspi on for 24 hours now and everything works again, with the same config.json.
Maybe the DDOS atack on github was interfering with my update.

**Comment by sweetpi** [comment]
The openweather plugin lacks proper error handing, so this errors show up with something wents wrong while fetching weather infos. You can ignore the message. pimatic does not shut down automatically if it runs as a service.

**Comment by NietGiftig** [comment]
I have it run from the terminal via putty , so I can see whats going on.
And then it shuts down.
I will remove openweather for now, because I'm just trying out how pimatics works with my 
433mhz and 768mhz interfaces

**Comment by sweetpi** [comment]
Should be fixes in the newest release of pimatic-openweather.
