### ISSUE TITLE
Error getting weather data

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#630]
I just updated the weather plugin but it won't update the weather:

```
error [pimatic]: Could not get attribute value of Deurningen.humidity: Request failed (406)
18:07:10error [pimatic]: Could not get attribute value of Deurningen.temperature: Request failed (406)
18:07:10error [pimatic]: Could not get attribute value of Deurningen.windspeed: Request failed (406)
18:07:10error [pimatic]: Could not get attribute value of Deurningen.status: Request failed (406)
18:07:10error [pimatic-weather]: Request failed (406)
```

**Comment by WimUtTwente** [comment]
Displayed weather ok but getting this error:
11:25:39debug [pimatic-weather]: Error: Request failed (406) at maybeWrapAsError (/home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:68:12) at /home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_resolver.js:41:50 at Request._callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/lib/weather.js:46:41) at Request.self.callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:344:22) at Request.EventEmitter.emit (events.js:98:17) at Request.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1239:14) at Request.EventEmitter.emit (events.js:117:20) at IncomingMessage.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1187:12) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)

11:24:49debug [pimatic-weather]: Error: Request failed (406) at maybeWrapAsError (/home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:68:12) at /home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_resolver.js:41:50 at Request._callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/lib/weather.js:46:41) at Request.self.callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:344:22) at Request.EventEmitter.emit (events.js:98:17) at Request.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1239:14) at Request.EventEmitter.emit (events.js:117:20) at IncomingMessage.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1187:12) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)
debug [pimatic-weather]: Error: Request failed (406) at maybeWrapAsError (/home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:68:12) at /home/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_resolver.js:41:50 at Request._callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/lib/weather.js:46:41) at Request.self.callback (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:344:22) at Request.EventEmitter.emit (events.js:98:17) at Request.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1239:14) at Request.EventEmitter.emit (events.js:117:20) at IncomingMessage.<anonymous> (/home/pimatic-app/node_modules/pimatic-weather/node_modules/weather-js/node_modules/request/request.js:1187:12) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)

**Comment by pimagical** [comment]
Use Pimatic-OpenWeather plugin

https://github.com/josecastroleon/pimatic-weather/issues/13#issuecomment-89509907
