### ISSUE TITLE
help alecto ws 4500

### ISSUE THREAD

**Issue by homone73** [pimatic/pimatic#631]
hello.
I saw that you open a post for the device alecto ws4500.
I need help ..
I can not set it up in any way with my router ...
I have tried many soluzioni..ma nothing fails to assign an IP address.
if you can help me I would be grateful.
Thank you very much

**Comment by incmve** [comment]
https://github.com/pimatic/rfcontroljs/issues/13#issuecomment-90416420

**Comment by sweetpi** [comment]
Sounds not like a pimatic issue :). Please ask in the troubleshooting section of the forum, if you still need help.
