### ISSUE TITLE
[pimatic] pimatic starting event not working

### ISSUE THREAD

**Issue by dandresm** [pimatic/pimatic#633]
Hi!

I have a rule which uses Pimatic starting event to push a message when pimatic starts. It worked well, until I changed some device ids. Then it stopped working. 

I have realized that the error ocurrs only when there are database errors, because after removing missing devices (previous ids) it works again.

Hope this helps to fix the issue...

**Comment by sweetpi** [comment]
Could you give some more info?

1. How does it fail, errors in the log?
2. What did you change?

**Comment by dandresm** [comment]
These are the error messages while starting pimatic:

* 10:08:50.251 [pimatic] rule push-pimatic-starting error executing an action: socket hang up
* 10:08:50.285 [pimatic] Error on evaluation of rule condition of rule push-pimatic-starging: socket hang up

And this is the rule sintax:
* if pimatic is starting then push title:\"Pimatic\" message:\"Pimatic starting\"

**Comment by Yves911** [comment]
Maybe push mechanism is not started yet, could you try with 
if pimatic is starting then push title:\"Pimatic\" message:\"Pimatic starting\" after 2 minutes

**Comment by dandresm** [comment]
Pushing the message after 2 minutes, as Ives911 proposed, works fine. I have also tried it with 30 seconds and it is enough.
Thanks!

**Comment by Yves911** [comment]
Okay great, @dandresm can you close this issue ?
