### ISSUE TITLE
pimatic-homeduino stops working after some minutes

### ISSUE THREAD

**Issue by KlausFeld** [pimatic/pimatic#634]
Hi,

my homeduino stops working after some minutes, here is the log:

15:13:05.405 [pimatic-homeduino] debug: data: "RF receive 512 1928 3880 9184 0 0 0 0 01020102020101020202020102010101010101010202020101010202010102010102020203"
15:13:05.409 [pimatic-homeduino] debug: received: [ 512, 1928, 3880, 9184 ] 01020102020101020202020102010101010101010202020101010202010102010102020203
15:13:05.414 [pimatic-homeduino] debug: weather1:  { id: 158,
15:13:05.414 [pimatic-homeduino] debug:>  channel: 1,
15:13:05.414 [pimatic-homeduino] debug:>  temperature: 22.7,
15:13:05.414 [pimatic-homeduino] debug:>  humidity: 39,
15:13:05.414 [pimatic-homeduino] debug:>  lowBattery: false }
15:13:05.505 [pimatic-homeduino] debug: weather5:  { id: 154, lowBattery: true, avgAirspeed: 15.2 }
15:13:05.928 [pimatic-homeduino] debug: data: "RF receive 512 1924 3880 9188 0 0 0 0 01020102020101020202020102010101010101010202020101010202010102010102020203"
15:13:05.932 [pimatic-homeduino] debug: received: [ 512, 1924, 3880, 9188 ] 01020102020101020202020102010101010101010202020101010202010102010102020203
15:13:05.935 [pimatic-homeduino] debug: weather1:  { id: 158,
15:13:05.935 [pimatic-homeduino] debug:>  channel: 1,
15:13:05.935 [pimatic-homeduino] debug:>  temperature: 22.7,
15:13:05.935 [pimatic-homeduino] debug:>  humidity: 39,
15:13:05.935 [pimatic-homeduino] debug:>  lowBattery: false }
15:13:05.938 [pimatic-homeduino] debug: weather5:  { id: 154, lowBattery: true, avgAirspeed: 15.2 }
15:13:40.415 [pimatic-volkszaehler] debug: GET http://192.168.1.204/middleware.php/data/1cbdebd0-cf4f-11e4-be24-a93000519f89.json?from=now
15:13:40.423 [pimatic-volkszaehler] debug: GET http://192.168.1.204/middleware.php/data/a528a3a0-bac8-11e4-9d42-8bf3a653c2e6.json?from=now

When I restart pimatic it starts working, but also homeduino died after some minutes,
I upload today the last Version of homeduino to my adruino nano.
Sending and recieving works fine, so programming the sketch must be succeessfull, I think.

When the rf Transmitter and Sender are connected directly to the raspberry it works fine, no complications. But then I have the Problem I must use serveral time the Switch to Switch the lamp on.

What can I do?

Best Regards,

Klaus

**Comment by KlausFeld** [comment]
Hi, I still have the Problems with the homeduino plugin and the arduino nano. My log tells this:

Disconnect completed
 11:12:23.513 [pimatic-homeduino] warn: Couldn't connect (Serialport not open.), retrying...
 11:12:23.521 [pimatic-homeduino] warn: Couldn't connect (Serialport not open.), retrying...

What can I check?

**Comment by incmve** [comment]
What type of Pi are you using and your power adapter?
Could be a power issue
https://projects.drogon.net/testing-setting-the-usb-current-limiter-on-the-raspberry-pi-b/

**Comment by KlausFeld** [comment]
I'm using the PI2, can that be a problem?
I have done apt-get update, upgrade and rpi-update.
I'm using a 2A power supply original from farnell.

**Comment by sweetpi** [comment]
I think its a power issue, too. Did you messure the voltate at the arduino?

**Comment by KlausFeld** [comment]
It's about 4,77V.
Maybe there is a Problem with the kernel 3.18 and not original ftdi Chips?
I found i smiliare Problem here:

http://www.raspberrypi.org/forums/viewtopic.php?p=680665

Here  CapnBry has the same Problem. And I found the message in my syslog too.
What kernel and raspberry do you use? Original Nano or clone?
I'm using this nano: http://www.amazon.de/gp/product/B00PL70XWW?psc=1&redirect=true&ref_=oh_aui_detailpage_o07_s00

**Comment by leader21** [comment]
maybe problems with fake FTDI chip?!
the nanos with ch340 chips run perfectly without issues here.

**Comment by incmve** [comment]
Try adding this to  <code>/boot/config.txt</code> and reboot
```
safe_mode_gpio=4
max_usb_current=1
```
I had problems with strange USB reactions to

**Comment by Icesory** [comment]
Can you post this? 
```
Dmesg | grep tty
```

**Comment by KlausFeld** [comment]
Hi, i changed the nano with the ftdi to a version with the ch340 chip and now it works since 10 hours without any problems. It's definitive a problem with the ftdi chip, because I changed nothing else.
Thx for your support!
