### ISSUE TITLE
Different Memory values in the Shell-execute and Sysinfo plugins

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic#635]
I have memory values that are different in the pimatic-shell-execute and pimatic-sysinfo plugins. What is the right system memory value?

My values are:
pimatic-shell-execute "Memory Usage": 472 MB
pimatic-sysinfo "MEM": 188.46 MB

Pimatic-shell-execute plugin device:
```
{
  "id": "mem-usage",
  "name": "Memory Usage",
  "class": "ShellSensor",
  "attributeName": "mem-usage",
  "attributeType": "number",
  "attributeUnit": "MB",
  "command": "free -m | awk '$5 ~ /[0-9.]+/ { print $3 }'",
  "interval": 60000
}
```
Pimatic-sysinfo plugin device:
```
{
  "class": "SystemSensor",
  "id": "syssensor",
  "name": "System",
  "attributes": [
    {
      "name": "cpu"
    },
    {
      "name": "memory"
    },
    {
      "name": "diskusage",
      "path": "/"
    }
  ]
}
```

**Comment by sweetpi** [comment]
It depends what "used memory" you want to count. Your ShellSensor additional counts kernel cache memory that will be released if it is needed for programs. It does not make much sense to count theses, because the kernel will always try to keep the cached filled.

```
% free
             total       used       free     shared    buffers     cached
Mem:      24683904   20746840    3937064     254920    1072508   13894892
-/+ buffers/cache:    5779440   18904464
Swap:      4194236        136    4194100
```
> To parse this, the first line of numbers (Mem:) lists total memory, used and free memory and the usage of shared, buffers and filesystem caches. In this line used includes the buffers and cache and this impacts free. This is not your "true" free memory because the system will dump cache if needed to satisfy allocation requests. The next line gives us the actual used and free memory as if there were no buffers or cache.

Source: http://unix.stackexchange.com/questions/152299/how-to-get-memory-usedram-used-using-linux-command
