### ISSUE TITLE
DHTSensor only get 0

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#636]
Hey guy's, 

Since the switch to pimatic-dht-sensors I get only "0" back from my sensor. 

Wiringpi is installed and the log looks ok:
[pimatic] info: New device "dht22"...

Any ideas? 

Regards 
n3ro

**Comment by n3roGit** [comment]
Any ideas? :)

**Comment by muhagl** [comment]
Hi,
is the pin number ok?
"pin": 1,   and not: "gpio": 17,
The Plugin uses the Wiring Pi pin numbers!
This was my failure.
Regards

**Comment by n3roGit** [comment]
Hey :) i use gpio 4.

http://wiringpi.com/wp-content/uploads/2013/03/gpio1.png

I trink this is right.

**Comment by n3roGit** [comment]
Aaahhh Pin 7 works!
