### ISSUE TITLE
could DS18B20 plugin omit 85° readouts

### ISSUE THREAD

**Issue by christophfroehlich** [pimatic/pimatic#637]
I have two DS18B20-par in parasitic mode and problems with the readouts, where every (let's say) 10th readout is 85°C. This can be be because of a lack of energy during the conversion or whatever (hardware) problem with the device, which I cannot solve here.
I could live with the lack of some readouts: Would it be possible to discard the readout without any error message saved? Maybe another option/device for this "robust" readout, and keep the configuration how it is now for debugging/other usages.
Precisely said: I'm sure it is possible, but I'm not familiar with javascript, json,.. to implement it on my own and kindly ask for your help, at it doesn't seem to be a big deal.

And just for my information: how does the plugin/pimatic schedule the readouts? If I configure the two sensors with a 10s period, when does it readout the values? every 5 seconds one sensor, or is this behavior some kind of random? Maybe does a distinct schedule solve this issue as well..

**Comment by sweetpi** [comment]
> I could live with the lack of some readouts: Would it be possible to discard the readout without any error message saved?

I've added a dicard for this value: https://github.com/pimatic/pimatic-ds18b20/commit/6fca4494e252b2684474ee4c8d97b486aef6a3c3

The readouts are done in parallel, but it just reads the virtual device file, so the kernel driver should handle that correctly.

**Comment by christophfroehlich** [comment]
Thanks a lot for the (almost) instant fix! Seems to work, I will check it the next days..
