### ISSUE TITLE
Pimatic Plugin for Video Player

### ISSUE THREAD

**Issue by bommey** [pimatic/pimatic#639]
Hi there,

i want to you pimatic for playing videos like playing audios with mpd player oder pimatic play.
Is there any possibility to play a defined video file without using shell command?

If i have to use shell command, can anyone tell me about a possible player and the neccessary syntax?

Thank you in advance

bommey

**Comment by leader21** [comment]
hi bommey, 
please use the pimatic forum for asking your questions : http://forum.pimatic.org
here you will find a growing community and also help for many previously asked questions.

git is now for bugs and major issues.
thanks a lot!
