### ISSUE TITLE
After Raspbian update pimatic menu updates function doesn't work any more.

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#642]
I update raspbian to 

Linux raspberrypi 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux

and after that the menu updates function of pimatic 0.8.66 give the following error:

 error [pimatic]: { name: 'StatusCodeError', statusCode: 504, message: '504 - <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n', error: '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n', options: { uri: 'http://api.pimatic.org/plugins', callback: undefined, simple: true, resolveWithFullResponse: false }, response: { _readableState: { highWaterMark: 16384, buffer: [], length: 0, pipes: null, pipesCount: 0, flowing: false, ended: true, endEmitted: true, reading: false, calledRead: true, sync: false, needReadable: true, emittedReadable: false, readableListening: false, objectMode: false, defaultEncoding: 'utf8', ranOut: false, awaitDrain: 0, readingMore: false, decoder: null, encoding: null }, readable: false, domain: null, _events: { end: [Object], readable: [Function], close: [Object], data: [Function], error: [Function] }, _maxListeners: 10, socket: { _connecting: false, _handle: null, _readableState: [Object], readable: false, domain: null, _events: [Object], _maxListeners: 0, _writableState: [Object], writable: false, allowHalfOpen: false, onend: null, destroyed: true, errorEmitted: false, bytesRead: 361, _bytesDispatched: 72, _pendingData: null, _pendingEncoding: '', parser: null, _httpMessage: [Object], ondata: null, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, connection: { _connecting: false, _handle: null, _readableState: [Object], readable: false, domain: null, _events: [Object], _maxListeners: 0, _writableState: [Object], writable: false, allowHalfOpen: false, onend: null, destroyed: true, errorEmitted: false, bytesRead: 361, _bytesDispatched: 72, _pendingData: null, _pendingEncoding: '', parser: null, _httpMessage: [Object], ondata: null, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, httpVersion: '1.1', complete: true, headers: { server: 'nginx/1.4.6 (Ubuntu)', date: 'Mon, 27 Apr 2015 20:11:59 GMT', 'content-type': 'text/html', 'content-length': '191', connection: 'keep-alive' }, trailers: {}, _pendings: [], _pendingIndex: 0, url: '', method: null, statusCode: 504, client: { _connecting: false, _handle: null, _readableState: [Object], readable: false, domain: null, _events: [Object], _maxListeners: 0, _writableState: [Object], writable: false, allowHalfOpen: false, onend: null, destroyed: true, errorEmitted: false, bytesRead: 361, _bytesDispatched: 72, _pendingData: null, _pendingEncoding: '', parser: null, _httpMessage: [Object], ondata: null, _idleNext: null, _idlePrev: null, _idleTimeout: -1 }, _consuming: true, _dumped: false, httpVersionMajor: 1, httpVersionMinor: 1, upgrade: false, req: { domain: null, _events: [Object], _maxListeners: 10, output: [], outputEncodings: [], writable: true, _last: true, chunkedEncoding: false, shouldKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _headerSent: true, _header: 'GET /plugins HTTP/1.1\r\nhost: api.pimatic.org\r\nConnection: keep-alive\r\n\r\n', _hasBody: true, _trailer: '', finished: true, _hangupClose: false, socket: [Object], connection: [Object], agent: [Object], socketPath: undefined, method: 'GET', path: '/plugins', _headers: [Object], _headerNames: [Object], parser: null, res: [Circular] }, pipe: [Function], addListener: [Function], on: [Function], pause: [Function], resume: [Function], read: [Function], request: { domain: null, _events: [Object], _maxListeners: 10, callback: [Function], uri: [Object], readable: true, writable: true, _auth: [Object], _oauth: [Object], _multipart: [Object], _redirect: [Object], _rp_resolve: [Function], _rp_reject: [Function], _rp_promise: [Object], _rp_callbackOrig: undefined, _rp_options: [Object], headers: {}, setHeader: [Function], hasHeader: [Function], getHeader: [Function], removeHeader: [Function], method: 'GET', localAddress: undefined, qsLib: [Object], qsParseOptions: undefined, qsStringifyOptions: undefined, pool: {}, dests: [], __isRequestRequest: true, _callback: [Function: RP$callback], proxy: null, tunnel: undefined, setHost: true, originalCookieHeader: undefined, _disableCookies: true, _jar: undefined, port: 80, host: 'api.pimatic.org', path: '/plugins', httpModule: [Object], agentClass: [Object], agent: [Object], _rp_promise_in_use: true, _started: true, href: 'http://api.pimatic.org/plugins', req: [Object], ntick: true, response: [Circular], originalHost: 'api.pimatic.org', originalHostHeaderName: 'host', _destdata: true, _ended: true, _callbackCalled: true }, toJSON: [Function: responseToJSON], caseless: { dict: [Object] }, body: '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n' } }

The rest seems to work fine.

**Comment by sweetpi** [comment]
Has nothing to do with the raspian update, just the update server seems to be in trouble. Watch #643 for updates.

**Comment by edautz** [comment]
Ok. Thnx.
