### ISSUE TITLE
Error 504 by searching plugins 

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#643]
Hey guys, 
When I search für plugins I get this error message:

error [pimatic]: 504 - <html>
 <head><title>504 Gateway Time-out</title></head>
 <body bgcolor="white">
 <center><h1>504 Gateway Time-out</h1></center>
 <hr><center>nginx/1.4.6 (Ubuntu)</center>
 </body>
 </html>

Any ideas to fix it? 

Btw. What is the right syntax to post code in github? :) at the moment it looks really ugly... 

Regards, 
n3ro

**Comment by Sjeff** [comment]
Since this morning i receive the same error.

error message : http://pastebin.com/nzGhKJ7B

**Comment by Sjeff** [comment]
after a restart of pimatic the error is gone

**Comment by n3roGit** [comment]
Still the same in plugins and update section

**Comment by sweetpi** [comment]
Thanks for reporting. It was a problem with the update server. All should now be stable again.
