### ISSUE TITLE
[pimatic-mobile-frontend] address bar is shown on Android 5.0 in web app mode

### ISSUE THREAD

**Issue by georg90** [pimatic/pimatic#651]
I'm new to Android but other web apps work without the address bar.

![screenshot_2015-05-08-14-44-17](https://cloud.githubusercontent.com/assets/6489464/7536621/bd52259e-f591-11e4-9f4e-f572c49b7b11.png)

**Comment by Yves911** [comment]
i **think** that's due to the ssl certificate (i have in addition a message telling me that the network is unsure)

**Comment by georg90** [comment]
that's the next thing: On my computer the certificate is trusted (in chrome) only on android there is a problem^^

**Comment by mwittig** [comment]
... which does not solve the trust issue per se

**Comment by georg90** [comment]
I created a simple android app which includes the mobile frontend :-) This works much better!

**Comment by Yves911** [comment]
@georg90 how did you that? Do you mean that you pined the webepage to the home screen?

**Comment by georg90** [comment]
I created an android App which uses a Fullscreen webview to display the mobile front-end.
Once I figured a way to nicely enter your pimatic details (username / address) I'll publish the app

**Comment by Yves911** [comment]
Okay sound good looking forward to test it

**Comment by sweetpi** [comment]
@georg90 When did you create your SSL cert? It could be that google chrome marks the cert as insecure because it was created with sha1 instead of sha256 and chrome only trusted sha256 or better. I adapted the setup script end last year: https://github.com/pimatic/pimatic/commit/254689e8b35c0f3d71fe9f651220d335e53dce21#diff-021553f17b9f3b5522a0228a1f08da32

**Comment by Yves911** [comment]
I tried to upgrade from sha1 to sha256 using the ~new script, after that i can't connect anymore to pimatic. No error during certificat creation, firefox say that connection was reseted.
@georg90 could you try to generate new SSL cert using the new script and post your result

**Comment by sweetpi** [comment]
@Yves911 Make sure you deleted all old certs (pi, browser, android, windows(?)) Restart all systems (pi, browser, android) and then import the new root cert (browser, android). That did the trick for me last year.

**Comment by Yves911** [comment]
Still no luck, this is how i proceed:
1. stop pimatic
2. rm -Rf ca
3. follow instructions to generate the new cert using latest version of ssl-setup
4. restart pi
5. start pimatic
6. remove all cert from browsers
7. Chrome and Firefox say ERR_CONNECTION_CLOSED
8. wget on the certificate says:
wget 'https://g#######.fr:8443/root-ca-cert.crt'
--2015-05-10 10:36:21--  https://g#######.fr:8443/root-ca-cert.crt
Résolution de g#######.fr (g#######.fr)... 98.156.52.854
Connexion vers g#######.fr (g#######.fr)|98.156.52.854|:8443...connected.
**GnuTLS: A TLS packet with unexpected length was received.**

**Comment by georg90** [comment]
@Yves911 I don't use self generated certificates (that's why it's odd that it's not accepted by Android (working with iOS - Chrome and on regular PC)

Your can try my "app" (which is just a container for the pimatic frontend):
https://github.com/georg90/pimatic-android-hybrid-app

**Comment by Yves911** [comment]
@georg90 i gave a try to your work, but still prefer to have the warning message at the moment (the container make pimatic slower (because of no caching?)). Anyway if i can't switch to proper certificate with pimatic, i will use stunnel for a ssl layer on top of it.

**Comment by georg90** [comment]
It's slow at the first start. For me after that it works just fine. It's basically the same a running it in chrome. - since we view used the chrome engine.

**Comment by georg90** [comment]
was due to the certificate error.
Close since there's an app now :)
