### ISSUE TITLE
Error on adding new rule

### ISSUE THREAD

**Issue by asksimplicity** [pimatic/pimatic#652]
While adding the rule
```
$weather.status is "clouds" or $weather.status is "rain" or $weather.status is "overcast clouds" and its 60 minutes before sunset
```
I get an error (the oops-popup) with this code.
```
S(nextInput.toLowerCase()).startsWith(parseResult.token.toLowerCase())
```

I don't have a clue, might be a bug?

**Comment by asksimplicity** [comment]
Today it worked as above. Maybe it was a pending update, sorry for the inconvenience!

**Comment by sweetpi** [comment]
Please reopen if the issue still exists.
