### ISSUE TITLE
Question: use 2 trigers as people counter

### ISSUE THREAD

**Issue by lcfm1** [pimatic/pimatic#653]
Hi!
in my configuration there are two doors, standing in series. Is it possible to make provision that allows to count the number entered or departed people?

like:

if door1 is opened and after 10 sec door2 is opened 
then
msg "Incoming People"

**Comment by leader21** [comment]
Hi Icfm1!
Could you please ask your questions at the [Pimatic Forum](http://forum.pimatic.org)
Git should only be used for major issues, bugs and development of course.
Thanks a lot!
