### ISSUE TITLE
EIO Error

### ISSUE THREAD

**Issue by cdkisa** [pimatic/pimatic#654]
Using pimatic with MySensors. Everything was going smoothly, went to watch a movie, came back and nothing was working. Checked the logs and seen this:

03:43:32.293 [pimatic] error: A uncaught exception occured: Error: EIO, read
03:43:32.293 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
03:43:32.308 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!

My set up:
Raspberry Pi B+ with NRF24l01+ directly connected to GPIO.
32G memory card with NOOBS installed.

All logs above error are just sensor values reporting, but there are lots.

Not sure what else you need to investigate the issue, but happy to provide you with whatever you need.

**Comment by sweetpi** [comment]
Could you post your config related to the mysensors plugin?

**Comment by cdkisa** [comment]
**PLUGIN**

    {
        "plugin": "mysensors",
        "driver": "serialport",
        "protocols": "1.4.1",
        "driverOptions": {
            "serialDevice": "/dev/ttyMySensorsGateway",
            "baudrate": "115200"
        }
    }

**DEVICES**


    "devices": [
        {
            "id": "laundryroom-temperature",
            "name": "Temperature/Humidity",
            "class": "MySensorsDHT",
            "nodeid": 1,
            "sensorid": [
                4,
                5
            ]
        },
        {
            "id": "laundryroom-pir",
            "name": "Motion",
            "class": "MySensorsPIR",
            "nodeid": 1,
            "sensorid": 3,
            "resetTime": 500
        },
        {
            "id": "laundryroom-light",
            "name": "Light",
            "class": "MySensorsLight",
            "nodeid": 1,
            "sensorid": 1
        },
        {
            "id": "laundryroom-moisture",
            "name": "Water",
            "class": "MySensorsLight",
            "nodeid": 1,
            "sensorid": 2
        },
        {
            "id": "laundryroom-lightswitch",
            "name": "Light Switch",
            "class": "MySensorsSwitch",
            "nodeid": 1,
            "sensorid": 6
        }
    ]

**Comment by sweetpi** [comment]
Hm really hard to find the issue without a stack trace. How often does the error happen? What other plugins do you use?

I'm not sure if its really the sensor plugin.

**Comment by cdkisa** [comment]
i am not sure what it is related to. i was just posting the issue since the error asked me to. i will try removing some of the other plugins to see if i can pinpoint which may be causing the error. thanks for your time.

**Comment by sweetpi** [comment]
@cdkisa thanks.

**Comment by sweetpi** [comment]
No replay so closing.
