### ISSUE TITLE
[pimatic or pimatic-sunrise] A uncaught exception occured 

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic#655]
![fullsizerender 1](https://cloud.githubusercontent.com/assets/11790664/7677784/671a623e-fd4f-11e4-8349-c71fdc21e3d9.jpg)

**Comment by sweetpi** [comment]
Thanks for reporting, could you post the sunrise rules you have?

**Comment by pimagical** [comment]
My sunrise rules.

	{
      "id": "good-morning",
      "name": "good-morning",
      "rule": "if night ends then set $status to \"Goodmorning!\"",
      "active": true,
      "logging": true
    },	
	{
      "id": "home-lights-on",
      "name": "home-lights-on",
      "rule": "if iPhone one is present or iPhone two is present and its after 60 minutes before sunset and before night then turn everything on and set $status to \"@home and after sunset💡\"",
      "active": true,
      "logging": true
    },
	{
      "id": "home-lights-on-both-home",
      "name": "home-lights-on-both-home",
      "rule": "if iPhone one is present and iPhone two is present and its after 60 minutes before sunset then set $status to \"Both@home and after sunset💡\"",
      "active": true,
      "logging": true
    },

**Comment by sweetpi** [comment]
I've released a update, which fixes a very rare race condition. Hopefully this fixes the problem.

**Comment by pimagical** [comment]
Ok after a whole week testing i know it for sure. Every rule with use of night (included before night, after night, night start, night ends) is all failing! (sunset and solar noon are working.)

**Comment by pimagical** [comment]
https://github.com/pimatic/pimatic-sunrise/issues/2
