### ISSUE TITLE
error [pimatic]: A uncaught exception occured pimatic-openweather

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#656]
Sometimes I got the following error:

error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'length' of undefined at /usr/local/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:76:28 at IncomingMessage.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:147:16) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!

Is it a bug?

**Comment by edautz** [comment]
Pimatic 0.8.68
Openweather 0.8.8

**Comment by leader21** [comment]
having this error too once or twice a day. 
but everything is still working as it should.
no need to worry i guess ;)

**Comment by sweetpi** [comment]
Thanks for reporting. Yes, kind of bug. Seems openweather sumtime respond with an invalid message.

**Comment by sweetpi** [comment]
I've added error handling for this case. Probably sometimes the openweather api returns no results. Reopen if the issue still exist after a update.

**Comment by edautz** [comment]
Updated it. Let you know if the problem persists. Thnx.
