### ISSUE TITLE
pimatic-ping error

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#658]
Hey i just tried the new DNS function but getting this error:

error [pimatic-ping]: Error on ip lookup of rbclient.fritz.box: Error: getaddrinfo ENOTFOUND
error [pimatic-ping]: Error on ip lookup of shark.fritz.box: Error: getaddrinfo ENOTFOUND
error [pimatic-ping]: Error on ip lookup of s3.fritz.box: Error: getaddrinfo ENOTFOUND

same with hostname only:

error [pimatic-ping]: Error on ip lookup of rbclient: Error: getaddrinfo ENOTFOUND
error [pimatic-ping]: Error on ip lookup of shark: Error: getaddrinfo ENOTFOUND
error [pimatic-ping]: Error on ip lookup of s3: Error: getaddrinfo ENOTFOUND

Is the host is up one time its OK

**Comment by sweetpi** [comment]
We are using the node `dns.lookup` (https://nodejs.org/api/dns.html#dns_dns) function. As far as I know this should work, if the os can resolve the hostname (by dns query, /etc/hosts, etc...). Can you ping the devices using these hostname using the ping command (`ping rbclient.fritz.box`)?

**Comment by n3roGit** [comment]
If the device is online. Everything is OK and the device is detected as online. But when it's going offline I get this error the whole time and the log is getting bigger and bigger :(

When using ping or nslookup from shell everything is working well

**Comment by n3roGit** [comment]
Can you please disable the error logging every x second for this plugin? 1 error for 1 host is enough^^

**Comment by thorstenreichelt** [comment]
I have the same error like @n3roGit. The Log is getting bigger and bigger. Any update on this issue?

**Comment by sweetpi** [comment]
The error should now only be logged ones per device. I also changed the log level to warning.
