### ISSUE TITLE
Can't access forum

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#659]
I can't access the forum from my house. only with this ip address: 185.82.195.249

**Comment by sweetpi** [comment]
That's strange. Can you `ping forum.pimatic.org`? What do you get if you try to visit the forum?

**Comment by sweebee** [comment]
Can't load the page. I'll get this:

PING forum.pimatic.org (185.82.21.117): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

**Comment by thorstenreichelt** [comment]
Which dns server do you use? Have you tried the 8.8.8.8 from google as dns in your network settings? Did you also cleared you webbrowser cache?

**Comment by borisxm** [comment]
Even with Google's DNS forum doesn't work, as well as api.pimatic.org:

dig forum.pimatic.org @8.8.8.8
; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> forum.pimatic.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5554
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;forum.pimatic.org.		IN	A
;; ANSWER SECTION:
forum.pimatic.org.	19792	IN	A	185.82.21.117
;; Query time: 106 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; MSG SIZE  rcvd: 62
---------------------------------------
ping forum.pimatic.org
PING forum.pimatic.org (185.82.21.117) 56(84) bytes of data.
^C
--- forum.pimatic.org ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3024ms

**Comment by mwittig** [comment]
Works for me! @borisxm maybe it is an issue with your IP provider? Can you traceroute 185.82.21.117, please?

```
C:\Windows\System32>nslookup forum.pimatic.org 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Nicht autorisierende Antwort:
Name:    forum.pimatic.org
Address:  185.82.21.117
```

**Comment by borisxm** [comment]
Here it is:
traceroute -q1 forum.pimatic.org
traceroute to forum.pimatic.org (185.82.21.117), 64 hops max, 40 byte packets
 1  82.200.154.46 (82.200.154.46)  1.754 ms
 2  92.47.145.100 (92.47.145.100)  20.295 ms
 3  95.59.172.9 (95.59.172.9)  16.172 ms
 4  95.59.172.15 (95.59.172.15)  20.289 ms
 5  217.150.44.146 (217.150.44.146)  32.393 ms
 6  *
 7  fra-anc-02gw.voxility.net (80.81.195.144)  103.537 ms
 8  *
 9  fra-in3-02gw.voxility.net (5.254.88.22)  101.353 ms
10  fra-in8-01c.voxility.net (5.254.88.6)  102.762 ms
11  ddos.protected.fra-ae0.net (5.254.86.6)  98.475 ms
12  *
13  *

The rest are stars, so it is definitely not my ISP.

**Comment by sebastienvg** [comment]
@sweebee I suspect voxility blocked your IP 185.82.195.249 on 5.254.86.6 (ddos.protectd...) not sure how to go about this, maybe @sweetpi can reach out to them and ask why the IP was catch by their anti-ddos system?

**Comment by sweetpi** [comment]
I got a mail from my provider, that they updated ther ddos protection mechanism. @borisxm Can you still no access the forum?

**Comment by borisxm** [comment]
Nope, doesn't work. Traceroute still can't pass past ddos.protected.fra-ae0.net. It is interesting, that 82.200.154.32/28 corporate network are very quiet and heavy filtered one, so it is highly unlikely to receive any 'ddos' from it in the past.

**Comment by sweetpi** [comment]
From Support (translated to english):
> if you can't reach the destination, please give us an backtrace. traceroute from your location to the server ip. 

@borisxm I already supplied your traceroute, but could you do one more and post it here?

**Comment by sweetpi** [comment]
I got the final response from my server provider:

> we have checked our setup and we are not filtering this subnet.
> Please ask your ISP to check his routing / filter list. I have also checked the backroute, and i can reach 82.200.154.46 with all our transits and peerings.

> The hop ddos.protected.fra-ae0.net is absolutely normal. Traffic is not getting filtered there.

**Comment by borisxm** [comment]
It started to work about day ago. The traceroute now completes normally:

traceroute -q1 forum.pimatic.org
traceroute to forum.pimatic.org (185.82.21.117), 64 hops max, 40 byte packets
 1  82.200.154.46 (82.200.154.46)  1.759 ms
 2  92.47.145.100 (92.47.145.100)  21.744 ms
 3  95.59.172.9 (95.59.172.9)  22.721 ms
 4  95.59.172.15 (95.59.172.15)  19.883 ms
 5  ebg06.transtelecom.net (217.150.36.58)  36.617 ms
 6  *
 7  fra-anc-02gw.voxility.net (80.81.195.144)  96.857 ms
 8  fra-eq5-02gw.voxility.net (93.115.88.137)  121.738 ms
 9  fra-in3-02gw.voxility.net (5.254.88.22)  95.682 ms
10  fra-in8-01c.voxility.net (5.254.88.6)  369.181 ms
11  ddos.protected.fra-ae0.net (5.254.86.6)  98.249 ms
12  antiddos.gw.r1-in.linevast.de (37.228.135.70)  99.350 ms
13  o2.linevast.de (185.82.21.122)  97.693 ms
14  185.82.21.117.rdns.static.linevast.org (185.82.21.117)  102.497 ms

As one can see, now it happily passes behind that ddos host.

**Comment by sweetpi** [comment]
Nice, that is working now. If there should be any issues again, please post again here.
