### ISSUE TITLE
TypeError: Cannot read property 'list' of null 

### ISSUE THREAD

**Issue by asksimplicity** [pimatic/pimatic#664]
warn [pimatic]: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
06:30:02error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'list' of null at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-openweather/node_modules/openweathermap/openweather.js:151:15) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13) This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
@asksimplicity Do you still get this error, occasionally?

**Comment by sweetpi** [comment]
Closes because no response.
