### ISSUE TITLE
[bug] pimatic ping with long timeout

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#666]
I have this in my configuration for 5 phones. But when i have a long timeout like this, pimatic won't ping some devices anymore till I restarted pimatic. 

```
{
      "id": "iphone-wiebe",
      "name": "iPhone van Wiebe",
      "class": "PingPresence",
      "host": "192.168.1.4",
      "interval": 10000,
      "timeout": 900000
    },
```

**Comment by mwittig** [comment]
Closing this one now. Please re-open if you wish to follow-up.
