### ISSUE TITLE
openweather plugin errors in log

### ISSUE THREAD

**Issue by 13sonic13** [pimatic/pimatic#671]
i need to atrach a pic as i just hav a screenshot from my iphone

**Comment by 13sonic13** [comment]
![image](https://cloud.githubusercontent.com/assets/8593276/8003812/ec6afb36-0b7a-11e5-85f4-f1f28a1de4cf.jpg)

**Comment by WimUtTwente** [comment]
Presumably the error has to do with the time.
Every 30 minutes, the error message.
Maybe a character in the time display that caused this error.

13:47:30.322 [pimatic-openweather] error: Unexpected token /
13:47:31.819 [pimatic-openweather] error: Unexpected token /
16:17:34.768 [pimatic-openweather] error: Unexpected token /
16:17:36.207 [pimatic-openweather] error: Unexpected token /
18:47:39.238 [pimatic-openweather] error: Unexpected token /
18:47:40.609 [pimatic-openweather] error: Unexpected token /
21:17:43.773 [pimatic-openweather] error: Unexpected token /
21:17:45.111 [pimatic-openweather] error: Unexpected token /
23:47:48.209 [pimatic-openweather] error: Unexpected token /
23:47:49.772 [pimatic-openweather] error: Unexpected token /
02:17:52.620 [pimatic-openweather] error: Unexpected token /
02:17:54.145 [pimatic-openweather] error: Unexpected token /
04:47:57.020 [pimatic-openweather] error: Unexpected token /
04:47:58.521 [pimatic-openweather] error: Unexpected token /
07:18:01.472 [pimatic-openweather] error: Unexpected token /
07:18:02.912 [pimatic-openweather] error: Unexpected token /
09:48:05.895 [pimatic-openweather] error: Unexpected token /
09:48:07.316 [pimatic-openweather] error: Unexpected token /
12:18:10.333 [pimatic-openweather] error: Unexpected token /
12:18:11.698 [pimatic-openweather] error: Unexpected token /

**Comment by sweetpi** [comment]
Should be fixed with the latest releases

**Comment by WimUtTwente** [comment]
Yes
