### ISSUE TITLE
ordering of devices on pages - api != webinterface

### ISSUE THREAD

**Issue by MaxWinterstein** [pimatic/pimatic#672]
Hello,

as i am currently playing around with my pebble and pimatic i found a little bug:

I would like to order devices on an page i named "Pebble".
I thought the ordering on the api (.../api/pages/ ) should be the same as on the website, but i seems that i am wrong.

I think this should be equal, right?

![image](https://cloud.githubusercontent.com/assets/5927148/8053543/0334c134-0e92-11e5-9cbe-fe223136e007.png)

**Comment by leader21** [comment]
The order at the gui and at the config.json doesn't need to be the same. Click on the gear wheel at the upper right corner, then you can move your devices via drag and drop.
Furthermore please ask your questions at our forum : http:// forum.pimatic.org unless you are having a bug, this should be reported on git.

Cheers
Chris

**Comment by MaxWinterstein** [comment]
i am not referring to the config.js, i mean the output of the API. If i do what you say - use the gear wheel to rearrange- the output of the API changes, but not according to the ordering of the gui.

In my opinion, this is a bug.

**Comment by leader21** [comment]
> edit: output of API is the same as config.js

that was my first thought. ok if you think it's a bug, @sweetpi has to check it

**Comment by MaxWinterstein** [comment]
okay, we can fight over the definition of this if you want :)

also, it seems like i was able to do this somehow:
![image](https://cloud.githubusercontent.com/assets/5927148/8058951/5f02195a-0ebd-11e5-8837-8455154004b2.png)

config.js doesn't seem to explain this:
    "groups": [
      {
        "id": "buro",
        "name": "Büro",
        "devices": [
          "max-maxbook"
        ],
        "rules": [],
        "variables": []
      },
      {
        "id": "mobile-gerate",
        "name": "Mobile Geräte",
        "devices": [
          "max-iphone",
          "buero-lampe"
        ],
        "rules": [],
        "variables": []
      },
      {
        "id": "schlafzimmer",
        "name": "Schlafzimmer",
        "devices": [
          "schlafzimmer-blauelampe"
        ],
        "rules": [],
        "variables": []
      },
      {
        "id": "wohnzimmer",
        "name": "Wohnzimmer",
        "devices": [
          "wohnzimmer-lavalampe"
        ],
        "rules": [],
        "variables": []
      }
    ],

this could also explain a strange behavior in rearranging devices on a page.

**Comment by leader21** [comment]
no need to fight and thanks for reporting :)
let the developers get a glance on that.

**Comment by Icesory** [comment]
The config is only updated while closing pimatic.
But i am not so deep in the web frontend.

**Comment by sweetpi** [comment]
The devices at the device pages are order by two criteria group and devices list in page array:

1. First all groups of the devices are collected
2. This groups are ordered by the ordering of the groups
3. Then for each group (in order) the devices are ordered by the ordering in the pages.devices array.
4. Devices in pages.devices without a group are outputted at the end.

You can find the javascript implementation here: https://github.com/pimatic/pimatic-mobile-frontend/blob/a2b133b21cfba901182664b8a75f201ab43d0ad3/app/scope.coffee#L356-L369

**Comment by sweetpi** [comment]
> (note the dubplicates of "Blaue Lampe" and others)
> config.js doesn't seem to explain this:

Seems like a bug in the mobile-frontend. Could you try in an inkognito tab (to prevent caching)?

**Comment by sweetpi** [comment]
No response, so closing.
