### ISSUE TITLE
Installing pimatic: sqlite3 fails

### ISSUE THREAD

**Issue by neibeck** [pimatic/pimatic#673]
Hi,

I am new to rasperry pi / pimatic and have some problems in installing pimatic. The system is basically running on OSMC and i would like to run pimatic in the background. Even trying to install sqlite manually doesn't work.
Here is a copy of the ssh session:

osmc@osmc:~$ npm install sqlite3
npm http GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan

> sqlite3@3.0.8 install /home/osmc/node_modules/sqlite3
> node-pre-gyp install –fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8 /node-v11-linux-arm.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8 /node-v11-linux-arm.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary .s3.amazonaws.com/sqlite3/v3.0.8/node-v11-linux-arm.tar.gz (falling back to sour ce compile with node-gyp)
make: Entering directory ‚/home/osmc/node_modules/sqlite3/build‘
ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/o bj/gen/sqlite-autoconf-3080900/sqlite3.c
TOUCH Release/obj.target/deps/action_before_build.stamp
CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080900/sqlite3.o
make: cc: Command not found
deps/sqlite3.target.mk:107: recipe for target ‚Release/obj.target/sqlite3/gen/sq lite-autoconf-3080900/sqlite3.o‘ failed
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3080900/sqlite3.o] Err or 127
make: Leaving directory ‚/home/osmc/node_modules/sqlite3/build‘
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_ modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:789: 12)
gyp ERR! System Linux 3.18.13-1-osmc
gyp ERR! command „/usr/local/bin/node“ „/usr/local/lib/node_modules/npm/node_mod ules/node-gyp/bin/node-gyp.js“ „build“ „–fallback-to-build“ „–module=/home/osm c/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node“ „–modu le_name=node_sqlite3″ „–module_path=/home/osmc/node_modules/sqlite3/lib/binding /node-v11-linux-arm“
gyp ERR! cwd /home/osmc/node_modules/sqlite3
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute ‚/usr/local/bin/node /usr/local /lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build –fallback-to- build –module=/home/osmc/node_modules/sqlite3/lib/binding/node-v11-linux-arm/no de_sqlite3.node –module_name=node_sqlite3 –module_path=/home/osmc/node_modules /sqlite3/lib/binding/node-v11-linux-arm‘ (1)
node-pre-gyp ERR! stack at ChildProcess. (/home/osmc/node_modules /sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (child_proces s.js:802:5)
node-pre-gyp ERR! System Linux 3.18.13-1-osmc
node-pre-gyp ERR! command „node“ „/home/osmc/node_modules/sqlite3/node_modules/. bin/node-pre-gyp“ „install“ „–fallback-to-build“
node-pre-gyp ERR! cwd /home/osmc/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.21
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute ‚/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modu les/node-gyp/bin/node-gyp.js build –fallback-to-build –module=/home/osmc/node_ modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node –module_name=n ode_sqlite3 –module_path=/home/osmc/node_modules/sqlite3/lib/binding/node-v11-l inux-arm‘ (1)
npm ERR! weird error 1
npm ERR! not ok code 0
osmc@osmc:~$

**Comment by leader21** [comment]
Stupid question but already tried with ```sudo npm install sqlite3```?

**Comment by asksimplicity** [comment]
I ran into the same problem, try to install with this command: ```sudo npm install --unsafe-perm --verbose -g sqlite3```

Worked for me!

**Comment by neibeck** [comment]
When i try sudo 
> npm install --unsafe-perm --verbose -g sqlite3 

it seems like building the package works, but then it still exits with errors:
> ...
make: g++: Command not found
node_sqlite3.target.mk:97: recipe for target 'Release/obj.target/node_sqlite3/sr                                                                                                                                                             c/database.o' failed
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 127
make: Leaving directory '/usr/local/lib/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_                                                                                                                                                             modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:                                                                                                                                                             12)
gyp ERR! System Linux 3.18.13-1-osmc
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_mod                                                                                                                                                             ules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/loca                                                                                                                                                             l/lib/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--                                                                                                                                                             module_name=node_sqlite3" "--module_path=/usr/local/lib/node_modules/sqlite3/lib                                                                                                                                                             /binding/node-v11-linux-arm"
gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local                                                                                                                                                             /lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-                                                                                                                                                             build --module=/usr/local/lib/node_modules/sqlite3/lib/binding/node-v11-linux-ar                                                                                                                                                             m/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/local/lib/node                                                                                                                                                             _modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_mod                                                                                                                                                             ules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces                                                                                                                                                             s.js:802:5)
node-pre-gyp ERR! System Linux 3.18.13-1-osmc
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/sqlite3/node_modul                                                                                                                                                             es/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.21
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modu                                                                                                                                                             les/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/n                                                                                                                                                             ode_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_na                                                                                                                                                             me=node_sqlite3 --module_path=/usr/local/lib/node_modules/sqlite3/lib/binding/no                                                                                                                                                             de-v11-linux-arm' (1)
npm info sqlite3@3.0.8 Failed to exec install script
npm info /usr/local/lib/node_modules/sqlite3 unbuild
npm info preuninstall sqlite3@3.0.8
npm info uninstall sqlite3@3.0.8
npm verb true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild sq                                                                                                                                                             lite3@3.0.8
npm info postuninstall sqlite3@3.0.8
npm ERR! weird error 1
npm verb exit [ 1, true ]
npm ERR! not ok code 0
osmc@osmc:~$

I think is has something to do with the path /usr/local/... should it not be in pimatic-app/... ?
See https://copy.com/V0lxn4tBmFeeb7GL for the full log.

**Comment by neibeck** [comment]
I just tried to install it on Raspian. Here everything works fine, so I guess it has something to do with OSMC and its different path. Can somebody tell me how to change the path of the sqlite3 installation?

**Comment by sweebee** [comment]
My config:

```json
 "database": {
      "connection": {
        "filename": "/media/usb0/pimatic-database.sqlite"
      },
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "expire": "7d",
          "type": "*",
          "interval": "0"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "expire": "1y",
          "type": "number"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "expire": "1y",
          "type": "number"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "1d"
        }
      ],
      "diskSyncInterval": "4h"
    },
```

**Comment by neibeck** [comment]
Thanks, but the pimatic config doesn't help me as i can't even start pimatic without sqlite3 installed. Today I tried to install in on Raspian with success, so is must have to do with OSMC...

**Comment by llgb** [comment]
>Today I tried to install in on Raspian with success, so is must have to do with OSMC...

Hm that's strange, I got the same issue like you have, three or four days ago with a freshly installed raspian. 
Only changed the wireless config and installed pimatic according to the guide on the website.

**Comment by neibeck** [comment]
No idea why, but now it worked! :)

**Comment by guiguid** [comment]
node (node-gyp) suppose "python" is python version 2, 
to allow build of sqlite3, I'have to temporaly set 
/usr/bin/python point on /usr/bin/python2.7
`npm config set python /usr/bin/python2.7  don't do the job.
`
