### ISSUE TITLE
install ping plugin error

### ISSUE THREAD

**Issue by lenny76** [pimatic/pimatic#679]
trying to add the plugin PING, I receive this error 
18:57:06.956 [pimatic] Loading plugin: "pimatic-ping" (0.8.5)
18:57:07.069 [pimatic] Cannot find module './build/Release/raw'

any idea how to solve this?
thanks

**Comment by sweetpi** [comment]
Which hardware / distro are you using?

**Comment by lenny76** [comment]
Rpi 2

**Comment by lenny76** [comment]
the command suggested does not work.
I think that there is problems with node 0.12 and node-gyp

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/pimatic-app/node_modules/pimatic-ping/node_modules/net-ping/node_modules/raw-socket
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.18.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-ping"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! raw-socket@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raw-socket@1.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the raw-socket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raw-socket
npm ERR! There is likely additional logging output above.

**Comment by sweetpi** [comment]
Yes, I'm sorry node v0.12.1 is not supported, you have to downgrade to 0.10 (http://pimatic.org/guide/getting-started/installation/).

**Comment by kjdijkema** [comment]
I have the same error! I just installed pimatic on a Rpi2 following the steps on pimatic.org. My npm version is 0.10.24, my Linux is Raspbian Jessie.

**Comment by sweetpi** [comment]
@kjdijkema What's your node version (`node --version`)?

**Comment by kjdijkema** [comment]
v0.10.24

**Comment by mwittig** [comment]
@kjdijkema You're not alone :) The problem occurs with a fresh installation of pimatic-ping. The problem is that the indirect dependency "raw-socket" no longer builds on node 0.10. @sweetpi I'll come up with suggested fix shortly.

**Comment by kjdijkema** [comment]
My problem is fixed, I can install the plugin. Thanks!
