### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by noxx2015** [pimatic/pimatic#680]
Hello, 
ive problems with Pimatic. LOG show SQL Error

Unhandled rejection Error: SQLITE_FULL: database or disk is full
07:30:21.783 [pimatic] error: SQLITE_IOERR: disk I/O error
07:30:21.811 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.811 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.815 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: SQLITE_IOERR: disk I/O error
07:30:21.831 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.831 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.848 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: SQLITE_IOERR: disk I/O error
07:30:21.865 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.865 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.868 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: SQLITE_IOERR: disk I/O error
07:30:21.879 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.879 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.882 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: SQLITE_IOERR: disk I/O error
07:30:21.888 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.888 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.891 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state, please restart pimatic so soon as possible!
^--- With additional stack trace: Error: SQLITE_IOERR: disk I/O error
07:30:21.906 [pimatic] error: A uncaught exception occured: Error: SQLITE_IOERR: disk I/O error
07:30:21.906 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
07:30:21.908 [pimatic] warn: Keeping pimatic alive, but could be in an undefined state,

**Comment by sweetpi** [comment]
Your sd card is full: `SQLITE_FULL: database or disk is full`
