### ISSUE TITLE
Homeduino: Switching fom gpio to anduino solution is not working

### ISSUE THREAD

**Issue by Nears** [pimatic/pimatic#681]
Hello,

yesterday I just switched from the gpio solution of pimatic-homeduino to the serialport solution.
But after this change the switches don't work anymore...

Do i need to change the devices settings or anything else than the the plugin settings?
With debugging activated I can see that the anduino receives data but the configured switches in pimatic won't work...

I also mentioned that the pimatic-homduino will only interpred the received data correctly if I do a long press on the remote control. A short press will not issue a reacrion of pimatic, but the hardware switch I self is reacting in the light turns on/off.

Any suggestions why it does not work with the aduino?
Thanks.

**Comment by sweetpi** [comment]
Please search the forum / ask there for help.

**Comment by Nears** [comment]
Why did you close this issue here?

**Comment by sweetpi** [comment]
Because we can trace this down better in the forum.
