### ISSUE TITLE
Problem with 3 sensors using weather1

### ISSUE THREAD

**Issue by tomansi** [pimatic/pimatic#687]
I have 3 sensors with weather1 (chanels 1, 2 and 3) with differents values.
3 devices has same values wich are last value received.

I think this is a bug.

More info here:
http://forum.pimatic.org/topic/623/problem-with-3-sensors-using-weather1/7

Thanks in advance.

**Comment by sweetpi** [comment]
That looks really strange. Could you add the line:
```
console.log event, p
```
here: https://github.com/pimatic/pimatic-homeduino/blob/bb0151146d5b52e2f0c69df79735f851eb2d8c14/homeduino.coffee#L683
and post the output after you received all three sensors?

**Comment by tomansi** [comment]
Sorry for the late response . I spent a few days holiday .

I added the line

`console.log event, p`

I check change:

`coffe-cache: compiling coffee-script file "homeduino.coffee" ... Done`

but I don't see any new message.

I run pimatic as service and I see log messages, log events and log file (pimatic-daemon.log).
Also I run pimatic directly with `sudo node_modules/pimatic/pimatic.js` but no new.

Am I doing something wrong?
Should I look elsewhere?

**Comment by tomansi** [comment]
@sweetpi I have installed coffee-script with:

`cd /usr/local`
`npm install -g coffee-script`

but I don't know use console yet.

I'm sorry.

**Comment by sweetpi** [comment]
Which config class do you use? For the edit from above you should use `class: "HomeduinoRFTemperature"`.

**Comment by tomansi** [comment]
First I was using HomeduinoRFTemperature but leader21 suggested me HomeduinoRFweather when I post in the forum (second entry in http://forum.pimatic.org/topic/623/problem-with-3-sensors-using-weather1).

I will change the class and try again.

**Comment by tomansi** [comment]
Eureka !

This is a piece of log:

{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 28 }
{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 147 }
{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 40 }
{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 28 }
{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 147 }
{ protocol: 'weather1',
  values:
   { id: 28,
     channel: 1,
     temperature: 27.5,
     humidity: 30,
     lowBattery: false } } { name: 'weather1', id: 40 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 28 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 147 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 40 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 28 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 147 }
{ protocol: 'weather1',
  values:
   { id: 40,
     channel: 3,
     temperature: 26.8,
     humidity: 25,
     lowBattery: false } } { name: 'weather1', id: 40 }

**Comment by tomansi** [comment]
Now, I write the json as:

```
    {
      "id": "rf-banggood-1",
      "name": "Remoto Banggood 1",
      "class": "HomeduinoRFTemperature",
      "protocols": [
        {
          "name": "weather1",
          "options": {
            "id": 28,
            "channel": 1
          }
        }
      ]
    },
```
and work fine.

I see the problem with the options key. The original and definition are:
```
    {
      "id": "rf-banggood-1",
      "name": "Remoto Banggood 1",
      "class": "HomeduinoRFTemperature",
      "protocols": [
        {
          "name": "weather1",
          "id": 28,
          "channel": 1
        }
      ]
    },
```

Thank very much for your help.  !!!!!

**Comment by sweetpi** [comment]
Good that it is solved. Sorry for my long response time. I didn't catch the wrong config, we need to add some more config checks here....
