### ISSUE TITLE
since 03.07. 10:13 no openweather forecast data

### ISSUE THREAD

**Issue by n3roGit** [pimatic/pimatic#688]
Hey,

since the 03.07 i get no data from the forecast openweather device with no errors in the logfile...

Any ideas?

Regards,
n3ro

**Comment by mwittig** [comment]
@n3roGit I can confirm it is the same problem. It will take some time resolve the problem. My suggestion is to close this ticket and to track progress https://github.com/josecastroleon/pimatic-openweather/issues/16

**Comment by sweetpi** [comment]
The fix was published with pimatic-openweather v0.8.14. Please report in josecastroleon/pimatic-openweather#16 if the problem still exists
