### ISSUE TITLE
[mobile-frontend] usage as application on homescreen broken

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#69]
opening new issue because the discussion in the other issue had not much to do with the heading.

I still can't use pimatic when adding it to my I device homescreen. The first time after I add it I get the login and after logging in I get the long "connecting ..." then everything works as expected. After I close it once and reopen it via the homescreen link I only get the "Loading, could not connect, retrying...". In the background I see the empty pimatic gui. On server side I don't get any output that someone has tried connecting, nothing at all, no socket stuff no handshake nothing.

It doesn't matter if im using SSL or not, also tried DYNDNS/"local hostname/IP"

**Comment by MaxWinterstein** [comment]
i had the same problem, but with a slightly other setup:

iPhone 6 with iOS 8.1 -> HAProxy with valid ssl -> pimatic without ssl (local.net - who cares)

i had the same problem with the not trusted thing. After some search i found that `no-tlsv10` is the problem. Seems like the webview thing is using an old TLS version. I use an dedicated port for pimatic, so this is something i can live with. 

To complete this, here is my `listen`:
```
bind *:444 ssl no-sslv3 crt /etc/haproxy/ssl/myCert.pem
```

and my `global`:
```
global
    # inspired by https://mozilla.github.io/server-side-tls/ssl-config-generator/
    # set default parameters to the modern configuration
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
```

Hope some day it will help somebody.
