### ISSUE TITLE
Wrong Timestamp handling for MYSQL

### ISSUE THREAD

**Issue by fbeek** [pimatic/pimatic#691]
Hello, 

i found another bug in the mysql support in pimatic. 
It looks like the timstamp based sql query without conversion break the database statements in pimatic installations that where running with mysql. 

You can check this if you render a graph wich should contain sensor data from yesterday. 

If you do that nothing shows up. If you check the value tables you can see that the values are there but the database delivers an empty result set.

I checked the statements, this one is generated for example with an empty result: 

```sql
 select 
 MIN(time) AS time, 
 AVG(value) AS value 
 from `attributeValueNumber` 
 where `deviceAttributeId` = 17 
 and `time` >= 1436090381089 
 and `time` <= 1436695181089 
 group by time/1800000 order by `time` asc limit 100
```

This one is fixed and delivers a result set in my setup:

```sql
 select 
 MIN(time) AS time, 
 AVG(value) AS value 
 from `attributeValueNumber` 
 where `deviceAttributeId` = 17 
 and `time` >= FROM_UNIXTIME(1436090381089 * 0.001) 
 and `time` <= FROM_UNIXTIME(1436695181089 * 0.001) 
 group by time/1800000 order by `time` asc limit 100
```

I will try to fix this and then create a pull request.

**Comment by sweetpi** [comment]
Hm a simple fix would be to set the type of the `time` column for mysql to integer, or?

**Comment by fbeek** [comment]
Hey, this could work BUT the user will lose the old data, without an update script or something.

I will evaluate this possibility, if it is okay for you?

**Comment by sweetpi** [comment]
> Hey, this could work BUT the user will lose the old data, without an update script or something.
> 
> I will evaluate this possibility, if it is okay for you?

ok.

**Comment by sweetpi** [comment]
@fbeek any news?

**Comment by fbeek** [comment]
Hey.Yes. I have written a patch for this, but i am still testing. I think till the weekend i will create a merge request.
