### ISSUE TITLE
HomeduinoRFButtonsDevice not triggering rules

### ISSUE THREAD

**Issue by tomreinartz90** [pimatic/pimatic#697]
Hi, 

i use a lot of 443 devices in and around my house to control mostly lights and to control everything with a 443 remote control by KAKU i would like to use the HomeduinoRFButtonsDevice. 

I have added the device with the following config: 
```javascript
   {
      "id": "Schakelaar-1-2-buttons",
      "name": "Schakelaar-1-2-buttons",
      "class": "HomeduinoRFButtonsDevice",
      "buttons": [
        {
          "id": "Schakelaar-1-2-on",
          "text": "on",
          "protocols": [
            {
              "name": "switch1",
              "options": {
                "unit": 1,
                "id": 17419334,
                "state": true
              }
            }
          ]
        },
        {
          "id": "Schakelaar-1-2-off",
          "text": "off",
          "protocols": [
            {
              "name": "switch1",
              "options": {
                "unit": 1,
                "id": 17419334,
                "state": false
              }
            }
          ]
        }
      ]
    },
```

And the rule to control my dimmer

```javascript
 {
      "id": "schakelaar-1-2-on-controll",
      "name": "schakelaar-1-2-on-controll",
      "rule": "if Schakelaar-1-2-on is pressed then dim dimmer to $dimmer.state + 10%",
      "active": true,
      "logging": true
    }
```

If i press the button on my remote or in the webinterface the rule does not get triggered and there is also no logged action of the button press. 

Please let me know if there is an option to resolve this issue.
Thanks in advance.

**Comment by leader21** [comment]
Your rule cannot trigger your buttons device since you are using the wrong names for triggering.
try the following : "if switch-1-2-on is pressed then dim dimmer to $dimmer.state + 10%", 
maybe this helps.

Furthermore please post questions about support at http://forum.pimatic.org and only bugs at git.  thx!

**Comment by tomreinartz90** [comment]
Hi Leader21, 

Thanks for the input, i changed the ID but it did not resolve my problem. 
If i use the dummyButtons device i have no problem to trigger rules. But then i still cannot use the remote. 

I have updated my previous comment to match the current configuration.

**Comment by tomreinartz90** [comment]
```coffee
    getButton: -> Promise.resolve(@_lastPressedButton)
    
    buttonPressed: (buttonId) ->
      for b in @config.buttons
        if b.id is buttonId
          @_lastPressedButton = b.id
          @emit 'button', b.id
          @_sendStateToSwitches(b.protocols)
          return Promise.resolve()
      throw new Error("No button with the id #{buttonId} found")

```
I have added the @emit and the Promise.resolve method to the buttonPressed and it works when i press the buttons in the webinterface. Later today i will test if this also triggers an event when i press a button on the remote. 

If this resolves the issue i will try to make a pull request with my changes.

**Comment by tomreinartz90** [comment]
i have created a pull request to resolve my issue:
https://github.com/pimatic/pimatic-homeduino/pull/41

**Comment by sweetpi** [comment]
Fix merged :)
