### ISSUE TITLE
[bug] rain value set to unknown

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#698]
After a time the rain value of the open weather device is set to unknown?

![](https://i.imgur.com/akTX4Hz.png)

![](https://i.imgur.com/qp7FoP2.png)

**Comment by mwittig** [comment]
Hi, I think I know what it is and I am going to fix it soon.

**Comment by sweetpi** [comment]
@mwittig What is it?

**Comment by mwittig** [comment]
@sweetpi I think this has been fixed already. See fixture https://github.com/josecastroleon/pimatic-openweather/issues/18

@sweebee Please complain if the issue still occurs

**Comment by sweebee** [comment]
Updated to the latest version. The plug-in is doing nothing anymore.

error [pimatic-openweather]: Unable to parse response: Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by mwittig** [comment]
@sweebee Please see [README](https://github.com/josecastroleon/pimatic-openweather/blob/master/README.md). You need to setup an apikey. See also https://github.com/josecastroleon/pimatic-openweather/issues/9 for background.
