### ISSUE TITLE
[pimatic-mobile-frontend] Cannot set property 'prev' of null

### ISSUE THREAD

**Issue by georg90** [pimatic/pimatic#699]
The error keeps repeating (no end..)

It occures in an incognito tab on google chrome. No error on microsoft edge.

```
Uncaught TypeError: Cannot set property 'prev' of null(anonymous function) @ 741_contentch.js:1b @ base-86e4089037d54c385616fce65c80dbf1.js:1
```

**Comment by sweetpi** [comment]
Do you have a stack trace for that? (following debug message).

**Comment by georg90** [comment]
unfortunately not..will see if it happens again.

**Comment by georg90** [comment]
error seems to be gone, since the last update..I will keep an eye on this and reopen if it does!
