### ISSUE TITLE
Error loading graph data for new device

### ISSUE THREAD

**Issue by camillo777** [pimatic/pimatic#700]
Hi,
I tried to see graph data for a device added yesterday.
I have got this message.

![unnamed](https://cloud.githubusercontent.com/assets/4798456/9034555/f17fe292-39d0-11e5-81d6-5fbee89e45a6.png)

**Comment by sweetpi** [comment]
I released a potential fix with pimatic-mobile-frontend v0.8.66. Please reopen if the problem still exists.
