### ISSUE TITLE
usage of 'out' in constructor can cause glitches, not inverting defaultstate

### ISSUE THREAD

**Issue by RogerHartmann** [pimatic/pimatic#701]
i have found this behaviour which causes an undesired glitch by using out:
this in the constructor sets the IO to out-LOW
@gpio = new Gpio config.gpio, 'out' 
in this lines, it is then set to high (assuming defaultStage = high)
if @config.defaultState?
        @_state = @config.defaultState
in my case, this causes a glitch because for a short time the port is driven low (and not going from high impedant to out-HIGH directly).
Also it looks like the inverted setting is not considered in the constructor.
Proposed solution (please double check, I am new to coffee script), I am especially unsure with these lines (regarding the @ or if I have to add a ?)
      if @config.inverted then @_state = not @_state
      if @_state

    constructor: (@config, lastState) ->
      @name = config.name
      @id = config.id
      if @config.defaultState?
        @_state = @config.defaultState
      else
        @_state = lastState?.state?.value or false
      if @config.inverted then @_state = not @_state
      if @_state
        @gpio = new Gpio config.gpio, 'high'
      else
        @gpio = new Gpio config.gpio, 'low'
      @gpio.writeAsync(if @_state then 1 else 0).catch( (error) =>
        env.logger.error("Couldn't toggle gpio pin: #{error.message}")
        env.logger.debug(error.stack)
      ).done()
      
      super()

**Comment by sweetpi** [comment]
@RogerHartmann Thanks for reporting and the fix, I released it with pimatic-gpip v0.8.7. Please reopen if there are still any problems.

**Comment by easy12** [comment]
Hi,

unfortunately this "fix" breaks the normal behavior with at least Pi 2. All relais are turned "on" after pimatic startup, regardless of which defaultstate is set or if the value exists at config. The inverted value is set. Pimatic nevertheless shows correct that everything is turned on and I can turn off but of cause thats not the intention. Before it worked with both inverted and defaultState set to "true", no glitch for me.

part of my config showing the try with different default states:
    {
      "id": "Pimatic_Relais_4",
      "class": "GpioSwitch",
      "name": "Pimatic_Toepfe",
      "defaultState": true,
      "inverted": true,
      "gpio": 21
    },
    {
      "id": "Pimatic_Relais_5",
      "class": "GpioSwitch",
      "name": "Carport Sprinkler",
      "inverted": true,
      "gpio": 8
    },
    {
      "id": "Pimatic_Relais_6",
      "class": "GpioSwitch",
      "name": "Pimatic_Beet_Seite",
      "defaultState": false,
      "inverted": true,
      "gpio": 26
    },

Regards Martin

**Comment by sweetpi** [comment]
Thanks for the fast reporting. Silly mistake, should now be working with the version 0.8.8 of pimatic-gpio.

**Comment by easy12** [comment]
Thanks, fix works.

**Comment by RogerHartmann** [comment]
thanks for fixing :-) I am on vacation, therefore the late reply, have to get home to check
