### ISSUE TITLE
Pimatic daemon not working

### ISSUE THREAD

**Issue by thorstenreichelt** [pimatic/pimatic#703]
Hi,
I installed pimatic on my raspberry pi using the original pimatic manual (http://pimatic.org/guide/getting-started/installation/) and also configured the autostart option. 

My problem is, if I use "sudo node_modules/pimatic/pimatic.js" to start pimatic it work's just fine, but if I use "sudo node_modules/pimatic/pimatic.js start" or "sudo pimatic start", i get the "Started" back, but the webserver can't connect. 

Is there a fix for this?

**Comment by leader21** [comment]
Try `sudo service pimatic start` to run the daemon. 
also please have a look at our forum http://forum.pimatic.org and the howto no. 1 http://forum.pimatic.org/topic/192/1-setup-pimatic-from-scratch .  
follow the steps from no. 11 downwards.

**Comment by poeml** [comment]
Hi,

I just observed that when pimatic has been started via the "service" tool, and crashes, it can't be started again via the service tool. I assume that some pid file or other state file is not cleaned up. Anyhow, after issuing a "service pimatic stop" once, "service start" works again for me.

So to fix would be to clean up the state file in case of a crash, or to have the init script look closer if pimatic is really running. (Just guessing, I didn't look into the details.)

HTH
Peter

**Comment by thorstenreichelt** [comment]
The post pimatic from scratch after a clean install works fine now. Thanks for help!
