### ISSUE TITLE
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'length'  - Receiver Homeduino 

### ISSUE THREAD

**Issue by sanstarr** [pimatic/pimatic#704]
Error Message:
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'length' of undefined at Function.Buffer.concat (buffer.js:491:20) at afterRead 

(/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:323:36) at /home/pi/pimatic-app/node_modules/pimatic-

homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9 at Object.wrapper [as oncomplete] (fs.js:454:17) This is most probably a bug in pimatic or in a 

module, please report it!

---

Pimatic crashes between 1-2 times in 2 days (before the last update) - now, with this error message - only the Receiver does not work (Homeduino, Nano)

Thanks!

**Comment by mwittig** [comment]
I had this problem too and it turned out to be powering issue in my case. What kind of power adapter do you use for raspberry? How many USB devices do you have attached to it?

**Comment by sanstarr** [comment]
Hi!
I use a Power Adapter with 2000mA
USB Devices: Only the Arduino nano (with 433MHz Receiver + Transmitter)
Other Equipment: Raspi Cam + I2C Display + DS1820 - Too much for this Adapter?

**Comment by incmve** [comment]
Since a few days I am also receiving a simmelar error, nothing changed in my setup.
It's not daily and my pimatic keeps running.
```
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'length' of undefined at Function.Buffer.concat (buffer.js:491:20) at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:323:36) at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9 at Object.wrapper [as oncomplete] (fs.js:454:17) This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by sweetpi** [comment]
However probably pimatic-homeduino is not working anymore, if the error occures. This error indicates a problem with the (usb) serial connection to the arduino. Mostly a hardware issue: broken arduino, unrelayable power supply, bad cable,...

I can't do very much about this..
