### ISSUE TITLE
A uncaught exception occured: Error: read ECONNRESET

### ISSUE THREAD

**Issue by asksimplicity** [pimatic/pimatic#709]
```error [pimatic]: A uncaught exception occured: Error: read ECONNRESET at errnoException (net.js:901:11) at TCP.onread (net.js:556:19) This is most probably a bug in pimatic or in a module, please report it!```

I think this has something to do with my doorsensors because a related rule gave an econnreset error too:

``` Error on evaluation of rule condition of rule e-mail-indien-voordeur-wordt-geopend: read ECONNRESET```

**Comment by sweetpi** [comment]
Which plugin does the doorsensor belong to?

**Comment by asksimplicity** [comment]
pimatic-homeduino.

**Comment by sweetpi** [comment]
Thats strage, because homeduino does not use a tcp connection.

**Comment by asksimplicity** [comment]
Maybe it's because I'm sending an e-mail when the door is opened?

{
      "id": "voordeur-deurcontact",
      "name": "Voordeur",
      "class": "HomeduinoRFContactSensor",
      "protocols": [
        {
          "name": "contact2",
          "options": {
            "id": xxxxxx
          }
        }
      ],
      "autoReset": true,
      "resetTime": 120000
    }

**Comment by mwittig** [comment]
How do you send e-mail? Via pimatic-mail or pimatic-shell-execute?

**Comment by asksimplicity** [comment]
plugin: mail.

Rule:

   {
      "id": "e-mail-indien-voordeur-wordt-geopend",
      "name": "e-mail indien voordeur wordt geopend",
      "rule": "if voordeur-deurcontact is opened then send mail to:\"mark.w.huys@gmail.com\" subject:\"Security: Voordeur geopend op {date()}\" text:\"Op {date()} werd de voordeur geopend.\" and push title:\"Voordeur werd geopend op {date()}\" message:\"Voordeur werd geopend op {date()}\"",
      "active": true,
      "logging": true
    },

**Comment by sweetpi** [comment]
@asksimplicity Did the error occur just one time (maybe no internet) or does is appear periodically?

**Comment by asksimplicity** [comment]
It happened a few times, without specific timing; I'm quite sure the internetconnection was working at the time. However, since the second last update I haven't seen the error :)

**Comment by sweetpi** [comment]
Please reopen, if it happens again
