### ISSUE TITLE
[pimatic-mobile-frontend] Custom Dimmer Attributes not displayed

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#710]
I have implemented a custom Dimmer and would like get additional attributes displayed (everyting except state and dimlevel) as it is possible with Switch devices, for example. Extending the `dimmer-template` as part of index.jade is farirly easy, but I am struggling with proper style settings, to get everyting rendered, nicely.  So, I need some help here, please.

**Comment by sweetpi** [comment]
@mwittig I've pushed a patch for this: https://github.com/pimatic/pimatic-mobile-frontend/tree/dimmer-attributes

Could you check if it works for you.

**Comment by mwittig** [comment]
@sweetpi Thank you very much for looking into this. I'll give it a try asap.

**Comment by mwittig** [comment]
@sweetpi Sorry for the delay in reply. Great! Your patch works as expected

**Comment by sweetpi** [comment]
Nice, published it.
