### ISSUE TITLE
Translation error in openweather dutch

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#712]
Hello,
There is a translation error when I use language "nl".
rain should be regen and snow should be sneeuw !!

![image](https://cloud.githubusercontent.com/assets/13299398/9955479/addc2cea-5df1-11e5-8053-b433d2963379.png)

**Comment by mwittig** [comment]
Hi. Thanks for your report! Actually, the attribute names have not been localized yet. I have filed a feature request for this (see link above) as we have a separate queue for pimatic-openweather. 

Please close this ticket, thanks!

**Comment by Ruba5913** [comment]
Ok. thank you for the quick respons
