### ISSUE TITLE
not defined error

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#716]
Since today i get these errors everytime the rule executes:

12:40:00error [pimatic]: rule wake-phones error executing an action: __ is not defined
12:40:00error [pimatic]: rule wake-phones error executing an action: __ is not defined
12:40:00error [pimatic]: Error on evaluation of rule condition of rule wake-phones: __ is not defined

The rule:

if every 5 minutes then execute "sudo hping3 -2 -c 3 -p 5353 192.168.1.5 >/dev/null 2>&1 || true" and execute "sudo hping3 -2 -c 3 -p 5353 192.168.1.6 >/dev/null 2>&1 || true" and execute "sudo hping3 -2 -c 3 -p 5353 192.168.1.7 >/dev/null 2>&1 || true"

**Comment by mwittig** [comment]
Did you update to the latest pimatic version 0.8.83?

**Comment by sweebee** [comment]
Havent updated. But there is something terrible wrong. I refreshed the mobile frontend in the browser and all i get is Cannot GET /.

**Comment by sweebee** [comment]
Looks like a lot of files are gone in the mobile frontend plugin. I'm trying to reinstall mobile frontend

**Comment by sweetpi** [comment]
Maybe a problem while updating. @sweebee Just in case make sure you have an backup of your sd card.

**Comment by sweetpi** [comment]
I justed published the update for the pimatic-kodi package. So the error should be gone.
