### ISSUE TITLE
[Forum] Can't login with github.

### ISSUE THREAD

**Issue by Oitzu** [pimatic/pimatic#718]
Forum software responds with following:
```
Internal error.
Oops! Looks like something went wrong!
/auth/github/callback
Cannot read property '0' of undefined
```

**Comment by leader21** [comment]
guess that issue results from the latest updated of nodebb to v0.8.2

**Comment by Oitzu** [comment]
https://community.nodebb.org/topic/6467/google-facebook-and-twitter-sso-gone/12
Maybe the last "tip" solves the problem?

**Comment by Oitzu** [comment]
Works again. :+1:
