### ISSUE TITLE
[pimatic] Strategy for migration to node v4.x

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#719]
According to [LTS](https://github.com/nodejs/LTS/ node), v0.10 is in maintenance mode and support will end by 1st of October 2016. Therefore, we need a strategy and plan for the migration to a newer version of nodejs, perferably node version 4.x.

See also [API changes between v0.10 and v4](https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4). However, beyond the documented API changes there are subtle differences with events handling which may cause problems in some edge cases.

**Comment by sweetpi** [comment]
:+1: 

I think we will have the most trouble with native modules used by plugins:

 * pimatic-homeduino and other use node-serialport: not yet ready, but there is a pull request: https://github.com/voodootikigod/node-serialport/pull/566
 * pimatic-gpio uses onoff: seems to be ready: https://github.com/fivdi/onoff#installation
 * pimatic-ble uses noble: ?
 * pimatic-dht-sensors uses node-dht-sensor: need to be updated
 * pimatic-ping uses node-raw-socket: almost ready: https://github.com/stephenwvickers/node-raw-socket/commit/f30be221c1244ca2914d6648e9e47e1081d12d7d
 * pimatic-sysinfo: uses nsutil, needs to be updated

I hope that are all. I think the most important and critical is node-serialport. If the update is ready and published I think we can go.

I think we should bump the version of pimatic to v0.9 for node v4 support. So that pimatic v0.8 supports only v0.10 and pimatic v0.9 node v4 (and greater).

**Comment by mwittig** [comment]
Thanks for your swift reply! I agree, the modules using native code will be troublesome and it is good to see some progress has already been made on some important base modules like node-serial, on-off. To get myself started I thought about using Vagrant to setup some base image(s) for testing. This way, it would be possible to trial different setups, easily. As part of this I'll also have a look at https://github.com/baswenneker/vagrant-pimatic-dev

I'll keep you posted on this. Another to look at is npm3 which also introduces some breaking changes.

**Comment by fivdi** [comment]
Yes, onoff is ready so there will be no problems there.

Not sure if it's relevant, but pimatic-lcd is missing in the list above. It depends on i2c-lcd which in turn depends on native module i2c. i2c doesn't support Node.js 4. Of course, you could always switch over to i2c-bus which does support Node.js 4 :)

**Comment by sweetpi** [comment]
@fivdi i2c-bus sound create. I will do some test with it. I'm currently don't use the lcd anymore, because it sometimes gets "out of sync" and only displays garbage. Maybe switching to i2c-bus does help here, too.

**Comment by mwittig** [comment]
@sweetpi @fivdi As we recently had a request to support [multiple LCD displays](http://forum.pimatic.org/topic/688/multiple-lcds-and-special-characters) and I would like to integrate support for monochrome OLED displays I am considering the development of new new plugin which can support both display types. For OLED I am planning to look into [oled-js-bpi](https://github.com/4ib3r/oled-js-pi). What do you think?

NB: Some OLED displays (such as SSD1306) support both SPI and I2C. I am planning to investigate both. I think I2C is good enough for text, but it may be too slow to display to display monochrome images.

**Comment by fivdi** [comment]
@sweetpi I've only ever used HD44780 LCDs with a parallel interface and when garbage was displayed it was usually a timing issue, the software wasn't waiting long enough for the display to complete its work,

@mwittig i2c-bus plays well with multiple devices on the bus so multiple LCD displays shouldn't be a problem, provided that the software driving the LCD actually uses i2c-bus. I haven't use OLED displays either and can't say much about how they perform with I2C.

**Comment by mwittig** [comment]
@sweetpi I have tried to setup pimatic as is on node4.1 and ran into the following problem:

```
vagrant@debian-jessie:~$ npm install pimatic --prefix pimatic-app --production
vagrant@debian-jessie:~/pimatic-app$ cp ./node_modules/pimatic/config_default.js ./config.json                                          
vagrant@debian-jessie:~/pimatic-app$ vi config.json #set password
vagrant@debian-jessie:~/pimatic-app$ sudo node_modules/pimatic/pimatic.js
coffee-cache: compiling coffee-script file "lib/daemon.coffee"...Done
coffee-cache: compiling coffee-script file "startup.coffee"...Done

/home/vagrant/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/cap                                              tured_trace.js:300
    var firstStackLines = firstLineError.stack.split("\n");
                                        ^
illegal access
```

I have managed to work-around the issue by removing and re-installing pimatic's deps as follows:
```
vagrant@debian-jessie:~/pimatic-app$ cd node_modules/pimatic/
vagrant@debian-jessie:~/pimatic-app/node_modules/pimatic$ rm -rf node_modules
vagrant@debian-jessie:~/pimatic-app/node_modules/pimatic$ npm install --production
```

After this, I can start-up pimatic without errors. Does the pimatic package contain pre-built packages and if yes, is it possible to override that?

**Comment by mwittig** [comment]
@sweetpi Regarding nsutil, this package has been ported to nan, meanwhile. So, may be it is enough to rebase your fork with the current nsinfo master.

**Comment by sweetpi** [comment]
> After this, I can start-up pimatic without errors. Does the pimatic package contain pre-built packages and if yes, is it possible to override that?

Yes dependencies get be bundled into the package: https://github.com/pimatic/pimatic/blob/master/package.json#L66

I will update all dependency and publish a new version.

**Comment by mwittig** [comment]
Ah, ok. Thanks!

**Comment by capitalfuse** [comment]
upgraded node v4.2.1, and success install and working dht-sensors plugin modified master code(see git pimatic-dht-sensors forked by "capitalfuse" ), but pin No. should be changed from No. of wiringPi to GPIO No. directly. Next, I tried to install sysinfo plugin, but for the following errors, I couldn't;

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.10-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/pimatic-dev/node_modules/nsutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

anybody got hints for this issue?

**Comment by sweetpi** [comment]
> @sweetpi Regarding nsutil, this package has been ported to nan, meanwhile. So, may be it is enough to rebase your fork with the current nsinfo master.

**Comment by capitalfuse** [comment]
thanks to @sweetpi showing some hints for this build error issue.
I changed nsutil fork to x6doooo's one modified for "nan". but below errors;
pi@raspberrypi ~/pimatic-dev $ npm install https://github.com/capitalfuse/pimatic-sysinfo.git#development
-
> nsutil@0.1.4 install /home/pi/pimatic-dev/node_modules/pimatic-sysinfo/node_modules/nsutil
> node-gyp rebuild

make: Entering directory '/home/pi/pimatic-dev/node_modules/pimatic-sysinfo/node_modules/nsutil/build'
  CXX(target) Release/obj.target/nsutil_linux/src/sutil/sutil_linux.o
  CXX(target) Release/obj.target/nsutil_linux/src/nsutil/nsutil_linux_funcs.o
In file included from ../src/nsutil/nsutil_linux_funcs.h:2:0,
                 from ../src/nsutil/nsutil_linux_funcs.cpp:1:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/nsutil/nsutil_linux_funcs.h:2,
                 from ../src/nsutil/nsutil_linux_funcs.cpp:1:
/home/pi/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/pi/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/pi/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/nsutil/nsutil_linux_funcs.h:2:0,
                 from ../src/nsutil/nsutil_linux_funcs.cpp:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), size)’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
nsutil_linux.target.mk:92: recipe for target 'Release/obj.target/nsutil_linux/src/nsutil/nsutil_linux_funcs.o' failed
make: *** [Release/obj.target/nsutil_linux/src/nsutil/nsutil_linux_funcs.o] Error 1
make: Leaving directory '/home/pi/pimatic-dev/node_modules/pimatic-sysinfo/node_modules/nsutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.10-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/pimatic-dev/node_modules/pimatic-sysinfo/node_modules/nsutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.10-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/capitalfuse/pimatic-sysinfo.git#development"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! nsutil@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nsutil@0.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nsutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nsutil
npm ERR! There is likely additional logging output above.

Would anyone like to show me more hints for this issue?  Should I wait for next version of Pimatic?

**Comment by sweetpi** [comment]
I think nsutil has to be ported to NAN 2.0.

**Comment by capitalfuse** [comment]
Appreciate for your hints. Success to port to Nan 2.0 using the reference from npm "upgrade-utils". In ~/pimatic-app,  $ npm install https://github.com/capitalfuse/pimatic-sysinfo.git#development

**Comment by mwittig** [comment]
So far, I have been using node v4 in a vagrant box which was easy to install. On Raspi, however, the setup can be still cumbersome if you don't want to build node yourself and you're still running on Wheezy. I found the following site useful, however, the latest build did not work for me out of the box, but should be easy to fix. http://node-arm.herokuapp.com/

If you know anything better, please let me know! Thanks

**Comment by sweetpi** [comment]
Didn't try, but the great thing with node v4 is that there are official binaries for arm: https://nodejs.org/dist/v4.2.3/

So you could use them.

**Comment by mwittig** [comment]
Ah, ok. Thanks for pointing this out. So, I'll use the official distribution then. The other link may be worth having a look at for installation on Wheezy which requires some tweaks. Basically, you need to upgrade to gcc v4.8

**Comment by fivdi** [comment]
There's also some information about when g++ 4.8 or higher is required [here](https://github.com/fivdi/onoff/wiki/Node.js-v4-and-native-addons).

Another good source of Node.js binaries is NodeSource. Details and installation instructions can be found [here](https://github.com/nodesource/distributions). However, NodeSource only provide ARMv7 binaries for machines like the Raspberry Pi 2.

**Comment by mwittig** [comment]
@fivdi Thanks for the links! It is great that nodejs binraies are now officially provided for raspi. Hopefully, more platforms will follow.

**Comment by fivdi** [comment]
@mwittig yes, it's good that there are now official ARM binaries available.

What's a little unfortunate is the fact that the Node.js v0.10.29 binaries that come pre-installed with Raspbian Jessie 2015-11-21 are broken. It's not possible to install native add-ons with this version of Node.js.

**Comment by fivdi** [comment]
It appears to be possible to workaround the issue that occurs when installing native add-ons with Node.js v0.10.29 on Raspbian Jessie 2015-11-21. See [here](https://github.com/fivdi/onoff/wiki/Node.js-v0.10.29-and-native-addons-on-the-Raspberry-Pi) for details.

**Comment by benbeton** [comment]
Hi,

I'm running Homebridge on my Pi (requires NodeJS 4.0) 
Additional I wan't to use pimatic on the same device.  (NodeJS 0.10.24)

Unfortunately I don't get it, how to run pimatic with Node 4, like posted above.
I'm not that experienced with NodeJS.

Would be great if some one can help and explain how to get pimatic up and running with NodeJS 4.0.
I know there are issues, but I wan't to try cause Homebridge and pimatic would be a perfect combination.

Is it possible to run 2 NodeJS versions on the same machine?! 

regards

**Comment by michbeck100** [comment]
@benbeton if you like homebridge you will love [pimatic-hap](https://github.com/michbeck100/pimatic-hap)

Anyways, is there any progress on this topic?

**Comment by benbeton** [comment]
thanks @michbeck100 I'll have look at it!
Since running Homebridge as a dockerized version, updating pimatic to work with Node 4 is not that important (to me) anymore. 

But would be a good thing to do it in near feature

**Comment by mwittig** [comment]
I think we can close this now. Please re-open if you wish to follow-up.
