### ISSUE TITLE
error [pimatic]: Could not find action "getGuiSetttings".

### ISSUE THREAD

**Issue by jensebub** [pimatic/pimatic#720]
after update to pimatic 0.8.86 following error appeares
```error [pimatic]: Could not find action "getGuiSetttings".```

regards 
jensebub

**Comment by sweetpi** [comment]
Thanks for reporting. Did you update the mobile-frontend as well?

Maybe needs a refresh on all devices, then the error should be gone.

**Comment by jensebub** [comment]
I've forgotten my smartphone.
After relogon everything is fine.
Thx

Regals
jensebub
