### ISSUE TITLE
Sending same value again via API did not work as expected 

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#721]
I want to send periodically sensor data to pimatic via api. In principle such a request looks like

curl -X PATCH \
       --header "Content-Type:application/json"  \
       --dat '{"type": "value", "valueOrExpression": 12}' \
       --user "user:password" \
       http://localhost/api/variables/temperature02

In pimatic GUI I watch the variable in graph view. As long as the value changes the graph is updated, but when the value keeps the same it is not stored. I also think, the following identical values are not stored into the database, because when I restart the graph those datapoints are not seen.
In database configuration I defined an avarage interval of 5 minutes. The value is updated about every minute.

**Comment by sweetpi** [comment]
The problem is, that currently a variable only emits an update event, if it changed. However I will change this in the future.

**Comment by Heizelmann** [comment]
Thanks a lot. Meanwhile I will try a workaround. May be it will we better to keep this event (renamed as changed event) and add an additional one to distinguish between changed and update variables.

**Comment by sweetpi** [comment]
Should now work. @Heizelmann Can you confirm this with pimatic v0.8.88?

**Comment by Heizelmann** [comment]
@sweetpi: Thanks a lot!
 
A quick test showed that a variable is stored as data point via API even though when the value keeps the same. 
The rule predicate 'changes' still works as expected. The rule fires only if value changes.
Question is, how to fire a rule on update a variable without value change?  Does it require a new predicate? See my last post.
  
Pimatic is great!

**Comment by sweetpi** [comment]
Great! You can use the `$var gets updated` instead of `$var changes` predicate.

**Comment by Heizelmann** [comment]
Why reverted in pimatic v0.8.89?

**Comment by sweetpi** [comment]
Because it leaded to an infinite loop in some cases: https://github.com/pimatic/pimatic/issues/727

While the inital change was reverted in v0.8.89, a better version was introduced in v0.8.90: https://github.com/pimatic/pimatic/commit/76db56a4fc5adcdbfbfaed487a0805c3ca7b2f24

**Comment by Heizelmann** [comment]
Thanks!
