### ISSUE TITLE
cyclic rules - bug or feature?

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#723]
I am wondering about the expected behavior of "cyclic rules" where the rule action performs a state change  which causes condition to evaluate to true. I have the folling device and rule.

```
   {
      "id": "dummySwitch1",
      "class": "DummySwitch",
      "name": "Dummy Switch"
    },
   ...
   {
      "id": "dummyswitchrule1",
      "name": "dummySwitchRule1",
      "rule": "if $dummySwitch1.state changes then toggle dummySwitch1 ",
      "active": true,
      "logging": true
    }
```

I would expect turning the switch will cause the rule to toggle the switch forever.  However, the switch is only toggled once. Is this a bug or feature? By the way, if I add "after 1 second" to the rule text it will toggle forever. Seems like the rule action needs to be deferred (e.g. to the next tick) to be able to detect the next state change as part of the rule condition.

**Comment by sweetpi** [comment]
Its actually a feature. Rules are limited to be triggered one time all 500ms.(https://github.com/pimatic/pimatic/blob/81a01833287a41bd6f7f1c36bb42899bb7f9a91b/lib/rules.coffee#L882-L888) This prevents the rule from being triggering again.

**Comment by mwittig** [comment]
Thanks, This makes sense to me. I think this should be documented as part of http://pimatic.org/guide/usage/rules

Btw, is the website under version as well? This I could make suggested documentation changes via PRs.

**Comment by sweetpi** [comment]
Yes, pull requests are welcome: https://github.com/pimatic/pimatic-guide

**Comment by mwittig** [comment]
Great! Which tool and templates do you use? 
I am just asking as I notice some glitches like sub-headers ## and ### are not tranlated to html headings. I guess, the problem simply is there is no space after the ## and ### markers, e.g.

###Built in  ==> will not be transformed properly
### Buli in ==> transformed to a heading

**Comment by sweetpi** [comment]
I'm using http://docpad.org/ with https://github.com/docpad/docpad-plugin-marked/
