### ISSUE TITLE
escaping curly braces in execute command

### ISSUE THREAD

**Issue by quantenschaum** [pimatic/pimatic#725]
I just updated pimatic (where do I find the version of pimatic itself in the web UI?) to shell-execute 0.8.11 and this broke previously working rules using the execute command.

The rule

    if $brightness.dimlevel changes
    then execute "curl -s -X PUT http://hue/api/developer1/lights/2/state -d '\{ \"bri\": $d \}' "

had to be changed to

    if $brightness.dimlevel changes
    then execute "curl -s -X PUT http://hue/api/developer1/lights/2/state -d '\{ \"bri\": $d }' "

The closing curly brace must not be escaped.

Is this a bug or a feature? It broke existing rules.

**Comment by sweetpi** [comment]
Thanks for reporting. It's a bug, should be fixed in pimatic v0.8.87.

**Comment by quantenschaum** [comment]
Yupp, working again. Thanks.

**Comment by mwittig** [comment]
@sweetpi Seems like the escaping for /n was broken too. One of my rules failed at least. I had to change \n to \\n in the configuration text.

**Comment by sweetpi** [comment]
There was a bug in the json parse (at config loading), that parsed `{"rule": "foo \\n  bar"}` (escaped backslash followed by n) to `{"rule": "foo \n  bar"}` (newline char), which leaded to a `\n` newline character in the saved config file, after a pimatic restart. If you want to use a new line in a rule, you have to enter `\n`, which should be json serialized to `\\n`. So `\\n` in the json file is correct. Make sure that you dependencies are uptodate (https://github.com/pimatic/pimatic/commit/1876ede9d4ac5573e7889ef66f388e8a4f739904).
