### ISSUE TITLE
Api Errors on Open-weather 0.8.16 plugin

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#726]
After upgrading Open-weather from 0.8.15 to 0.8.16

error [pimatic-openweather]: Unable to parse response: Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by mwittig** [comment]
See [README](https://github.com/josecastroleon/pimatic-openweather/blob/master/README.md)

**Comment by leader21** [comment]
You will now have to get your own api key from openweathermap.org and insert this into your openweather device 
"apiKey": "xxxxxxxxxx",

**Comment by edautz** [comment]
After obtaing the key and updating the openweater plugin and changing the country parameter. It works. Thanks for the swift support.
