### ISSUE TITLE
bug with DummyHeatingThermostat temperatureSetpoint and rule comparison

### ISSUE THREAD

**Issue by kregory** [pimatic/pimatic#728]
I have a rule that turn a device on when the temperature is lower then DummyHeatingThermostat.temperatureSetpoint
If the temperatureSetpoint is set to something below 10 and the temperature is above 10 the rule is true instead of beeing false.

if dht22.temperature = 18 and tempsalonsettings.temperatureSetpoint = 9 the next test is true
"$dht22.temperature" < "$tempsalonsettings.temperatureSetpoint"

**Comment by sweetpi** [comment]
Could you post your comlete rule?

**Comment by kregory** [comment]
if Fenetre Salon is closed and \"$dht22.temperature\" < \"$tempsalonsettings.temperatureSetpoint\" then turn chauffageSalon on

**Comment by sweetpi** [comment]
Try to remove the quotes.

**Comment by kregory** [comment]
removing the quotes solve this issue, thank you

**Comment by sweetpi** [comment]
I've added some checks. An error is now thrown, if string get compared with "<", "<=",...
