### ISSUE TITLE
Updated pimatic to the latest. before evereything was working fine but now I get this error

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#729]
error [pimatic]: Error in VariablePredicateHandler: Can not compare strings with <=!
20:40:59debug [pimatic]: Error: Can not compare strings with <=! at VariablePredicateHandler._compareValues (/home/pi/pimatic-app/node_modules/pimatic/lib/predicates.coffee:643:23) at /home/pi/pimatic-app/node_modules/pimatic/lib/predicates.coffee:628:25 at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23) at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:507:31) at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:581:18) at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:697:14) at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:123:16) at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:133:10) at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:15:14) at process._tickDomainCallback (node.js:459:13)

**Comment by sweetpi** [comment]
Do you have a rules, where you compare two variables with "<=" ?

**Comment by Ruba5913** [comment]
Yes I have 2 rules with "<=" but they are not putted on yet, because the hardware isn't ready yet.
Before I wrote this bug here, I changed "<=" to "is less or equal than" but that didn't solve this issue.
I deleted the 2 rules completely and now the problem is solved.
Before the latest update of pimatic I didn't have any problem with these rules !!
So pimatic is now working as before. 
Thanks.

**Comment by sweetpi** [comment]
The variables you comparing in the rules are of type string and you can't compare string with "<=". Before the update pimatic did silently compare the strings (with a undefined result)...now it throws the error. Make sure that the variables are numbers and you should not get the error again.
