### ISSUE TITLE
[Bug] pimatic doesn't keep me logged in.

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#731]
I use the mobile frontend as web app on my iPhone. But since a while ago it doesn't log in automatically anymore. (almost) everytime i have to enter the username and password.

**Comment by Yves911** [comment]
are you using pimatic SSL server? Did you import certificate into the IOS?
I don't have issue with mine.
Also if you have pin pimatic to desktop, maybe you can delete it and recreate.

**Comment by sweebee** [comment]
I re imported the certificate. Let's see if it works now.

**Comment by sweebee** [comment]
Also re added The pinned app. But still doesn't work.  

iOS also won't remember the username and password. So everytime I have to enter them again.

**Comment by sweebee** [comment]
Okay. I found the problem. I have 2 pimatics running. Both in the same network. One is at home and the other one in an other building with a direct fiber connection. At home is running at 443 and the other one and 444. When I open pimatic at home and log in, close the app and open it again it works fine. But once I open the other pimatic and login I have to login again at pimatic home. And the other way around.

**Comment by sweetpi** [comment]
hm strage. The instances are running on different machines, right? Do you access them via the same domain / hostname?

**Comment by sweebee** [comment]
Yes on different machines and I use the same hostname.

**Comment by sweetpi** [comment]
Strange that different ports don't get handled as different realms => different cookies. Try to use either different hostnames or same login (user + pw) and same secret in config.

**Comment by sweebee** [comment]
Tried different hostnames and it works fine.
