### ISSUE TITLE
[Pimatic] Variable timing problem

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#734]
When using a variable with a duration in a rule.
For instance: 

If $alarm-melding = 1 for 2 minutes then <perform action> 

doesn't result in the action when the conditions are met.

**Comment by sweetpi** [comment]
How do you set the variable to 1?

**Comment by edautz** [comment]
I use a rule to set the variable

If PIR Sensor  is present and Alarmstatus is turned on for 5 minutes then $alarm-melding = 1

**Comment by edautz** [comment]
Tested again, but now it works. I think i got another problem.
