### ISSUE TITLE
[pimatic][devices] CometDECT thermostat implementation: technical questions

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#737]
I'm in implementation and have a couple of questions. The Thermostat has support for `HeatingThermostat` as well as `TemperatureSensor` functionality. I intend to subclass `HeatingThermostat` as its more complex:
- how should I implement both in one class or split into two classes/ devices?
- `TemperatureSensor` does not have internal _temperature variable and _setTemparature getTemperature unlike structure of the `PresenceSensor` - is this intentional? PR wanted?
- `HeatingThermostat` and `ThermostatItem` are already quite specific and complex. Would it make sense to have a base class of `SimpleXXX` that only hast the ability to define a temperature without all the auto etc buttons? PR wanted?

**Comment by sweetpi** [comment]
> how should I implement both in one class or split into two classes/ devices?

If it does make things not to complicated, I would split that in two device classes. I think it makes the gui more flexible and clear. Config is a little bit more work, but shouldn't be a problem if it is documented.

> TemperatureSensor does not have internal _temperature variable and _setTemparature getTemperature unlike structure of the PresenceSensor - is this intentional? PR wanted?

You are right this is inconsistent. A PR is welcome to add the missing default functions and variable.

> HeatingThermostat and ThermostatItem are already quite specific and complex. Would it make sense to have a base class of SimpleXXX that only hast the ability to define a temperature without all the auto etc buttons? PR wanted?

I am for keeping one complex (configurable version). If a feature is not needed or not supported by the real device it can be disabled. This has the advantage, that the gui must only support the one (complex) template, instead of different separate simplified versions.

If you need different modes (currently: manu, auto) or preset buttons (eco, comfy), I can rewrite the device class and item, so that the modes and preset buttons can be defined as part of the device implementation.

**Comment by andig** [comment]
>> how should I implement both in one class or split into two classes/ devices?

> If it does make things not to complicated, I would split that in two device classes.

I thought so and its utterly simple but the user would need to give 2 names then which I find confusing. I'll try with one but its easy enough to change.

> You are right this is inconsistent. A PR is welcome to add the missing default functions and variable.

Hah! Will do ;)

> I am for keeping one complex (configurable version). If a feature is not needed or not supported by the real device it can be disabled. This has the advantage, that the gui must only support the one (complex) template, instead of different separate simplified versions.

Right, but then I need some help:

  a. HeatingThermostat must e.g. make display of the valve position configurable
  b. The config options of unavailable controls should not be part of the userconfiguratble settings- where would I stick those "guiShowXXX=false" declaration?
  c. Adding my own attributes like the current temp becomes a pain. Is there a way to `$.extend` the parent class attributes? Otherwise code will invariably fail on missing attributes...

**Comment by sweetpi** [comment]
> After quick prototype: while I can hide the controls the values would still show up in the graph screen, e.g. for the unavailable valve value. Can those be hidden as well? Or go for a BaseThermostat after all?

Redefine the attributes with just the one you need. Then we extend the thermostat item (gui) to respect this.

> A separate TemperatureSensor also means that I cannot show temp setpoint and actual temperature in a single graph. Any ideas?

Why not? You can show attributes of different devices the same time.

> Last point (hope I'm not spamming but would like to do this properly): I could- when constructing the thermostat- add a TemperatureSensor to the device tree by code instead of user configuring it as it doesn't really support any customization. All the user would have to do then is create the thermostat, potentially configure a name for the TemperatureSensor and add both devices to his pages. What do you think? Too much magic?

No worries about spamming. I wouldn't do that. Just make it clear in the readme that both devices are needed / can be defined. If you dislike the two devices approach, I would also be happy to extend the thermostat device with support for the actual temperature. Its better then the magic :) I think you convince d me, that this is the better way.

**Comment by andig** [comment]
> Redefine the attributes with just the one you need. Then we extend the thermostat item (gui) to respect this.

Got it working now. Only change needed is to make `mode` access optional. Will submit PR.

>  If you dislike the two devices approach, I would also be happy to extend the thermostat device with support for the actual temperature.

I have both now. A thermostat device that has a temp attribute but not exposed in the gui plus a sensor if GUI is needed.

If you want a temp attribute at the thermostat let me know, maybe after user testing.

**Comment by andig** [comment]
Closing on feedback
