### ISSUE TITLE
[pimatic-mobile-frontend] How to debug gui items

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#740]
Duing my implementation I'm confronted with loads of stack traces like 

	16:44:56.001 [pimatic-mobile-frontend] Client error: this.getAttribute(...) is null
	16:44:56.039 [pimatic-mobile-frontend] {
	16:44:56.039 [pimatic-mobile-frontend]   "mode": "stack",
	16:44:56.039 [pimatic-mobile-frontend]   "name": "TypeError",
	16:44:56.039 [pimatic-mobile-frontend]   "message": "this.getAttribute(...) is null",
	16:44:56.039 [pimatic-mobile-frontend]   "url": "http://127.0.0.1:8088/",
	16:44:56.039 [pimatic-mobile-frontend]   "stack": [
	16:44:56.039 [pimatic-mobile-frontend]     {
	16:44:56.039 [pimatic-mobile-frontend]       "url": "http://127.0.0.1:8088/assets/index-ad69f87a7b4c86f86687f04bedc88735.js",
	16:44:56.039 [pimatic-mobile-frontend]       "func": "c",
	16:44:56.039 [pimatic-mobile-frontend]       "args": "",
	16:44:56.039 [pimatic-mobile-frontend]       "line": "5",
	16:44:56.039 [pimatic-mobile-frontend]       "column": "10625",
	16:44:56.039 [pimatic-mobile-frontend]       "context": [
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a,b,c,d,e,f,g,h,i=function(a,b){return function(){return a.apply(b,arguments)}},j=[].indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(b in this&&this[b]===a)return b;return-1}...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a=[].slice;!function(){var a,b;return jQuery.mobile.loader.prototype.fakeFixLoader=function(){},b={},a=function(){var a,c,d,e;d={text:\"\",textVisible:!0,textonly:!1},a=!1;for(c in b)e=b...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a=[].indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(b in this&&this[b]===a)return b;return-1};!function(){var b,c;return c=function(a,b){var c,d;return d=function(){var b,d,...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a;a=pimatic.tryCatch,$(document).on(\"pagebeforecreate\",function(){var b;if(null==pimatic.socket)return pimatic.socket=io(\"\"+document.location.host+\"/\",{reconnection:!0,reconnectionDela...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a={}.hasOwnProperty,b=function(b,c){function d(){this.constructor=b}for(var e in c)a.call(c,e)&&(b[e]=c[e]);return d.prototype=c.prototype,b.prototype=new d,b.__super__=c.prototype,b},...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a,b,c,d=function(a,b){return function(){return a.apply(b,arguments)}},e=[].indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(b in this&&this[b]===a)return b;return-1};b=pimatic...",
	16:44:56.039 [pimatic-mobile-frontend]         "(function(){var a;a=pimatic.tryCatch,$(document).ready(a(function(){var a,b;return a=function(){function a(){}return a.prototype.showLoginDialog=function(){var a;return this.redirectPage=(null!=(a=$.m..."
	16:44:56.039 [pimatic-mobile-frontend]       ]
	16:44:56.039 [pimatic-mobile-frontend]     },

It seems some attribute is missing- but I cannot find which or where. 

Could you point me to a place where to add logging, an assert or how to access env for purpose of the logger?

**Comment by sweetpi** [comment]
Do the following:

1. Set the `mode` option of the mobile-frontend to `"development"` (https://github.com/pimatic/pimatic-mobile-frontend/blob/master/mobile-frontend-config-schema.coffee#L14)
2. Clear all browser caches and delete all app settings. Best is to use an incognito tab for testing.

 =>You should get better stack traces.

In `"production"` mode the minified files are used and the coffee files only compiled ones. In `"development"` the files are compiled on request and no minification is done, so you should find the right places easily. If you have a special question for a device type, feel free to ask further.

**Comment by andig** [comment]
Perfect & wfm. Do you want to leave this open as "documentation"?

**Comment by sweetpi** [comment]
I added it to the Q&A.
