### ISSUE TITLE
[pimatic-mysensors] Manual Mysensors plugin install fails

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#744]
I have some issues with  the lastest Mysensors plugin (0.8.22)

After removing this plugin with npm

I try to revert to the earlier 0.8.21 version,  

sudo npm install pimatic-mysensors@0.8.21.

But it fails.

```
pi@raspberrypi-beneden /usr/local/pimatic-app $ sudo npm install pimatic-mysensors@0.8.21
npm http GET https://registry.npmjs.org/pimatic-mysensors/0.8.21
npm http 304 https://registry.npmjs.org/pimatic-mysensors/0.8.21
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist

> serialport@1.7.4 install /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
make: Entering directory '/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/0.10.24/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm"
gyp ERR! cwd /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.12.28+
node-pre-gyp ERR! command "node" "/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.24
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-mysensors@0.8.21"
npm ERR! cwd /usr/local/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/pimatic-app/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sweetpi** [comment]
What does `/usr/local/pimatic-app/npm-debug.log` say?

**Comment by edautz** [comment]
There are 2129 lines of out of npm-debug.log

These are the last lines:

2110 info preuninstall serialport@1.7.4
2111 info uninstall serialport@1.7.4
2112 verbose false,/usr/local/pimatic-app/node_modules,/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules unbuild serialport@1.7.4
2113 verbose /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/.bin,[object Object] binRoot
2114 info postuninstall serialport@1.7.4
2115 verbose about to build /usr/local/pimatic-app/node_modules/pimatic-mysensors
2116 info /usr/local/pimatic-app/node_modules/pimatic-mysensors unbuild
2117 info preuninstall pimatic-mysensors@0.8.21
2118 info uninstall pimatic-mysensors@0.8.21
2119 verbose true,/usr/local/pimatic-app/node_modules,/usr/local/pimatic-app/node_modules unbuild pimatic-mysensors@0.8.21
2120 info postuninstall pimatic-mysensors@0.8.21
2121 error serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
2121 error Exit status 1
2122 error Failed at the serialport@1.7.4 install script.
2122 error This is most likely a problem with the serialport package,
2122 error not with npm itself.
2122 error Tell the author that this fails on your system:
2122 error     node-pre-gyp install --fallback-to-build
2122 error You can get their info via:
2122 error     npm owner ls serialport
2122 error There is likely additional logging output above.
2123 error System Linux 3.12.28+
2124 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-mysensors@0.8.21"
2125 error cwd /usr/local/pimatic-app
2126 error node -v v0.10.24
2127 error npm -v 1.3.21
2128 error code ELIFECYCLE
2129 verbose exit [ 1, true ]

**Comment by sweetpi** [comment]
Could you upload the whole file or use pastebin (http://pastebin.com/)?

**Comment by edautz** [comment]
I renamed the npm-debug.log file to npm-debug.jpg. Otherwise I have not the permissions to upload a text file.

Hope you can rename and read it.

![npm-debug](https://cloud.githubusercontent.com/assets/11003867/11042219/3382348c-8716-11e5-9332-e21b80301cf6.jpg)

**Comment by edautz** [comment]
Dear SweetPi,

Does it help you when you recieve the logfile as an attachement on this mail?

Kind regards,

Edautz

**Comment by sweetpi** [comment]
I've received the log file, but can't spot the problem. You could try to install it again

```
sudo rm -r node_modules/pimatic-mysensors
sudo npm install pimatic-mysensors@0.8.21
```

**Comment by edautz** [comment]
I tried again, without success:

This is the complete errorlog. I got on the screen. Hopefully you can spot the problem now.


pi@raspberrypi-beneden /usr/local/pimatic-app $ sudo npm install pimatic-mysensors@0.8.21
npm http GET https://registry.npmjs.org/pimatic-mysensors/0.8.21
npm http 304 https://registry.npmjs.org/pimatic-mysensors/0.8.21
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist

> serialport@1.7.4 install /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
make: Entering directory '/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/0.10.24/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.12.28+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm"
gyp ERR! cwd /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
node-pre-gyp ERR! System Linux 3.12.28+
node-pre-gyp ERR! command "node" "/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.24
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/usr/local/pimatic-app/node_modules/pimatic-mysensors/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-mysensors@0.8.21"
npm ERR! cwd /usr/local/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/pimatic-app/npm-debug.log
npm ERR! not ok code 0

**Comment by sweetpi** [comment]
see: https://github.com/voodootikigod/node-serialport/issues/535
Try:
```
sudo npm install --unsafe-perm pimatic-mysensors@0.8.21
```

**Comment by mwittig** [comment]
@edautz Can you please let me know what kind of problems you have with the latests version pimatic-mysensors?

**Comment by edautz** [comment]
I started using  pimatic-mysensors@0.8.21. I got with this version correct sensor readings in combination with a serial gateway. After implementing pimatic-mysensors on my second pi, I got some times wierd sensors readings, but it was in combination with version 0.8.22.  I tried to revert to 0.8.21 on my second pie to check if the problem then is gone.

I have to test the @sweetpi solution for reverting to 0.8.21 and wil check the problem again.

**Comment by edautz** [comment]
The command
 
sudo npm install --unsafe-perm pimatic-mysensors@0.8.21

works with some WARNINGS:

npm WARN unmet dependency /usr/local/pimatic-app/node_modules/pimatic/node_modules/convict requires cjson@'0.3.0' but will load
npm WARN unmet dependency /usr/local/pimatic-app/node_modules/pimatic/node_modules/cjson,
npm WARN unmet dependency which is version 0.3.1

But the plugin pimatic-mysensors@0.8.21 is installed en at the first glance is working properly.

@sweetpi Thanks very much for your help. Very much appreciated!
