### ISSUE TITLE
Name of trigger device

### ISSUE THREAD

**Issue by iMarvinS** [pimatic/pimatic#746]
Is there a way to get the name of the device which triggered the rule?
I try to do the following:

IF alarm is turned on and contact-garage or is opened or contact-cabin is opened THEN execute " wget curl -X POST https://maker.ifttt.com/trigger/alarmTriggered/with/key/1337?value1=$TRIGGER_DEVICE"

I´d like $TRIGGER_DEVICE (or whatever you call it) to be the plain string name of the device.

Is there already something like this implemented or can it be done without problems?

**Comment by mwittig** [comment]
What do you mean exactly by trigger? As far as I can see your example has three triggers?!

**Comment by iMarvinS** [comment]
Maybe my choice of words was not ideal. I want to have some kind of secret variable for example called "$TRIGGER_DEVICE " which conatins the name of the device which initially triggered the rule.
You can see that my rule contains an or-statement.
I exactly want to know the device of this statement that triggered the rule.
I want to have this kind of variable to build a burglar alarm which consists of several contacts and pirs.
When alarm is triggered I request the IFTTT Maker channel with a variable which tells me which contact was opened.

**Comment by leader21** [comment]
maybe do it with a workaround by creating further rules? 
`IF alarm is turned on and contact-garage is opened THEN set $TRIGGER_DEVICE = "Garage"`
and
`IF alarm is turned on and contact-cabin is opened THEN set $TRIGGER_DEVICE = "Cabin"`

**Comment by sweetpi** [comment]
Currently predicates do not set variables you can use in the then part. However the system is build to support this in the future.

Currently you nee multiple rules, for example like @leader21 suggested.

**Comment by iMarvinS** [comment]
The idea of creating a rule for every contact is a bit impractical in my case because I have installed 31 of those.
I managed this problem by creating a variable and changing it on every modification of the contact device.
I´ve done the following modification to my contact class :
```
 variable = @plugin.framework.variableManager.getVariableByName('lastModContact')  
          if variable  
            variable._setValue(@name)
          
@_setContact(if value > 0 then on else off)
```
Maybe this can be solved more nicely in the upcoming version.
