### ISSUE TITLE
General z-wave Plugin Proposal 

### ISSUE THREAD

**Issue by renz45** [pimatic/pimatic#748]
I tried to post this to the forums, but for some reason it refuses to send me a confirmation email.

I'm planning on making a general z-wave plugin that works with the aeotec usb dongle, I've been experimenting with node-openzwave-shared and recently submitted a pull request for OSX compatibility which I've been using to great success. I was going to make something from scratch, but I like the idea of getting all the other device functionality with pimatic.

My questions are:

Can I use the rules api to create a builder ui for adding/configuring new z wave devices or is this out of the scope of pimatic? On that note, can I define rules in a more programatic way instead of using the expressions in the examples? There are just so many zwave devices, I'd hate to have to define them all individually, and it would be more useful to other users to have the builder option.

I'm planning on using https://github.com/atom/electron to make a desktop interface, along with the ability to start a server, add rules, general home automation setup/control, etc. I'd like to run this on a mac mini eventually for my home as opposed to a pie.

Do these few things sound possible using pimatic behind the scenes?

Thanks again!

**Comment by sweetpi** [comment]
> I tried to post this to the forums, but for some reason it refuses to send me a confirmation email.

I've marked you account renz45 as validated.

> Can I use the rules api to create a builder ui for adding/configuring new z wave devices or is this out of the scope of pimatic? 

This is a upcoming feature of v0.9 see #745

> On that note, can I define rules in a more programatic way instead of using the expressions in the examples? There are just so many zwave devices, I'd hate to have to define them all individually, and it would be more useful to other users to have the builder option.

What do you mean exactly? I'm a little confused because you seem to be mixing device configuration and rules.

For device setup: Currently devices must be added manually to the config. However an api for device discovery is planned.
For rules: Predicates and actions currently only support one device. So you have to mention each device you want to use in a rule. Groups would be a nice addition. I'm happy about proposals for that.

> I'm planning on using https://github.com/atom/electron to make a desktop interface, along with the ability to start a server, add rules, general home automation setup/control, etc. I'd like to run this on a mac mini eventually for my home as opposed to a pie.

Why not simply run pimatic on the mac and access the gui via browser? I would not reinvent a user interface. Sure you could use electron to display the current web interface in a "less browser like" way.

**Comment by renz45** [comment]
Thanks for the quick reply! 

I think my planned approach to using pimatic is largely based on my initial work with z wave and the necessity to pair/configure. I think I understand what you mean about having device configuration and rules confused. Device configuration would still be needed, at least at a general level to provide things like a ui to interact with. I think when I first made this post I was thinking pimatic was more of a low level interface to the various automation technologies rather then a large focus on providing a UI. (I've learned different after spending more time looking around).

My wife is a UX designer by trade and has all sorts of things she wants to try, which is what prompted the custom ui need. I'm likely going to just build something with ReactJS or AngularJS that plugs into the socket.io api.

I'd be willing to give grouping a go once I get more familiar with the code base. Some of the things I'm thinking about would probably benefit from that.

Thanks again for all the hard work on this library, I do a lot with NodeJS on a daily basis and am really glad I found something that isn't java for home automation dev that handles so many different devices. 

I'll take the rest to the forums :)

**Comment by sweetpi** [comment]
Sounds great!

The [pimatic-mobile-frontend](https://github.com/pimatic/pimatic-mobile-frontend) does have currently the most features. However it is bases on JQuery mobile (what I wouldn't use again) and knockout.js (where ReactJS or AngularJS are far better alternatives). Nevertheless it works very good and has a relatively nice ui imho.

There is a [angular-material-frontend](https://github.com/denniss17/pimatic-angular-material-frontend), which is very nice and supports almost all device types, however non configuration. So if you (or your wife) plan to use Angular team up with @denniss17.

A ReactJS gui would be really nice. I'm very interested in that (I have learned to love React in my latest  projects). I would love to build a new version of the mobile framework based on React, however I have not the time and other more important pimatic enhancements todo. So if you start that, I'm happy to contribute.
