### ISSUE TITLE
[pimatic][shell-execute][mysensors]

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#750]
I got a problem when sustract or add a variable from a shellsensor attributetype number with a variable from a mysensors multisensor type integer. In this case the shellsensor will be treated as 0, regardless the value of the shellsensor. A mulitisensor type number is not available, also a shellsensor type integer is not available.

**Comment by sweetpi** [comment]
Could you post your config of both devices and the rule?

**Comment by mwittig** [comment]
@edautz This is known bug which I reported about four weeks ago - see https://github.com/DheerajKhajuria/pimatic-mysensors/issues/46

The suggested bug fix has been merged yesterday into master. As it has not been released yet you can clone the master into your pimatic installation.

**Comment by edautz** [comment]
@mwittig I can't determine if the problem you describe solved my issue. But I am not a programmer. I will wait until @DheerajKhajuria releases the new version of the plugin and test again.
Thnxs.

**Comment by edautz** [comment]
After upgrading pimatic-mysensors to version 0.8.23 problem solved.
