### ISSUE TITLE
How to declare a button

### ISSUE THREAD

**Issue by saxn-paule** [pimatic/pimatic#753]
I need to declare a button, that triggers a bash script for de-/increasing the volume of my pioneer receiver.

The DummySwitches aren't usable, because they have a state. I need buttons, that are stateless and only do a "fire and forget". Is there a solution for it yet?

**Comment by Yves911** [comment]
You can add a button like this : 
```
    {
      "buttons": [
        {
          "id": "snap",
          "text": "⚡"
        }
      ],
      "id": "snap",
      "name": "Snap",
      "class": "ButtonsDevice"
    },
```
Pls use the forum for help request : http://forum.pimatic.org

**Comment by rutgerh** [comment]
Hi,

I think you are looking for 'ButtonsDevice".


Bye,

Rutger

**Comment by psc-bss** [comment]
Thank you. It's working. Here my config:
device:
```javascript
    {
      "id": "change-volume",
      "name": "AVR Volume",
      "class": "ButtonsDevice",
      "buttons": [
        {
          "id": "level_LO",
          "text": "Leiser"
        },
        {
          "id": "level_HI",
          "text": "Lauter"
        }
      ]
    }
```

My rule:
```javascript
    {
      "id": "avr-leiser",
      "name": "AVR leiser",
      "rule": "if level_LO pressed then execute \"sudo expect /home/pi/pioRemote/volume-down.sh\"",
      "active": true,
      "logging": true
    }
```

And the corresponding script for controling my VSX-921:
```javascript
#!/usr/bin/expect
set ip "192.168.0.15"

spawn "/bin/bash"
send "telnet $ip\r"
expect "BridgeCo AG Telnet server"
send "VD\r"
sleep 0.2
send -- "^]\r"
send  "quit\r"
```

**Comment by mwittig** [comment]
@psc-bss Have a look at http://forum.pimatic.org/topic/979/denon-marantz-avr-remote-control

May be you can re-use parts of the project (e.g., device definitions, rule definitions) for your own stuff.

**Comment by sweetpi** [comment]
This is more a quesiton for the forum. Please use the forum next time.
