### ISSUE TITLE
[pimatic-gpio] GpioSwitch: Handling of "defaultState" is broken (Bug)

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#759]
@sweetpi I think the handling of `defaultState` is broken. 
https://github.com/pimatic/pimatic-gpio/blob/master/gpio.coffee#L41-L44

Actually, lines 43-44 will never be executed as  `@config.defaultState` can never be undefined or null as it has a default value. Thus, it is not possible to recover the `lastState`from database.

This happened due to a falsy change proposal suggested by @dfliess
https://github.com/pimatic/pimatic/issues/665 which led to https://github.com/pimatic/pimatic-gpio/commit/440264d9aa6e07dcf33dcc0ad1211345b04cdc61

The behaviour before that commit was also wrong as it did not allow for setting a the initial state to false. Actually, this requires a tri-state, which could be implemented by adding another , e.g. `enableDefaultState`.

I'll make a PR for this shortly.

**Comment by sweetpi** [comment]
You are right. Why not just remove the default value for `defaultState` from the config scheme?

**Comment by mwittig** [comment]
@sweetpi I thought about this two, but then you're still not able to recover the lastState from DB - ir, is ir possible to make the property optional?

**Comment by sweetpi** [comment]
If we remove the default from the config, `defaultState` is null, if not set. So [the check](https://github.com/pimatic/pimatic-gpio/blob/master/gpio.coffee#L41-L44) works like intended. I quickly do the patch.

**Comment by sweetpi** [comment]
Oh it has no default state, so imho it should be working correct already.

**Comment by sweetpi** [comment]
@mwittig I think this can be closed?

**Comment by mwittig** [comment]
@sweetpi Yes, that's fine. I have added another PR adding documentation of the defaultState as part of the README
