### ISSUE TITLE
SocketIoClientDotNet vs pimatic: No cookie transmitted

### ISSUE THREAD

**Issue by neographikal** [pimatic/pimatic#760]
I'm trying to connect to the websocket server with the SocketIoClientDotNet c# client:

    public PimaticService()
        {
            ConnectionString = "http://url/?username=admin&password=blub";
            Connect();
        }

        public void Connect()
        {
            Socket = null;
            Socket = IO.Socket(ConnectionString);
            Socket.On(Socket.EVENT_CONNECT, () =>
            {
                Log.Info("Pimatic socket connected");
                Connected = true;
            });
            while (true)
            {
               Thread.Sleep(1000);
            }
        }

It tries to connect as far as I can see, but pimatic throws  a warning in the log: No cookie transmitted. What is going wrong?

**Comment by mwittig** [comment]
I guess the cookie is created by the server and you need to send it along with every request, which should be doable by simply setting some property (or calling a function once) to let SocketIoClientDotNet as the header for you. May be the following test code is any helpful to understand how to do it: https://github.com/Quobject/SocketIoClientDotNet/blob/master/Src/SocketIoClientDotNet.Tests.net45/ClientTests/ServerConnectionTest.cs#L1254-L1283
If this does not help please raise an issue on the SocketIoClientDotNet project

**Comment by sweetpi** [comment]
The log message you see is from the socket.io debug log stream. It's not pimatic specific, so best is to ask for help at he SocketIoClientDotNet github project.

It could be that you are missing some cookie handling.

**Comment by vanturenhout** [comment]
Maybe this will help:
```
var option = new IO.Options
                {
                    Reconnection = true,
                    ReconnectionDelay = 1000,
                    ReconnectionDelayMax = 3000,
                    Timeout = 20000,
                    ForceNew = true,
                    QueryString = "username=uname&password=pdw"
                };

                var socket = IO.Socket("http://YOUR_IP", option);
```
It works for me...
