### ISSUE TITLE
error moving device into group /error when moving device in to other group

### ISSUE THREAD

**Issue by hansjeu** [pimatic/pimatic#761]
After the update yesterday to mobile-frontend v0.8.76. i get an (or two) error moving a device into group and i get errors when moving device in to an other group.
the error i got first was:
error [pimatic-mobile-frontend]: Client error: TypeError: $root.createToggleGroupCallback is not a function.
After an other reset i get the error:
error [pimatic-mobile-frontend]: Client error: Unable to process binding "with: function (){return $root }"
Message: Unable to process binding "click: function (){return $root.createToggleGroupCallback($parent,$data) }"
Message: $root.createToggleGroupCallback is not a function

Greetings Hans

**Comment by incmve** [comment]
Got the same thing, removed the mobiel-frontend and re-installed it but that didn't fix it.

**Comment by koffienl** [comment]
Same here

**Comment by sweetpi** [comment]
Thanks for reporting should be fixed in pimatic-mobile-frontend v0.8.78.

**Comment by incmve** [comment]
When I fold or unfold the Ungrouped group I get this
```
Client error: Uncaught TypeError: h.apply is not a function
```
Devices are shown and I can move them so it's not a problem just to let you know.

**Comment by sweetpi** [comment]
@incmve Thanks for the notice. Did publish an additional fix for that.

**Comment by incmve** [comment]
Confirmed thanks
