### ISSUE TITLE
[pimatic-cron] Time Rules dont work correctly

### ISSUE THREAD

**Issue by Darkonionz** [pimatic/pimatic#764]
Hello i have a Probleme with the rules , 
 I Added Rules like "if its After 22:00 and before 6:00 then do stuff " These Rules dont run when its After 22:00 dont Know how to fix this Hope You Guys can help me

**Comment by sweebee** [comment]
the rule works fine. because when its 2300 its not before 0600.

use: "if its After 22:00 or before 6:00 then do stuff

**Comment by Darkonionz** [comment]
ah thank You im so a idiot to not notice this easy fault ;)

**Comment by sweebee** [comment]
Np, but next time ask questions like this on the forum. 

Met vriendelijke groet,

Wiebe Nieuwenhuis

www.wiebenieuwenhuis.nl
wiebenieuwenhuis@gmail.com
06-10 49 22 94
