### ISSUE TITLE
Collapsable groups in mobile frontend not in all browsers

### ISSUE THREAD

**Issue by Clark2309** [pimatic/pimatic#765]
Hi,
the collapsable groups does not work in Chrome on my iPad. In Safari it works.
Is this a bug?
Best regards Chris

**Comment by sweetpi** [comment]
What does "not work" mean exactly? Be sure to refresh the mobile-frontend twice and clear the cache if there are still problems.

**Comment by incmve** [comment]
On android it worked after refreshing in Chrome.

**Comment by Icesory** [comment]
After four refreshs in Chrome the collapsible groups appears.

**Comment by Clark2309** [comment]
After a few updates it works :-)
