### ISSUE TITLE
Please, what is the newest version of node.js to use for pimatic with raspian jessie

### ISSUE THREAD

**Issue by tkbi** [pimatic/pimatic#767]
Hi,
I'm quite new with all this stuffs around rasp pi2 and arduino, as well Partikel photon (which work great for me)

I have already installed an Owncloud on my rasp pi2, which is running almost a year without probklems in Version 8.2.0 now.
Because I'll will start a new Project, with my photon (have wifi !) to get a weather Station in my garden, and to switch on and off some actors (like lights, water filter pump etc.) i will use the Phonton for this, because wifi is working fast and id avaible around my garden.

Please for this, I have two question:

1.)  You are connecting the arduino with USB at the raspi and bind with pimatic, would it be posible to connect over wifi as well ?

2.) At the day (2 ago) I installed the pimatic, I got some yellow warnings, in case the node.js is not the neweset on (0.10.24), so I search and find at the node.js page only 0.10.26, but it's work.
Today I red, that the version 4.0XXX for armf71 will work on a raspi, is this version working already for pimatic ?

By the way, I tried fhem and pilight before, but pimatic look's like much better for using, and the webserver is stable, as well the integrated update function is a big Job.
fhem is to resources using, because off using a perl Server, and pilight is not stable - no Support at all now.

In this way, Gratulation for the well done work.

**Comment by mwittig** [comment]
For the time being please stick to the recommendations given in the [pimatic installation guide](http://pimatic.org/guide/getting-started/installation/), that is node v0.10.24. Unfortunately, there are no newer v 0.10.x builds for Raspberry unless a few unofficial builds which I do not recommend. If you know how to build node from source you can try to build latest-v0.10.x from source, but this has some pitfalls. Build time on Raspi2 is about 40 minutes. 

Regarding newer versions of node, Pimatic will most likely work, but some plugins won't. As part of pimatic v0.9 it is planned to have full support for node v4 which is the current long term support version. Node v5 is for nerds who always install the newest (beta) software on their computer and then complain it does not work properly ;) Note, no timeline has been set for pimatic v0.9.

Regarding, your arduino wifi question it depends on what to do:
* pimatic-homeduino - I don't think it is supported right now, but it is generally possible. There is side project called "homeduino-esp8266-node", but this is "work in progress"
* pimatic-johnny-five - supported
* pimatic-mysensors - should be supported using the mysensors serial gateway
