### ISSUE TITLE
[Pimatic-log-reader] Values not updated

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#768]
I made a logreader device following the setup from @leader21:

http://forum.pimatic.org/topic/664/sma-solar-inverter-device-via-sbfspot/1

But the device is only updates when pimatic is started. Not when pimatic running.

The source file is updated every 5 minutes,.

I am using log-reader 0.8.7 and pimatic 0.8.91

**Comment by edautz** [comment]
The logfile I used was created on another Raspberry and tranferred with SCP to the Raspberry with Pimatic. 

Even when I touch the files or edit with nano, the values are not updated with the log-reader. 

I discovered that the values are only updated when I copy the files locally to another filename and back again.

Is this a bug?

**Comment by mwittig** [comment]
Please reopen if the issue still occurs with pimatic 0.9
