### ISSUE TITLE
Shutter buttons squeezed together

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#770]
after updating to mobile frontend 0.8.80 my shutter controls are looking strange
![](http://www.youscreen.de/kbpgyuek55.jpg)

any suggestions?
having this on firefox and chrome as well as on my android mobile

**Comment by p4co86** [comment]
I noticed it too.

**Comment by sweetpi** [comment]
Thanks for reporting, should be fixed in monile-frontend v0.8.81.
