### ISSUE TITLE
[pimatic-calendar] socket hang-up

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#771]
wanted to test the new calendar plugin but getting this error 
![](http://www.youscreen.de/ljqqpsdz00.jpg)

**Comment by sweetpi** [comment]
Strange, with which calendar provider did you try (e.g. google)? How big is your ical file, if you download it yourself?

**Comment by leader21** [comment]
using google calendar, my ical file has approx 76kb

**Comment by sweetpi** [comment]
That shouldn't be a problem. Does the error happen all time?

**Comment by leader21** [comment]
happens once pimatic starts up. honestly I did not   investigate any further if the plugin works nevertheless. gonna try it later maybe

**Comment by leader21** [comment]
ok tested it and it works as expected!! sorry to bother with this issue.
thx for this nice plugin!!
