### ISSUE TITLE
not a bug not an error but not nice

### ISSUE THREAD

**Issue by hansjeu** [pimatic/pimatic#773]
i use the pulgin filter to eliminate some extremes in my location readings.
    {
      "class": "SimpleTruncatedMeanFilter",
      "id": "filter2",
      "name": "Filter2",
      "size": 5,
      "output": {
        "name": "afstand_weg",
        "expression": "$iphone-xxxxx.routeDistance",
        "acronym": "AW2",
        "type": "number",
        "unit": "m"
      }

when i start pimatic i get the error
error [pimatic-filter]: Error on device filter2: Input value is null or undefined

i understand filter needs 5 readings in this example, but is there no way to suppress this error?
As i said no bug, not an error but ......

Greetings Hans

**Comment by mwittig** [comment]
https://github.com/mwittig/pimatic-filter/issues/3

**Comment by mwittig** [comment]
Should be fixed now!
