### ISSUE TITLE
[pimatic-max] Autoreconnect to the cube

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#780]
Sometimes I receive this error: connection error: Error: read ECONNRESET
I would be glad if the plugin would try to reconnect itself instead of having to restart pimatic.

**Comment by leader21** [comment]
Which plugin you are talking about?

**Comment by Xento** [comment]
Oh I thought I saved the change to the title.

**Comment by sweetpi** [comment]
Added with pimatic-max v0.8.15
