### ISSUE TITLE
error [pimatic]: Cannot read property 'length' of undefined - using HomeduinoRFShutter - class,Shutter 4 protocol

### ISSUE THREAD

**Issue by TRIROG** [pimatic/pimatic#782]
Trying to control Rohrmotor24 motor using the shutter 4 protocol and HomeduinoRFShutter and i get the following:
 [pimatic] error: Cannot read property 'length' of undefined

Also HomeduinoRFShutter class is missing the stop button (or should another class be used for my roller shutters?)

if i use tthe same protocol with HomeduinoRFButtonsDevice class everything works normally (except my config gets awfully long)

Here is the excerpt from my config.json:
```
  "devices": [
    {
      "id": "Shutterds",
      "name": "ShutterDS",
      "class": "HomeduinoRFShutter",
      "protocols": [
        {
          "name": "shutter4",
          "options": {
            "channel": 0,
            "id": XXXXXXXX
          }
        }
      ]
    },

    {
      "id": "Shutterdsb",
      "name": "ShutterDSb",
      "class": "HomeduinoRFButtonsDevice",
      "buttons": [
        {
          "id": "roll1-up",
          "text": "Up",
          "protocols": [
            {
              "name": "shutter4",
              "options": {
                "id": XXXXXXXX,
                "channel": 0,
                "command": "up"
              }
            }
          ]
        },
    {
          "id": "roll1-stop",
          "text": "Stop",
          "protocols": [
            {
              "name": "shutter4",
              "options": {
                "id": XXXXXXXX,
                "channel": 0,
                "command": "stop"
              }
            }
          ]
        },
        {
          "id": "roll1-Down",
          "text": "Down",
          "protocols": [
            {
              "name": "shutter4",
              "options": {
                "id": XXXXXXXX,
                "channel": 0,
                "command": "down"
              }
            }
          ]
        }
      ]
    }
  ],
```

**Comment by mwittig** [comment]
Thank you for you bug report. I can reproduce this error and I think it same the same problem as reported 
on the forum http://forum.pimatic.org/topic/969/homeduinorfshutter-shutter3-how

**Comment by mwittig** [comment]
I have open a ticket on pimatic-homeduino for this.

**Comment by TRIROG** [comment]
OK
Also HomeduinoRFShutter class is missing the stop button (or should another class be used for roller shutters?)

**Comment by mwittig** [comment]
I am not sure why the Shutter UI has no stop button. **Please raise this as a question on pimatic forum.**

All shutter protocols we have seem to support the stop command, so, ther should be a stop button I think. As work-around you can use the buttons device you already have setup.

**Comment by Icesory** [comment]
The Shutter device has generally no stop button. The stop function is implemented as an reclick on the button. When you want to close you shutter, you click on down. The button change his color to blue. When the shutter reached the target high you must click again on the down button to stop the shutter.

**Comment by TRIROG** [comment]
Thank you for this explanation!
