### ISSUE TITLE
[shell-execute]  [pimatic-shell-execute]: ShellSwitch: stderr output from getStateCommand for Samsung TV

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#786]
Good morning. 

i get this error message when i stop my kwhmeter service.
```
 [pimatic-shell-execute]: ShellSwitch: stderr output from getStateCommand for Samsung TV: Terminated
grep: Schreibfehler: Datenübergabe unterbrochen (broken pipe)
```
First of all, i read my kwh meter with an arduino and write the data to a file.after that i have a logreader device.

this is my python programm to read the datat from the arduino.
```
#!/usr/bin/env python


import time
import serial
ser = serial.Serial('/dev/serial/by-id/usb-Arduino_LLC_Arduino_Leonardo-if00', 9600)

while 1:

    data = ser.readline()
    f = open("/root/log/kWhmeter.log","a")
    f.write(data)
    f.close()
```

But sometimes i have the problem, that the service is still alive, but the arduino sends no datat via serial to the logfile. 

i have this thing installed on a rpi1 wich works perfectly without any error, but on the rpi2 i get the described error.

when i then stop the service on the rpi2 i get the error message wich i describe at the beginning.

The Samsung thing is a shell switch.

Both systems run jessie

Thanks for any help !

**Comment by mwittig** [comment]
Getting a broken pipe is rare but not necessarily an error. May be the following post gives some hints on how to fix it in your case - http://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error

**Comment by mwittig** [comment]
No feedback. @p4co86, please reopen if you wish to follow up on this.
