### ISSUE TITLE
[pimatic-shell-execute] Add autoreset for ShellPresenceSensor

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#788]
SensorsDevices HomeduinoRFPir, HomeduinoRFContactSensor, MySensorsPIR have the autoreset option (properties autoreset, resetTime. Actually in ShellPresenceSensor this feature is missing.

See also http://forum.pimatic.org/topic/1271/autoreset-for-shellpresencesensor

**Comment by sweetpi** [comment]
Looks good. If you want, you can merge and publish it. I granted you npm and github permissions.

**Comment by mwittig** [comment]
Ok, thanks. Will do.
