### ISSUE TITLE
[pimatic-filebrowser]  no "configSchema" property

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#789]
Hey, after installing pimatic-filebrowser for using it to display the changelog, described here: https://forum.pimatic.org/topic/1263/solved-wanted-howto-see-pimatic-version-in-gui/, i get the following warning:

[pimatic] package.json of "pimatic-filebrowser" has no "configSchema" property. Could not validate config.

here is the filebrowser plugin config:
{
   "plugin": "filebrowser",
      "mappings": [
        {
          "path": "/files",
          "directory": "/"
        }
      ]
}

I couldn't find anything about a configSchema property. What causes this warning?

**Comment by mwittig** [comment]
I think this warning can be safely ignored as "pimatic-filebrowser"  does not expose devices. 

The code as part of the pimatic core checking the plugin descriptors could perhaps be improved to avoid this warning for plugins which don't expose devices.

**Comment by leader21** [comment]
Guess you're trying to install the changelog devices eh ;)
this message can be ignored. The file browser works anyways. having it too.

**Comment by thost96** [comment]
Thanks for your feedback.
