### ISSUE TITLE
Command Failed Error

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#790]
Hi, i'm getting this two errors and don't know what is causing this:

Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)

Has anyone an idea?

**Comment by mwittig** [comment]
When does it happen exactly and what is the result of this? It'll also be great if you can provide the log file, please.

**Comment by leader21** [comment]
i guess this has something to do with the changelog devices you are actually trying to implement. 
if not - forget everything below this line :joy: 

as i formerly said [](here https://forum.pimatic.org/topic/1263/solved-wanted-howto-see-pimatic-version-in-gui/10) you are only having 60 api calls per hour. if those are used up, there's an error. 
you can check wether you have any free api calls with this command ``curl https://api.github.com/rate_limit`
should give you something like that : 
![](http://www.youscreen.de/xfapmvxm91.jpg)

i have faced similar problems with that issue when testing the devices, especially i figured out that the rule `IF $pimatic-version-git.versionrequest gets updated THEN do some stuff` will be triggered at every start of pimatic. actually, i don't know exactly why... any idea how to solve this? usually the update of the CHANGELOG.md file and the parsing into the log files should only take place if the online version changes. 
the version request is a shellsensor that will be triggered at pimatic start and then the variable gets updated and then the rule will be triggered.
when you're now working at pimatic and start and stop multiple times you'll have this issue.
should be gone after you're done with your changings

**Comment by thost96** [comment]
@leader21 yes, i added the changelog device. I had totally overread this part of your tutorial.

**Comment by thost96** [comment]
@leader21 after waiting from yesterday due to today nothing on this error changes. So i restartet pimatic und run the `curl https://api.github.com/rate_limit`command. This is my output:

```
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 15,
      "reset": 1453036676
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1453035318
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 15,
    "reset": 1453036676
  }
}
```
I also added the pimatic log:
[pimatic-daemon.txt](https://github.com/pimatic/pimatic/files/93389/pimatic-daemon.txt)

The command was run after pimatic started succesfully. I also get no content in the changelog device. Paths are all ok.
