### ISSUE TITLE
[pimatic-mysensors] Attribute 'batterySensor' for MotionSensor missing

### ISSUE THREAD

**Issue by Heizelmann** [pimatic/pimatic#791]
see also https://github.com/DheerajKhajuria/pimatic-mysensors/issues/55

**Comment by mwittig** [comment]
I've closed this ticket as this appears to be duplicate.

**Comment by Heizelmann** [comment]
I placed it first to https://github.com/DheerajKhajuria/pimatic-mysensors/issues/55 and then I saw that on this plugin is not much conversation. Then I saw that here it is common to place issues for plugins with the plugin name in brackets as prefix to the title, so I did this too.

For me this is an important issue which should not overlooked.

**Comment by mwittig** [comment]
No worries. However, we should avoid duplication of issues.  DheerajKhajuria/pimatic-mysensors#55  is the right place as @DheerajKhajuria is maintaining the plugin
