### ISSUE TITLE
[pimatic-shell-execute] ShellSwitch executes shell command twice

### ISSUE THREAD

**Issue by scobby** [pimatic/pimatic#792]
Simple Shell switch:

    {
      "id": "test-shell-switch",
      "name": "test shell switch",
      "class": "ShellSwitch",
      "onCommand": "eventghost.sh spotify on",
      "offCommand": "eventghost.sh spotify off",
      "interval": 0
    },

all shellswitch commands are runs 2x with a delay of 2-3 seconds.
Log:
spotify  :  on
Di 19. Jan 20:35:07 CET 2016
spotify  :  on
Di 19. Jan 20:35:09 CET 2016

Please fix this!

**Comment by mwittig** [comment]
I can't reproduce your problem. 

Does this happen as a result of switch manually or is it as part of a rule - or may be even both?

**Comment by scobby** [comment]
no rule or something is triggered. its just a normal result of a switch event with the GUI. Currently i changed all my switches to the "execute ... "-method. This works without problems.

**Comment by mwittig** [comment]
So, you are saying it is happening when you switch manually with the UI? That's what I tested. I'll try again and outline my test setup.

**Comment by Icesory** [comment]
You have also problems with Homeduino. 
https://github.com/pimatic/homeduino/issues/23
Eventually is your pimatic installation broken?

Which  plugins did you have installed to. 
Can you post your complete config please.

**Comment by scobby** [comment]
added the config in issue https://github.com/pimatic/homeduino/issues/23

**Comment by scobby** [comment]
yeah it happen when i switch manual via webinterface.

**Comment by mwittig** [comment]
Here is how I have tested it:

### Device Configuration

```
    {
      "id": "Lampe-Fenster",
      "name": "Lampe-Fenster",
      "class": "ShellSwitch",
      "onCommand": "/home/pi/scripts/lampe-fenster.sh EIN",
      "offCommand": "/home/pi/scripts/lampe-fenster.sh AUS",
      "interval": 0
    },
```

### Shell Script

```
#!/bin/bash
echo "`date` $1" >> /home/pi/scripts/lampe-fenster.log
```

### Log Output

```
Fri Feb 12 11:18:08 CET 2016 EIN
Fri Feb 12 11:18:27 CET 2016 AUS
Fri Feb 12 11:18:30 CET 2016 EIN
Fri Feb 12 11:18:31 CET 2016 AUS
```

**Comment by mwittig** [comment]
Which browser do you use? - I have tested with Chrome 48, Firefox 43, Edge 25, and iOS Safari.

**Comment by scobby** [comment]
i try to reproduce later. using chrome and safari.

**Comment by mwittig** [comment]
@scobby any news on this?

**Comment by mwittig** [comment]
No feedback. @scobby please re-open if you still have the issue. Did you try to reproduce with the outlined test case?
