### ISSUE TITLE
Can not update pimatic

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#794]
Hello,

I have 2 rpi with pimatic and I can't update anymore.
I the errorlog I found this:

error [pimatic]: 504 - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

**Comment by leader21** [comment]
please restart pimatic, then everything should be fine again.
the update server had some troubles last night.

**Comment by Ruba5913** [comment]
Yes, this solved the problem.
Everything is working well again
Thanks !!!
