### ISSUE TITLE
Error while installing pimatic-led-light plugin

### ISSUE THREAD

**Issue by Nears** [pimatic/pimatic#795]
Hi all,

i got the following error after I added the led-light plugin and restared pimatic.
I did install libudev-dev but it won't help....
Any suggestions what I can do?

21:18:22.874 [pimatic] Cannot find module 'serialport'
21:18:24.194 [pimatic] Error: Cannot find module 'serialport'
21:18:24.194 [pimatic]>    at Function.Module._resolveFilename (module.js:338:15                                                                                        )
21:18:24.194 [pimatic]>    at Function.Module._load (module.js:280:25)
21:18:24.194 [pimatic]>    at Module.require (module.js:364:17)
21:18:24.194 [pimatic]>    at require (module.js:380:17)
21:18:24.194 [pimatic]>    at Object.<anonymous> (/home/pi/pimatic-app/node_modu                                                                                        les/pimatic-led-light/node_modules/node-milight-rf24/index.js:2:18)
21:18:24.194 [pimatic]>    at Module._compile (module.js:456:26)
21:18:24.194 [pimatic]>    at Object.Module._extensions..js (module.js:474:10)
21:18:24.194 [pimatic]>    at Module.load (/home/pi/pimatic-app/node_modules/pim                                                                                        atic-mobile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-scri                                                                                        pt/register.js:45:36)
21:18:24.194 [pimatic]>    at Function.Module._load (module.js:312:12)
21:18:24.194 [pimatic]>    at Module.require (module.js:364:17)
21:18:24.194 [pimatic]>    at require (module.js:380:17)
21:18:24.194 [pimatic]>    at module.exports (/home/pi/pimatic-app/node_modules/                                                                                        pimatic-led-light/devices/milightRF24.coffee:5:21)
21:18:24.194 [pimatic]>    at module.exports (/home/pi/pimatic-app/node_modules/                                                                                        pimatic-led-light/pimatic-led-light.coffee:6:17)
21:18:24.194 [pimatic]>    at PluginManager.loadPlugin (/home/pi/pimatic-app/nod                                                                                        e_modules/pimatic/lib/plugins.coffee:42:16)
21:18:24.194 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic/lib/plug                                                                                        ins.coffee:379:25
21:18:24.194 [pimatic]>    at tryCatcher (/home/pi/pimatic-app/node_modules/pima                                                                                        tic/node_modules/bluebird/js/main/util.js:26:23)
21:18:24.194 [pimatic]>    at Promise._settlePromiseFromHandler (/home/pi/pimati                                                                                        c-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:507:31)
21:18:24.194 [pimatic]>    at Promise._settlePromiseAt (/home/pi/pimatic-app/nod                                                                                        e_modules/pimatic/node_modules/bluebird/js/main/promise.js:581:18)
21:18:24.194 [pimatic]>    at Promise._settlePromiseAtPostResolution (/home/pi/p                                                                                        imatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:245:10)
21:18:24.194 [pimatic]>    at Async._drainQueue (/home/pi/pimatic-app/node_modul                                                                                        es/pimatic/node_modules/bluebird/js/main/async.js:128:12)
21:18:24.194 [pimatic]>    at Async._drainQueues (/home/pi/pimatic-app/node_modu                                                                                        les/pimatic/node_modules/bluebird/js/main/async.js:133:10)
21:18:24.194 [pimatic]>    at Async.drainQueues (/home/pi/pimatic-app/node_modul                                                                                        es/pimatic/node_modules/bluebird/js/main/async.js:15:14)
21:18:24.194 [pimatic]>    at process._tickCallback (node.js:415:13)

**Comment by mwittig** [comment]
Did you install libudev? Please see the Installation section of the README - https://github.com/philip1986/pimatic-led-light/blob/master/README.md

**Comment by Nears** [comment]
Yes i did, but it does not solve the problem.

**Comment by mwittig** [comment]
May be you need to run `npm install` again. 

```
cd /home/pi/pimatic-app/node_modules/pimatic-led-light/
sudo npm install
sudo service pimatic restart
```

**Comment by Nears** [comment]
Thanks for your response, but it won't fix my problem. I still get the same error when starting pimatic.
Any other ideas what I can try? 
Thanks in advance.

**Comment by mwittig** [comment]
A few days ago I had problems with another plugin using seriaport which did install properly if installed as root. Please try the following
```
sudo service pimatic stop
cd /home/pi/pimatic-app/node_modules/
sudo rm -rf pimatic-led-light
# Install the plugin as user pi
npm install pimatic-led-light
sudo service pimatic start
```

Please also let me know you debian version nodejs version. Thanks

**Comment by Nears** [comment]
Installing it as pi user and not as admin solved the issue.
Thanks for your support.

**Comment by mwittig** [comment]
Great!
