### ISSUE TITLE
Web interface not showing up

### ISSUE THREAD

**Issue by MathijsG** [pimatic/pimatic#796]
I just installed a brand new version of Raspbian Wheezy on my Raspberry Pi 2, using this image: https://www.raspberrypi.org/downloads/raspbian/

Then I followed http://pimatic.org/guide/getting-started/installation/ _exactly_

Now everything is installed, but after starting the software I get nothing when I put in the IP:PORTNUMBER

Here is my Log file:

coffee-cache: compiling coffee-script file "startup.coffee"...Done
coffee-cache: compiling coffee-script file "lib/logger.coffee"...Done
00:01:22.648 2016-01-23 Saturday
coffee-cache: compiling coffee-script file "lib/api.coffee"...Done
coffee-cache: compiling coffee-script file "lib/users.coffee"...Done
coffee-cache: compiling coffee-script file "lib/devices.coffee"...Done
coffee-cache: compiling coffee-script file "lib/matcher.coffee"...Done
coffee-cache: compiling coffee-script file "lib/milliseconds.coffee"...Done
coffee-cache: compiling coffee-script file "lib/variables.coffee"...Done
coffee-cache: compiling coffee-script file "lib/variables-ast-builder.coffee"...Done
coffee-cache: compiling coffee-script file "lib/actions.coffee"...Done
coffee-cache: compiling coffee-script file "lib/predicates.coffee"...Done
coffee-cache: compiling coffee-script file "lib/rules.coffee"...Done
coffee-cache: compiling coffee-script file "lib/rules-ast-builder.coffee"...Done
coffee-cache: compiling coffee-script file "lib/plugins.coffee"...Done
coffee-cache: compiling coffee-script file "lib/database.coffee"...Done
coffee-cache: compiling coffee-script file "lib/groups.coffee"...Done
coffee-cache: compiling coffee-script file "lib/pages.coffee"...Done
coffee-cache: compiling coffee-script file "lib/framework.coffee"...Done
00:01:52.554 [pimatic] info: Starting pimatic version 0.8.98
coffee-cache: compiling coffee-script file "config-schema.coffee"...Done
00:01:53.965 [pimatic] info: Installing database package sqlite3, this can take some minutes
00:01:56.805 [pimatic, npm] info: http GET https://registry.npmjs.org/sqlite3
00:01:57.218 [pimatic, npm] info: http 200 https://registry.npmjs.org/sqlite3
00:01:57.404 [pimatic, npm] info: http GET https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.1.tgz
00:01:57.596 [pimatic, npm] info: http 200 https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.1.tgz
00:02:59.346 [pimatic, npm] info: http GET https://registry.npmjs.org/nan
00:02:59.617 [pimatic, npm] info: http 200 https://registry.npmjs.org/nan
00:02:59.749 [pimatic, npm] info: http GET https://registry.npmjs.org/nan/-/nan-2.1.0.tgz
00:02:59.907 [pimatic, npm] info: http 200 https://registry.npmjs.org/nan/-/nan-2.1.0.tgz
00:03:03.498 [pimatic, npm] info: > sqlite3@3.1.1 install /home/pi/pimatic-app/node_modules/sqlite3
00:03:03.501 [pimatic, npm] info: > node-pre-gyp install --fallback-to-build
00:03:04.558 [pimatic, npm] info: node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v11-linux-arm.tar.gz
00:03:06.978 [pimatic, npm] info: node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v11-linux-arm.tar.gz
00:03:06.989 [pimatic, npm] info: node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v11-linux-arm.tar.gz (falling back to source compile with node-gyp) 
00:03:09.854 [pimatic, npm] info: gyp http GET http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
00:03:10.147 [pimatic, npm] info: gyp http 200 http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz
00:03:42.754 [pimatic, npm] info: make: Entering directory '/home/pi/pimatic-app/node_modules/sqlite3/build'
00:03:42.763 [pimatic, npm] info:   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
00:03:43.730 [pimatic, npm] info:   TOUCH Release/obj.target/deps/action_before_build.stamp
00:03:43.761 [pimatic, npm] info:   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
00:06:56.576 [pimatic, npm] info:   AR(target) Release/obj.target/deps/sqlite3.a
00:06:56.645 [pimatic, npm] info:   COPY Release/sqlite3.a
00:06:56.697 [pimatic, npm] info:   CXX(target) Release/obj.target/node_sqlite3/src/database.o
00:06:59.160 [pimatic, npm] info: ../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton*)’:
00:06:59.165 [pimatic, npm] info: ../src/database.cc:143:9: warning: unused variable ‘status’ [-Wunused-variable]
00:06:59.183 [pimatic, npm] info: ../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton*)’:
00:06:59.187 [pimatic, npm] info: ../src/database.cc:227:9: warning: unused variable ‘status’ [-Wunused-variable]
00:06:59.291 [pimatic, npm] info: ../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton*)’:
00:06:59.296 [pimatic, npm] info: ../src/database.cc:505:9: warning: unused variable ‘status’ [-Wunused-variable]
00:06:59.317 [pimatic, npm] info: ../src/database.cc: In static member function ‘static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton*)’:
00:06:59.321 [pimatic, npm] info: ../src/database.cc:605:9: warning: unused variable ‘status’ [-Wunused-variable]
00:07:08.169 [pimatic, npm] info:   CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
00:07:13.692 [pimatic, npm] info:   CXX(target) Release/obj.target/node_sqlite3/src/statement.o
00:07:15.880 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginPrepare(node_sqlite3::Database::Baton*)’:
00:07:15.884 [pimatic, npm] info: ../src/statement.cc:118:9: warning: unused variable ‘status’ [-Wunused-variable]
00:07:15.910 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginBind(node_sqlite3::Statement::Baton*)’:
00:07:15.913 [pimatic, npm] info: ../src/statement.cc:322:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:15.922 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginGet(node_sqlite3::Statement::Baton*)’:
00:07:15.925 [pimatic, npm] info: ../src/statement.cc:370:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:15.935 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginRun(node_sqlite3::Statement::Baton*)’:
00:07:15.938 [pimatic, npm] info: ../src/statement.cc:438:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:15.956 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginAll(node_sqlite3::Statement::Baton*)’:
00:07:15.959 [pimatic, npm] info: ../src/statement.cc:504:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:15.996 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginEach(node_sqlite3::Statement::Baton*)’:
00:07:15.999 [pimatic, npm] info: ../src/statement.cc:601:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:16.016 [pimatic, npm] info: ../src/statement.cc: In static member function ‘static void node_sqlite3::Statement::Work_BeginReset(node_sqlite3::Statement::Baton*)’:
00:07:16.026 [pimatic, npm] info: ../src/statement.cc:724:5: warning: unused variable ‘status’ [-Wunused-variable]
00:07:30.163 [pimatic, npm] info:   SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
00:07:30.637 [pimatic, npm] info:   SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node: Finished
00:07:30.649 [pimatic, npm] info:   COPY Release/node_sqlite3.node
00:07:30.697 [pimatic, npm] info:   COPY /home/pi/pimatic-app/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node
00:07:30.747 [pimatic, npm] info:   TOUCH Release/obj.target/action_after_build.stamp
00:07:30.769 [pimatic, npm] info: make: Leaving directory '/home/pi/pimatic-app/node_modules/sqlite3/build'
00:07:38.945 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/convict requires cjson@'0.3.0' but will load
00:07:38.952 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/cjson,
00:07:38.955 [pimatic, npm] info: WARN unmet dependency which is version 0.3.1
00:07:38.966 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect requires connect-timeout@'~1.6.2' but will load
00:07:38.969 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/connect-timeout,
00:07:38.972 [pimatic, npm] info: WARN unmet dependency which is version 1.7.0
00:07:39.239 [pimatic, npm] info: sqlite3@3.1.1 node_modules/sqlite3
00:07:39.242 [pimatic, npm] info: └── nan@2.1.0
00:07:45.012 [pimatic] info: message table created!
00:07:45.053 [pimatic] info: deviceAttribute table created!
00:07:45.068 [pimatic] info: attributeValueNumber table created!
00:07:45.077 [pimatic] info: attributeValueString table created!
00:07:45.567 [pimatic] info: Installing: "pimatic-cron" from precompiled source (node-11-armhf-linux-0.8.5)
00:07:53.947 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.5)
00:07:54.606 [pimatic] info: Installing: "pimatic-mobile-frontend" from precompiled source (node-11-armhf-linux-0.8.81)
00:08:23.224 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.81)
00:08:24.571 [pimatic-cron] info: the time is: Sat Jan 23 2016 00:08:24 GMT+0000 (UTC)
coffee-cache: compiling coffee-script file "device-config-schema.coffee"...Done
00:08:24.991 [pimatic-mobile-frontend] info: packing static assets
00:08:25.627 [pimatic-mobile-frontend] info: packing static assets finished
00:08:25.637 [pimatic-mobile-frontend] info: rendering html
00:08:32.411 [pimatic-mobile-frontend] info: rendering html finished
00:08:32.467 [pimatic] info: Listening for HTTP-request on port 80...
00:09:12.577 [pimatic] info: Flushing database to disk, please wait...
00:09:15.683 [pimatic] info: Flushing database to disk, please wait... Done.
00:09:15.686 [pimatic] info: exiting...
00:15:36.239 2016-01-23 Saturday
00:15:48.614 [pimatic] info: Starting pimatic version 0.8.98
00:15:52.422 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.5)
00:15:53.322 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.81)
00:15:55.137 [pimatic-cron] info: the time is: Sat Jan 23 2016 00:15:55 GMT+0000 (UTC)
00:15:55.464 [pimatic-mobile-frontend] info: packing static assets
00:15:56.544 [pimatic-mobile-frontend] info: packing static assets finished
00:15:56.557 [pimatic-mobile-frontend] info: rendering html
00:16:09.356 [pimatic-mobile-frontend] info: rendering html finished
00:16:09.418 [pimatic] info: Listening for HTTP-request on port 8080...

And here is my config:

{
  "//": "Please only change this file when pimatic is NOT running, otherwise pimatic will overwrite your changes.",
  "settings": {
    "httpServer": {
      "enabled": true,
      "port": 8080
    },
    "database": {
      "deviceAttributeLogging": [
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "*",
          "interval": "0",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "*",
          "type": "continuous",
          "interval": "5min",
          "expire": "7d"
        },
        {
          "deviceId": "*",
          "attributeName": "temperature",
          "type": "number",
          "expire": "1y"
        },
        {
          "deviceId": "*",
          "attributeName": "humidity",
          "type": "number",
          "expire": "1y"
        }
      ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },
    "authentication": {
      "secret": "xqOOR3/LrSyDxDjG9r0OjMh7mzmwuvhR3sUxj6dQosmmOnH+E7RaOZ0cv4JsFC0rkRb9/wSfvf39B7bijtd5pg=="
    },
    "httpsServer": {},
    "gui": {}
  },
  "plugins": [
    {
      "plugin": "cron"
    },
    {
      "plugin": "mobile-frontend"
    }
  ],
  "devices": [],
  "rules": [],
  "pages": [
    {
      "id": "favourite",
      "name": "Favourites",
      "devices": []
    }
  ],
  "groups": [],
  "users": [
    {
      "username": "admin",
      "password": "admin",
      "role": "admin"
    }
  ],
  "roles": [
    {
      "name": "admin",
      "permissions": {
        "pages": "write",
        "rules": "write",
        "variables": "write",
        "messages": "write",
        "events": "write",
        "devices": "write",
        "groups": "write",
        "plugins": "write",
        "updates": "write",
        "database": "write",
        "config": "write",
        "controlDevices": true,
        "restart": true
      }
    }
  ],
  "variables": []
}

Can anyone see a solution?

**Comment by mwittig** [comment]
> 00:16:09.418 [pimatic] info: Listening for HTTP-request on port 8080...

As you're writing you have followed the instructions exactly, I am wondering whether or not you tried to connect to port 8080?

**Comment by MathijsG** [comment]
Yeah, I sure did it with the port set, I even set it to 8080 manually to exclude a possible problem with port 80 already in use. But somehow after a few reboots, I did got a web page. So it's working now :).
