### ISSUE TITLE
Black Saturday, no rule works with Operation Weekday Saturday

### ISSUE THREAD

**Issue by mathiaslehmann** [pimatic/pimatic#800]
All rules with Operation Weekday Saturday at 01/30/2015 do not work.

**Comment by mathiaslehmann** [comment]
It also works today on Sunday the 31.01.2015 not.
My test Rule is "If Sunday then switch Light on"
Last week it still works, since yesterday no longer.

**Comment by mathiaslehmann** [comment]
Sorry, the Date is 30.01.2016 and 31.01.2016

**Comment by kenci** [comment]
For me it's also not working. `IF its sunday THEN log "Sunday"`

**Comment by sweetpi** [comment]
Found the bug. It should be fixed with pimatic-cron v0.8.6. Please reopen if the problem still exists with the new version.
