### ISSUE TITLE
No cookie transmitted

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#801]
Sometimes pimatic gets flooded by this message. I don't know where it comes from.
```
14:28:48.051 [pimatic] warn: No cookie transmitted.
14:28:48.258 [pimatic] warn: No cookie transmitted.
14:28:49.688 [pimatic] warn: No cookie transmitted.
14:28:52.080 [pimatic] warn: No cookie transmitted.
14:28:52.266 [pimatic] warn: No cookie transmitted.
14:28:53.423 [pimatic] warn: No cookie transmitted.
14:28:55.831 [pimatic] warn: No cookie transmitted.
14:28:57.348 [pimatic] warn: No cookie transmitted.
14:28:57.471 [pimatic] warn: No cookie transmitted.
14:28:59.811 [pimatic] warn: No cookie transmitted.
14:29:00.126 [pimatic] warn: No cookie transmitted.
14:29:01.592 [pimatic] warn: No cookie transmitted.
14:29:03.029 [pimatic] warn: No cookie transmitted.
14:29:04.442 [pimatic] warn: No cookie transmitted.
14:29:06.184 [pimatic] warn: No cookie transmitted.
14:29:07.251 [pimatic] warn: No cookie transmitted.
14:29:08.645 [pimatic] warn: No cookie transmitted.
14:29:10.019 [pimatic] warn: No cookie transmitted.
14:29:11.382 [pimatic] warn: No cookie transmitted.
14:29:12.734 [pimatic] warn: No cookie transmitted.
14:29:14.069 [pimatic] warn: No cookie transmitted.
14:29:15.395 [pimatic] warn: No cookie transmitted.
14:29:16.711 [pimatic] warn: No cookie transmitted.
14:29:18.020 [pimatic] warn: No cookie transmitted.
14:29:19.303 [pimatic] warn: No cookie transmitted.
14:29:20.583 [pimatic] warn: No cookie transmitted.
14:29:21.849 [pimatic] warn: No cookie transmitted.
14:29:23.106 [pimatic] warn: No cookie transmitted.
14:29:24.346 [pimatic] warn: No cookie transmitted.
14:29:25.578 [pimatic] warn: No cookie transmitted.
14:29:26.808 [pimatic] warn: No cookie transmitted.
14:29:28.019 [pimatic] warn: No cookie transmitted.
14:29:29.220 [pimatic] warn: No cookie transmitted.
14:29:30.410 [pimatic] warn: No cookie transmitted.
14:29:31.589 [pimatic] warn: No cookie transmitted.
14:29:32.753 [pimatic] warn: No cookie transmitted.
14:29:33.916 [pimatic] warn: No cookie transmitted.
14:29:35.064 [pimatic] warn: No cookie transmitted.
14:29:36.215 [pimatic] warn: No cookie transmitted.
14:29:37.343 [pimatic] warn: No cookie transmitted.
14:29:38.448 [pimatic] warn: No cookie transmitted.
14:29:39.552 [pimatic] warn: No cookie transmitted.
```

**Comment by thost96** [comment]
@sweebee Could you clear all browsers cache?`

**Comment by mwittig** [comment]
@sweebee  The [code block](https://github.com/pimatic/pimatic/blob/master/lib/framework.coffee#L352-L384) in question is responsible for enforcing authentication of incoming http requests. The log message is prompted in the last code block which is executed if the request neither contains login credential nor contains a cookie. I can reproduce this behaviour if disable using cookies in the browser. 

Apart from browser interaction may be you have some other service sending http requests to pimatic? May be it is ESPimatic sending requests to pimatic?

**Comment by sweebee** [comment]
This message happened when i was working, so one one was accessing the mobile frontend. I use Locative to set the dummy pirs with the pimatic api, and a php script that reads the power usage from the api, but that only happens just before midnight.. Maybe that could be it?

**Comment by mwittig** [comment]
A similar case we had with a .NET client - https://github.com/pimatic/pimatic/issues/760

**Comment by mwittig** [comment]
@sweebee Possibly, May be you can do some isolated tests with the Locative app and the PHP script?! Unfortunately, the "Unauthorized" error does not appear to result in a HTTP error response. If I am doing this in the browser I get a 200 status  code and the "Unauthorized" is part of the response body data.

**Comment by leader21** [comment]
@sweebee have you solved it? If yes can you tell what  the issue has been?

**Comment by sweebee** [comment]
Well, it never happened again. Don't know why but it works.
