### ISSUE TITLE
Using required attribute on attribute with type = "object" in config schema breaks JSON schema validation

### ISSUE THREAD

**Issue by michbeck100** [pimatic/pimatic#803]
I'm trying to create a new config schema where an attribute of type "object" can be optional, so I've added the required attribute. 
This is an example:

```javascript
ExampleDevice: {
  title: "foo"
  type: "object"
  properties:
    optionalProperty:
      type: "object"
      required: false
      properties:
        anotherProperty:
          ...
}
```

When this config schema gets validated using Jayschema in Framework._validateConfig (framework.coffee:80), the complete process hangs and after a while stops with "process out of memory". 
I guess this is due to https://github.com/natesilva/jayschema/issues/56. It says that the required attribute cannot be of type boolean, but rather of type array (as of JSON schema v4).

This again contradicts the validation in decl-api, which expects the required attribute's value to be false if the attribute is optional.

I'm not sure how to get around this.

**Comment by sweetpi** [comment]
I've removed the decl-api validation and all config schemes are now completely validated by jayschema. To be bachward compatible all `required` boolean attributes will normalized to the `required` array:

```cs
ExampleDevice: {
  title: "foo"
  type: "object"
  properties:
    optionalProperty:
      type: "object"
      required: false
      properties:
        anotherProperty:
          ...
}
```

get automatic converted to

```cs
ExampleDevice: {
  title: "foo"
  type: "object"
  required: ["list", "of", "required", "properties"]
  properties:
    optionalProperty:
      type: "object"
      properties:
        anotherProperty:
          ...
}
```

which is json scheme compatible.

You can now use the old boolean syntax or the array syntax.
