### ISSUE TITLE
Error loading device c1: "contact2" must be one of the following types: "switch, contact"

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#804]
Hello,

since last update i get this message
```
Error loading device c1: "contact2" must be one of the following types: "switch, contact"
```
this is how my device is configured
```
    {
      "id": "c1",
      "name": "Porte d'entrée (c1)",
      "class": "HomeduinoRFContactSensor",
      "protocols": [
        {
          "name": "contact2",
          "options": {
            "id": 773727
          }
        }
      ],
      "autoReset": true,
      "resetTime": 5000
    },
```
and until now it was working fine.
Any idea?

**Comment by Icesory** [comment]
The protocol contact2 is declared as an wrong type. https://github.com/pimatic/rfcontroljs/blob/master/src/protocols/contact2.coffee#L13

this line should be "contact"
Can you fix it for your self? Will wait until the next weekend to see what is also broken.

**Comment by Yves911** [comment]
@Icesory thanks, i have discovered today that my contacts are back.
Thx
Yves
