### ISSUE TITLE
error [pimatic]: Error loading device rolladen: Protocol "shutter3" has no property named "unit". Available properties are: "id" "id" "channel" "command" 

### ISSUE THREAD

**Issue by andi216** [pimatic/pimatic#805]
Hello,

since last update i get this message:

error [pimatic]: Error loading device rolladen: Protocol "shutter3" has no property named "unit". Available properties are: "id" "id" "channel" "command" 

{
      "id": "rolladen",
      "name": "Rolladen",
      "class": "HomeduinoRFButtonsDevice",
      "buttons": [
        {
          "id": "roll1",
          "text": "▲",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": 128457074,
                "unit": 1,
                "command": "up"
              }
            }
          ]
        },
        {
          "id": "roll2",
          "text": "Stop",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": 128457074,
                "unit": 1,
                "command": "stop"
              }
            }
          ]
        },
        {
          "id": "roll3",
          "text": "▼",
          "protocols": [
            {
              "name": "shutter3",
              "options": {
                "id": 128457074,
                "unit": 1,
                "command": "down"
              }
            }
          ]
        }
      ]
    },

**Comment by mwittig** [comment]
Can you please post the device configuration in question? Thanks

**Comment by Icesory** [comment]
We habe implemented a stricter config check. You must only remove the unit entry from your config and all should work again.

**Comment by andi216** [comment]
error [pimatic]: Error loading device sx1: "contact2" must be one of the following types: "switch, contact"


{
      "id": "sx1",
      "name": "Sx 1",
      "class": "HomeduinoRFContactSensor",
      "protocols": [
        {
          "name": "contact2",
          "options": {
            "id": 670325
          }
        }
      ],
      "autoReset": true,
      "resetTime": 3000
    },

**Comment by Icesory** [comment]
The failure with contact2 is know. Will be fixed with the next Patch.

**Comment by andi216** [comment]
I changed "unit" to "channel".
The error has disappeared.
Thank you!
