### ISSUE TITLE
[MobileFrontend-Pimatic] "Iphone 6S Plus" Rotate

### ISSUE THREAD

**Issue by DerGrafausB** [pimatic/pimatic#808]
If I rotate iPhone display, and rotate it back, it looks like this 

![img_0611](https://cloud.githubusercontent.com/assets/17230502/13032530/43f890f0-d2f6-11e5-801e-f7fef009efd1.PNG)
![img_0612](https://cloud.githubusercontent.com/assets/17230502/13032531/43f9404a-d2f6-11e5-8c7e-277a8c8240e8.PNG)
![img_0613](https://cloud.githubusercontent.com/assets/17230502/13032532/43f96c14-d2f6-11e5-941a-3ca52b8b7815.PNG)

**Comment by sweetpi** [comment]
Hm, can someone confirm this. Does it happen all the time or just randomly?

I have no ios device to test...

**Comment by sweebee** [comment]
Happens to me also when there is a thermostat

**Comment by poeml** [comment]
Happens all the time to me, and since a long time. My workaround is to reload the page in the browser, in "upright" orientation of the device. In horizontal orientation, reloading doesn't help.

**Comment by mwittig** [comment]
I have a different behaviour on iPhone 6 using Safari. When I rotate the display the UI rotated but also zoomed. If I rotate again it will be zoomed again. This can be repeated up to some maximum zoom level. As I am a numb iPhone user I don't know how to zoom out again :(

Chrome ist showing the same behavour btw. Does the frontend provide for proper viewport settings?

**Comment by sweetpi** [comment]
So the thermostat-device does cause the bug?

**Comment by sweebee** [comment]
It also happens at the login screen when installed as app. 

[Imgur](http://i.imgur.com/5xebiWr.jpg)

**Comment by sweebee** [comment]
I think its a bug in safari. Happens on Some other webapps also. Chrome does the same because iOS chrome = safari

**Comment by DerGrafausB** [comment]
i think it is not the thermostat.
![img_0622](https://cloud.githubusercontent.com/assets/17230502/13123102/d1594ba8-d5ba-11e5-83b6-7ae6ed56a37c.PNG)
![img_0623](https://cloud.githubusercontent.com/assets/17230502/13123104/d15b5d26-d5ba-11e5-8b30-f61f7c0b613e.PNG)
![img_0624](https://cloud.githubusercontent.com/assets/17230502/13123103/d159a97c-d5ba-11e5-9afb-1c11c14a7eb6.PNG)

**Comment by sweetpi** [comment]
Ok you are right seems to be a safari bug: http://webdesignerwall.com/tutorials/iphone-safari-viewport-scaling-bug

**Comment by sweetpi** [comment]
I've published a patch. Could you check if the problem still exists?

**Comment by DerGrafausB** [comment]
It works!
Perfect.

Thank You

**Comment by DerGrafausB** [comment]
You can rotate it, then it Shows the second room.
When you rotate it back, it is perfect.
I think it is better.

![img_0632](https://cloud.githubusercontent.com/assets/17230502/13141491/e5e804ec-d637-11e5-8c6e-6960417e8cc8.PNG)
![img_0633](https://cloud.githubusercontent.com/assets/17230502/13141492/e5ea7178-d637-11e5-83ef-0509a111f045.PNG)

**Comment by mwittig** [comment]
@sweetpi DId you consider "solution 2" to work around the problem? For usability concerns, "solution 1", i.e., setting maximum-scale, is not an ideal solution because user can not zoom the page.
