### ISSUE TITLE
Not able to build pimatic

### ISSUE THREAD

**Issue by promille** [pimatic/pimatic#809]
Hi,

i want to build pimatic but without luck.

mode node version is set to 0.10 with nvm
`node --version
v0.10.24`

`npm install pimatic --prefix app --production`
...
`make: Verzeichnis „/home/pimatic/app/node_modules/pimatic/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build“ wird betreten
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Verzeichnis „/home/pimatic/app/node_modules/pimatic/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build“ wird verlassen
npm WARN unmet dependency /home/pimatic/app/node_modules/pimatic/node_modules/convict requires cjson@'0.3.0' but will load
npm WARN unmet dependency /home/pimatic/app/node_modules/pimatic/node_modules/cjson,
npm WARN unmet dependency which is version 0.3.1
npm WARN unmet dependency /home/pimatic/app/node_modules/pimatic/node_modules/express/node_modules/connect requires connect-timeout@'~1.6.2' but will load
npm WARN unmet dependency /home/pimatic/app/node_modules/pimatic/node_modules/connect-timeout,
npm WARN unmet dependency which is version 1.7.0`

Any ideas how to get around this version mismatch?

**Comment by Icesory** [comment]
Normally you can ignore the warn fields. 
When it really not build to the end. Try it with sudo.

**Comment by sweetpi** [comment]
Try if it works. It looks "ok" :D. Please reopen if there are problems.
