### ISSUE TITLE
[pimatic-upnp-root]

### ISSUE THREAD

**Issue by Ruba5913** [pimatic/pimatic#813]
Hello,

After the last pimatic update on both pi's that I have, I get after every time after restarting the pi's this error:
error [pimatic]: Invalid config of pimatic-upnp-root: Property "uuid" is not a valid property.

I deleted the uuid of the plugin upnp-root and than restart the pi, no error occured.
 checked the plugin and there is a new uuid filled in.

Restarting second time and again the error is back !!

**Comment by Icesory** [comment]
I think the config Schemata of the upnp plugin is wrong. Pimatic got a new better config check. So this is now an failure. Eventually you should post this in the github page for this plugin.

**Comment by sweetpi** [comment]
@Icesory is right. I submitted a pull request. 

@Ruba5913 Thanks for reporting. You can ignore the error till a update for the plugin is available.
