### ISSUE TITLE
Pimatic does not start after update from 0.8.100 to 0.8.101

### ISSUE THREAD

**Issue by Sjeff** [pimatic/pimatic#819]
Error: Startup error : error: ENOENT, no such file or directory '/home/pi/pimatic-app/node_modules/pimatic/lib/../locales'

Anyone know how to fix this?

09:17:51.826 [pimatic-mysensors] debug: <- I_LOG_MESSAGE 0;0;3;0;9;read: �'W��mismatch
09:17:51.864 [pimatic-mysensors] debug: <- I_LOG_MESSAGE 0;0;3;0;9;read: 0-0;0;3;0;9;gateway started, id=0, parent=0, distance=0
09:17:58.948 [pimatic-mobile-frontend] info: packing static assets
09:18:08.458 [pimatic-mobile-frontend] info: packing static assets finished
09:18:08.574 [pimatic-mobile-frontend] info: rendering html
09:18:34.816 [pimatic] error: Startup error: Error: ENOENT, no such file or directory '/home/pi/pimatic-app/node_modules/pimatic/lib/../locales'
09:18:34.816 [pimatic] error:> at Object.fs.mkdirSync (fs.js:642:18)
09:18:34.816 [pimatic] error:> at write (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:404:8)
09:18:34.816 [pimatic] error:> at read (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:383:5)
09:18:34.816 [pimatic] error:> at translate (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:335:5)
09:18:34.816 [pimatic] error:> at i18nTranslate (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:96:11)
09:18:34.816 [pimatic] error:> at eval (eval at <anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:160:8), <anonymous>:5:343)
09:18:34.816 [pimatic] error:> at res (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:161:38)
09:18:34.816 [pimatic] error:> at Object.exports.render (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:257:10)
09:18:34.816 [pimatic] error:> at Object.exports.renderFile (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:293:18)
09:18:34.816 [pimatic] error:> at Object.exports.renderFile (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:278:21)
09:18:34.816 [pimatic] error:> at Object.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
09:18:34.816 [pimatic] error:> at Object.ret [as renderFileAsync] (eval at <anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:12:39)
09:18:34.816 [pimatic] error:> at MobileFrontend.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:136:20)
09:18:34.816 [pimatic] error:> at MobileFrontend.renderIndex (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:131:9)
09:18:34.816 [pimatic] error:> at /home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:95:21
09:18:34.816 [pimatic] error:> at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
09:18:34.816 [pimatic] error:> at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:507:31)
09:18:34.816 [pimatic] error:> at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:581:18)
09:18:34.816 [pimatic] error:> at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:128:12)
09:18:34.816 [pimatic] error:> at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:133:10)
09:18:34.816 [pimatic] error:> at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:15:14)
09:18:34.816 [pimatic] error:> at process._tickCallback (node.js:415:13)
09:18:34.855 [pimatic] info: exiting...

**Comment by Sjeff** [comment]
`Error: Startup error : error: ENOENT, no such file or directory '/home/pi/pimatic-app/node_modules/pimatic/lib/../locales'

Anyone know how to fix this?
I will upload the logfile tonight for more info.

09:17:51.826 [pimatic-mysensors] debug: <- I_LOG_MESSAGE 0;0;3;0;9;read: �'W��mismatch
09:17:51.864 [pimatic-mysensors] debug: <- I_LOG_MESSAGE 0;0;3;0;9;read: 0-0;0;3;0;9;gateway started, id=0, parent=0, distance=0
09:17:58.948 [pimatic-mobile-frontend] info: packing static assets
09:18:08.458 [pimatic-mobile-frontend] info: packing static assets finished
09:18:08.574 [pimatic-mobile-frontend] info: rendering html
09:18:34.816 [pimatic] error: Startup error: Error: ENOENT, no such file or directory '/home/pi/pimatic-app/node_modules/pimatic/lib/../locales'
09:18:34.816 [pimatic] error:> at Object.fs.mkdirSync (fs.js:642:18)
09:18:34.816 [pimatic] error:> at write (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:404:8)
09:18:34.816 [pimatic] error:> at read (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:383:5)
09:18:34.816 [pimatic] error:> at translate (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:335:5)
09:18:34.816 [pimatic] error:> at i18nTranslate (/home/pi/pimatic-app/node_modules/pimatic/node_modules/i18n/i18n.js:96:11)
09:18:34.816 [pimatic] error:> at eval (eval at <anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:160:8), <anonymous>:5:343)
09:18:34.816 [pimatic] error:> at res (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:161:38)
09:18:34.816 [pimatic] error:> at Object.exports.render (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:257:10)
09:18:34.816 [pimatic] error:> at Object.exports.renderFile (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:293:18)
09:18:34.816 [pimatic] error:> at Object.exports.renderFile (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/jade/lib/jade.js:278:21)
09:18:34.816 [pimatic] error:> at Object.tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
09:18:34.816 [pimatic] error:> at Object.ret [as renderFileAsync] (eval at <anonymous> (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:12:39)
09:18:34.816 [pimatic] error:> at MobileFrontend.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:136:20)
09:18:34.816 [pimatic] error:> at MobileFrontend.renderIndex (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:131:9)
09:18:34.816 [pimatic] error:> at /home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/mobile-frontend.coffee:95:21
09:18:34.816 [pimatic] error:> at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:26:23)
09:18:34.816 [pimatic] error:> at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:507:31)
09:18:34.816 [pimatic] error:> at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:581:18)
09:18:34.816 [pimatic] error:> at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:128:12)
09:18:34.816 [pimatic] error:> at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:133:10)
09:18:34.816 [pimatic] error:> at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:15:14)
09:18:34.816 [pimatic] error:> at process._tickCallback (node.js:415:13)
09:18:34.855 [pimatic] info: exiting...`

**Comment by sweetpi** [comment]
Sorry closed this accidently. @Sjeff did you get it to work?
