### ISSUE TITLE
[pimatic-shell-execute] interval: 0 let CPU climb up to 100%

### ISSUE THREAD

**Issue by p4co86** [pimatic/pimatic#821]
When i set an interval to 0 the CPU goes to 100% till i change from 0 to 2000

**Comment by mwittig** [comment]
Did you try with the latest release 0.8.15? It was among the things I fixed.  Please re-open if the issue still occurs.

It may be sensible to limit the minimal to something like 1000 as spawning a process is rather time consuming. So, doing shell executes at such a frequency will keep raspberry busy. What do you think?
