### ISSUE TITLE
error [pimatic]: typeof p.changeListener is "function"

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#825]
I get this error with 1 rule, and can't delete it or modify it.

rule:

```
if its 2016-03-06 16:00 then turn Balkon onder verwarming on for 6h
```

This rule doesn't work of course but i was testing what date would work. After some 'guessing' i can't edit/remove this rule anymore. and i get:
```
error [pimatic]: typeof p.changeListener is "function"
```

Happened on my home pimatic installation and the installation at work.

**Comment by sweetpi** [comment]
Thanks for reporting, is fixed in pimatic v0.8.102.
