### ISSUE TITLE
[v0.9] Error after editing device

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#835]
You fixed the issue where pimatic crashed after editing a device.

When I edit a pimatic-hue-zlll bulb (the grouped ones xxxxxxxxxxGroup)
Doesn't happen with the normal bulb devices.

I get this:

```
error [pimatic-hue-zll]: Error while polling light group 3 status: @lightStatusResult?.state?
```

Don't know if this is a bug in the hue plugin or in pimatic?

**Comment by sweebee** [comment]
And one more error, sometimes pimatic gives an error with:

```
Oops, not found!
```
But the device is edited.

**Comment by sweetpi** [comment]
> And one more error, pimatic gives an error with:
> 
> Oops, not found!
> But the device is edited.

Does this happen on save?

**Comment by sweebee** [comment]
Yes indeed. Click save and i get that error. But the device is edited properly.

**Comment by sweetpi** [comment]
Thanks, is fixed in the latest beta. The pimatic-hue-zll is plugin related. I will write some infos for plugin authors as soon as pimatic v0.9 is usable.
