### ISSUE TITLE
[v0.9] Can't remove device attribute (array)

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#838]
I can't remove a item in a array of the device editor. You have to hold and move it to the red bar but i can't get it on top of the red bar :p

Browsers:

Safari
Chrome

Screenshot:
![](https://i.imgur.com/Qd8zHHY.png)

**Comment by sweebee** [comment]
Fixed

**Comment by sweetpi** [comment]
Yes fixed :)
