### ISSUE TITLE
Pimatic crashes every time on Pi2

### ISSUE THREAD

**Issue by daice24** [pimatic/pimatic#839]
Hi guys, i have a big problem. A couple of weeks ago i switched my hardware from Raspberry Pi B+ to an Pi2. For the first shot i used the same SD Card and Image. I have updated the debian and everything seems to work. But the system was not working for more than one day. Then it crashes completly, not only Pimatic. The system was not responding over ssh so the only thing i could do was switch the power off. The thing is that the Pi is working fine when Pimatic is not running. So i made a complete new installation with Debian Jessie Lite (4.1). But it is still the same. When i start pimatic it runs fine for the momant, but after some minutes or hours it freezes the Pi.
So i looked into syslog and pimatic-deamon.log, but i can't find error messages.

I hope you guys have some ideas whats happening there...

daice

**Comment by mwittig** [comment]
* Do you have USB Devices connected? If yes, disconnect them as much as possible. If you use a WiFi dongle consider using LAN cable instead for testing
* Which Power Supply do you use. A lot of stability problems are actually power problems.
* It might also be an issue with SD card, but normally you should see file systems errors in the log at some point.

**Comment by daice24** [comment]
Hi,

i used a new SD card with the new installation. The Pi is connected over LAN, but there are a some USB devices connecetd (directly connected: 2 serial devices and ardoino nano; on USB HUB: GEMBIRD Power Socket, WLAN dongle.
I used one power supply (5V,3A) for Pi and USB hub. After the problems started i used an aditional power supply for the pi (5V,1,2A).

**Comment by mwittig** [comment]
Regarding powering: 5V,1,2A should be OK in most cases, however, a 1.8 - 2.5A power supply (PSU) is officially  recommended for Raspi 2 <https://www.raspberrypi.org/help/faqs/#powerReqs>. Despite the nominal capacity of the PSU there other aspects which come into play and some PSUs are known to cause problems. Make sure to have look at <http://elinux.org/RPi_VerifiedPeripherals#Problem_power_Adapters>.

If possible try to run without USB devices.  Regarding the serial devices do you know about their power draw, or do you power them separaetly?

**Comment by mwittig** [comment]
No response. I am closing this now. Please also use the Pimatic Forum for general questions and trouble shooting
