### ISSUE TITLE
Cannot update from 0.8.101 to 0.8.102

### ISSUE THREAD

**Issue by Xento** [pimatic/pimatic#840]
When I try to update from 0.8.101 everything seems to work.
But when I restart pimatic than the update notification is still there ...
I have tried this many many times.
Other updates like plugins etc. work.

**Comment by sweetpi** [comment]
Could you post the log?

**Comment by Xento** [comment]
14:19:40.673 [pimatic] info: Starting pimatic version 0.8.101
	14:19:42.475 [pimatic] warn: Could not find a device with the ID "dhtbuero" from group "buro" in devices config section.
	14:19:42.481 [pimatic] warn: Could not find a device with the ID "dhtbuero" from page "status" in devices config section.
	14:19:42.484 [pimatic] warn: Could not find a device with the ID "dhtbuero" from page "heizung" in devices config section.
	14:19:44.877 [pimatic] info: Loading plugin: "pimatic-hap" (0.6.1)
	14:19:46.126 [pimatic] info: Loading plugin: "pimatic-mpd" (0.8.11)
	14:19:46.312 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.7)
	14:19:47.347 [pimatic] info: Loading plugin: "pimatic-led-light" (0.3.3)
	14:19:49.858 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.82)
	14:19:51.569 [pimatic] info: Loading plugin: "pimatic-log-reader" (0.8.8)
	14:19:51.665 [pimatic] info: Loading plugin: "pimatic-max" (0.8.15)
	14:19:51.807 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.10)
	14:19:51.917 [pimatic] info: Loading plugin: "pimatic-sunrise" (0.8.3)
	14:19:52.038 [pimatic] info: Loading plugin: "pimatic-gpio" (0.8.15)
	14:19:52.184 [pimatic] info: Loading plugin: "pimatic-pushover" (0.8.5)
	14:19:52.272 [pimatic] info: Loading plugin: "pimatic-volkszaehler" (0.2.0)
	14:19:54.596 [pimatic] info: Loading plugin: "pimatic-enigma2" (0.1.2)
	14:19:55.631 [pimatic] info: Loading plugin: "pimatic-homeduino" (0.8.72)
	14:19:57.617 [pimatic] info: Loading plugin: "pimatic-easybox" (0.1.2)
	14:19:59.326 [pimatic] info: Loading plugin: "pimatic-shell-execute" (0.8.19)
	14:19:59.425 [pimatic-hap] info: Starting homekit bridge
	14:19:59.492 [pimatic-cron] info: the time is: Fri Mar 25 2016 14:19:59 GMT+0100 (CET)
	14:19:59.572 [pimatic-sunrise] info: Your location is set to lat: 51.5070147, long: 7.5028754
	14:20:00.782 [pimatic] error: Invalid config of device "WohnzimmerMilight": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ brightness: { time: 1458507395886, value: 100 },
	  color: { time: 1458858275810, value: '#C4FF00' },
	  mode: { time: 1458880982948, value: 'COLOR' },
	  power: { time: 1458910723974, value: 'on' } }
	14:20:00.850 [pimatic] info: New device "Alle"...
	14:20:00.976 [pimatic] error: Invalid config of device "WohnzimmerMilightRaum": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ color: { time: 1458858275843, value: '#C4FF00' },
	  brightness: { time: 1458507395928, value: 100 },
	  mode: { time: 1458880982952, value: 'COLOR' },
	  power: { time: 1458910723983, value: 'on' } }
	14:20:00.988 [pimatic] info: New device "Raum"...
	14:20:01.062 [pimatic] error: Invalid config of device "WohnzimmerMilightKugel": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ color: { time: 1458858275850, value: '#C4FF00' },
	  brightness: { time: 1458507395944, value: 100 },
	  mode: { time: 1458880982954, value: 'COLOR' },
	  power: { time: 1458910723986, value: 'on' } }
	14:20:01.081 [pimatic] info: New device "Kugel"...
	14:20:01.142 [pimatic] error: Invalid config of device "WohnzimmerMilightFenster": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ color: { time: 1458858275856, value: '#C4FF00' },
	  brightness: { time: 1458507395966, value: 100 },
	  mode: { time: 1458880982956, value: 'COLOR' },
	  power: { time: 1458910723995, value: 'on' } }
	14:20:01.154 [pimatic] info: New device "Fenster"...
	14:20:01.226 [pimatic] error: Invalid config of device "LEDLampeSchlafzimmer": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ brightness: { time: 1458878374099, value: 12 },
	  color: { time: 1458336162356, value: '#FFBF00' },
	  mode: { time: 1458880982850, value: 'COLOR' },
	  power: { time: 1458880980151, value: 'off' } }
	14:20:01.239 [pimatic] info: New device "LED-Lampe Schlafzimmer"...
	14:20:01.302 [pimatic] error: Invalid config of device "Wandbild": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ power: { time: 1458878319408, value: 'off' },
	  mode: { time: 1458336162358, value: 'COLOR' },
	  color: { time: 1458336162359, value: '#FFBF00' },
	  brightness: { time: 1458336155553, value: 100 } }
	14:20:01.311 [pimatic] info: New device "Wandbild"...
	14:20:01.373 [pimatic] error: Invalid config of device "Schreibtisch": Property "port" is not a valid property, Missing property "port" in /zones/0
	{ mode: { time: 1458811232181, value: 'WHITE' },
	  power: { time: 1458834570788, value: 'off' },
	  color: { time: 1458336162361, value: '#FFBF00' },
	  brightness: { time: 1458336155555, value: 100 } }
	14:20:01.390 [pimatic] info: New device "Schreibtisch"...
	14:20:01.461 [pimatic] info: New device "Heizung"...
	14:20:01.529 [pimatic] info: New device "Phone"...
	14:20:01.612 [pimatic] info: New device "iPhone"...
	14:20:01.698 [pimatic] info: New device "Strom"...
	14:20:01.759 [pimatic] info: New device "Radio"...
	14:20:01.854 [pimatic] info: New device "Heizung Wohnzimmer"...
	14:20:01.927 [pimatic] info: New device "Fenster"...
	14:20:02.019 [pimatic] info: New device "Temp Wohnzimmer"...
	14:20:02.124 [pimatic] info: New device "Heizung Küche"...
	14:20:02.257 [pimatic] info: New device "Temp Küche"...
	14:20:02.304 [pimatic] info: New device "Fenster"...
	14:20:02.358 [pimatic] info: New device "Heizung Büro"...
	14:20:02.425 [pimatic] info: New device "Heizung Schlafzimmer"...
	14:20:02.493 [pimatic] info: New device "Temp Schlafzimmer"...
	14:20:02.537 [pimatic] info: New device "Temp Büro"...
	14:20:02.619 [pimatic] info: New device "Fenster"...
	14:20:02.663 [pimatic] info: New device "Fenster"...
	14:20:02.724 [pimatic] info: New device "Temp S1"...
	14:20:02.785 [pimatic] info: New device "Trockner"...
	14:20:02.840 [pimatic] info: New device "Waschmaschine"...
	14:20:02.879 [pimatic] error: Invalid config of device "temperature-kuechenfenster": Property "template" is not a valid property
	14:20:02.884 [pimatic] info: New device "Temp Küchenfenster"...
	14:20:02.938 [pimatic] error: Invalid config of device "temperature-balkon": Property "template" is not a valid property
	14:20:02.943 [pimatic] info: New device "Temp Balkon"...
	14:20:02.983 [pimatic] error: Invalid config of device "temperature-sensor3": Property "template" is not a valid property
	14:20:02.988 [pimatic] info: New device "Temp Sensor 3"...
	14:20:03.034 [pimatic] error: Invalid config of device "temperature-sensor2": Property "template" is not a valid property
	14:20:03.038 [pimatic] info: New device "Temp Sensor 2"...
	14:20:03.091 [pimatic] info: New device "Büro Temp"...
	14:20:03.168 [pimatic] info: New device "Nadines Handy"...
	14:20:03.237 [pimatic] info: New device "Markus Handy"...
	14:20:03.325 [pimatic] info: New device "iPhone anwesend"...
	14:20:03.388 [pimatic] info: New device "Balkon"...
	14:20:03.456 [pimatic] info: New device "Radio Schalter"...
	14:20:03.528 [pimatic] info: New device "Deckenlampe"...
	14:20:03.638 [pimatic] info: New device "Büro"...
	14:20:03.709 [pimatic] info: New device "Esstisch"...
	14:20:03.788 [pimatic] info: New device "RadioStatus"...
	14:20:03.850 [pimatic] info: New device "RadioLautstaerke"...
	14:20:03.922 [pimatic] info: New device "Schranklicht"...
	14:20:03.981 [pimatic] info: New device "LED"...
	14:20:04.070 [pimatic] info: New device "LED Lampe"...
	14:20:04.127 [pimatic] info: New device "Tür"...
	14:20:04.190 [pimatic] info: New device "Rauchmelder Wohnzimmer"...
	14:20:04.264 [pimatic] info: New device "Rauchmelder Flur"...
	14:20:04.360 [pimatic] info: New device "Rauchmelder Schlafzimmer"...
	14:20:04.434 [pimatic] info: New device "Temperatur"...
	14:20:26.358 [pimatic] info: rule nadine-handy-online: set $NadineHandy to 1
	14:20:26.363 [pimatic] info: rule wohnzimmer-nightmode-reset: set $NightModeWohnzimmer to 0
	14:20:26.797 [pimatic] info: rule heizung-an: set mode Heizung Büro to auto
	14:20:27.674 [pimatic-mobile-frontend] info: packing static assets
	14:20:29.455 [pimatic-mobile-frontend] info: packing static assets finished
	14:20:29.472 [pimatic-mobile-frontend] info: rendering html
	14:20:32.491 [pimatic-volkszaehler] info: Public channel 87a56780-43c8-11e4-bb2e-f376e83ca383 Stromverbrauch (power)
	14:20:32.676 [pimatic] info: rule heizung-an: set mode Heizung Küche to auto
	14:20:32.905 [pimatic-homeduino] info: Connected to homeduino device.
	14:20:33.066 [pimatic] info: rule heizung-an: set mode Heizung Wohnzimmer to auto
	14:20:40.591 [pimatic-mobile-frontend] info: rendering html finished
	14:20:40.638 [pimatic] info: Listening for HTTP-request on port 8080...
	14:20:56.318 [pimatic] info: rule trockner-benarichtigung: Message send.
	14:20:56.965 [pimatic] info: rule trockner-benarichtigung: Pushover Nachricht wurde erfolgreich gesendet
	14:21:19.890 [pimatic] info: rule nadine-handy-online: set $NadineHandy to 1
	15:05:52.510 [pimatic] info: rule nadine-handy-abwesend: set $NadineHandy to 0
	15:08:30.184 [pimatic] info: rule nadine-handy-online: set $NadineHandy to 1
	15:14:57.837 [pimatic] info: rule nadine-handy-online: set $NadineHandy to 1
	15:54:57.364 [pimatic] error: [Error: Couldn't find plugin info for pimatic-plugin-commons]
	15:54:59.338 [pimatic] info: Installing: "pimatic" from npm-registry.
	15:59:15.510 [pimatic] info: Restarting...
	15:59:15.520 [pimatic] info: Flushing database to disk, please wait...
	15:59:16.266 [pimatic] info: Flushing database to disk, please wait... Done.

**Comment by sweetpi** [comment]
Thanks, no install output. Strange. What is you npm version? `npm --version`

**Comment by Xento** [comment]
root@bananapi ~ # npm --version
3.7.3

**Comment by sweetpi** [comment]
Downgrade to npm2 `npm install -f npm@2`

**Comment by Xento** [comment]
Now it worked. Didn't noticed that I had a wrong version of npm installed.

**Comment by sweetpi** [comment]
We should add some check and warning.

**Comment by sweetpi** [comment]
I've added a npm version check in v0.9 and in the upcoming v0.8 release.
