### ISSUE TITLE
[v0.9, pimatic-file-browser] Filebrowser does not work

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#842]
Presumably this is due to changes in express v4.
"Middleware and routes are now executed in the order they're added."

**Comment by sweetpi** [comment]
I think the problem was that "directory" middleware was not included in express 4 anymore. I move it to "serve-index" middleware and it is now working (https://github.com/pimatic/pimatic-filebrowser/commit/1a254b5bf57b54342c1b35a503f213e7adba43fa).

**Comment by thost96** [comment]
I installed filebrowser version 0.9.0 and get this error 
```
Cannot GET /files
```
