### ISSUE TITLE
[v0.9.x, pimatic-sysinfo] error [pimatic]: name in [

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#845]
I have changed the device-config-schema as follows to be able to edit the "attributes" property and to have a reasonable set of default values (I thought it might be helpful to have all values (attribute entity names) included so that the user can simply drop values not required. When I create a new device with the device editor the device is properly displayed. However, when I click on "save" an errer is raised: "name in [".

```
module.exports = {
  title: "pimatic-sysinfo device config schemas"
  SystemSensor: {
    title: "SystemSensor config options"
    type: "object"
    extensions: ["xLink", "xAttributeOptions"]
    properties:
      attributes:
        description: "Attributes of the device"
        type: "array"
        default: ["cpu", "memory", "temperature", "dbsize", "diskusage", "memoryRss", "memoryHeapUsed", "memoryHeapTotal", "uptime"]
        items:
          type: "string"
  }
}

**Comment by sweetpi** [comment]
The attributes array contains objects with name property not plain strings. Therefore the assert https://github.com/pimatic/pimatic-sysinfo/blob/development/sysinfo.coffee#L40 did fail.

I added a correct config scheme: https://github.com/pimatic/pimatic-sysinfo/commit/2a1c995a92d05bf5fd56c3ec723a24c55bdb45d3
