### ISSUE TITLE
Modules missing?

### ISSUE THREAD

**Issue by quintz** [pimatic/pimatic#854]
Hi folks,

i finally managed to get pimatic to run but I got some errors in the log.
It said
```
error [pimatic]: Cannot find module './build/Release/raw'
error [pimatic]: Cannot find module 'extend'
```
Do you have an idea what could be the problem?

It is a freshly installed pimatic.

**Comment by sweetpi** [comment]
Could you enable debug logging (see #137) and post the corresponding stack traces?

**Comment by quintz** [comment]
I think I managed to find out what the problem was.
I made a clear reinstall of pimatic again but this time I started pimatic the first time via  the .js and not via the daemon.
This way I could see when it was finished with compiling. I guess the module wasn't installed because I interrupted the compiling process.
Now everything's fine. So this can be closed.
