### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by johnappletree** [pimatic/pimatic#855]
I'm trying to configure SSL. However after running the ssl-setup script and adjusting the config file pimatic wont start anymore.

config file:
>  "settings": {
>     "httpServer": {},
>     "httpsServer": {
>       "enabled": true,
>       "port": 443,
>       "hostname": "",
>       "keyFile": "ca/pimatic-ssl/private/privkey.pem",
>       "certFile": "ca/pimatic-ssl/public/cert.pem",
>       "rootCertFile": "ca/certs/cacert.crt"
>     },

The log file look like this. The first start was with https enabled, the second time with https disabled. it looks like it is going wrong at " [pimatic-cron] info: the time is: Tue Apr 12 2016 22:26:46 GMT+0200 (CEST)"

> 22:09:22.252 2016-04-12 Tuesday
> 22:09:32.049 [pimatic] info: Starting pimatic version 0.8.101
> 22:09:34.385 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.6)
> 22:09:35.232 [pimatic] info: Loading plugin: "pimatic-denon-avr" (0.8.5)
> 22:09:35.876 [pimatic] info: Loading plugin: "pimatic-hap" (0.6.1)
> 22:09:36.951 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.9)
> 22:09:37.038 [pimatic] info: Loading plugin: "pimatic-sysinfo" (0.8.13)
> 22:09:37.317 [pimatic] info: Loading plugin: "pimatic-openweather" (0.8.18)
> 22:09:37.549 [pimatic] info: Loading plugin: "pimatic-z-way" (1.1.0)
> 22:09:37.602 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.82)
> 22:09:38.885 [pimatic] info: Loading plugin: "pimatic-pushover" (0.8.5)
> 22:26:29.635 2016-04-12 Tuesday
> 22:26:39.330 [pimatic] info: Starting pimatic version 0.8.101
> 22:26:41.536 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.6)
> 22:26:42.352 [pimatic] info: Loading plugin: "pimatic-denon-avr" (0.8.5)
> 22:26:42.992 [pimatic] info: Loading plugin: "pimatic-hap" (0.6.1)
> 22:26:44.066 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.9)
> 22:26:44.156 [pimatic] info: Loading plugin: "pimatic-sysinfo" (0.8.13)
> 22:26:44.424 [pimatic] info: Loading plugin: "pimatic-openweather" (0.8.18)
> 22:26:44.586 [pimatic] info: Loading plugin: "pimatic-z-way" (1.1.0)
> 22:26:44.649 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.82)
> 22:26:46.021 [pimatic] info: Loading plugin: "pimatic-pushover" (0.8.5)
> 22:26:46.084 [pimatic-cron] info: the time is: Tue Apr 12 2016 22:26:46 GMT+0200 (CEST)
> 22:26:46.145 [pimatic-hap] info: Starting homekit bridge
> 22:26:46.194 [pimatic-z-way] info: initialized pimatic-z-way with hostname localhost

Whats the problem that im facing?

**Comment by sweetpi** [comment]
Try to start pimatic in non deamon mode: `./pimatic-app/node_modules/pimatic/pimatic.js` and hope you see any error in the output. Without an error message its really hard to find the actual problem.

**Comment by johnappletree** [comment]
Thanks sweetpi for the Tip. It solved the problem! I figured out from that log that an other service was using the 443 port. I changed the https port in the configuration file and now it's working. 
This problem can be closed.

**Comment by mwittig** [comment]
I am closing this one now as it has been resolved. Just tried an setup with an httpsServer listener on an already used port which gives the following message in the log file:

19:16:06.441 [pimatic] error: Could not listen on port 443. Error: listen EADDRINUSE :::443. Is a server already running?
19:16:06.446 [pimatic] info: exiting...
