### ISSUE TITLE
v0.8.103 needs npm v2 - error after update

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#861]
from the forum
check here : https://forum.pimatic.org/topic/1669/error-after-updating-pimatic

After updating to the latest 0.8.103 version of pimatic the following error occurs in the logs:
error [pimatic]: pimatic needs npm version 2, your version is 1.3.21, run "npm install -g npm@2".

**Comment by sweetpi** [comment]
Relaxed the check to npm v < 3
