### ISSUE TITLE
[v0.9] grunt-bump@0.7.2 wants grunt@>=1.0.1 but grunt-coffeelint@0.0.8 wants grunt@~0.4

### ISSUE THREAD

**Issue by michbeck100** [pimatic/pimatic#863]
the grunt-bump dependency in v0.9.x uses a caret which means that all versions up to 1.0.0 will be included. Unfortunately version 0.7.1 adds a dependency to grunt in version >= 1.0.1. 
Because of that pimatic won't let me npm install the 0.9 branch anymore.

**Comment by mwittig** [comment]
Merged, but needs review. 
How to handle this for the future?

**Comment by mwittig** [comment]
This has been resolved. Meanwhile, we upgraded to grunt ^1.0.1 and grunt-bump 0.8
