### ISSUE TITLE
[v0.9] Should node version for travis build be 4.x?

### ISSUE THREAD

**Issue by michbeck100** [pimatic/pimatic#865]
Since pimatic 0.9.x supports node 4.x, i would suggest setting the version to build in travis to 4.x, too. This makes sure that no changes break this compatibility.

**Comment by mwittig** [comment]
Thanks for pointing this out! Changed for v0.9.x branch. However, the travis builds are failing at the moment as there is an issue with coffeelint:app. So, more work is required on the build setup.

**Comment by michbeck100** [comment]
id did fix this already with https://github.com/pimatic/pimatic/pull/864 ;-)

**Comment by mwittig** [comment]
Great. Merged & Build is passing now :)
