### ISSUE TITLE
[v0.9.x] Device editor doesn't allow filling out device_id on netatmoBase device

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#868]
the device editor doesn't allow filling out device_id on netatmoBase device. Not when adding a new one and not when editing this new incomplete one.
![screenshot](https://www.dropbox.com/s/wc7pz5b446fwxcs/Screenshot%202016-04-23%2016.17.36.png?dl=1)

**Comment by thexperiments** [comment]
I think I found the issue, type was not set in the config schema. Should we maybe default to string?

**Comment by mwittig** [comment]
I think the idea is to define the attribute types explicitly rather than using implicit defaults which are not part of the schema language as far as I know

**Comment by thexperiments** [comment]
would it then make sens to fail loading the plugin or at least print an error message if the type is not defined? Then every plugin developer would immediately know he is missing something.

**Comment by mwittig** [comment]
Well, did you check the log output? You should get a warning message at start-up.  A plugin load failure on schema error certainly makes sense. It is a bit more relaxed at the moment as about 50% of trhe plugins are affected by the stricter schema validation introduced with pimatic 0.9.

**Comment by mwittig** [comment]
As far as I can see the issue has been solved by https://github.com/thexperiments/pimatic-netatmo/commit/cec8d0c8f65a537e15408e0d13531578fbb86c5b
