### ISSUE TITLE
[Pimatic] Api role

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#873]
I want to use an Api user to restrict usage of pimatic api and strengthen my security.
I want to set variables and turn switches off and on using the api.

For patching variables  "variables": "write" is enough.

But I have trouble to get the role definition for turning switches off and on.

I assumed  "controlDevices": true was enough.

I use the api syntax: 
{"actionString": "turn <switch>  on"}

I tried several combinations but get always **forbidden.**

Which permissions do I need to restrict the API user and still able to turning switches off and on?

**Comment by edautz** [comment]
I tried another api syntax:

curl http://apiuser:<pwd>@<ip adres pimatic>/api/device/<device>/changeStateTo?state=true

This works. 

Is the above probem a bug?

**Comment by sweetpi** [comment]
> curl http://apiuser:pwd@ip adres pimatic/api/device/deviceid/changeStateTo?state=true

this is possible with "controlDevices": true.

> {"actionString": "turn on"}

needs "rules": "write".

I hope this answers your question.
