### ISSUE TITLE
info [pimatic]: Could not get plugin info from update server, request info from npm

### ISSUE THREAD

**Issue by kayloehmann** [pimatic/pimatic#875]
This is the error message i'm receiving when trying to update plugins.
info [pimatic]: Could not get plugin info from update server, request info from npm

Any suggestions? I turned on debug mode, but no related messages are displayed.
Thanks.

**Comment by sweetpi** [comment]
It isn't really a error message, more a fallback message. Do you have actual trouble updating?

**Comment by kayloehmann** [comment]
Lets put it that way, i'm not sure anymore! When is this message triggered? Never had it before, started since last pimatic update.

**Comment by skipper79** [comment]
Same at my side! After mentioned error message I get the message: Error: connect EHOSTUNREACH

**Comment by seelenbrokat** [comment]
I get the Same Message.

**Comment by sweetpi** [comment]
As I said, the fallback is no problem at all. Probably the update server was down.
