### ISSUE TITLE
[v0.9] weird rule behavior

### ISSUE THREAD

**Issue by sweebee** [pimatic/pimatic#877]
I have a rule thats acting strange. It worked fine in 0.8.

```
when
[[[its before 07:00 or its after 23:00] and if keuken-pir is absent for 15m] or [trigger: light of woonkamer-ldr > 96% and state of keuken-switch1 was not updated for 15m and keuken-pir is absent] or trigger: thuis is closed] and keuken-tafel is turned on
then
turn keuken-tafel off
```

Like this night, at 03:10 the light went on by a PIR. on 03:11 the PIR went absent. But at 03:34 the light was still on, this rule should turn it on after 15m?

And when i enter the kitchen and try to turn on the light when the PIR hasn't triggered yet, this rule will directly turn the light off again. ```keuken-pir is absent for 15m``` triggers only at exactly 15 minutes right?

**Comment by sweebee** [comment]
Simplified the rule to:
```
when
[trigger: light of woonkamer-ldr > 96% and keuken-pir is absent] or trigger: thuis is closed or keuken-pir is absent for 15m
then
turn keuken-tafel off
```
But on trigger: thuis is closed nothing happens. While it should trigger the rule.

**Comment by sweebee** [comment]
on thuis closed:

Works: ```when trigger: thuis is closed```

Doesn't work: ```when keuken-pir is absent for 15m or trigger: thuis is closed```

**Comment by sweebee** [comment]
Ok, I think I found it. when I add something like ``` x is absent for x minutes``` in a rule, the whole rule stops working.

Tried in a different rule:

Works: ```[trigger: light of woonkamer-ldr > 68% or trigger: thuis is closed] and woonkamer-switch1 is turned on```

Doesn't work: ```[trigger: light of woonkamer-ldr > 68% or trigger: thuis is closed] and woonkamer-switch1 is turned on or woonkamer-pir is absent for 15m```

**Comment by sweebee** [comment]
Quickly tried some different timings like 5m 10s 1s. But that didn't help. 

But what did happen is that my living room is now turning off at random times, so looks like the rules are delayed somehow. So yes, something is wrong with ```absent for x time```

**Comment by thexperiments** [comment]
Same here now. Using mysensors motion sensor with auto reset after 1 second.
```
when Bewegungsmelder Küche is absent for 30 seconds
then turn Licht Küche off
```

somehow with an esp8266 setting dummy contact sensor with also 1 second auto reset it worked

It also goes crazy after many triggers. Looks like 60 seconds after the sensor is absent once the light gets turned off although sensor was present after this and should have reset the 60s timeout 
@sweetpi how are these rules evaluated?

**Comment by thexperiments** [comment]
Bump, any news, my PIRs driving me crazy.

Can I anyhow help resolving this? Is the concept of the rule processing documented anywhere?

**Comment by mwittig** [comment]
Sorry, no news yet. I suspect this to be an issue with pimatic-cron. I'll have a look into this asap

**Comment by sweetpi** [comment]
Hm, I can't reproduce the issue. "for x seconds" is actual interpreted as "for at lease x seconds". Maybe this is the issue. 

@thexperiments 

```
when Bewegungsmelder Küche is absent for 30 seconds
then turn Licht Küche off
```

works perfect for me with a dummy pir.

@sweebee 

```
[trigger: light of woonkamer-ldr > 68% or trigger: thuis is closed] and woonkamer-switch1 is turned on or woonkamer-pir is absent for 15m
```

The rule is triggered when: "light of woonkamer-ldr > 68%" or "trigger: thuis is closed" and at the same time "woonkamer-switch1 is turned on" or "woonkamer-pir is absent for **at least** 15m". I highly recommend don't use the trigger keyword anymore. The rule is equivalent with:

```
When light of woonkamer-ldr > 68% or thuis is closed
and if woonkamer-switch1 is turned on or woonkamer-pir is absent for 15m
then ...
```

**Comment by sweebee** [comment]
in pimatic 0.8 its exactly at 15m, it doesn't trigger if its after 15m. How can i use it that way? that it only triggers at exactly 15m.

**Comment by sweebee** [comment]
Also if i remove the trigger, my rule doesn't work anymore as it should. Why should I don't use trigger anymore then?

if i remove trigger from ```light of woonkamer-ldr > 68``` and don't check if the living room is turned on, the rule gets triggered even when the living room is already off, so it triggers the rule but its not needed, only if the living room is on.

**Comment by sweebee** [comment]
This doesn't work:
```
light of woonkamer-ldr > 68% or thuis is closed and if woonkamer-switch1 is turned on
```
If i turn on the lights when the ldr > 68% the lights go off again when that ldr value changes. But it should only turn off when the value gets above 68%. So lets say from 67 to 69. Not from 69 > 70

**Comment by sweetpi** [comment]
> in pimatic 0.8 its exactly at 15m, it doesn't trigger if its after 15m. How can i use it that way? that it only triggers at exactly 15m.

No, nothing changed here. Ofcause it depends how you use it. If you use it with the trigger keyword, then it only triggers at exactly 15m.

> Also if i remove the trigger, my rule doesn't work anymore as it should. Why should I don't use trigger anymore then?

Because all predicates in the "when"-part are triggers and all conditions in "and if" are not.

> if i remove trigger from light of woonkamer-ldr > 68 and don't check if the living room is turned on, the rule gets triggered even when the living room is already off, so it triggers the rule but its not needed, only if the living room is on.

That's why its checked in the "and if" part in my proposed rule.


> This doesn't work:
> 
> light of woonkamer-ldr > 68% or thuis is closed and if woonkamer-switch1 is turned on
> If i turn on the lights when the ldr > 68% the lights go off again when that ldr value changes. But it should only turn off when the value gets above 68%. So lets say from 67 to 69. Not from 69 > 70

Could you post the whole rule? The rule should trigger only from 67 to 69 and not from 69 to 70.. So there is mybe a bug.

**Comment by sweebee** [comment]
The whole rule:
```
light of woonkamer-ldr > 68% or thuis is closed and if woonkamer-switch1 is turned on then turn woonkamer-switch1 off
```

Its not possible to use trigger when you've added "for x time":

Rule: ```when trigger: woonkamer-pir2 is absent for 5m then turn woonkamer off```

Error:  "trigger: woonkamer-pir2 is absent for 5m" is marked as trigger, it can't be true for "woonkamer-pir2 is absent"

**Comment by sweebee** [comment]
Also this doesn't work as i mentioned:
```
when keuken-pir is absent for 15m or trigger: thuis is closed
```
the rule doesn't trigger when thuis gets closed. It does when i remove the keuken-pir is absent for... part.

**Comment by sweetpi** [comment]
@sweebee What kind of device is "keuken-pir"? Can you reproduce it with dummy devices?

**Comment by mwittig** [comment]
I can't reproduce the problem so far. I have used the following which works fine for me, i.e. switch is turned on at 40 seconds (once a minute).

```
{
      "command": "if [ `date +%S` -lt 30 ]; then echo 1; else echo 0; fi",
      "id": "shell2",
      "name": "shell2",
      "class": "ShellPresenceSensor",
      "interval": 5000
  }
...
{
      "id": "r1",
      "name": "r1",
      "rule": "when shell2 is present for 10 seconds then turn denon-avr-power on",
      "active": true,
      "logging": true
}

**Comment by sweebee** [comment]
Its a mysensors pir. I Will do Some tests tomorrow with dummy devices.

**Comment by sweebee** [comment]
Okay, did a test and created:

Dummy switch
Dummy pir
Dummy contact

this rule:
```
when dummy-pir is absent for 15m or trigger: dummy-contact is closed then turn dummy-switch off
```

But when i change the contact of the dummy contact, the switch won't turn off.

Video: https://youtu.be/bq7hEARUWb8

**Comment by sweetpi** [comment]
Thanks for the test case. Now I was able to reproduce the issue and solve it. I did rewrite the code for the rule system in the commit above.

@sweebee It would be great if you could test the new code. But be warned it could break potentially all your rules. But my quick tests and test cases get well.

In addition I __plan__ to introduce "for exactly x" and "for at least x" to specify the behavior of the "for" suffix explicitly.

**Comment by sweebee** [comment]
Looks like its working fine now :) Also, my dummy pir is now absent for 33 minutes. when i switch the dummy switch on now, it won't go off because of the absent for xx time. Like it worked pimatic 0.8. For me thats correct, but you said it should also trigger after the absent for x time?

**Comment by sweebee** [comment]
Got a weird error today (with commit ee10b06) 
Rule:
```
trigger: 30m before sunset and thuis is opened or trigger: thuis is opened and its after 30m before sunset
```
Error:
```
error [pimatic]: rule buitenlampen-aan error executing an action: _this.filterConflictingState is not a function
21:04:22error [pimatic]: Error on evaluation of rule condition of rule buitenlampen-aan: _this.filterConflictingState is not a function
```

**Comment by mwittig** [comment]
filterConflictingState is a method implemented by pimatic-hue-zll devices. Which device class do you for your buiten-lampen?

May be this is an error in the pimatic-hue-zll. Note there has been a fix for "missing filterConflictingState method to HueZLLOnOffLight" about two months ago which has not been published yet! So, the fix is not part of 0.2.0!

**Comment by sweebee** [comment]
Its a HueZLLDimmableLightGroup

**Comment by mwittig** [comment]
Ah, ok. This is derived from HueZLLOnOffLight. So, if you're using pimatic-hue-zll v0.2.0, installing the master (`npm i markbergsma/pimatic-hue-zll`) should fix the issue.

**Comment by sweebee** [comment]
Yes thanks. Everything is working now.

**Comment by thexperiments** [comment]
when will the fix be published on npm with the @beta tag?

**Comment by mwittig** [comment]
There is a new pimatic beta available now. Enjoy!

**Comment by thexperiments** [comment]
Great! first tests look fine. Just re-enabled all rules with "is absent for" :+1:
