### ISSUE TITLE
Update server and forum down

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#878]
Actually the forum and update server of pimatic is having some trouble and cannot be accessed. 
Seems as somebody pulled the plug ^^ 

So if you're having issues with updating pimatic pls be patient, we're working on it to get things up again.

**Comment by leader21** [comment]
allright, troubleshooting was faster then expected :)
all is working again. if you're still having trouble try to clear cache and reload.

**Comment by mwittig** [comment]
Please re-open if issue pops up again

**Comment by thexperiments** [comment]
Seems to be the issue again

**Comment by mwittig** [comment]
Forum has been migrated to a new server. 
This hopefully solves the problem with  intermittent system failures.

**Comment by thexperiments** [comment]
And down again

**Comment by mwittig** [comment]
This morning I had a 503 with a message indicating massive load on the server. May be someone is driving DoS attacks against the server?!

**Comment by thexperiments** [comment]
Aslo saw it this morning. DDOS is unlikely I think. Maybe some unintended DDOS by an article/post somwhere on the internet about how great Pimatic is ;)
Someone would need to take a look at the logs/analytics.

**Comment by leader21** [comment]
We will move the forum and update server to a more powerful machine soon, hoping to get rid of these issues then.
