### ISSUE TITLE
[v0.9.x] mobile-frontend checkboxes need two clicks/taps

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#882]
Currently checkboxes in the GUI seem to need at least two taps/clicks in order to be activated/deactivated.

Examples: Remember login, Rule logging
Browser: Chrome, Mobile Safari

**Comment by sweetpi** [comment]
On which device(s)?

**Comment by sweebee** [comment]
Same here, it happened since fast click is added. For instance the remember login at the login page.

**Comment by thexperiments** [comment]
Devices are iPad/iPhone

**Comment by sweebee** [comment]
fix works!
