### ISSUE TITLE
website: please add links  to the plugins page

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#886]
Cannot currently find a way to navigate to more plugin information. Plugin pages should contain links to either/or plugin homepage and npm site.

**Comment by mwittig** [comment]
Can please explain exactly what you need? On <https://pimatic.org/pages/plugins/> you have all plugins listed with links to the github project and a page generated from the content of the README and schema files. Normally, the generation works reasonably well.

**Comment by andig** [comment]
I didn't notice the small github link on the overview page. If possible both npm and gh links should be on details page, too. 

Viele Grüße,
Andreas

**Comment by sweetpi** [comment]
I added a npm link and the links to the detail pages.

**Comment by andig** [comment]
> I added a npm link and the links to the detail pages.

much appreciated, thank you! Even I could find it now ;)
