### ISSUE TITLE
2 Pull requests are waiting to be integrated

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#887]
Hi,

There are 2 translations updates awaiting integration (pull requests).
Will it be integrated?

Cheers
Yves

**Comment by mwittig** [comment]
Good question. I have merged your changes into the v0.9.x branch. Regarding the PR from @sweebee I am not sure how @sweetpi wished to handle it as it contains several additions. I guess he needs to review it.

**Comment by mwittig** [comment]
All merged to v0.9.x
