### ISSUE TITLE
[v0.9.] Can't evaluate boolean attributes in rules

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#889]
Looks like evaluation of boolean attributes for conditions/triggers currently is not possible. Works fine for strings and numbers.

See:
https://forum.pimatic.org/topic/1758/react-on-milight-actions/12

Saw this with 0.9.x, maybe also valid for 0.8.x

**Comment by mwittig** [comment]
Hi. I have quickly tested it. Eval of boolean attributes works fine for me. It won't work for variables though as variables can only be of type number or string.

**Comment by mwittig** [comment]
Closing this now. Please reopen if you have new fundings or the problem pops up gain
