### ISSUE TITLE
Homeduino crashes on Raspberry Pi 2

### ISSUE THREAD

**Issue by firesgc** [pimatic/pimatic#890]
I am getting a “A uncaught exception occured: Error: spawn ENOENT”-exception if I enable the homeduino plugin with following configuration:
```
{
  "plugin": "homeduino",
  "driver": "gpio",
  "driverOptions": {},
  "receiverPin": 0,
  "transmitterPin": 1
}
```
It seems that the home "pimatic-homeduino/node_modules/homeduino/bin/vhduino"-binary is not compatible to the raspberry pi 2 (at least I am not able to start it, if i call it directly from the bash and get a "-bash: ./vhduino: No such file or directory-error" ).

The file attributes of the binary are correct:
```
~/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/bin$ ls -la .
total 96
drwxr-xr-x 2 fires fires  4096 Mar 28 13:56 .
drwxrwxrwx 7 fires fires  4096 May 11 19:52 ..
-rwxr-xr-x 1 fires fires 88883 Mar 28 13:56 vhduino

**Comment by mwittig** [comment]
Hi. "The pin numbers are Arduino pin numbers. The receiverPin must be either 0 (INT0) or 1 (INT1). The transmitterPin must be a digital pin between 2 (D2) and 13 (D13)."

**Comment by firesgc** [comment]
Hi!

Thank you for the fast answer. 

I am using the gpio driver and my transmitter and receiver are connected to the raspberry pi 2 gpio directly (using pin11/wiringPi0 and pin12/wiringPi1 for data). For this reason I thought I would have to use the same options like in pilight.

On the other hand I don't understand why pimatic throws an ENOENT exception, which indicates a missing file or directory most of the time. And last but not least I am not able to run the vhduino binary directly on the raspberry pi 2.

**Comment by mwittig** [comment]
I am not sure whether or not homeduino supports this. As far as I know the "gpio" option involves a "ATTiny45 / 85 Prefilter" connected between Raspi and the receiver/transmitter. See [README](https://github.com/pimatic/pimatic-homeduino) for details. May be you can create a topic in the pimatic forum on this to get help from other users and to discuss the best way forward for what you're trying to achieve. https://forum.pimatic.org/

**Comment by leader21** [comment]
There should be no difference between pi1/2/3 
Have a look here at the howto and compare your setup 
https://forum.pimatic.org/topic/202/4-homeduino-433-mhz-sending-receiving-and-even-more/2

You should not use the pilight attiny prefilter anymore (as far as you still use it) Remember that users reported issues. Homeduino has a built in filter as well.

another question, did you install the gpio plugin ?

**Comment by firesgc** [comment]
I have reverted to an older version of vhduino (7b3b677  on 13 Feb 2015 @bjornhij bjornhij Correct binary)
and at least I am able to start pimatic now.

If you call readelf on the "old version", you can see that it request an arm interpreter instead of an "normal" one.
So the currently submitted vhduino is not compatible with arm devices

The output:

readelf -l ./vhduino |grep interpreter
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
	  
readelf -l ./vhduino_org |grep interpreter
      [Requesting program interpreter: /lib/ld-linux.so.3]

**Comment by ManuelW77** [comment]
Hey there, i have the same problem on pi2 with xbian. 
any hint how to solve this?

**Comment by mwittig** [comment]
@firesgc @ManuelW77 Maybe the following is helpful for you: https://forum.pimatic.org/topic/2460/solved-installing-pimatic-0-9-osmc/53
