### ISSUE TITLE
no working frontend

### ISSUE THREAD

**Issue by dennis071nl** [pimatic/pimatic#891]
Recently i installed some other components on the Raspi but afterwards i realised i broke the pimatic installation. I tried to repair it by removing the other packages, but now i cannot reach the frontend anymore. Backend seems to work (i still receive pushover messages from the pimatic installation) but frontend keeps down. 

in the log files there is a java exception: 

Unhandled rejection Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

My programming skills arent's that good, so maybe some of you guys can help me out??

Thanks in advance, i really would like to get this install working again without having to reinstall everything again...!

**Comment by leader21** [comment]
Try the following 
Delete your pimatic-mobile-frontend folder and restart pimatic. Assuming the standard installation in the home/pi directory it's like the following command (otherwise change the path!):
`sudo rm - rf /home/pi/pimatic/node_modules/pimatic-mobile-frontend`
`sudo service pimatic restart`
The plugin will be installed again.
If the error persists pls report back with some debug information.

**Comment by dennis071nl** [comment]
Chris, 

Getting a bit closer....:-)

Now i see the frontend, but it keeps reconnecting (xhr poll error)..

pimatic-daemon.log: 


07:35:12.417 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/convict requires cjson@'0.3.0' but will load
07:35:12.459 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/cjson,
07:35:12.468 [pimatic, npm] info: WARN unmet dependency which is version 0.3.1
07:35:12.532 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/node_modules/connect requires connect-timeout@'~1.6.2' but will load
07:35:12.542 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-app/node_modules/pimatic/node_modules/connect-timeout,
07:35:12.560 [pimatic, npm] info: WARN unmet dependency which is version 1.7.0
07:35:13.422 [pimatic, npm] info: pimatic-mobile-frontend@0.8.83 node_modules/pimatic-mobile-frontend
07:35:13.443 [pimatic, npm] info: ├── colour.js@1.5.2
07:35:13.459 [pimatic, npm] info: └── jqmthemer@0.0.1 (bluebird@2.2.2)
07:35:16.920 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.83)

**Comment by dennis071nl** [comment]
Chris, 

Nevermind, i rebooted the Pi and everything is allright now. 

Thanks for your support and solution!

**Comment by leader21** [comment]
Nice to hear ! 
You're welcome. 
Could you pls. Be so kind and close this issue then? Thx!
