### ISSUE TITLE
[0.9.x] Plugins page - "installed" should initially be highlighted

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#894]
When going to plugins first time the istalled plugins are shown. This should also be visible in the installed/available header navigation. "installed" should be highlighted.

**Comment by andig** [comment]
I've also noted that the "restart now" message doesn't disappear in the frontend if the server has been manually restarted after configuring a plugin.

**Comment by mwittig** [comment]
> I've also noted that the "restart now" message doesn't disappear in the frontend if the server has been manually restarted after configuring a plugin.

Restart from UI is only possible if pimatic has started daemonized. You can also start the serve pimatic manually in daemonized mode as follows: `node pimatic start`

**Comment by andig** [comment]
> Restart from UI is only possible if pimatic has started daemonized. You can also start the serve pimatic manually in daemonized mode as follows: node pimatic start

I know. However I _have_ manually restarted the process, yet the message remains even after frontend is reconnected.

**Comment by sweetpi** [comment]
Thanks for reporting. Fixed in v0.9.x branch.
