### ISSUE TITLE
[0.9.x] config is not defined

### ISSUE THREAD

**Issue by andig** [pimatic/pimatic#895]
Trying to create a new fritz thermostat device through the UI I run into a pimatic core error when saving:

	14:18:53.457 [pimatic] config is not defined

Probably a plugin problem but I don't really know where to look- pointer would be appreciated.

**Comment by mwittig** [comment]
Can please add a link to the codebase so that I can review the code. It is plugin source code problem indeed

**Comment by andig** [comment]
@mwittig its the usual suspects: https://github.com/andig/pimatic-fritz

**Comment by andig** [comment]
Wait a minute. I gues I forgot to publish you updates for 0.9. let me retest this.

**Comment by mwittig** [comment]
Most likely. Version on npmjs is 0.3.3, published 6 months ago

**Comment by andig** [comment]
Thats it. Fixed after publishing 0.3.4.
