### ISSUE TITLE
Idea: new plugin "pimatic-epg"

### ISSUE THREAD

**Issue by Man-in-Black** [pimatic/pimatic#897]
Hi all together,

I hope I'm placing this feature request right.

I'm going to buy sime IR transmitters and I want to control my IR devices with it.

It would be nice if there is anyone wo may create a new plugin called "pimatic-epg" to control my receiver based on the show I want to see.

I'm glad to hear your response to that idea.

**Comment by Yves911** [comment]
Hi,
We have a forum and a section for feature-requests : https://forum.pimatic.org/category/14/feature-requests 
It will be easier to discuss this plugin at this place.
Cheers
Yves

**Comment by mwittig** [comment]
As @Yves911 said we use the forum to discuss, vote for, and prioritize feature requests. Moreover, there are more pimatic users subscribed to the forum than to github.  You can easily use your github account to enroll a forum account. I am closing this issue now.
