### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Kamaluk** [pimatic/pimatic#900]
the projects website is down

opening https://pimatic.org/ leads to an error.

> 502 Bad Gateway
> nginx

**Comment by mwittig** [comment]
Thanks for reporting!

**Comment by Kamaluk** [comment]
gern :)
Vielleicht ist es ja auch mit nem Neustart behoben?

**Comment by Kamaluk** [comment]
Ach, hätte das vielleicht unter pimatic.org posten können... Naja. Nun ist es hier.

**Comment by mwittig** [comment]
Läuft wieder!
