### ISSUE TITLE
Pimatic does'nt work after plugin update update

### ISSUE THREAD

**Issue by nco1512** [pimatic/pimatic#902]
Hi guys,
after I updatet some plugins in my system, Pimatic won't run anymore.
Here's what it's saying:
"21:46:14.594 [pimatic] error: A uncaught exception occured: Error: spawn EACCES
21:46:14.594 [pimatic] error:>    at errnoException (child_process.js:980:11)
21:46:14.594 [pimatic] error:>    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
21:46:14.594 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
21:46:14.597 [pimatic] info: exiting...
"
I don't know what to do :-(

**Comment by mwittig** [comment]
This is a duplicate of https://github.com/pimatic/pimatic-homeduino/issues/62

Please upgrade to version 0.8.12 (assuming you're running pimatic 0.8). You should be able to simply update via frontend
