### ISSUE TITLE
Pimatic won't start after latest updates

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic#903]
After latest update today (homeduino and something else) and a restart. Pimatic will not start anymore.

pi@raspberrypi ~ $ sudo service pimatic status
Pidfile exists, but process is dead.

**Comment by mwittig** [comment]
Can you provide a log file, please? Thanks

**Comment by pimagical** [comment]
pi@raspberrypi ~/pimatic-app $ cat pimatic-daemon.log
01:22:28.251 2016-05-25 Wednesday
01:22:51.580 [pimatic] info: Starting pimatic version 0.8.107
01:23:00.055 [pimatic, npm] info: 1.3.21
01:23:00.181 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.8)
01:23:01.425 [pimatic] info: Loading plugin: "pimatic-mobile-frontend"
(0.8.83)
01:23:04.385 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.14)
01:23:04.635 [pimatic] info: Loading plugin: "pimatic-sysinfo" (0.8.14)
01:23:05.130 [pimatic] info: Loading plugin: "pimatic-openweather" (0.8.22)
01:23:05.325 [pimatic] info: Loading plugin: "pimatic-shell-execute"
(0.8.20)
01:23:05.451 [pimatic] info: Loading plugin: "pimatic-links" (0.8.6)
01:23:05.566 [pimatic] info: Loading plugin: "pimatic-homeduino" (0.8.80)
01:23:07.582 [pimatic] info: Loading plugin: "pimatic-sunrise" (0.8.7)
01:23:07.678 [pimatic] info: Loading plugin: "pimatic-play" (0.8.0)
01:23:07.948 [pimatic] info: Loading plugin: "pimatic-upnp-root" (0.8.9)
01:23:08.378 [pimatic] info: Loading plugin: "pimatic-ipcamera" (1.1.1)
01:23:11.436 [pimatic] info: Loading plugin: "pimatic-mail" (0.8.6)
01:23:13.890 [pimatic] info: Loading plugin: "pimatic-iframe" (0.1.3)
01:23:14.118 [pimatic] info: Loading plugin: "pimatic-hap" (0.6.3)
01:23:16.216 [pimatic] info: Loading plugin: "pimatic-max" (0.8.17)
01:23:16.405 [pimatic] info: Loading plugin: "pimatic-smartmeter" (0.0.18)
01:23:16.490 [pimatic-cron] info: the time is: Wed May 25 2016 01:23:16
GMT+0200 (CEST)
01:23:17.112 [pimatic-hap] info: Starting homekit bridge
01:23:19.038 [pimatic] info: New device "Livingroom"...
01:23:19.210 [pimatic] info: New device "Kitchen"...
01:23:19.315 [pimatic] info: New device "Gardenroom"...
01:23:19.411 [pimatic] info: New device "Bedroom"...
01:23:19.488 [pimatic] info: New device "Bathroom"...
01:23:19.571 [pimatic] info: New device "Bedroom radiator"...
01:23:19.656 [pimatic] info: New device "Kitchenroom radiator"...
01:23:19.741 [pimatic] info: New device "Livingroom radiator"...
01:23:19.819 [pimatic] info: New device "Gardenroom radiator"...
01:23:19.886 [pimatic] info: New device "Bathroom radiator"...
01:23:19.964 [pimatic] info: New device "DummyMaxCube"...
serialport options
{ portName: '/dev/ttyUSB0',
  baudRate: 115200,
  dataBits: 8,
  parity: 'none',
  stopBits: 1,
  flowControl: true }
01:23:21.607 [pimatic] info: New device "Smartmeter"...
01:23:21.721 [pimatic] info: New device "Fixed Temperature"...
01:23:21.834 [pimatic] info: New device "ShellSwitch+xConfirm"...
01:23:21.915 [pimatic] info: New device "DummyDimmer"...
01:23:22.228 [pimatic] info: New device "Garden room"...
01:23:22.315 [pimatic] info: New device "Garden room"...
01:23:22.367 [pimatic] info: New device "Living room"...
01:23:22.459 [pimatic] info: New device "Hagestein Beneden"...
01:23:22.556 [pimatic] info: New device "Hagestein Boven"...
01:23:22.661 [pimatic] info: New device "Nieuwegein"...
01:23:22.776 [pimatic] info: New device "Dordrecht"...
01:23:22.883 [pimatic] info: New device "Pimatic Version"...
01:23:22.990 [pimatic] info: New device "Pimatic Version Request"...
01:23:23.075 [pimatic] info: New device "Kribbemonde"...
01:23:23.139 [pimatic] info: New device "Display"...
01:23:23.214 [pimatic] info: New device "Sound"...
01:23:23.310 [pimatic] info: New device "iRoomba"...
01:23:23.349 [pimatic] info: New device "Disco mode"...
01:23:23.412 [pimatic] info: New device "Station"...
01:23:23.455 [pimatic] info: New device " "...
01:23:23.518 [pimatic] info: New device "Control"...
01:23:23.627 [pimatic] info: New device "Bank lampen"...
01:23:23.716 [pimatic] info: New device "Boekenkast lamp"...
01:23:23.797 [pimatic] info: New device "Eettafel lamp"...
01:23:23.871 [pimatic] info: New device "Dressoir lampen"...
01:23:23.947 [pimatic] info: New device "Kledingkast lamp"...
01:23:24.016 [pimatic] info: New device "Group one"...
01:23:24.115 [pimatic] info: New device "Group two"...
01:23:24.194 [pimatic] info: New device "inbouw"...
01:23:24.258 [pimatic] info: New device "Livingroom"...
01:23:24.314 [pimatic] info: New device "Garden"...
01:23:24.379 [pimatic] info: New device "Restart"...
01:23:24.479 [pimatic] info: New device "Time"...
01:23:24.566 [pimatic] info: New device "IP address"...
01:23:25.849 [pimatic] info: New device "Outside"...
01:23:26.022 [pimatic] info: New device "Tomorrow"...
01:23:26.103 [pimatic] info: New device "Raspberry Pi 2"...
01:23:26.212 [pimatic] info: New device "Zonsopgang"...
01:23:26.309 [pimatic] info: New device "Zonsopgang / Ondergang"...
01:23:26.368 [pimatic] info: New device "Iemand thuis"...
01:23:26.413 [pimatic] info: New device "Beide thuis"...
01:23:26.465 [pimatic] info: New device "Status"...
01:23:26.521 [pimatic] info: New device "iPhone William"...
01:23:26.597 [pimatic] info: New device "iPhone Harriëtte"...
01:23:26.666 [pimatic] info: New device "Internet"...
01:23:26.710 [pimatic] info: New device "Synology"...
01:23:26.757 [pimatic] info: New device "Printer"...
01:23:26.800 [pimatic] info: New device "Maxcube"...
01:23:26.849 [pimatic] info: New device "Chromecast"...
01:23:56.927 [pimatic] info: rule good-night: set $status to Good night,
sleep well!
01:23:56.933 [pimatic] info: rule group-one-two-off: press button
radio-pause ofdevice radio-control
01:23:57.320 [pimatic] info: rule magicmirror-display-off: turned Display
off
- Serial port is open
01:23:57.691 [pimatic-max] error: connection error: Error: connect
EHOSTUNREACH
01:23:57.701 [pimatic-max] error: Error on connecting to max cube: connect
EHOSTUNREACH
01:23:57.744 [pimatic] error: A uncaught exception occured: Error: spawn
EACCES
01:23:57.744 [pimatic] error:>    at errnoException
(child_process.js:980:11)
01:23:57.744 [pimatic] error:>    at Process.ChildProcess._handle.onexit
(child_process.js:771:34)
01:23:57.744 [pimatic] error:> This is most probably a bug in pimatic or in
a module, please report it!
01:23:57.749 [pimatic] info: exiting...

2016-05-25 1:59 GMT+02:00 Marcus Wittig <notifications@github.com>:

**Comment by mwittig** [comment]
Thanks! 

This should already have been fixed with the latest pimatic-homeduino release. See also https://github.com/pimatic/pimatic-homeduino/issues/62

Try to manually update pimatic-homeduino, e.g.
```
cd /home/pi/pimatic-app
sudo npm install pimatic-homeduino --unsafe-perm
sudo service pimatic restart
```

Hope, this helps

**Comment by pimagical** [comment]
Thanks!

**Comment by nco1512** [comment]
Yeah, thanks! This way works! :-)
