### ISSUE TITLE
[v0.9.x] Uninstalling a plugin via frontend does not work. 

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#904]
Uninstalling a plugin via frontend does not work. 

Observed Behaviour:
If the Uninstall button is pressed, a toast is displayed with a "Not Found" error. No error message is shown in the log. The plugin is removed from the list of plugins, but there is no indication that pimatic needs to be restarted. When pimatic is restarted manually, the plugin will be re-installed

07:25:08.262 [pimatic] Installing: "pimatic-yoctopuce@1.0.7" from npm-registry.

**Comment by mwittig** [comment]
If "Deactivate" a plugin I'll be prompted for "Restart". When I "Uninstall" after restart the "Not Found" error is displayed, but if I restart again the plugin is no longer re-installed.

Here are my conclusions from the observed behaviour:
* "Uninstall" needs to perform "Deactivate" internally
* The "Not Found" must be handled gracefully in the given context

**Comment by sweetpi** [comment]
The 404 error was accidentally thrown because the uninstalPlugin action was declared with an result, but did not return a value. I've fixed the api declaration.
