### ISSUE TITLE
Pimatic doesent start 

### ISSUE THREAD

**Issue by seelenbrokat** [pimatic/pimatic#905]
21:52:37.403 [pimatic-max] connection error: Error: connect EHOSTUNREACH
21:52:37.421 [pimatic-max] Error on connecting to max cube: connect EHOSTUNREACH
21:52:37.460 [pimatic] A uncaught exception occured: Error: spawn EACCES
21:52:37.460 [pimatic]>    at errnoException (child_process.js:980:11)
21:52:37.460 [pimatic]>    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
21:52:37.460 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
21:52:37.475 [pimatic] exiting...

**Comment by mwittig** [comment]
Please see https://github.com/pimatic/pimatic/issues/903
