### ISSUE TITLE
[v0.9.x] destroy function is performed after recreating the device.

### ISSUE THREAD

**Issue by wutu** [pimatic/pimatic#907]
More info I posted here:
https://forum.pimatic.org/topic/1830/pimatic-v0-9-destroy-function-and-mqtt

**Comment by mwittig** [comment]
Hi, Unfortunately, it is not that easy to change the ordering of creation and destuction as I expected. I think I need @sweetpi to give advice on this as I am not fully familiar with device management mechanics.

https://github.com/pimatic/pimatic/blob/v0.9.x/lib/devices.coffee#L1392-L1397

**Comment by sweetpi** [comment]
Thanks for reporting, should be fixed in the latest beta.
