### ISSUE TITLE
[0.9] Can't edit config, error when saving

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#908]
![](https://www.dropbox.com/s/i5edslniaurp9z5/Screenshot%202016-05-28%2021.33.44.png?dl=1)

can't edit the config anymore with latest update mobile-frontend 0.9.5

don't know if it was broken before, I don't use it often.

This happens right when you try to save the config.

**Comment by sweetpi** [comment]
Thanks for reporting. Should be fixed in latest beta.
