### ISSUE TITLE
[v0.9] Cant update to 0.9.16

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic#910]
````
23:37:03.712 [pimatic] info: Installing: "pimatic@0.9.16" from npm-registry.
23:37:31.112 [pimatic, npm] info: WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
23:38:18.192 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/decl-api requires lodash@'~2.4.1' but will load
23:38:18.210 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/lodash,
23:38:18.212 [pimatic, npm] info: WARN unmet dependency which is version 3.10.1
23:38:18.214 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/decl-api requires bluebird@'~2.3.0' but will load
23:38:18.216 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird,
23:38:18.228 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
23:38:18.231 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/knex requires bluebird@'^2.9.24' but will load
23:38:18.233 [pimatic, npm] info: WARN unmet dependency /home/pi/pimatic-beta/node_modules/pimatic/node_modules/bluebird,
23:38:18.242 [pimatic, npm] info: WARN unmet dependency which is version 3.3.4
23:38:18.584 [pimatic, npm] info: ERR! Linux 4.1.19-v7+
23:38:18.593 [pimatic, npm] info: ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "pimatic@0.9.16" "--unsafe-perm"
23:38:18.596 [pimatic, npm] info: ERR! node v4.2.6
23:38:18.600 [pimatic, npm] info: ERR! npm  v2.14.12
23:38:18.602 [pimatic, npm] info: ERR! code EPEERINVALID
23:38:18.850 [pimatic, npm] info: ERR! Please include the following file with any support request:
23:38:18.858 [pimatic, npm] info: ERR!     /home/pi/pimatic-beta/npm-debug.log
````

**Comment by mwittig** [comment]
> 23:38:18.596 [pimatic, npm] info: ERR! node v4.2.6
> 23:38:18.600 [pimatic, npm] info: ERR! npm  v2.14.12

Please update to node v4.4
Make sure to shutwon any running node processes before updating

**Comment by thexperiments** [comment]
Is this a hard requirement? Or is this just a mechanism to make the people update to the latest Node LTS release?

If I update to 4.4 it will break my complete z-wave integration due to this issue:
https://github.com/Z-Wave-Me/z-way-issues/issues/107

**Comment by mwittig** [comment]
We ran into problems with pimatic 0.9 earlier when using pimatic 4.0. About v4.2 I am not sure. 

Hopefully, the issues with Z-Way get fixed soon. Looking at the issues history I am getting the impression that software support by Z-Wave-Me leaves much to be desired.

Regarding the "EPEERINVALID" may be this caused by one of the plugins. Please check package.json files for "peerDependencies" throughout the plugin directories.

**Comment by PoltoS** [comment]
@mwittig We have a new test version **v2.2.2-test-new-webserver-5-gba57763** that is a transitional beta with new webserver. Will certainly become release in June

**Comment by mwittig** [comment]
@PoltoS Thanks for letting me know! I apologize for my unqualified comments regarding support. I believe you guys are working very hard to make things better.

**Comment by PoltoS** [comment]
@mwittig from your comment looks like we need to work better ;) we understand this and we are open for your requests.

**Comment by mwittig** [comment]
@thexperiments Did you check the "peerDependencies" throughout the plugin directories (including the pimatic directory in node_modules)?

**Comment by sweetpi** [comment]
Our patched npm (ppm) ignores the EPEERINVALID error. So this should no be an problem anymore.
