### ISSUE TITLE
[Pimatic] Posting the state or value of a pimatic variable to a webservice error

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#911]
I want a webservice running in a ESP8266 update with some pimatic variabele info.

If I make a rule with static content like below:

if something changes
then
execute "curl --silent -X POST --header \"Content-Type:application/text\"  --data 'Information=value' http://192.168.X.XX/webpage"

it works.

But when I put an variable in the rule like:

if something changes
then
execute "curl --silent -X POST --header \"Content-Type:application/text\"  --data 'Information=**$button.state**' http://192.168.X.XX/webpage"

it doesn't work and it throws the following error:

19:17:28error [pimatic]: rule xxxxxxx error executing an action: Command failed: 
debug [pimatic]: Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)

Is it a syntax error?

**Comment by SLiX69** [comment]
Maybe the error appears cause the variable is quoted with ' '

Just an idea, you could try something like this 'Information='$button.state

**Comment by edautz** [comment]
@SLiX69

Just tried your suggestion, but it throws the same error. 

In my investigation I tried single quotes, escaped double quotes, variabele in single quotes, but this doesn't work. All the same error.

**Comment by thexperiments** [comment]
put the variable in curly brackets 

`'Information={$button.state}'`

**Comment by edautz** [comment]
@thexperiments,


To bad. Doesn't also not work even when I escape the { and } with \.

But a slightly different error message:

debug [pimatic]: Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by edautz** [comment]
@thexperiments,

I made a programmic error on the ESP side.
Your solution with variable in curly brackets works like charm.

Thanks.
