### ISSUE TITLE
[pimatic-shell-execute] - ShellSensor Acronym option

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic#913]
![image](https://cloud.githubusercontent.com/assets/11790664/15713945/d75936ca-2818-11e6-89d1-000ae5cb6c7c.png)

Using the ShellSensor device i was missing the Acronym field option:
>     {
      "id": "water-level-nieuwegein",
      "name": "ShellSensor",
      "class": "ShellSensor",
      "attributeName": "cm",
      "attributeType": "number",
      "attributeUnit": "cm",
      "command": "curl -s http://www.rijkswaterstaat.nl/apps/geoservices/rwsnl/awd.php?mode=html | html2text | grep Nieuwegein |awk '{print $4}'",
      "interval": 660000
    },
> 

A VariableDevice does have a acronym field:
> 
    {
      "id": "variabledevice-water-level-nieuwegein-acronym",
      "class": "VariablesDevice",
      "name": "VariablesDevice & Acronym",
      "variables": [
        {
          "name": "Water level",
          "type": "number",
          "unit": "cm",
          "label": "Water level",
          "acronym": "NAP",
          "expression": "$water-level-nieuwegein.cm"
        }
      ]
    },
> 

A ShellSensor with a "attributeAcronym" would be great and maybe also a "attributeLabel?

*NAP is the same as Normalnull

**Comment by mwittig** [comment]
pimatic-shell-execute@0.8.22 and pimatic-shell-execute@0.9.3 (beta)
* Added attributeAcronym
