### ISSUE TITLE
homeduino not working after update V0.8.83

### ISSUE THREAD

**Issue by wernersenz** [pimatic/pimatic#914]
after the last update pimatic-homeduino of Version 0.8.83 not working homeduino and not Devices

**Comment by leader21** [comment]
Could you provide more information or debug data pls.

**Comment by leader21** [comment]
you could do the following
`sudo rm -rf /home/pi/pimatic-app/node_modules/pimatic-homeduino`
`sudo service pimatic restart`
the plugin will be installed again

**Comment by wernersenz** [comment]
it works now, thank you
