### ISSUE TITLE
[pimatic-mobile-frontend] SweetAlert issues with Microsoft Edge

### ISSUE THREAD

**Issue by mwittig** [pimatic/pimatic#922]
See https://forum.pimatic.org/topic/1871/edit-config-via-front-end

Using the Config Edior the password  dialog disasppears immediately. Using the latest dist of SweetAlert solves the issue, however, more testing is required to make sure it still works as expected with other browsers.

Another point to consider: SweetAlert does not appear to be well maintained (latest commit 8 months ago, 180 open issues, 56 pending PRs). Thus it might be sensible to migrate to SweetAlert2. This package started as a fork of SweetAlert, but now is promise-based. Thus, it requires some code changes to start with. 

- https://github.com/limonte/sweetalert2

- https://limonte.github.io/sweetalert2/

**Comment by leader21** [comment]
sweetalert2 looks good. 
very nice options for customisation.

**Comment by mwittig** [comment]
Using the latest version of SweetAlert I noticed some resources have been renamed. Thus, the dialog icons isn't displayed.

@sweetpi Are the sweet-alert files you added to the project (css-file, in particular) the original ones or did you perform some changes before adding them to version control?

**Comment by sweetpi** [comment]
> @sweetpi Are the sweet-alert files you added to the project (css-file, in particular) the original ones or did you perform some changes before adding them to version control?

I don't know anymore. I switched to sweetalert2.

**Comment by mwittig** [comment]
Excellent. Thanks for sorting this one! Works great with Edge!
