### ISSUE TITLE
Pimatic doesn´t stop anymore

### ISSUE THREAD

**Issue by hyp3rx** [pimatic/pimatic#924]
Hello, 
got the problem in:
pimatic version 0.8.107

sudo service pimatic stop
Sending SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGQUIT to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGKILL to pimatic, waiting for process exit...
......

Pimatic doesn´t STOP anymore, it also doesn´t restart inside gui

**Comment by mwittig** [comment]
I have the same, occasionally. I think it is OS-related as it is impossible to kill -9 the process. To workaround the issue, reboot the Raspi.

**Comment by hyp3rx** [comment]
yep, KILL -9 did it, after restarting pimatic, everything works again as expected incl. STOP and restart command.

**Comment by thexperiments** [comment]
Had the same issue on multiple occasions, seems to be stuck in some driver
(most likely networking) but I have no Idea how we could prevent it.

2016-06-13 15:38 GMT+02:00 hyp3rx <notifications@github.com>:
