### ISSUE TITLE
[v0.9] logreader device manager not able to config lines and attributes

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#925]
it's not possible to create a logreader device via the device manager with lines and attributes.
the device manager shows a popup menu without option for any input
running pimatic on 0.9.23 / mobile frontend 0.9.7

![](http://www.youscreen.de/bahpmooby82.jpg)

**Comment by mwittig** [comment]
This is a known issue and its on my list. As the device editor is not able to handle "patternProperties" which is not easy to implement, we need to change the device config schema of the logreader. I briefly discussed the matter with Oliver a couple of weeks ago and we came up with a first sketch of the modified config. Here is an example:

```
{
     "match": "TransportState: PLAYING",
     "predicate": "music starts",
     "set": [
     	{
     	"attribute": "music-state",
     	"value": playing"
     	}
     ]
   },
```

**Comment by sweetpi** [comment]
I have update the config scheme of the log-reader in 0.8.9 and added support for additionalProperties in the config editor.
