### ISSUE TITLE
[v0.9] Startup error: TypeError: this.framework.pluginManager.spawnNpm is not a function

### ISSUE THREAD

**Issue by hongkongkiwi** [pimatic/pimatic#926]
When I install pimatic using @beta or @0.9.23 then I run it using ./node_modules/pimatic/pimatic.js I get the following error (without any additional modules installed).

`Startup error: TypeError: this.framework.pluginManager.spawnNpm is not a function`

Any idea why this could happen?

Running:
* Node v4.2.6
* NPM v3.9.6

I have tried installing npm@2 (doesn't help) and using a new config.json file from default (doesn't help).

**Comment by mwittig** [comment]
Yes, it is a bug, unfortunately. It creeped in with the introduction of the pimatic package manager to overcome some shortcomings of npm (cba91d83ebe44749198aee9ae5bdda0a6fc01505). I'll fix that asap

**Comment by mwittig** [comment]
Released pimatic@0.9.24

**Comment by mwittig** [comment]
Assume this issue is resolved. Please re-open if the issue remains
