### ISSUE TITLE
Sent with php data to pimatic

### ISSUE THREAD

**Issue by Rickry** [pimatic/pimatic#927]
Hello,

How can i sent data from a php file to pimatic variable?

i just have this: `$data = array("valueOrExpression" => "value");                                                                    
$data_string = json_encode($data);   

$login = 'admin';
$password = 'password';
$url = 'http://pimaticadress/api/variables/zonnepanelen';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERPWD, "$login:$password");
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);                                                                  
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);   
$result = curl_exec($ch);
curl_close($ch);  
echo($result);`

Any body can help me please!!?

**Comment by mwittig** [comment]
Hi there, 

For questions and How-Tos, please use our forum - https://forum.pimatic.org as only a smaller number of users use github (mainly developers). Please also make sure to have a look at our online documentation for the Pimatic API. https://pimatic.org/api/actions/
