### ISSUE TITLE
Debug don´t work

### ISSUE THREAD

**Issue by t1m02k16** [pimatic/pimatic#933]
Hello,
i dont get a debug after i updated to 0.9
homeduino and my-sensors affected

I have debug enabled in Config

Thanks for help

```
  ],
      "messageLogging": [
        {
          "level": "*",
          "tags": [],
          "expire": "7d"
        },
        {
          "level": "debug",
          "tags": [],
          "expire": "0"
        }
      ]
    },

```
and homeduino
```
 "plugin": "homeduino",
  "driver": "serialport",
  "debug": true,
  "active": true,
  "driverOptions": {
    "serialDevice": "/dev/ttyUSB0",
    "baudrate": 115200
  },
  "receiverPin": 0,
  "transmitterPin": 4,
  "rfrepeats": 7,
  "enableReceiving": true
```

**Comment by mwittig** [comment]
You need to set "logLevel" as part of "settings" as described in https://pimatic.org/pages/config/

See also https://forum.pimatic.org/topic/1915/solved-no-debug-output/7

**Comment by sweetpi** [comment]
I changed the debug logging behavior in pimatic v0.9.28. If debug is enabled for a plugins its debug output is logged regardless of the log level.

**Comment by thexperiments** [comment]
So we can now easily activate debug logging for any plugin? Is this documented somewhere? Also had problems when implementing my last plugins.

**Comment by mwittig** [comment]
> So we can now easily activate debug logging for any plugin? 

Yes

> Is this documented somewhere? 

I don't think so.  

> Also had problems when implementing my last plugins.

Now, it should no longer an issue. You can simply implement you own debug handling by adding a debug property to your plugin conf. If set to true your debug messages will be logged.
