### ISSUE TITLE
Travis CI builds of fork not passing

### ISSUE THREAD

**Issue by leader21** [pimatic/pimatic#941]
from the forum
please check here for more information:  
https://forum.pimatic.org/topic/1973/travis-ci-builds-of-fork-not-passing

@michbeck100 wrote:
I have forked the pimatic repository in my github account. Everytime i push my changes, the Travis CI build starts automatically, but i doesn’t pass.
The error doesn’t come from my changes, though. See https://travis-ci.org/michbeck100/pimatic/builds/141443469 for example.
```
  1) pimatic startup should startup:
     Uncaught Error: spawn ./node_modules/pimatic/ppm.js ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
  
  2) pimatic #isDeviceInConfig() should find actuator in config:
     TypeError: Cannot read property 'match' of undefined
    at getAssertionExpression (node_modules/cassert/index.js:43:16)
    at assert (node_modules/cassert/index.js:27:18)
    at Context.<anonymous> (test/pimatic-test.coffee:88:7)
```
The same error occurs when running the tests locally.

**Comment by mwittig** [comment]
@michbeck100 Your branches are behind the mainstream branches. Resync your fork and your problem should be gone.

**Comment by michbeck100** [comment]
Please open this issue again. My fork https://github.com/michbeck100/pimatic is even ahead of the pimatic master branch, but it doesn't work.
