### ISSUE TITLE
[filebrowser] Cannot GET /files

### ISSUE THREAD

**Issue by thost96** [pimatic/pimatic#944]
Hi,
I installed filebrowser version 0.9.0 and get this error
```
Cannot GET /files
```

Here is my config:
```
{
      "mappings": [
        {
          "path": "/files",
          "directory": "/home/pi/pimatic"
        }
      ],
      "plugin": "filebrowser",
      "active": true
    }
```

what is wrong here?

**Comment by mwittig** [comment]
Are you sure the given directory `/home/pi/pimatic` exists and is readable?

**Comment by thost96** [comment]
Yes, this is my root directory for my pimatic installation (instead of pimatic-app) and it's readable also.

**Comment by thost96** [comment]
This also happens on my second rpi. I tested other directories, without success.

**Comment by mwittig** [comment]
Did you restart pimatic after defining the plugin settings?

**Comment by thost96** [comment]
Ah okay, now it's working fine. A note to the plugin readme would be nice ;)

**Comment by mwittig** [comment]
Actually, the Plugin View should indicate a Restart is required for the changes to take effect. I have filed an issue for this one - https://github.com/pimatic/pimatic/issues/945

I'll add a note to plugin README also
