### ISSUE TITLE
Help with dynamical attributes

### ISSUE THREAD

**Issue by stingone** [pimatic/pimatic#946]
Small question to the developers here. I worked for couple of day's on the OTGW plugin and adding all the remaining and missing data that could be captured from the central heating. It's all working however currently all attributes are being displayed as static in the plugin. 

could anyone help me out to make the attributes dynamical in the device config? so people can show or hide devices in the class through the config and choose what they want to be showed. Below is a snipped of 2 devices of the total 13 i have. But currently the devices are static in the plugin.

I already managed to update the destroy function for the plugin.

I’d like to do a pull request but if the dynamical attributes could also be implemented would be great.

```
temperature: null
temperature1: null

attributes:
  temperature:
    description: "Temperature"
    type: "number"
    unit: 'Â°C'
    acronym: 'Control Setpoint'
  temperature1:
    description: "Temperature1"
    type: "number"
    unit: 'Â°C'
    acronym: 'Remote Override Setpoint'

constructor: (@config, lastState) ->
  @id = @config.id
  @name = @config.name
  @temperature = lastState?.temperature?.value
  @temperature1 = lastState?.temperature1?.value

  super()

  plugin.otgw.on("control_setpoint", (data) =>
    if data?
      @temperature = Number(data)
      @emit 'temperature', @temperature
  )
  plugin.otgw.on("remote_override_setpoint", (data) =>
    if data?
      @temperature1 = Number(data)
      @emit 'temperature1', @temperature1
  )

getTemperature: -> Promise.resolve(@temperature)
getTemperature1: -> Promise.resolve(@temperature1)`

**Comment by mwittig** [comment]
See https://github.com/pimatic/pimatic/issues/928

**Comment by stingone** [comment]
Sorry but i dont get it. e.g. attributes:

What i want to achief is that the attributes temperature and temperature1 as below can be added/removed from the config file. currently temperature and temperature1 are being showed permanent as they are part of the plugin itself.

Could you please write an example so i can understand. I can show the whole code if required.

temperature:
description: "Temperature"
type: "number"
unit: 'Â°C'
acronym: 'Control Setpoint'
temperature1:
description: "Temperature1"
type: "number"
unit: 'Â°C'
acronym: 'Remote Override Setpoint'

**Comment by mwittig** [comment]
Not sure this is still an issue. If ticket 928 did not help please have a look pimatic-metar-weather, pimatic-wmi or pimatic-snmp, for example. These plugin provide the ability to define attributes as part of the device configuration.
