### ISSUE TITLE
504 Gateway Time-out – nginx/1.10.0 (Ubuntu) 

### ISSUE THREAD

**Issue by sverrevh** [pimatic/pimatic#949]
When going to the Plugin page this appears in the logs:
`<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
`

**Comment by leader21** [comment]
Thx for reporting! Seems that the update server is down. We will check that!

**Comment by Redferne** [comment]
Same problem here.

/R

**Comment by mwittig** [comment]
@Redferne See comments above. You may need to restart pimatic once to make the error message disappear.

**Comment by Redferne** [comment]
Yes. Works perfectly again. Thanks!

/R
