### ISSUE TITLE
[pimatic-shell-execute] option to fail silently

### ISSUE THREAD

**Issue by kanedo** [pimatic/pimatic#950]
I use the shell execute plugin to retrieve statistics from my nas which my not be running. In this case all commands fail and produce an error log. I tried using `2> /dev/null` to prevent it from logging but it doesn't help. 
I know that usually an error should be logged but in this instance it is a expected behavior. It would be nice if I could specify per device if it should fail silently

**Comment by mwittig** [comment]
Thank you very much for your input!

We collect feature requests using the pimatic forum to give a wider community the opportunity to submit comments and to upvote which we sometimes use to priotize requests. Accordingly, I have filed a feature request at: <https://forum.pimatic.org/topic/2043/silent-mode-for-pimatic-shell-execute>. Thus I am closing this issue now.
