### ISSUE TITLE
Error: androidInterface is not defined

### ISSUE THREAD

**Issue by DavidZH** [pimatic/pimatic#953]
When I opened the web interface on my Android mobile phone last night, the interface was very sluggish and about every 16 seconds the error message showed up:
**error [pimatic-mobile-frontend]: Client error: Uncaught ReferenceError: androidInterface is not defined** 

I'm running 0.9.28, Android 5.1.1, browser is Dolphin 11.5.8

(I'm also testing PimaticDroid, but that doesn't show all devices on the front page. Different problem, different developer.)

**Comment by thost96** [comment]
Have you cleared you browser cache and tried it again after this?

**Comment by mwittig** [comment]
No response. Assuming this has been solved. Pls re-open if issue is still pending.
