### ISSUE TITLE
[pimatic-homeduino] Switch 8 | Programcode only Numeric in Webfrontend

### ISSUE THREAD

**Issue by MarcelMertens** [pimatic/pimatic#956]
Hello,

i bought this [pack ](https://www.amazon.de/Etekcity-Funksteckdosen-Fernbedienungen-Selbstlern-Funktion-2300/dp/B016I3TZ58/ref=sr_1_1?ie=UTF8&qid=1470158498&sr=8-1&keywords=etekcity) of switching plugs.
They are discovered with
`debug [pimatic-homeduino]: doorbell1:  { id: 1375, unit: 1077, state: false }
19:11:01debug [pimatic-homeduino]: switch14:  { id: 21843, unit: 1, all: true, state: false }
19:11:01debug [pimatic-homeduino]: switch8:  { systemcode: 24, programcode: 'A2', state: false }
19:11:01debug [pimatic-homeduino]: switch6:  { systemcode: 3, programcode: 24, state: true }
19:11:01debug [pimatic-homeduino]: received: [ 172, 536, 5580 ] 01010101011001100110011001100110010110101010010102
19:11:01debug [pimatic-homeduino]: data: "RF receive 172 536 5580 0 0 0 0 0 01010101011001100110011001100110010110101010010102"`

Switch6 is not working, Switch14 only "On" but not "Off". Adding Switch8 via WebGui says that "programcode" must be numeric.

But adding this to the config file
`{
      "protocols": [
        {
          "name": "switch8",
          "options": {
            "systemcode": 24,
            "programcode": "A2"
          },
          "send": true
        }
      ],
      "id": "erekcity_plug_1",
      "name": "💡 LED Lampe Flur",
      "class": "HomeduinoRFSwitch",
      "forceSend": true
    },`

works perfect with the remote plugs

**Comment by mwittig** [comment]
It is an inconsistency in the config scheme which should be addressed. For now, it is save to ignore warning message.

**Comment by mwittig** [comment]
I think this issue has been solved. Otherwise, please re-open
