### ISSUE TITLE
[pimatic-shell-execute] Switch off action doesn't execute "off" command if ShellSwitch is off

### ISSUE THREAD

**Issue by Wikibear** [pimatic/pimatic#960]
I don’t know if my issue is a bug or a feature.
I use brennenstuhl gateway and some power switches. I use also hardkey wireless control from brennenstuhl to control some lights manually by hand. Before update to 0.9 i can use both: hardkey and software of pimatic to control light or switches. You can find a script here in forums to control brennenstuhl gateway with pimatic. That works very well. But not with all condition and rules.

Now happens following issue:

If i switch with my hardkey my light on then pimatic dont switch light off if a rule set my powerswitch to off. The rule will start and you can see in log file that pimatic rule gets active but nothing happens.
I think pimatic get a littlebit more smarter and don’t switch a button off its in off position. But thats stupid for me. If i switch my light on via hardkey then pimatic think its off. But its on. I have no chance to make a request of status. It’s not depended.

Question: Is this a bug is this a feature? If this is a feature i must force the execute command that i get my power switch off if its off in pimatic.

Again: A button in off position can’t be switch off again if its in off mode. But then my script for this button will not execute.

**Comment by ChiefZ** [comment]
I had this problem too (and don't like it either).
A workaround is to use "receives off/on" instead of "is turned off/on" in the rule. That is executed every time that event is fired. BUT this will ignore the switch on pimatic itself, so you can't toggle a switch on the web-ui for example. 

That applies for HomeduinoRFSwitch, so I am not sure if it helps you :)

**Comment by mwittig** [comment]
@Wikibear As you say, usually there is no back channel to query the status of a 433 Mhz actuator, i.e. power switch in your case. Typically, the switch can only receive commands. It always may happen for various reasons that the pimatic switch state is not in line with the power switch state. Thus, a sliding switch isn't the best choice here, I must admit. It would be a nice feature request to ask for different UI option for switch, e.g. using ON and OFF push buttons. You can file feature request in our forum at: https://forum.pimatic.org/category/14/feature-requests

I am closing this ticket now, but please feel free  to re-open if you wish to discuss this further.

**Comment by Wikibear** [comment]
This problem is not solved. I think you misunderstood me. I know this is a one direction. And i understand pretty well that pimatic don't have a clue if somebody is switching it via hardkey, cause there is no answer back from the gateway. BUT!

Before 0.9 i don't have a problem that a rule switch a button off, switch the button off and then the script execute my scriptfile. NOW it seems that there is a logic that don't execute off command, cause the button is off. With 0.8 i don't have this problem. The rule switch light off and it was not depended if button is on or off. This is what i will say and this is NOW after update to 0.9 my problem!

If there is now a logic in pimatic that don't exec off cause it's off then it's for me a punch in my face and a reduction in quality of using! If there is a logic, there must be a force option in device settings to force the button off when its with it state off.

Thats exactly the point! Before 0.9 all was fine.

**Comment by mwittig** [comment]
Can you please post the rule in question. Thanjs

**Comment by Wikibear** [comment]
Totally simple. This rule works, if i switch the button in pimatic on:

![unbenannt](https://cloud.githubusercontent.com/assets/18314278/17446824/733266c4-5b4b-11e6-8715-3a96e560d553.PNG)

**Comment by Wikibear** [comment]
Its brennenstuhl gateway with execute buttons command on and off via execute script as describe in forum.

I can switch on and off the button and a exec script send commands via command line to the gateway. 

What happens:

switch via pimatic button on -> rule work
switch via hard key powerswitch on -> pimatic button off (normal we don't get feedback) -> rule doesn't work

I test it many times with different rules. Switch via pimatic button on a rule switch off. Do it via hard key rule doesn't switch on and so on... But this works before update.

**Comment by mwittig** [comment]
Ah, ok. So it is a ShellSwitch. Most likely your are affected by the following code submitted by @michbeck100  https://github.com/pimatic/pimatic-shell-execute/commit/dbe43f0a7e60ddcbdf5757c7427aa12f09f98bd8

Suggested resolution. We add property "forceExecution" which will be set to false by default. This is for Pimatic-hap users which have been affected by https://github.com/michbeck100/pimatic-hap/issues/37. For your use case you can set "forceExecution" to true then. It will take some time to get this processed due to the holiday season.

**Comment by Wikibear** [comment]
Sometimes its hard to explain something and important things you forgot to write down makes this not easier. Yes i forgotten that shellexec is not a part of pimatic. But you are right that this error will be maybe a part of it.

Thank you for your help!

**Comment by michbeck100** [comment]
Just remember that this bugfix prevents infinite loops when switching in some cases depending on the used plugin and in conjunction with pimatic-hap. So keep that in mind when using "forceExecution"

**Comment by mwittig** [comment]
Released with version 0.9.7
