### ISSUE TITLE
Can't post or comment in the forum

### ISSUE THREAD

**Issue by cm86** [pimatic/pimatic#961]

**Comment by cm86** [comment]
Don't if I'm right here
But when I will post something the text I'm writing I going away when my iPhone shows the keyboard. When put the keyboard down the text is shown...
![](http://i.imgur.com/ahfDCny.jpg)
![](http://i.imgur.com/JBx4OTQ.jpg)

**Comment by mwittig** [comment]
To finally post the message, you need to press on the ">" sign in right corner of the blue bar at the top.  I am closing this now. Please re-open if you still have issues.

**Comment by cm86** [comment]
The problem was that the text wasn't visible when I'm writing.

**Comment by cm86** [comment]
So again here...

I can See nicht Text when i'm Writing...![](http://i.imgur.com/9BndM7N.jpg)![](http://i.imgur.com/TD4nXph.jpg)
