### ISSUE TITLE
pimatic 0.9.32 - plugin pimatic-dht-sensor shows only zero

### ISSUE THREAD

**Issue by Man-in-Black** [pimatic/pimatic#962]
Hey together,

today I've upgraded from pimatic 0.8 to 0.9.32.
Since then I cannot use the pimatic-pilight plugin anymore.

I want to get the values from my dht22 sensor, but with the dht-plugin I only get "zero".

Can you please help me?

Thank you.

**Comment by thost96** [comment]
@Man-in-Black have you checked, that the right pin is set in the plugin config?

**Comment by Man-in-Black** [comment]
Yes I checked this.
Sometimes I got the correct values, sometimes it only shows zero.

**Comment by mwittig** [comment]
See also https://forum.pimatic.org/topic/2217/pimatic-dht-sensors-node-dht-sensor-update-for-testing and https://forum.pimatic.org/topic/2213/dht11-sensor-showing-0-value-for-temp-and-humidity

**Comment by mwittig** [comment]
Should be fixed in pimatic-dht-sensors@0.9.2. Please see https://forum.pimatic.org/topic/2404/important-note-for-pimatic-dht-sensors regarding important changes.
