### ISSUE TITLE
LIRC not working with 0.9.32

### ISSUE THREAD

**Issue by Man-in-Black** [pimatic/pimatic#963]
Hey togehter,

another issue from me:
Recently I used the lirc library to control my devices with IR-commands.

Since pimatic 0.9.32 there is no support for pimatic-lirc.

Is there any other way for pimatic to receive ir-commands?

Thank you.

**Comment by SLiX69** [comment]
You could use irexec to invoke pimatic actions via api (eg with curl)

**Comment by Man-in-Black** [comment]
I will give it a try and will report it.
Thanks for the hint.

**Comment by SLiX69** [comment]
I dont know. The last commit on github was 12 months ago.

**Comment by Man-in-Black** [comment]
I reverted to Version 0.8 of pimatic.
I will be waiting if there is an equivalent to pimatic-lirc or an update.

**Comment by SLiX69** [comment]
Hi, just saw this PR https://github.com/tester22/pimatic-lirc/pull/1/commits
Wait till it's merged or directly use the forked version from @thejatom here https://github.com/thejatom/pimatic-lirc

**Comment by Man-in-Black** [comment]
That would be nice.
I will test this very soon, If my other case (#962) will be fixed.

**Comment by mwittig** [comment]
@Man-in-Black Any news on this one? Please let me know if you need guidance on how to install from the fork https://github.com/thejatom/pimatic-lirc

**Comment by Man-in-Black** [comment]
@mwittig: since my Raspberry crashed couple of weeks ago I had to recreate every single configuration from scratch.
After that I had no issues anymore.

This issue can be closed.

Thank you for your help.

Sascha
