### ISSUE TITLE
API: Cannot change state of a switch - "type in [ value, expression ]"

### ISSUE THREAD

**Issue by dnn1s** [pimatic/pimatic#967]
I'm trying to set a switch to either "on" or "off" by using the API. For testing, I merely open the dev tools panel in Firefox on the pimatic URL, this is the jQuery code I'm using:

`$.ajax({
	url:"http://<ip-address>/api/variables/dummy-switch",
	data:{
		"type": "state",
		"valueOrExpression":true
	},
	method:"PATCH",
	success:function(r){
		console.info(r);
	},
	error: function(r) {
		console.warn( r.responseText );
	}
})`

This is the response:

`{"success":false,"message":"type in [\"value\", \"expression\"]"}`

What am I doing wrong?

**Comment by dnn1s** [comment]
Ok, I got it with a GET request (found in the forums), but would also like to change it via POST:

`http://<ip-address>/api/device/dummy-switch/turnOn`

Why wasn't I able to found this syntax in the API documentation?

**Comment by SLiX69** [comment]
We don't know, why you did not found it. Title is 'callDeviceAction'. Example there is: ```GET /api/device/:deviceId/:actionName```

Why do you want to change this via POST?
btw you can use action 'toggle' too (instead of turnOff, turnOn)

**Comment by dnn1s** [comment]
I haven't found any occurence of "turnOn" or "turnOff" in the API docs, could you provide a link to the documentation please?

**Comment by incmve** [comment]
https://pimatic.org/api/actions/#scrollNav-5

**Comment by mwittig** [comment]
I think this is solved now. Please consider using our forum for general questions and how-tos as it used by more users than github - https://forum.pimatic.org/
