### ISSUE TITLE
[pimatic-0.8] update problem

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#970]
Tried to update from pimatic 0.8.101 to 0.8.107. The gui said that will be carried out, but unfortunately it did a update to the lastest 0.9 version. With the Raspbian Weeze version running and an old node.js version and a lot off dependency errors, pimatic didn't run anymore.

Reverted to 0.8.101.

Two questions: Is it possible to manually update pimatic to 0.8.107?
If not can I upgrade to 0.9 but what about my config? Can I after properly installing 0.9, copy my 0.8 config.json file and will it be converted to a 0.9 config file after starting 0.9?

**Comment by mwittig** [comment]
> Two questions: Is it possible to manually update pimatic to 0.8.107

You can try as follows:

```bash
sudo service pimatic stop
cd /home/pi/pimatic-app
sudo npm i pimatic@0.8.107
sudo service pimatic start
```

> Can I after properly installing 0.9, copy my 0.8 config.json file and will it be converted to a 0.9 config file after starting 0.9

If you opt for upgrading to pimatic 0.9 which is recommended as pimatic 0.8 will no longer be supported please follow the instructions given in <https://forum.pimatic.org/topic/1903/announcing-the-release-of-pimatic-v0-9>. As part of this it is possible to upgrade your existing 0.8 configuration.

Please use the Pimatic Forum for general questions which normally will give you faster feedback from a growing user community..
