### ISSUE TITLE
Pimatic error: database disk image is malformed

### ISSUE THREAD

**Issue by WolfgangHusen** [pimatic/pimatic#971]
folks,

after adding a new device to the config, Pimatic returns a lot of issues. The added device works as planned.
issues:
error [pimatic]: A uncaught exception occured: Error: insert into "attributeValueNumber" ("deviceAttributeId", "time", "value") values (54, '2016-08-29 22:33:01.153', false) - SQLITE_CORRUPT: database disk image is malformed
 This is most probably a bug in pimatic or in a module, please report it!
22:32:36error [pimatic]: select "deviceAttributeId", count("id") from "attributeValueString" group by "deviceAttributeId" - SQLITE_CORRUPT: database disk image is malformed
22:29:08error [pimatic]: A uncaught exception occured: Error: insert into "attributeValueNumber" ("deviceAttributeId", "time", "value") values (35, '2016-08-29 22:29:08.114', 16.8) - SQLITE_CORRUPT: database disk image is malformed
 This is most probably a bug in pimatic or in a module, please report it!

etc. etc.

Greetings,
Wolfgang

**Comment by mwittig** [comment]
Can you please to a file system check? Most likely the  error is caused by a corrupted file system. If you're using an SD Card this is a common error.

**Comment by leader21** [comment]
you can try to delete or rename the sqlite database. pimatic will create a new / empty one.
but as mwittig said above check your fs! 
if using a sd card, consider to install your [fs onto an usb hard disk](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=44177)

**Comment by WolfgangHusen** [comment]
thanks both - deleting the DB helped for now. As I have 4 raspies running at home with Pimatic the hard disk option is not my preferred way, a bit "overdone" for a light-weighted raspi solution.
I found the "database configuration howto", I will try, as well.

**Comment by WolfgangHusen** [comment]
update: the SD card was damaged, as well. Also I am gonna use an old hard disk for the "main" raspi and switch off the DB options for the others - I assume with that I reduce the hard disk write/read accesses tremendously.
Thanks again for feedback.
