### ISSUE TITLE
!MAX Error

### ISSUE THREAD

**Issue by DerGrafausB** [pimatic/pimatic#981]
error [pimatic]: A uncaught exception occured: TypeError: Cannot read property 'toString' of undefined
    at MaxCube.parseCommandDeviceList (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:222:59)
    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:123:19)
    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:75:26)
    at Array.forEach (native)
    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:70:8)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
 This is most probably a bug in pimatic or in a module, please report it!

**Comment by leader21** [comment]
does this still happen?

**Comment by DerGrafausB** [comment]
A uncaught exception occured: TypeError: Cannot read property 'toString' of undefined
19:00:49.245 [pimatic]>    at MaxCube.parseCommandDeviceList (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:222:59)
19:00:49.245 [pimatic]>    at MaxCube.parseCommand (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:123:19)
19:00:49.245 [pimatic]>    at MaxCube.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:75:26)
19:00:49.245 [pimatic]>    at Array.forEach (native)
19:00:49.245 [pimatic]>    at MaxCube.onData (/home/pi/pimatic-app/node_modules/pimatic-max/node_modules/max-control/index.js:70:8)
19:00:49.245 [pimatic]>    at emitOne (events.js:77:13)
19:00:49.245 [pimatic]>    at Socket.emit (events.js:169:7)
19:00:49.245 [pimatic]>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
19:00:49.245 [pimatic]>    at readableAddChunk (_stream_readable.js:153:18)
19:00:49.245 [pimatic]>    at Socket.Readable.push (_stream_readable.js:111:10)
19:00:49.245 [pimatic]>    at TCP.onread (net.js:531:20)
19:00:49.245 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!

**Comment by DerGrafausB** [comment]
Still Happen

**Comment by bjornhij** [comment]
The problem is in the for condition:

  for(var i = 1; i <= this.deviceCount; i++) {

(just above line 222)

This should be:

    for (var j = 0; j < this.deviceCount; j++) {

We only have this.deviceCount - 1 devices, if we start counting by 0.

Everybody on this version should have this problem.

**Comment by mwittig** [comment]
> The problem is in the for condition:

@bjornhij Are you sure? Did you test your suggested change? 

I just glanced over the code. As far as I can see the index variable `i` is not used inside the for block if I haven't overlooked something. If so, your change won't change the behaviour.

**Comment by bjornhij** [comment]
i is not used, but currentIndex is, and currentIndex is incremented every loop.

Yes, this fixed it for me - but since it used to work before and I do not see any commits that changed this condition it could be I'm missing one device now.

**Comment by mwittig** [comment]
ok, I see. However, `(var i = 0; i < this.deviceCount; i++)` and `(var i = 1; i <= this.deviceCount; i++)` basically result in the same number of cycles.

**Comment by bjornhij** [comment]
Ah typo, it is now:

  for(var i = 1; i < this.deviceCount; i++) {

I copied the second for loop from line 198, and didn't notice the 0 / 1 and < / <= difference. 

So I'm probably missing the last device now, but at least I can now start pimatic :) Will do some further debugging.

**Comment by bjornhij** [comment]
OK, the problem is in my cube. When connected, the cube will report a list of connected devices. In my case, it reports 14 devices (function MaxCube.prototype.parseCommandMetadata). But, when it later reports the status of the devices (function MaxCube.prototype.parseCommandDeviceList), it will only give status for 13 devices. One of the devices (a wall thermostat) is missing. That one probably needs a reconnect.

How about this?

  for(var i = 0; i < this.deviceCount, currentIndex < decodedPayload.length; i++) {

**Comment by bjornhij** [comment]
Repairing the wall thermostat solved the problem. I now get updates for 14 devices.

**Comment by DerGrafausB** [comment]
Hi, 

sorry that I answer so late.
This is the 8th time that this happens.
I testetd a lot of things.
If I disable Max Plugin, everthing is ok.
I changed the Cube 6 weeks ago.
Same Problem.
Workarround:
Reset the cube, and add all devices.
Enable Max Plugin.

==> everthing works.

But why?

I think that there is any communication error to one device.
Is it possible to change first the Plugin that not the whole pimatic crash?

**Comment by bjornhij** [comment]
My pull request will solve the crash problem. It might not be the most clean solution, but it will at least fix the pimatic crash. @mwittig or @sweetpi, can you accept the pull request and release a new version? We can work towards cleaner code later.

**Comment by mwittig** [comment]
Released fix as part of pimatic-max@0.8.19

**Comment by bjornhij** [comment]
Thanks!
