### ISSUE TITLE
update device temperature from another rasperrry pi

### ISSUE THREAD

**Issue by hg-smart** [pimatic/pimatic#982]
hello,

is it possibe to create a real device (device class extends real sensors - pimatic-hap) and update the value (e.g temperature) from remote. We only saw that we can manipulate variables via the rest interface.

- Can such a device be created on the pimatic ? 
- Is this aproach useful or should we use mqtt ?

Even integration with pimatic-hap only works if the Device class extends "real sensors.."

Best
hg-smart

```
# example for variable hgtestvariable 

  curl \
  -X PATCH \
  --header "Content-Type:application/json" \
  --data '{"type": "value", "valueOrExpression": 70}' \
  --user "admin:password" \
  http://192.168.178.35/api/variables/hgtestvariable
```

**Comment by mwittig** [comment]
Please use our forum for general questions and howtos.
https://forum.pimatic.org/

Regarding your question, there are several possibilities. Two of them:

A. Pull the value with a ShellSensor

If you can pull the value from the remote raspi you can use a ShellSensor which is part of the pimatic-shell-execute plugin.
h
B. Push the value to a Pimatic Variable / Use a VariablesDevices

If you can't pull the value, you can push the value to a pimatic variable. The curl command sequence included in your post should work, but you need to setup the variable "hgtestvariable" in pimatic first. The you can setup a VariablesDevice to handle the variable as a device.

**Comment by hg-smart** [comment]
correct, but [pimatic-hap](https://www.npmjs.com/package/pimatic-hap) only supports classes which extend

- ContactSensor
- DimmerActuator
- PresenceSensor
- PowerSwitch
- ShutterController
- TemperatureSensor
- HeatingThermostat

out of the pimaticcode... 
```
class VariablesDevice extends Device
class Device extends require('events').EventEmitter
```

`class TemperatureSensor extends Sensor`

Is there no way to create a "TemperaturSensor which extends class Sensor" which reads it's value from a variable ??  -> could be easily manipulated from foreign pi and pimatic-hap works without changes ?

Thx in advance
hans

**Comment by mwittig** [comment]
> Is there no way to create a device "where class TemperaturSensor which extends class Sensor" which reads it's value from a variable ?? -> could be easily manipulated from foreign pi and pimatic-hap works without changes ?

No. You should have look at pimatic-mqtt then and use a mqttclien to publish data on the remote pi
