### ISSUE TITLE
[pimatic 0.9.33 cron 0.8.8] rule trigger problem

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#983]
When using it is 0:01 and [it is february 2-28 or it is march 1] it will always execute on 0:01 despite the correct date. It executes always.

Using the syntax 0:01 and [february 2-28 or march 1] causing the same behavour. Using simular rules with other months are doing fine, only the above combination causes trouble.

Had the problem also using 0.8.101 but remains after the update (fresh reinstall) to 0.9.33.

**Comment by SLiX69** [comment]
just an idea:

add square brackets like this:
```[it is 0:01 and [it is february 2-28 or it is march 1]]```

**Comment by edautz** [comment]
Configured that way. I see when I switched to Gui mode the extra brackets disappear. 

I will see this night if your suggestion solves the problem. Update wil be posted tomorrow.

**Comment by SLiX69** [comment]
tried this, seems like it did not work for me

**Comment by edautz** [comment]
Also not for me. Problem persists.

**Comment by sweetpi** [comment]
Unfortunately I couldn't reproduce the bug. 

Is this the full rule condition?
Is your time correct?

**Comment by edautz** [comment]
This is the full rule condition.
The Pi is ntp time synced, I checked the time is correct.

I going to make some test rule to determine if I can narrow it down.

**Comment by edautz** [comment]
Did some more tests:

it is 0:01 and [it is february 2-28 or it is march 1]  is the original problem, triggers on the correct time but on every date in the year (as far i can see).

it is 22:20 and it is february 2-28 also triggers on correct time and today.  

it is 22:22 and it is february 2-3 also triggers
it is 22:29 and it is february 1-28 also triggers
it is 22:31 and it is february 5 **doesnot** trigger
it is 22:33 and it is february 5-6 triggers again

Linux Date command:  Sun  2 Oct 22:39:34 CEST 2016

@SLiX69 could you reproduce my issue?

Hope this helps.

**Comment by SLiX69** [comment]
I'm not sure about anymore. Deleted it the next day. 
Will add it again and report tomorrow

**Comment by edautz** [comment]
Very strange, the problem seems to widen. Since 22-9-2016 the problem shifted from the month february to march with pimatic 0.8.101 and widen on pimatic 0.9.32. The rules triggers also on rule definitions january and march. Can't see when that started to happen.

**Comment by edautz** [comment]
Made mistake in Pimatic version, is version 0.9.33. Changed all the 0.9.32 version numbers to 0.9.33 in this issue.

**Comment by macitemre** [comment]
i opened this issue on forum.  Please have a look
https://forum.pimatic.org/topic/2593/pimatic-cron-doesnt-work-until-i-login-to-web-panel

**Comment by edautz** [comment]
After upgrading my RPIB+ to RPI3 and upgrade node.js from V4.4.5 armv6 to V4.6.2 armv7, does this issue not occur anymore.
