### ISSUE TITLE
pimatic.org Down

### ISSUE THREAD

**Issue by Kamaluk** [pimatic/pimatic#990]
As of now - and for the past days - if I try to access pimatic.org
I only get a 502 Bad Gateway

Maybe you can restart the server?

**Comment by mwittig** [comment]
Thanks for reporting

**Comment by mwittig** [comment]
Site is back on-line. Thanks again for reporting

**Comment by sweetpi** [comment]
The API is up again.

I’m sorry I will not do any further development on pimatic. Thank you for all your support and patients.

I will maintain the api server for one more year. If you want to host you own api server you can look at https://github.com/pimatic/update-server for the source and modify it slightly to setup your own. You also have to change the url in pimatic core.

For a pimatic replacement you can take a look at [home assistant](https://www.home-assistant.io/).

If someone wants to continue development pimatic and get access to the github repos cantact me.

Thanks.

**Comment by leader21** [comment]
After many years of silence i just have to speak some words again. Sorry at first for being not able to take part on the pimatic project anymore. Circumstances of life have made my life very difficult so I had to withdraw my participation.  My work with Oliver/Sweet Pi an Marcus/MWittig was always a pleasure. I always had lots of fun and was often astonished on the fast developments in all areas of pimatic. The pimatic project started as small development by Oliver to get some hardware interactive and communicative for the purpose of further development and commercialization. But Oliver decided to make pimatic free for all, that was a great move and the best possibility to advance the pimatic code. Many users took part in developing add-ons or  even worked on the main core. Nowadays there are many possibilities to use smarthome products and software, but in my opinion pimatic is still one of the best and provides many many possibilities with it's powerful API.

I would love to see any further development or even a makeover some day, as @mwittig has implied. This requires a lot of work to get pimatic on the latest  code and rework the major add-ons. As Oliver already said - if anybody wants to continue the pimatic project, please go ahead!  For me, i offer my personal assistance in evaluation and moderating a forum again. 

I would be sad if pimatic dies, it has been alwways been a nice community project and a great piece of software!

Finally i would like to thank @sweetpi  and @mwittig  for keeping things up the last years. Also I want to thank all free coders who evolved many add-ons to make pimatic special. 

Keep up the good work no matter on what you work right now, you rock! Stay safe stay healthy!

Cheers 
Chris/leader21

**Comment by danielschmalhofer** [comment]
Hey Chris,

so sorry to hear that! Totally agree, that it would be very sad it pimatic dies...!! I finally convinced my dad to try it out ;)
I don't have any time on my hands, but am willing to pay like a monthly fee (croudfunding) to support it, if someone might feel motivated by that.

Cheers
Daniel
