### ISSUE TITLE
saveConfig() does not work

### ISSUE THREAD

**Issue by wutu** [pimatic/pimatic#992]
Hi all.
Pls see https://forum.pimatic.org/topic/1444/new-plugin-pimatic-mqtt/47

If I uncomment @framework.saveConfig(). No error. Plugin will start up fine.
If I purposely makes an error in the create config data. Pimatic reacts and listing error.
I can not move with it. Advise anyone?

**Comment by mwittig** [comment]
Hi, I don't think this is a bug. I have written a more detailed explanation as part of the mentioned thread, see <https://forum.pimatic.org/topic/1444/new-plugin-pimatic-mqtt/50>. Basically, saveConfig() cannot be called before pimatic has been fully initialized. At the time when plugins are loaded this unfortunately not the case.

**Comment by mwittig** [comment]
I am closing this one now. Please re-open if you want to followup.
