### ISSUE TITLE
A uncaught exception occured: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by hyp3rx** [pimatic/pimatic#996]
Today i updated some plugins... Also MQTT Plugin, After restart of Pimatic it doesn´t start anymore:

> 15:22:07.278 [pimatic] error: A uncaught exception occured: TypeError: Cannot read property 'forEach' of undefined
15:22:07.278 [pimatic] error:>    at outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:465:11)
15:22:07.278 [pimatic] error:>    at that.outgoing.(anonymous function) (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:140:15)
15:22:07.278 [pimatic] error:>    at /home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:881:9
15:22:07.278 [pimatic] error:>    at Store.del (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/store.js:77:5)
15:22:07.278 [pimatic] error:>    at MqttClient._handleAck (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:868:26)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:293:12)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at MqttClient._handlePacket (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:294:7)
15:22:07.278 [pimatic] error:>    at process (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:242:12)
15:22:07.278 [pimatic] error:>    at Writable.writable._write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/lib/client.js:252:5)
15:22:07.278 [pimatic] error:>    at doWrite (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:319:64)
15:22:07.278 [pimatic] error:>    at writeOrBuffer (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:308:5)
15:22:07.278 [pimatic] error:>    at Writable.write (/home/pi/pimatic-app/node_modules/pimatic-mqtt/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:246:11)
15:22:07.278 [pimatic] error:>    at Socket.ondata (_stream_readable.js:542:20)
15:22:07.278 [pimatic] error:>    at emitOne (events.js:77:13)
15:22:07.278 [pimatic] error:>    at Socket.emit (events.js:169:7)
15:22:07.278 [pimatic] error:>    at Socket.emit (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:63:24)
15:22:07.278 [pimatic] error:>    at readableAddChunk (_stream_readable.js:153:18)
15:22:07.278 [pimatic] error:>    at Socket.Readable.push (_stream_readable.js:111:10)
15:22:07.278 [pimatic] error:>    at TCP.onread (net.js:536:20)
15:22:07.278 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!

>

**Comment by hyp3rx** [comment]
I have deactivated MQTT Plugin in order to have a running pimatic until i figured out whats happend.

**Comment by leader21** [comment]
did you delete the folder pimatic-mqtt and restart again? mqtt will be insattled again. maybe there has been some kind of error on the first Installation

**Comment by wutu** [comment]
If the problem persists, please submit issue directly to the MQTT plugin page. Thx.
https://github.com/wutu/pimatic-mqtt

**Comment by hyp3rx** [comment]
now i´m into trouble, i´ve deleted pimatic-mqtt folder, and after restart it says:
error [pimatic]: ENOENT: no such file or directory, open '/home/pi/pimatic-app/node_modules/pimatic-mqtt/package.json'

**Comment by leader21** [comment]
delete the folder again and Start pimatic.
if this fails too, open your config.jsom and delete the mqtt  plugin from the plugins section

**Comment by hyp3rx** [comment]
I´ve managed reinstalled but problem is still present as mentioned above ! I write the issue to:

https://github.com/wutu/pimatic-mqtt

**Comment by mwittig** [comment]
Closing this one now

https://github.com/wutu/pimatic-mqtt/issues/18
